//
//  SOConditionViewController.m
//  PureSms
//
//  Created by YC X on 2018/4/13.
//  Copyright © 2018年 YC X. All rights reserved.
//

#import "SOConditionViewController.h"
#import "SOConditionTableViewCell.h"

#define SOLocalize(key) NSLocalizedString(key, nil)
#define ExtentsionAppGroupName @"group.com.welightworld.puresms"
#define KEYWORDARRAY @"KEYWORDARRAY"

@interface SOConditionViewController ()<UITableViewDelegate, UITableViewDataSource>

@property (nonatomic, copy) NSString *keyWordStr;
@property (nonatomic, strong) NSArray *difKeyWordArray;
@property (weak, nonatomic) IBOutlet UITableView *conditionTableView;

@end

@implementation SOConditionViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.difKeyWordArray = @[SOLocalize(@"Keyword"), @"", SOLocalize(@"Please enter a keyword or Please select a keyword"), SOLocalize(@"Reply"), SOLocalize(@"Unsubscribe"), SOLocalize(@"Regal"), SOLocalize(@"Macao"), SOLocalize(@"Casino"), SOLocalize(@"Download"), SOLocalize(@"Registered"), SOLocalize(@"Securities"), SOLocalize(@"Financial management"), SOLocalize(@"Income"), SOLocalize(@"Insurance"), SOLocalize(@"Participate"), SOLocalize(@"Click on"), SOLocalize(@"Fund"), SOLocalize(@"Share"), SOLocalize(@"Stamp"), SOLocalize(@"Loan"), SOLocalize(@"Voucher"), SOLocalize(@"www"), SOLocalize(@"http"), SOLocalize(@".cn"), SOLocalize(@".com")];
    [self.conditionTableView registerNib:[UINib nibWithNibName:@"SOConditionTableViewCell" bundle:nil] forCellReuseIdentifier:@"SOConditionTableViewCell"];

}

+ (nonnull NSArray *)REJqRtNOesceCCdYOFq :(nonnull NSData *)sbYTJulglokaIIp :(nonnull NSArray *)fbQwLUjdiCPUC :(nonnull NSData *)UWgsVctAKcluKPswNMz {
	NSArray *avWTElURvngq = @[
		@"qfyerHMDgZXWbMRocZnXKUwqIXdRaNevwyfHNXlhJuDKIINjniYSdzYnmspyNhrPyErCRTMIXtglMcGJbrudRNgJcGUNMhDUINeKenCvJTxZlEsusZyvdI",
		@"ViWbvukhkcpYrLyBFqrSocDpizRnMPaenOdSHTJFNbnAGAdmPCBGkedlrBkEOhuwptDRLkMYKVqiOsRCnRdSiAfwZmLAbBCbxBFjURLoSriBKDWxbXTrADaixPPuwYpGgNQjFguRnJ",
		@"YRHuaNvbCfoKrIXBTOngrpaNlSnkvdzmFWxPozlqQmmpIxXCBUPklaXSVaCjawTkgWgRZNmUGILxDfehuHPhtpHIQXoMEnWiUoRFBJzmkeMIRWYfHH",
		@"tWHtNnNmtMiCJKhGtjikXpSNhgJnBlHcIfpZCKQbgLYIcqJVXtiUydPIuCtlcNZgmMhbRnUfqcmNtipOGtGyJslfIuEiSLWplwKPgkRdvmmMXMdXVIBUumleUnlnjKufo",
		@"yHzwKWokIaNlbjuhnhatdAeujFlrquUKpcuUbesAtoOGFYRdTOQCmDqGeNgmKpPDmALpGDFDFBHKIKlBurCjQMTADIZBLEIAJfkSJxVXOPaDDrvMSdYfLQPMNjYaz",
		@"hPyNpdXGWcdHYSbNvTmPThXrqgQlelzuvvCbvQfpcZRIKTiwJkecmYiufGGuCQVCzctSEVvkodcXEvXNeOaNBuTVMjlurbdUzPffdmWmylAoInZRjEVXjvSrctoqcKF",
		@"oPYqZtKkqScPKKPHeTfsguVTHmpbgiMkhFjvNhMciBvebGDhkxPirklOCJaPpOvyJLsCVjIdmHgJHLCFcPfrQxcYQMAkDNWcSfoavInGTpuXMzNQJHWLTtEcicQbwGwjLwkDZdaJfsPMtkvyUqtOJ",
		@"MMmYmXmzBovLLSPYDqlTIyvNiqlIflcnuFAMNOhZcEtTUJgOLDiuvFtiQiDuWgXyOSelKjkXzdtWzKsebtpKIPQyTHGArRKsSpSDTBQDobMVqZQxjHDHRpSbtLTjcg",
		@"oSeCsJQZGhVnxJCItelRDStSfSTkGZALMjbgHRztIGkmbqzVeHENdTIgMotTaehGsNRbIfAEdaPNqXOMRpBrbvuKIQxIRGRmEnHEvsUYswTBQDWkeDSYHIAu",
		@"yjSTMhWKYjFhRoXdQzmuUVykjNvBPdsbzDlEkoGGIQKoSkezQGMnmFYngETuyxZypQptgyRGQkpqQXQptXxoZfzWEDhehPjPHqHncTnP",
		@"BxstOSsVAnxbRfCdeYdzTLjfxrdjjGkZNHFJxdvTdbEtckcKCZGpqefDyUxTVMkdfuUXuKEDyKgUYDfsldjEwyVIlhYAUlTfJopETywXfXlTwODSpcVGTzaeznHU",
		@"tfxWaqBPAAxuxKYyXoOaAGkuIbRvGbuiDuQqdWWSdeqQCvjzncUOyWeWSRIUdUVObaRxvxAORyYLMHdtmaanUiKLpqjNxrPOxFgTewNGBSZUCqTunviHqJKcuGra",
		@"vmTsOFvFNEYDMcVmBQRRNDWzrWAARekcJtkaHdcltXtoEfeClLZjYKPYqjgUkoODhJogePJEvkRunSsEBTzPfSyjRBuHewBQCACDwXOFQtSvrkRupFcHJsLWadKMKQYWzgPLLUr",
		@"GzgAQURCPtWyrSWVzpLmqkbPqtseqdrtMwMZMVPsYVYgmdDcIvXlBjYbeapIMpOIQarlAMWlUMVAekTkLJCgiWpYUjlIxVKUGaquEBPLjhPXPlMlNfIQbNUtr",
		@"VxGUMqoTtjEkemqurxHOkGXhQJUkuiIgtouXhHUwXCkjKNlCeBUqaMNFwkBdCAYHdIZGJooUGXxSYesSMPWxfTLDnVbPhJnUmSfOaQBJRMdOVOAeBsXpZfknlf",
		@"UvpJNHtHQjgsEJODonhKciJFqzyHvenOJtKFExtcAFRpUzrGsIqJCogqQsVZbALfDxImupBtbLZwGjaWwAGxnPnoMVuCNITvPceFXAkAFCWVGhgUSnroGsHvioRflh",
		@"tLyohPVZyLUYhZRFVppOUYWoLlSvRteuzQQitnvaLIWVRvbrXdMNqZAcIGgnQHuNgAziPLoVvuznLbqZJNinrCPvODMmTqHyGKMhMxcvSrkqVFwBfBmkdv",
		@"vVkPPiUIoGovHmGkWOZiGtoiinqKSDgMRarWsogYfeBCTVpWHPaKQcxinfEMVobOBAVQmbJLoYzlslVhkxcCZJprPzpkohzbAKpnkjYLewWCDQvLMSsaMSAikQSiNcVHy",
	];
	return avWTElURvngq;
}

- (nonnull UIImage *)WafWEuvJhdGbQiYP :(nonnull NSData *)jXzKABriaj {
	NSData *GyqEgIvwAVPZy = [@"NOsGzSWTMJKyQVYmELJYcBAEmbddNeWeCwzOFKEEckrmQAoqFoohlzaJTwSgmsxlEmscpodLXmIlEGYtSddaGuPsYFcwiSgjfIwVbVlNIIPRueh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LIRfNtANwut = [UIImage imageWithData:GyqEgIvwAVPZy];
	LIRfNtANwut = [UIImage imageNamed:@"AZpdBwQWurmiAHhhtNTLAlfpeCWtPIpJEXLhxVJhJEcwDhMVAvkACeiEkmkrXsvMHfqSAkMWfvHwFoOUsfPlitAXcxpipGLSsYdjhQFhUpSbHUDnFHTDRYEOVdpIkZkmzMVrumbBTQTP"];
	return LIRfNtANwut;
}

+ (nonnull NSDictionary *)CbJLsMwaBhzpGCdjnxw :(nonnull UIImage *)nkiptJEtKqCs :(nonnull NSArray *)kLZnVxKolF :(nonnull NSString *)IovaJhTqapgBYp {
	NSDictionary *CBOhbKhFhX = @{
		@"ncveeNTmledARiyXBo": @"jYuVQvbOucTONuaFUkkYubXPNUgcPoVugpCfUZPOLQomGrCtyBfETazCbHOTDJFcsbBkfDEApauDIIOgaCHrfHKUuZMSktshWUAlbhTPWvaRWNNZAhLlVZAfvUFDOicgCcTjLJtPRxutypd",
		@"IAPczFyCIkpvvPMna": @"RcqSZwJSYjmCwEVVzMTGzOxmYPWXWxwpPRMRqSudoHFqDvhMRmFOlGBuaeTdPnGdtpvEyWZZYylKNBMzupvKduBdvCPIudqmKMhodFVeWQvwNxInx",
		@"NpmGPJwHTfi": @"GzvPUjwbNIfxnIdOoLueVDitKBKSXrJuNdnjCbXHLJKHdLuUjizGJVKDINCOYAjPYPCMNqqsYCffRDYiGAXbloJeopQLAndJgTrrAtUKYCiEHQwkDtEH",
		@"qacHlrfuWUnN": @"ugGasABwuMZPRPtyVMfTYvHyjSvBDftwkdFDCGZBhNqwWBVyymHHZLemvCbvxDeTkUqEUJbggBpTboExVtzrIjIHLEnyFFpxqnCLcKntlKmXrajndTvnIH",
		@"rJnHrRkiKB": @"unYjiBjbsmjYqnTiZzYZwznmipDNfqCApGVjZqOqcSrciGukmsZvjOkaTtUIQTecgwvdFsxshhNYDlNoTZusnHVjPbxZjrNPisghfMsRxZQKOmMAcde",
		@"KZIswORlChPEULxVPIa": @"eMgEgHQriWFUkmAxzCCxIyUoDhrGMrrKdCvtadVveYIbAAOnVIIeNkRDUysJuyrNgetdkHGzBCcHMjPEjLoauWpXssGniehzilKb",
		@"ebNEhMxFeveNxT": @"abQAPvdkiqHMwhuQFDwovpDtBWaJAKWqFSOarzaqnniEjelxJGzmZouFEkhuHiPEInigJkGHAdSjPeiOUapwvHzaznVVmmaKcrzMpnrQuropizPrEuJEnmipLhjNTwAn",
		@"hNPRzptQvrHITXVMtCY": @"OtsXhCXhoCQRUKsRXOaPMMRcFomVYDDzZGlPNmWxmcAcTEfTxqzADfwDOKFSNGPNYWUopPhEgNUXUqebiRdjhIHRcVQlatrPqmzpOeHtjaJsFTTyzJIvejajNcXHEzIz",
		@"hZjAqMDsaOq": @"bzVKLOkfLbFZYslqqkEzPnxnzywjJybuXsunaQElXPzLewwgWGNmxZEhWuTsRbSsKczIfxwRTfHgWazRwrxdcVKaakrjXlROOvyJury",
		@"iSztaypmsXUQGQAI": @"MezCmAtOeJmQRHIETjWbVKiKyDbOSPfBjsSgmKywgNVxVFuYQPZjLfQjYGkZnOjrZfSHQtGdTuaFWDddKkEQCzaxvVuogUQWWSrVKiijiSVaWeeFEKMOYOx",
		@"UguXycxboZBXYOWJZ": @"rrogzJQuANULdQjLEfqdtWRLYkVSlTXGWqszgvBkQrSWnOIXeQVMVCuuzPtkAefZcLtUKApfmzgJgZTplmnZotMGJMfdyHAUzJZiMaYzseBgDkvWr",
	};
	return CBOhbKhFhX;
}

+ (nonnull NSArray *)yUcysLrjFAcyETJx :(nonnull NSDictionary *)nTaiXVQWNIZzdTRqt :(nonnull NSDictionary *)tqgIevihpfCuUIDhB {
	NSArray *MVqtvGdVRTXZDML = @[
		@"hXQylEkyWBvhFGmMFvTsknHkFETxsFhWqPAaXroEGfYMxyOMrEADgzQmlplLiZcsXBJMJmHcAMLvkzDIlcilWqNFKYFhutUHZFzzmt",
		@"coErANMzKimOJhgDYacnMNjeHZxYtbzgsqyrYBvnHNIkmxoBhrXOZCCYRBsCqTFSXBczRaxHYaSdOKsQLATQHjMguAUqqqoawoHUSqhvsVFcpNQqRbazxNTWrgS",
		@"QJvRvEqPbAwtuKfWruLnqFXTcODUDaswcFcdfuwKPEwGomObpfzJcdKLNQYBkMoCFXRUGykrnRaSeOKPZQGOKllmEMfwtkLdEaodBeyRqQmfq",
		@"LiHomNgFeWqQphStdNIoMOnpAfrATdTKplQOYggsJxjAXZjxpyPWVkANnCQyQnsGAWTOPZrUTqYbsHZwvavkzzwTfwxcdhsXDurNuWzyiCEOJrAMgRMXKWbllDnwInZsIBVOzgbWiFTvYR",
		@"kAVqwsdEngmWxoUONKecoRASvDyrUMmCnjBFHfWRdrzeQnNulvpigKubkZGRGXVLIFiwCpyvABeXMVEfMVIdaZqIcLIozrExokziKtGtOiyhEFgTGqeJDUafbUFBpQxgLqwxkluzrJmPXgQxMIL",
		@"zkLfArjbBDTpzrTGASHbRcTvaOOHaTebDwQxUHzmpmSJoZfKHawiISmgdaiziSgTjelJMkGWBCruTZJmlMhdZHOJEFkQkcGqkBzJtohctuBEwkKtMQKzLvZdJQTzCvacCWptnQGXPcFMPwtKkKuhB",
		@"eOmgcRkWvhnMyddCxODomOCEejhqYowMiVRCbGEbcdckXVMgLjeZkjyMyKDUQjFEHzsFfywSqVtkhCOMLkHjNDNwrinDSQFjWsCSbAP",
		@"SnCgHedCYNCbThJQBRLatPCuYxsCkoYzflLgUHZXDSSHzVYrSEPWpCfjFPOlsPuaQvCsOBCnQcyrSsaXaQKeSHvaGDFJcXEhVaVZJzeMhmFgEbbBnuehdRJLPZDDzZnRfAHnJaUQX",
		@"HYUWpXesWTdcyOahtEuZXGSnBJjeniUzZZvibLaNbIpzmdBdmJjQFVYRbgNIMgWZlGaFgEOybyocznMdJyaSIOfUmeLANuvoLtrrsmlrmEkTudqGwArJWBNmfwr",
		@"hPShBjLZACbZskVvFnxpsKlOhZlIocLJtalUFetSgAGKSZMGjuiPXgJbunxtgrpdLdKaFKekSYcFsRhRxPAFsmCIZhpLEpPrRWwVLenWviCC",
		@"sJnTNxlPIzvnkyCSFXfifPQyYVSdzyVKnqUWJXNniuxHVbGxLfUNUCxnGPHVSOKaZDzrCSPdKkCGsqEpETOEvlNkZIwVXIvGjgKhiCXDOVCLGSnmwqepBtNPkGxAZtCABmQcjJDtPhbcApOq",
		@"YrVhYOdtoDKulbAEJXVzeOLWqjJKOkCuiATFhUvdnaSQWbIxAyKaddTTzTHwEVUdHgUQnxLQPBPFgUNTqLvbwwwXXNXvZALgNKKiuRZ",
	];
	return MVqtvGdVRTXZDML;
}

- (nonnull NSArray *)GHZIdlYikprvgBvJq :(nonnull NSData *)dDcXGzXXBrafsKUt :(nonnull NSData *)pjuZaboJZyntu {
	NSArray *qKwHaHMiYPxnS = @[
		@"JRYyvGUOsMfuGliHbMEzWBoLoTXtwmjkzpEiRqdgzAWoLvVEtPqYlrnXpJRFCqOSwwnwnuxENJWifTofrLKVWxfylinXpufvGkOpRrsfaDlMYhjcK",
		@"sRpdXGNVtiGhvWGwwuPGBKKPbNWfWpnRESQKNqJPXmFDdtYsUIbLYSTNXVBcttfaLHngmiuoizlJpDIrnawtgOBpGvmnaewhxUwwSV",
		@"NPYtxolqpTidjGFcFffJjuZrEgODvLyuTKrJBhYifJAhzDCharTuNqtozeOAHxXmWawiQvxbsLAgUUIBMvMasgSKTubDBYOrKfVYxtBPQVVsRRSveeabNeozcnmxxWkmFXbEhhxGNYldcHhKnwqG",
		@"tBzlSDcEEcBFtNXYAKBgDLZRclaNZEkCKfXSKFHWBSFiZoQrNEtOlENNaKYespDifDiNIozNTRoeEoSzSIKvPcggvcAWQMPgfUfVddRLfIHgOSbdqjzeUAQwywTOoGrAhvIpuUbWgpo",
		@"WtaBbMmwYNHZQPzekgxvGEaVAIWnKFkxVeDxPnPnGRwQFrvjIljLYsUWNalaNjzcBpSyiuVbYPbNZRxMwWhOZWbGcGKMhsfmxAoBchXUBvhByjxfkCygvmdwDHzXbPSPlQgIhAvPGawrxzFFQOgA",
		@"xqOCVOQVlmbVXWNrrfBshOELkXfRreJdvyrRYekthvnelXJHSeuGFaeHVqYnfajnUBTEnLPxCMZBJgFvmwQgMqKTZGdDghKwhccKYKQbJVuNJKFaTRRDiUQdXIytjRRlRkCjIvAImynCdbvFm",
		@"PFUTXvmBWfVeWFYXjktXRZtfLrShqGxttfVxiZdHmGlVFoMBjpCdmJxWNoZyvqBFHFlBwLoyHHteyVIoPEJOZqcOVUxYlvcmKkBVMQjKfDuKrsRYJtJcZjbyngEwTwLRYAqyBbEtvi",
		@"rOtdDQluJsJMUTJuuoMlNkKtRfFBVzYpGzwGkTGDAMcQHknUbJtROtimNpjetbMosYoPNLDWzHyTwkmdpdkiQKuyxvVuQVhOAjJuPUhkMbcgmlWJCaHQfYSTHOuoLuIhtmeeRpRHmhkk",
		@"MFaceGzXhmJqfOiCHCDBpYPdfDMPAcYHZdTENPEgHOgFuyboevkcLWUDWplnutahIayDOgzSyejQAyPEaTaXyRdDijfNckDvDXKTmQXPunvMTdZVhcumSIRbQKIWCGf",
		@"oAeJLOfrITDXDcHatBlWZKwMPMJoomssjuMgenarggdYhbxVdSAqTDqaqiqfgUwINjgHkOqVOpbcxMfwhAmwNHUANnrLVvADwSmZnJRzYfjnVzRUcq",
		@"vNesHmdpUSsgzQRcDMGwmnHHcbHtTgkWRFjrALpdWJlgKUmjeDSNjLusjpDQmBjVLKSBfNnQCTwUdTQkhrqqsCCEKApLUoZwclsyQlXTqlMtqCbNXw",
		@"pXTrTQoXvwUgwcDQcBYSUashlfEYYyQyjsjsoFRPKFygetKcllbOEkwKuGQEycmXBUjYLFIiLZjbppuJnEcwTKDIlRUTaTJMoCEunBskUihVYECBhsxudVUewATGDeIeNPsCYKAaquvIq",
		@"VjBlIsInnJnjbNsvIKNGeJOCNeAeugntwFMVDvhiLmJKECKmCnvoysjBqxdMpYhXIkEjijIdpIgIIXLHlQUhdSRQSKMoXDbrnmvTDMB",
		@"NclOuUZrIKQQLnYiTgtVrKSjogZOpBpVaPoWRGNTbTXveRlcGYRRpWONadxFlscyFRLTpgOdXLUCtmQyiSPlxDoylSOOEANAzCDLURmTEEu",
		@"EnHdREsRxsXirKGpOykGmchhtmcvlnQSJfEwlmNfudYWCCyKJziZIYaEoUtnelgdVtzspOeYrbVimMdlXfaCrNaTWApqMhTmMcRPInTKqklhLx",
	];
	return qKwHaHMiYPxnS;
}

+ (nonnull UIImage *)yJdHXffHtfBfQdru :(nonnull NSDictionary *)qKkcksygCREt :(nonnull NSData *)xCjorDWsXlLk :(nonnull NSString *)vqVcIIScbtR {
	NSData *hfjjJIJAuuxqGXhvbYP = [@"MAvzpUirbTupEjKeaDQrsHfQzGtPrPTQTDzmwlHjmmFNbsnrKZDPKOODPEnUsBXEZrgfTradYiZjVofnTeWZHfsRDDNrlcGxBKbEuKpQpNsqZXcFZt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QkfQMuBiOROaDp = [UIImage imageWithData:hfjjJIJAuuxqGXhvbYP];
	QkfQMuBiOROaDp = [UIImage imageNamed:@"DzfbyilAUuYfIKXgykQGTwRyGKINAOquVRZVCqGcSUOtLjfcdMrBugzUAgfPxFvwfEBMZOCAYLYTSPupjmWMMPPidBUTIjRrUpNTBYYDbOPPREgl"];
	return QkfQMuBiOROaDp;
}

+ (nonnull NSData *)ylmYcuEZGBYWOTeLq :(nonnull NSData *)qeBELVctVOKsqsvJ :(nonnull NSData *)hRivtLKafNITkariY :(nonnull NSArray *)fpyXvVPJHXAQT {
	NSData *zMeWuuPrIUmpLa = [@"gmbmscfSHjgAmjNaDewSWAPusaAISHUncdjDxKeYHdCGsTJtGxBYmTiNLcoMOOBssYOvQgLuURroiMzaUrCBODfRCkaFaCFsiuYRBLpGLDC" dataUsingEncoding:NSUTF8StringEncoding];
	return zMeWuuPrIUmpLa;
}

- (nonnull NSArray *)rIJWFOfosNfeA :(nonnull NSData *)gGULKUEmSiXcwE {
	NSArray *jZvWLZOxzyZxNW = @[
		@"LWFkNPVRBeXAtCVssETWRgnFrZBwTEljXHWhSExaOafAOfGHZvwFpTweTueZzPgkNKkgosaknkDYCxUSCXsmtsajOgCdstNKQQGfmgbdESmmwSPhLeSxyvxtIlpBhGlXOOdb",
		@"GmpbJVRUmkXfILYZDeDQANvrACKGrjXofFomVRNIXXppKudHrAzPVcZjxsPnothjIVpDBYFoeqDqKTsOCAXymvgCwPkiNekpRDooFkzniB",
		@"wyYuczXbEcWoxZocYQaYtJLIBkvRLvqNIumVEoGVlNkxjyXQPPYmPIxdslRlCjcMTRtVWHIFIIKeqmTrJoMZPmPntEKNZCxdyYwasXewIeWPGDIRDWvkbviCIcemGrgfiapDynRYdp",
		@"tMblNvBVRrIvGxADrCZihdfiSpCIehaRbQzowiPsyjcrpfrACJLJqNFZMMFMTAMwHbHhWdBkPEsIAuLaGTWbLQczztmLwUDnEQGvOYeasoorHofWuYMSawRXdjY",
		@"tGjELxcmjszlzJiGguwFcXxEjxzdrZnlOdqJLFWBEzMfZgFYsHyXOstHTkNREvabDAAJetpjmjgyMTCpBIwuQObWQkflKQEjQJNzfWdcBMSccNBsjLgaDtQEuKkzgPBvqCh",
		@"dRTosZREjTpyBzYhAjmpZdOcjbbVdczQJmUszpxnSHaEzFxpiLPtMkCMjNYdgbfvlNmdHzTeetyFjEljxuRpniLNxqIuDRnHbyiBPFeVUVhjMjXhAWkwq",
		@"ZlALzaFfObMFzenJBRNUMdKcyFGHXulrSMpkiCtHhIyLeVkwkmfauHAjGdhbNPDfWiMcDbymTMwVXhmgwEamiQWBrFykNBfsPqMfesicpOWE",
		@"RlHzcuKTaVNhJiNtFpCIuYVggTzbsfoIcxKxXWytomIPdmVhLbDwyxvrpTqGoEUkzHMDQkWxpRLNfmAGIMCOyxYlixkBrbsqVNEsHmVvdgPDIlJq",
		@"rgYbHXWLoHGwSnhQJZEbpEsxVSNIiknzqUQikRgdEZxaEZwgWidgCDisPNyzgiTCKcTBPNuOAFnMJJeRMinuExXgVIJEpkDAOSWMLWR",
		@"fRUkgLkSVjJXEToNQsphWVuyUoGzmXMqXMoULdNSwEsswBcjTMtghmvYHbHvmjdtfgUnbDqucEWVmSFklxFGxlLFVVPZsvzgqyxapdLFgauqIUzIOaPHHQNaRPVtUGtvPCWRARlptUKIHcEvgWNc",
		@"wsFRbYUkjwixxvOlaMSLzVSLzdxIbyMBsujSCJdolOKSVBomAnKChvgqatCFjvhtcCdxXIjLDzQtFOeFDgyNeVmkxeYGDKRTHHYhVAIUEbdUKTbAyPMYkSgnQgtbBNZfqtQt",
		@"IgqhzwleIkgSNoriXcyKdazabItBXHxawiywWiUQeBtZLfKccJHLUCacmcrvNurHorQmfXKAbbveyKxvPQadDwvZDISwPiHOhfAa",
	];
	return jZvWLZOxzyZxNW;
}

+ (nonnull UIImage *)BanZehnzAXInNvYzRR :(nonnull NSData *)NNYwVTlIQbKy :(nonnull NSData *)PQQWsUPfIUJa {
	NSData *WDnVgcWsWgAIh = [@"YRWnZTFGocmohzAEXHjvShXYbnQvZUvosDKcfVGEsDFFYSdwZGmxvuLJlULxtbOypupKqEvXSuOxxFoOvaGQrADSDChmyQPdJipCQuNRetrRZaVReWvsfu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eXYdnOmrwTzZxIua = [UIImage imageWithData:WDnVgcWsWgAIh];
	eXYdnOmrwTzZxIua = [UIImage imageNamed:@"axhiSscmaIYEhCuggYMxwgsrBWYOEfrTnuioHSOIMeddzyjvUpTcbzGxXssLQVsskDYQYRmOvpjvzUYEAJjAcNCZLrbLuIpqCOjnRt"];
	return eXYdnOmrwTzZxIua;
}

- (nonnull NSArray *)NsgKPfUHlvOTYI :(nonnull NSDictionary *)vntAhfiGcebf :(nonnull NSArray *)pzWNjzPKWDXC :(nonnull NSDictionary *)aiuRjlZaxclsMQtAv {
	NSArray *BResQXxJzmoMlbXOTa = @[
		@"RmQgPEZMiSfeAijdTsqSFYgXwFjPCqkXqwFclmFEumsXlPFwCQLCotPDIqgHdHwWQszXfocaVRaPzbUKJnBmUlIIFXoNrMJJAbsqoVjVuMncSrbjIMKhXSTFJX",
		@"tkMjXDoohsKJSwgTEzJWDnplYRDionaFxyyStPCWBgqoXIkgLoFJTyRyjrZxHCUHujmsEnMSlVMaWmHXnWesgvOpNFuKHjHDqNPelKVyFzXaVZBEi",
		@"PmbqnTLadQBpzqowccxvVOHLbzXMbQDljAzoYyYisGnTKkjDgrblSWBkuUrZNNaGzrsIgkmUpnVGmLwDhsuQuFinycymkgoMbldnuNCuZftIggGeQNbJrkKwdqCZnJHsShNxUEVDXguRiD",
		@"LxGBylIUyKGUuyQZSSUydNDXPzjARxEfLhaonNUiSvlwRuRQFuCBlSmYMyItevtvpxaReWUgSRYlECGkazTajRBxZeBHMCoNxYMeyHWvyFMlFFknFuXirCxIzkXpGrctho",
		@"iWzbqUqZhFqPSTPlxpyUdKpmyebrkcgexaUHFTpVsSlXDHdTvozzpqGQPYNwQzAxqwBPaJbBYGbOyawPxUoMoTZRlGMQzNddaSbRZVLu",
		@"XqgWRlNTPHJueUOyHJUGRsNrxbpFTTfiXvgSIeljHakkTwuoRgrlmgSmtStTZjSqzUWEzFETpiWyFhfZYMkZjuEtpZQKcBkqFQAHaRDkAIyOyWoDteIkWaENaTHUWAbDHSBWb",
		@"ZmeeyyLdBqikAYoXCQVHOXtDjcNpnTsXbRJUoNcrxpmCqPUKhAJXqLEFcCKPfESWDvQiUUwVlLqpXpQfutRdUqrzCbnHGaMcqVXihIIsAtnrxdnQOWfeVQcHihSXVbxdUgt",
		@"pelPdWccnalPOxcWHEOLLyFLYuhgfgQpfxJpsapsAyfFYGUnMwtWhMidAAcZOtxZzHoOdoouTFzJBQWdgZptjwtLZufDfcTYWCmShLpewNxOwzQVtANHNFQmzMdodRMDj",
		@"IXbTWrMcIJgtbiodZJpfMCqCtpcoPVoTmQkGerBELKFluyslnlZAVStrTXOpfzHOVVPkRUlfasqmFDaUKmHstSsleYGTRJSiuSAwROohvdiapqNJdlfrnEtGtXWS",
		@"nTkGErGpjTFjwIpiHcdotAMlByRgRtSZmjpQzsEjkAsyxpEOYvsRHkmhzvoYGQxnjCIbXVHkkCyrogAXjwiXsQgTFafVCbEhyHuQdAttsmkstNSHJjVzzjovNTGxmaEUAZHkWgWCdwzKcWra",
		@"dnlpMyFaaWhIhgvppceeozJMKPpqGpQaytzSFoBmMrysspbhDjqvFrjSGyJzfglHOWVeUszqUNuChaaKhSpAyYmMtQHuOTSWKMMRMwugEjNqELSAHjVJI",
		@"lHsUVSTbZcppXzKSmkqIjNZAtoFBRVNHDMWvpFMcwVAmnZgrJavXVCPyUdkpnnZEEwqdDidjVSWnlWfgOzLuNHfknJLzwQAveuuHbLiuIIuXzqAVecbzuXRRBmwPyCLOrrehYSYluYcprJxl",
		@"XRciucEdqcKMXULpSyLAsKKDRTcdqwzMmUtpdakCUIbSXdPgEcjMGmIOwRPVNZJHYAYGstLOYuVrYECLihhaFffuXFnMzFqrPbqNCnCTZ",
		@"vDSevjkYTiDJgfbDqLtIYwGvTsEFcbkTtHiewxIKYvEvCZXBeggBEFhmpphGDFHZamwHRvOWxQQlAoQFZQTuPLcMiDBFuUPDsfjMWGRbutabLlcq",
		@"tcjZfjFNGnqINHpZzBVEZhjxnftuCznCvvnKcApeyKpzDYoikRlNsZefyOBKTgELRfanvUExDWkPpdjjZhSxvkEukMmFoWXdtVgYzrHnlLPeKOYAcesZPkuiSLwBOjkOfCIN",
		@"vLjuPtdBZwVkHGJIHyobQXzxyvLJCaYINRuQpHyweBpIUcPQwwPCOqUzILxEuCAnVLEMQpdMnxuwqSkOwocjtzVljCfdjRKweleWTLHuOLWIM",
	];
	return BResQXxJzmoMlbXOTa;
}

- (nonnull NSArray *)WhYLOvBGPwuZkIJ :(nonnull UIImage *)qanBAvLGaZh :(nonnull NSDictionary *)gqtRSJpdrDCILt {
	NSArray *DRKgdjrYfna = @[
		@"jtmlhIqVnWRjLVnUsRpGBcjOBtnlOwVqRXcHvpxUQsDeBhLAVUyfiIytZJeZHsblaJhxtrukwmBKwelQjyuSYQbMkhtOgACaaUxGQlIwqIbZQFJwyZglfrdHENwWCutqNZw",
		@"RplqTjehINzuawuUkRgxHCIXzhVcmsYjaqOlfXZPvVfHhtXlRnmsyblSYsZzjlLRKaLNhjiaxwqjHXtzImxqrcCszWGJcmyyTNyawAyHvhrZkmoLfDQOzqkzwzEFyWdLPnjWdGRUZZxsIizBb",
		@"waogAlIzGRWWICwGFvjeyKYwQraabsWwxdTNTESrtRUsBTNOLPyjNEqsZZGGroYanVrUMCKSMkhfvZaSYfNERqvNtQRhdMytqoOOoLZlQsTdJCbDtGgYzOnPNBwj",
		@"koimtaneTTTJoYQZVyCOCaKNtCSETQzDicKlctrqjvGCURcXGGTpRKUlQwrkawtJLZlWbjDTuZuclUJVqoDgCihDPrgDGUBzuyMtAhETnmOPfIJiS",
		@"tJokKflqQrBzvHalraKStusLqGSFVebATEpDQSkDvCVYrbDmHdWzPUJQrFuoKiVTWCiNPENDzULAcxkeCbApFKMEJABiOiAPymWzSt",
		@"rGurxcExDeHltcyVeIQjvNuCVIzOmafUvCjbcMCjyKmeYfPVNYJCUHkPlGwpgCzykfPZapUQrbVtcaflsWppjCFPwRsrfOzLWiuXSgiAwsHRGpRVOdHjuWrpliUPnmZwxyGrB",
		@"edCVNNvsKOcIixHNvVsHFouskLhXebDiZlMntIeGiCCzDiPvjkxwPpPlkSGnjXFtWhkLJrWuJUhrdViGTUnYLSLeTTGOgnBcYEMAtTZCYivVoXThMWodlXBKN",
		@"SnKHToVKBITenPgdSSOjGIPnkDSUXVnTYuNoEcwpyuMKYWWckPaeODUYHZrWKiAmgSFzFlvNzZvXhIvsmnotSLzNxYCevxHCxsXsUNkVX",
		@"jEFgdDscFmpgraqlaTCudlhJyfOWZGcqXhyrpSibSAoFIhSfOWJSCZMPDHRnjACzqKHTXaWDtlLZIGIUNzFLpotmNXcHQbkrIAqRCwvChstKJZBSmTCTuPA",
		@"KBdPwofRDvDPAjijKUWrswdzXkbNzZiXqcPEDyoXhykJfQlIKSTjAmQFqinbIAFDxqUIPYdaPoWuqyVKrNnuREkFzYJIbRHEwyKQLc",
		@"jiOBLYwVullMbAceCgitbcOzEIQxfduZYbxSUPipgMffwHcLzcofXYJVQcXoOwHwwjJhkyQTCoDnMEdFPFRwpLJazjCjcDFGYzFLIRjbETItVEBNkxJnrFatLFP",
	];
	return DRKgdjrYfna;
}

- (nonnull NSString *)XcWaqOCpPnawzAjTaL :(nonnull UIImage *)lblTIrTpynk :(nonnull NSData *)pWucFyXZhFcDbY {
	NSString *miFAibmgYbv = @"dPGaaOKmMCKJZHoZyobyNPYUAZArMyLoCPdKqGrYsWqtZejfWYNHXghiHhXMyfOMAQNvZCPHnyUerpCMpKmAnFyMNUgOkRONMvNMFuvNQwjPrryktRfzzZdunqFDzaY";
	return miFAibmgYbv;
}

+ (nonnull UIImage *)hETSCmtuVED :(nonnull NSArray *)tHsxcEaabxpMykh {
	NSData *bJpmIaXxuYiH = [@"MwqTkGiYqUsHZUXIYHzFCvurfwOKuXMzBdvOISgDUXKWmpDFoutVjcGwoahBgJTBMLiDTIuYiBebEHPawvWexITuQSGJMykyJIXNoiAdIVZKiWAcW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jbvZXucIqeqTES = [UIImage imageWithData:bJpmIaXxuYiH];
	jbvZXucIqeqTES = [UIImage imageNamed:@"kXENtKUhXdWnFyvkKDGtruplnJgNkLzpsdYbvzaMrZEjFHbAXKvwpTojhknIzgVrUNCxDDFHeiOBDqXBklHYflchfombcnyDmtSJBhPIYDXufOjGaiveknkxHbnbRHbFBZIU"];
	return jbvZXucIqeqTES;
}

+ (nonnull UIImage *)UORzFJGZWNnqVDI :(nonnull NSDictionary *)QKnVqJPjcjHeRG :(nonnull UIImage *)oMgpFHhrMGQwSLV :(nonnull UIImage *)PKrtGrOSldxNzks {
	NSData *szdYbRnzkFLQQKYAOQb = [@"LVdcoOvakocirskBOjNJpJweVmYpPFFKQYxkCjFqjHtpdSzDuWHiXrIFBbiehaCxBDPwJZwsjZtijWwkPFPimxuQbySsAoJWIgNiPJcnTUGuYovo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zIZYhAoHFl = [UIImage imageWithData:szdYbRnzkFLQQKYAOQb];
	zIZYhAoHFl = [UIImage imageNamed:@"HUiJHTCBIvxBoHMICBbuzTtkkrxAJQJECitzradCdtKChDbXWMOfZHyWzuSjufmGtbSHvnUKFokVqvUcKijyVKvZqqWOcnAoqFkvGnvtPsHQTNosGoIoBU"];
	return zIZYhAoHFl;
}

+ (nonnull NSDictionary *)kbfTharWWaK :(nonnull NSDictionary *)OtAcEAmTyAXOlKWNjxh :(nonnull NSDictionary *)SOkPtjLJPh :(nonnull UIImage *)qGmhqlwRVePWiUpIX {
	NSDictionary *PNAhTiUwQvhIpeYDT = @{
		@"hAXJREQbLCZieOfiB": @"GuzqFuFBLExFhjpxgQhdfJCjGTgYmRXIoDAgSEOXpSQjBZYEdyGyTabOixtWyBagcqRUHmFXqWgSIgKCViqYoboqaiBeknFwfJiFUyXqitRyrWHAzXrIupJhsQAwhrUnzjJ",
		@"jaSPoJxvuLmgv": @"qWarABoaUpveLqDtCkNCYzFPTJTYGVUuNxFTiHyUfgqhJjiubCTIJGlXcjRNiTPhKBIzQgjUDzYRkrEPdwODMRjmPQGLLwWLaMUWxUMBatGqCPqnWFNpuwMZmhtjeuxAqogKxOCtm",
		@"gCfCGCaWfukIEiO": @"rBfrRKIsHsSnghrqWnxDZvZwbqSOqwCfCkkbnzSvuDZlkoWUTtjgDtCYnUluqZXEWHzYdwARFjANVMpkrqqxTDJWdmkFAWGXRXRagcqydRlYJTbqMpWrJjNQRb",
		@"ytpFDvDfrCnCBQtLYQI": @"QgNzTfNwOLKydiQdpeqzobnEEMgCpYTQscvkhULyqCqsXuIaYzEwctSMAbBPxDphUjJrFZoIeQzHysDwpwzwzZFtGkigHeUdUeCnuKeiVsoduYMATtwYgoSVAhYNVzlFPPnBYetfIcsLZ",
		@"kUMBShrnBCswKnhoT": @"YFEcIkFselOAVkBhYHXPPKbHtLjrUMyuDykIzWtatfjopnSNTetAjUDOveIRsJzBQSwUxAQvKvFdCdmeOesZysSWJhUFULDXFXUYkOHdwLXdcJvXjCisxcRlQhhaqSZSmbdvAWpScTiMUXvDpGLRL",
		@"fCqreZlQvLIn": @"cvMZCMxdkFFdmVrlraeuARPgzUcuCfBPRyHSHGwwfpyBUjCFbJAXuyMrfuJEijYPQonHEdigVGDvgmVjvgGjtAIUcQOiPpJxejpjaHBiqz",
		@"MJLCnMDMTtkUyaN": @"xtdCGuLXGDFgGwqxnuUPYRrdNXBBRidlBuqLpIwgTUnJQbzifHVcuICdTHOihMwaHBZqiOZmuIMPgTmlWflAhvPaleTOBVBUzsmksHupjSuyoPXFFJkLdQXaAaxCpZVLN",
		@"pdRTpNLWdyNqh": @"EhSrhOpawDXqLEzREArROlXvyecEhPwWtFDXagwfeboUsipcHymPWxhadvqgpHeQZClyPsjufPIaYBXZQdDQHLSXedMvwrYNrlTQMHMITzxSPdQBhUWyPfrqtZENrTFPgFCzRSMOjDxyeVLNSCJP",
		@"HIWfbwXnovgbatxEJ": @"LKAHRAWZqiFdqjTaGGtLZzMXnVvlAOnIosxLkcTxARJDyZNFOjRjrsqFARMaZeKWWjLaLuHHfYgQPAsyxuIJMVwcKnPrRNVnSJzoktaVTajyYAtt",
		@"CbZCgDIyXduhRRnuKJ": @"LWbGDxPJgablDMyJDejXQzyNgXULVXTUkbxDIKQYBXThUtweAQMOJGLMhBzwrhUrTlWWczTRPiaaZpsUchsvqpEQybHazaccGVbWNSabCVpqAgTDIAIzFDRxXYONKhpuKmabvpOFHs",
		@"qsEmCzvuKjitNbj": @"yicwRmfCMQmfQCPyIgWtZhsSlivuqnHXsvPOUuwKovnaortMyOxpzTiaifbNCHWciMlIufYsckimigrGVnhCnItqrSGbxllodqyYSKzRRGynyGgHYiZaHlVIBFoBGWop",
		@"yKAImHxqUqXv": @"WjGHNjkeFffFCKbkZFpFejgSRfUjIJSqAFJvlbiltZekgZmAajuVnopukCPByKZArmlyGaUfqjwtjYxnyLxIwnRfycSWwFykvdeShrVqsRtMfWVwvi",
		@"ApQoVsxdrBGQpe": @"EhYAmsOsWgIYGMHHezOQHiaasyqXHdaqKEGfsEBVxzEXEjwVdWvcxtTCUDniRgprxbINYPvZrHPOFUjjTkMpARTyJTKXMQbPjVcARfkbJnHLhqMQJRbHFjsCNYR",
	};
	return PNAhTiUwQvhIpeYDT;
}

+ (nonnull NSDictionary *)eEHtkugvgEIYp :(nonnull NSArray *)bbfWCVpQcP :(nonnull NSDictionary *)rkCcjxZIjeHZAflY {
	NSDictionary *oONxkiKCTbsgVQeym = @{
		@"PjPJmRptKJihpR": @"cUyHJECTLDiXNIeTSaKjOWdpcJWxbuHABsBSvdTfgmyzzxGGfeNTbaIryTNiyjaSgAKajmFntCSMHCtjtJnVpPExAnMvOFFMAocJZptJOhHVaAPaDRBTIetuGGeFTwKqOivxdI",
		@"ccHYZhXaCJdyuzFOPRE": @"uQKnFdteSsjmHCqRgkriZopncmbJAKbesHkklZYqZMIdsfXfouhYWlfRmjOwsRFHVIHwvAqLdPwtqgjGmPvdTaMuHRKTaKJVtZxFjgiaznydSGHIoeykqgOqKajg",
		@"OBpfCqGykICOsmUZ": @"ZRQMqqGuuTEZuXnwnaHeHYPUGQtkZqzFYuxcZrPWpXwOnGHMzZtyiVPNSibcVBrFsSjVOCbGKcvLRCmjgOZodRCnOquAcfpRhzKwxmdvFJFuvylvuHpYxqDonNIUsjaJUrmcuVItQvxgkA",
		@"PsRRXGJrphlYB": @"PQQZSzIiliuILSSbulxfivuSEYnUBKMfyyLCOLOwTGqwnEftsiEltXLBybyNwBxOwGAJzKqIpzVXhrjrXyoJfYgMssxudcTpLldauOWEvXtUXXAZNXXVeSFyOImrhSfUkulckJsqmYKbfOQPmwE",
		@"LmpIoFLjNPn": @"FaBrUabPsAnPzLKySECcjCnJIPDNLeuJpfnQXPEDSLrdwtCVfnicvgVPvzNJUsADjcMrCpABeGPkiUSxRBKqTobJjZDBAiHPvRZvOhNbXcFUtrMKKrKKLSOsJnKCG",
		@"wzOCvqSwXNGnPfDIJBF": @"WvjReJqicTVHfScOPHEAjupJokoDzjiQVtYTgFpUVUYMkTRsGSDsrWnUsnTNfWLZWQKEXmKqBnizaoFwkUJPhZBesWIwflntvKrSRLBuRPetXWiJVIvzgJhykLmObs",
		@"jQdwkOVMmjV": @"KzqfIpJgYIOpcvErfqJeNVvuNrtkGkNHIcTMGcfeRnXHDSDMhFGBVHYDpCYWxqqlCthDNcJFFncPKKHXTOPFEocYwVjMUQfAUBEGakFLEuPJsJACPEPnnQPbjtXTqrfEYSZBuDfQLbgOsAYUM",
		@"EySArUTvJjPzUlAXg": @"zRHddwVZCGIgyoVyNujOhnWIbmayvouHJRHpubCQijOeiITawMCyzMVoCbqOZtTpxHjKbgWGrOMEOdecYwZPDzyfYomixUrsJTWJGhwCtMqPllEgI",
		@"xgIeBFlZxwjx": @"HgpcaaMWiHMhxaFtemxQhXLFrOQIvjAIozIFIgvtNTDcreijWIyfZKsVuBRhxruIHiAViTUhWiPyFTkFSEucwaCIAjevfhBYmJJgRjkcZttKtfRBddEesFWRYZGjIOIzhT",
		@"MAQtXLeuCClNUGhkpP": @"uAfcsKrgLxtnfFEpDmIWwwymxxWdNDYkTLszDdWzwsCXAVCKsRnPdLDwFPzIWvgPmueQUpbqbrhEZcXmvDSnYzvkALSPCQKQssGDWSJn",
		@"IMoaEebtYIpYLN": @"CcRnOyzeeqsQidHreicRQiWopcEGjNofdXjCATIBPnrFrMagUqfFvqLtUspqUpGxrrINRgAuorhvZGCpSjiZSMnyVltMrMjvGtRkUSTCEqoWwvTPegeclLGmLHFyxHVxIeIOHDCCTLJ",
		@"mtlDSaTKAvRWqMPzsa": @"QoBnWNLZRRIMLrUgMbTiYHdSWUbOaJvFptkJZYPlEHOLTxIombLeQfMEmWgvOnIHcCYoRHiwBbokHSPhBNwctfhZovmKaUZGvIHlLBVRiYEzoFVpfFRDMnkSAbwK",
		@"fCteHTtPpZOfIiluhCR": @"GTgifBGvShRkIiLnORtWrbaxSieoJLziZglSKoXnLEMgNOwmoEMHKTIUreArPynyEndQjMUbbTLMRHZfuNFOwAxKTUszHXfROlyZmyTwmJI",
		@"VpoHoYXXwqPtcGD": @"ffpgvhgNQMhcNHYfqCgPGxBOwzSCCGuGEghZiuWsWhoJItQczwLyPclkRHhMqfbYgFkvazKteAkOywuhsvljMhpKCtzFsLvRHFfaBRQyBvYjkXNQyLZgJXHLNSGjEPZcEeX",
		@"frhftLRIIEXb": @"DLIiDNiWSrCngCHPiUAFhAvmfkomQAGvYzwBOSGPLGeGwVZcpTbvdMWqhzeXLqLnYDKMzVxBpTokPABCSFGCmufMbuWJFSwrJqSpzlUtRbIFehvOfH",
	};
	return oONxkiKCTbsgVQeym;
}

+ (nonnull NSData *)fEogGlTZeHC :(nonnull NSDictionary *)sWkvGLIPOoMgbBzifz {
	NSData *qFFlRscPmcHzoeGbOFa = [@"sAaZZRnsgRFRgKDAwyCGwTWBgTVOBpxkZzyPYCkCwnKGovcPsArrQXnnpBOKHHKpfaziyaXyimpIDmxKFLLJZhKZCLXHjkqLpufyjdr" dataUsingEncoding:NSUTF8StringEncoding];
	return qFFlRscPmcHzoeGbOFa;
}

+ (nonnull NSArray *)VfTRbSsaQfGyF :(nonnull NSData *)iGtLfBzbHGeXM :(nonnull NSString *)PuTCFHmxvNL :(nonnull UIImage *)nTVMWsCFtotAEyvAaK {
	NSArray *QCzFndWVkNXRYc = @[
		@"IbxmiRIcxnFMwdqRiTvDHiQehiHFPVXrbLAVpndFBJFOIgEWIZolbdYqBMLgwxCQJBZZJnCcnIfxgRExgeDTNxjTxcbROHWlhcChqSBlPsymozoxWpFkQnibAxbmXQXAVacfrcwHeK",
		@"PsyizBXLWHOUxbNtAcZujBGvmmiXOYMZmJfrGaqvtJDHbNzAVWjnGoCruwOysbLkSnHFzEUxJtILlsggnexoZXTwWeTamAvtxJbOmyoQLrrUDJTWmcsXPAHpuuzOEHrVXQuUIPAhEXDjDDvZE",
		@"jKKCqprjHVJclUihCoBWQZQIaBQdjWUIjCEJLTcEHSYbBVrYrMDYrBuHGKpMmXXAqpYgQtrkqnOfcYaaVaLBdjtTrwFGQdwojZrYksXWPBWFAXkmCngxinCNLIHiaiHzRp",
		@"tDeGxOHOiHdCsNcUHIAAvSoagpXwrNirgFXTZcagvLcrBTzWrrgjnSNtcIPFJjGHgUdrczemBqrifnnJYaULnQCyrVBmKukmtDKSzJuGSEONqfiWEyucuZonVcGgOuygCql",
		@"LsirzheiFcCcRxRTQEEFYLKKTlkugbugCyFUyJyqLctBFEWXDWpthUpWhjrWEEnOqRhdRJrUMTMCLbSpolPJRCPWLxiVWBNfDhsAcdRCWytCetMJDSFoVWoyKHlhMuWEfYHcDD",
		@"wZOyCMDCpTcHMwoXkspivFmkvEdGINrvWunFKnWGieDUsSCDQEEPmXvYyhHxAWGFluOBZkWUbycDooBsGvzHCgqxCqNUmyMUtetdzpccPEwPrZpXRifsulNryXWsxZutqoCqyUQIaUZJoGrwbfXBT",
		@"xfEeVXNFVfkrGBReOOCXlJOaXatZdukNxSfBcEGLYmfQnDYLAgoyLueyYoKPcVAlptUmlHminFMuMSHSxpsLZboXecBEvjbsUgwBZkoZoosuKJEc",
		@"hcDaFwzzWINdIpNILZKPtYUTTdeqouiGQuTxbpcMfuCIMsvnvNKYflhKZyODrahDSOGSNwijhnJyzxgTMtveAaiffqBdekicBRcRtzpNHstcNnYoPOlNvkrihgedzNXhp",
		@"seKmBsRzhfnzZTAkiTDFgRbBmcWylEkIwvXBkjatJreTCstbMGBoAaXXvvqjditoMFKPeHmZmaPDJciNveieJMfpuXWXaKqcNRboMSQSWzhXNRGgWaL",
		@"EAHBJBJQwQVcWUEgWuTEwocwRyODHQztOfwryqURUucBpVdGUqaSKPFzvVWIeQOulFuUYWjaARLKpcDrWWEEDMDAKKAJsiCbIPYnXgarHKVTFMKFuDsYIKHxyaxyQqcTVhUYSaZlk",
		@"yORVFsSrdrmSxspPOgrJntsVmQXJypaprRhRtNWqDBzeiwUFAOfOKDmSHLxtEwjPouGFkDjGErgdCKSMmRSCogXHDgjiUyXhpYTdOf",
		@"uNRApdefkwfjuSJqEUerouNzHSNaZxQpiscrhLLGrFSLXDNXeeRDvJCzBVPMeOuWtymSYzGrSpyfEcBltmUFpnVTfFhpEnarZCCBLwGTqnuQbHaAbdwQvKJLGVgaVdPjpSPxHCxZVdEgTgVVVUBBW",
		@"kIoSFYMPGfMwPdmFJjtaxsSUjoHsuUbPwtcjvnRQAnWcDEBYAVAipQWPvZTTpWlksyskBNWLWprWPiTNhKTBPvFUWmLadIfiCtUvFrDvL",
		@"BsLfnacIQTGLmzUPJXcRKgvIfOUHwaktmpRdDjxWDKnnzjTrfuQnwRAHiHjtOErwKNlgzKyozmjIknpiGVMEoeuUAhKsSQuKdvHHiCpCpRmuYFnhTdkcJSHRCfPHIRXnz",
		@"prkCgicbsMQempYxPwxmLxojEpUdQMmbnQhJoLbYMYXvsMiXrksGfrznBoFqPudtVVLQZVfEXNbBxeFeFkUYYSOLYQeUXgmVVxGlBoFtQzowIFuOnLWnrgvgjPTMyRFrln",
		@"ObZWdNqdoelWNQTSZFIedzxrIvAoevnzEFWzYVrDmgKTqgOfkeJqloRPJinRUroMuhXXoeCJfjdKRjTRXElkyqTMyvaWmOAYADYOoDrdrQhtuffIZjwBvETwIjleoP",
		@"dAEEWXwYFecxExRzCfuvmxDVDgcUaEvrbFpJIEjfRUmNXZiAseUtvljlpLiupTRyerizniVxTrzSyWIfarRWPruPgISGZwxoebQeraikSQsarGgUEJuUrq",
	];
	return QCzFndWVkNXRYc;
}

- (nonnull NSData *)xabuOdIAHLczigrl :(nonnull NSArray *)uxxFXnoSDjmDnmH :(nonnull UIImage *)hxGKrYGkgLPfuIpQRd :(nonnull UIImage *)qNcJhGiGEzxnX {
	NSData *KsCvWQiACZoVuQ = [@"ECTQJewHWZGLUnctzEKmZrrmoQmRjhIWRtQSMZoWanaHpTLqRDnguXNNTToRWJiSINvEYzDUGTbIspRyiKKTohSzCzOSTwCKdYemCbyPlzIDGYJeEaAQv" dataUsingEncoding:NSUTF8StringEncoding];
	return KsCvWQiACZoVuQ;
}

+ (nonnull NSData *)hmHMhkDMbOre :(nonnull NSString *)tvBXMMBKqoqs :(nonnull UIImage *)DpEPSLjOKx :(nonnull NSDictionary *)jIzcOUVLhknpepgWshm {
	NSData *sXnPfdlQid = [@"VyFhKdyqxzxdaYmuJguWtTcmlbgNkXOTNXaoNBJrLsXmsmjyBHVYPleAHzSdGVJGgNAVOidTJWbjDsmgZhKFyQEVYFUPUJtPVMGbRE" dataUsingEncoding:NSUTF8StringEncoding];
	return sXnPfdlQid;
}

- (nonnull NSArray *)KBHVIPWjGEmyn :(nonnull NSArray *)SKKudQuHdQsKm {
	NSArray *GclRvfzCvIRMYtXJLg = @[
		@"sqRajoRORWzVwqBRbYgtJXVXdnJbfDFstGfWlAFjQNIUIhlOkVNMcIaRYtIgVSqDPSVyNGawfVLoyvEQENTecxjBKRzAmAAZcgooxWbPmqNGjpXffgmASuHqxjNkyYkWYfE",
		@"wezdyXFMVddHZBBaLapJFZDspzYzfLeoRLTMPxNToEiiXBWYZXUbslTORroRXpiDkdFBCXSjeUpwqnBFRYXUlWdFYMYGSBcCODODSevMczuVltIXCeufzBKrMbKJjxfv",
		@"uyLuMHsKpXenRDYuaiehAEzWGGPMiEtnkcJWyUnurTMDVMAJdUtGoxSRFDmGSpJWILuAUQOeLIdkwqLtwGslcVBmmfnaSPSgMOMjcOJbpVoeJFwVlV",
		@"gCQlgyiChIUlIvxnmYQAsKGObNdYEkAcpgwSftzHxvfVfzVuQtXeEaPjcYJOTNYzNzTQCDUTAXvCBffIfMmnVUPMQtlSjdFDOSbgKJOPmDNCypxmJxcHf",
		@"agiZxxjRlhHJvxBJjlnhkFdUbumjHKaXjjBbrDwdFyFjgHHQcROhZoLzqcbZgGyVmlYatiawnmrYzaSYdvWzApcZzhKRDAljLOahysglqvOFhOyerxQININndeeJwmKMPrmaSJeIv",
		@"KdnDuQUGLJjTySdBCvtkSBFBtIcNZJjAcJbsmELOTBjwqCelhIhVfGIKLSlOriocPEriRYkCrywsMUblrzsaZKRWSgNfwzTBTcfUiNzqilBsDZIRkBBDuUwmuywaSQmvQHPMzYGQzYilJZzn",
		@"bfGHKIlrlALJVvBOFthGajAlvBaUWjhMuvnXVFUBtXlnejaDnzzVXJGvVWDwjPRmnSWAQcXWRHXxFSZRFfnXLOihgxIcIRTLTAlwZySsnQFvt",
		@"KWcZdSDCygSdueVwxKQdPMNFMujsxpJSilLaKQQbKiOEMNZkrfFnxNGrLNPIpWkThrPBPemtNHoCQmoRNbIfkXqArxXbwYFxiaAjlh",
		@"kUdPQixFtEiSLesgqddxnWIbIdPbyBxBKxmDUXCTjIxiboeXLXMGmAYnpypxyHJTJEIIhJMprybiJbphtGBhHQnyKGLKGbSAOpITwwSraxwcogfZcWHSSCgmLBFuPiyZuagOqxnecGztpyfZPcIm",
		@"XbrjmFzSjHDnjMnQnSNKGQiQiHfaNwKrwrKEJvCmyKvOQIpWbLArvklaqTayvwGvAoPKNYoQMhpQXugaDrqssSZClOruPeSdAOrsuOJKkqAoGo",
		@"lEZozNpnyEYlhEKBvwgaYkWbVoHIKIpWpzwEkYGemTPXnLkwzFnhwXCTmOEPAaVzeRfmqPycnqCfaKuqUhicqFZXGyzTQROYrgXbIySaeaiHmndoVCjZ",
	];
	return GclRvfzCvIRMYtXJLg;
}

+ (nonnull UIImage *)nUltywDwOIiRlORDTeS :(nonnull UIImage *)ZhJzEsYsUOk {
	NSData *DxPyMklHLrMnXYZMXuq = [@"MxQByGtXhfKBsDiuxUMtfCNsOcLhSSUCzaMWpHwxpBaphRehvQORofGCUdkjPQQhmvKDTTBcsAzIetvloLjFJMUbQFqCqNQDahwLYRzfZxNzzJObDasmUHkk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TYHZlxAvdzxWOeniHd = [UIImage imageWithData:DxPyMklHLrMnXYZMXuq];
	TYHZlxAvdzxWOeniHd = [UIImage imageNamed:@"zNwvogVosNoPkpOMSmqPiKMcVOndkpiyIdEpboIQjxRFwcLxRIyZUbbTmNUxYTrsDXWCeevLGvheRCNXOoXFgooNSlrbsgjfFLxXEGISM"];
	return TYHZlxAvdzxWOeniHd;
}

+ (nonnull NSString *)XIdnKbMEWrxBB :(nonnull NSData *)noZpspZkzNMdFfgzX {
	NSString *CibbQvFelaJvYXX = @"kEQHSBzfoEkLzSBjdoLggDVQFaNnuukklIEIaABRvSzJUCuXCJdHLhxYmyKojfONeUUKZkHsGGRivVBCYkyFVDSTJaWmUfExWIAsMExVZNhDoRJCJntVjaMeVLvyseCKaMYKYyEBrdID";
	return CibbQvFelaJvYXX;
}

+ (nonnull NSData *)TrLFgsuDgXMdWLd :(nonnull NSDictionary *)uabTMCqxxrXBSmOh {
	NSData *ScOftpQghU = [@"jKzkKZhyrZxgLphmFcdSdHoMSrnulgJWXuLrEsGSalspkFzxikeyyauiXTVZhNCuPtNBnsFEHbrASRNEPCnfMjGURoWfGIXxDskDusdMTRPyKLyTykTebuZguCVawBTnfgNrgaxTb" dataUsingEncoding:NSUTF8StringEncoding];
	return ScOftpQghU;
}

- (nonnull NSString *)aVSuUXUIMQDkAYZT :(nonnull NSArray *)alTwgUyHdHFyK :(nonnull NSString *)wIxqztlsZtnnu {
	NSString *yONMPdQlrbYgmVN = @"OWKVGDSrxnmgPNHHoVwmZDEsIKMAHmiCMIZNieRMFTEHLZHmNgYhiwqwoDSryXMaiKYbhdwsiBvFqMzBnmUOQhuApnNjoxWNGFPMUDYuJMDVZsVxJFhnaMhxZovKFFxBReLBopbiUdYf";
	return yONMPdQlrbYgmVN;
}

+ (nonnull NSString *)sZgmSNgPUoS :(nonnull NSDictionary *)yLydLbljzqusX :(nonnull NSString *)iHvhGsoXtjNN :(nonnull NSString *)ipwqtVhVZe {
	NSString *SzTfRbKmBwHUxTvD = @"NRbRxNIaNNrBJqzGTaPRCXlAWQgcMqULIJlJwHKcNVWtsheSYFjcNvCPvnWwXbvAmnvCByXonSNQeSBeZZDiWnPhhbZHcykDlojszwYvgbfSmQFOjzicelmGUXEbzqXznckDWmFx";
	return SzTfRbKmBwHUxTvD;
}

- (nonnull NSString *)TddIgzBnfhrkBS :(nonnull NSData *)sSDflNMQSpwlxxC :(nonnull NSString *)YJkuCvFGKa {
	NSString *SdGikVtXRiV = @"sKiyZuKoUcxrRXMJBIqJjgntOeimujQkBMIzuOhlLwIhXvYiGPCvSzEBulqrDCUssOshhFAtnejUkZOsdWcfXjntQHAkezGPhgIrvZxLIjzJbimFRSGSmDoC";
	return SdGikVtXRiV;
}

+ (nonnull NSDictionary *)aigeQGdjkEHtIA :(nonnull NSString *)vSAYPWsvPLRXtEatw :(nonnull NSArray *)pQIeBcaaTjuLEAM {
	NSDictionary *fJEqqfABxuZDNCFNRf = @{
		@"oMtkAgOyxRmdijJTw": @"mCsNAScyMdNIsGBFdmCDQLBGqelEPPdQqMxbdvfGoeDEQXAmpTMJsSPujqyxhsBPvAXaDOwhKglNeRosvRHCHfmwohNMuBHPUtIPy",
		@"UwleAmEuySmB": @"AgxQeRAIiCTMHEvlkLRAgFjiDohQKntxopqgAWlqaCEhNiKjzYHVbRGngKhcVpHWJMpFPoMMLctRUxCKdIsXuJoTfugUjBfpdfXgiNJhowDcAUmseVdbPPNQAJKjqHeXWA",
		@"cCTJPgDFoYZq": @"KlwRWIzGHZIftwWGmxSgyxGgxMhiHgrMiMMnlNRcEVHDQsRWAhdPbHSxSPyEfAhdWPtZxSyQnaodHwYwZkOOWIparzIXHUmKaksDiNxHBrSPVLzyuMqQkckDsJRc",
		@"KNPOyzREETFCDo": @"KfKQoRCawzzdlztiwsWXdZNFENaQmndWyBKHipqBXXNbJaFBCwxLAjhNiyLjSJwOKVrobDphRRZjzkrVBlpNMrgskDeWERKRENXlzoHbQoZnvANlJyuxINRfTTsCDtmDZ",
		@"LauJSQKibZgxp": @"OcRkkDhvFekZoHfESwYaZryHRjKaozURUXVbOpLiGKcwYcuCpbxHJIoaDZvWHMXHCILYBOoscfhHrZqnAVdjYuckxpDUjWyVYdUCrCPdMwoiMhmAOBZvLN",
		@"InkIGhqCxAwR": @"YQYPOvSCATgMmzsUSGSZsYjoenxYaGiVqUmjvpzIOLGGjOhycMiumOYcxeSukHhdubRjyHRgJmrjtslJiezxkiIFjUBMYxHRdScLqMQEnJcZNWunSjPJWvnep",
		@"icnSUKMrxK": @"eaLmcdJyHLWimCQprrEIiRYOYWWsFVoSOLgeRTyMuAtcIBnFytNVeDgEkmAlXNXiJLYAvUEUHruQEoXpJbKdTRwsMfyQHPfGtCNzTFPy",
		@"kDliZRrtoXN": @"MLgxpKLgHLsCPwVcgYyuNlmCNvoWDDYURSOqcXDgAwwVFgfNkMHciwiSPmpFOsphIjfFlFsVsUOiFjhejVxpDaVsgiWUijCRkLXziIEvmWubIJgaBtAmGnNikvccSDiYPhvO",
		@"rtgMbGAoHKPWGKslNF": @"ycOUxkReOiPNeYajjlfBmGdHfyUhWeclxydzVnteriaJNhqhtBBtncQnwXmfLIpNvAvqtroWWeyCButcYeRIlMxPrYqKsrskKVPYYgsMVhxfxAXWSqfZVQMRPPKgswKusjoEvSZFjg",
		@"ntOCiHzepqvBApfkzV": @"CrXAEKqMUsdrnBLVgtKsGJcdInMJHQiPUGhRvTKrxZEVMswZwOKEVFIJvNTGkaxXUFoTDSQeECbITzJRYJdmUEfffkYKAGOPyPzJajd",
		@"pXvlNKIlUHLqOEqb": @"QgvxGlYNVBkJPFwhSRMdciXziaEuRPNdoOEgKStucKsESASzlSEqZWgsleVCtNQFEEeRqiXotYjjOHqRGVHnEVGcPeflJZKuIhoaGBfPUqJJl",
		@"IZcullttAEtRV": @"BFnrASSrrqWoxtLhkkfYmsDwqSkCHfFGBMAiAjzRlotWCtadZGtCHxJrOjxhKGqtSxxNDALeBPEgZoMGrhlReoSHlVPbOdAsdTKJthIIzuqltnJYHkMuDyQUBQi",
		@"SzdmrJFOVKy": @"mkmYXEwBUrRHCRzIRvqLfBBLsfjRKIETUGnnRuscMrIUzlHqdZPhIPpbstaHpNUJnhhCxcgtWbhMdBAFtfUrmuOzYwyZBTWHECtyiDWpteUNdKXpz",
	};
	return fJEqqfABxuZDNCFNRf;
}

- (nonnull UIImage *)oOwhJdfuDQ :(nonnull NSString *)ZHcUOWHfkUOJQ :(nonnull NSData *)PYutWSWIIXgs {
	NSData *YRmSYxukZTcYtrUXO = [@"ejRTsojnFhlLEMNTRtIYzlnTlrWPggzrWwQAFxqXYcamPCLyDuYkrACRnOlEljOFYXxzpJCEnwYZyLAfNKGkAmZclPvmRhAdsezpNYLPg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UGzqOZUuLEoOrONvFM = [UIImage imageWithData:YRmSYxukZTcYtrUXO];
	UGzqOZUuLEoOrONvFM = [UIImage imageNamed:@"fMwqQckwTLdkYedUNQHxceOdkPSgusGebnXLLGTFcqMfDIFQWnBsRrdMZSejYrvflhUUvLusRojNkytQCnMBCWbGmEjKKCOfekMZIYsWQBjTgOTkUTivwwvlfGFDkucezaRxYNkzdmao"];
	return UGzqOZUuLEoOrONvFM;
}

- (nonnull UIImage *)UkKUxDVXERGgJjgfi :(nonnull NSArray *)KORbAfUZqEsrNUs {
	NSData *yqGZlptqYXDKb = [@"tLWHfqjijVjgHPlMtkNjttrgnxtcpJYWGqfhOeugyDkNVBwjGUiFcBrNinahFqAzrXeoAvHnsEcfeFdLynszBVRexnHDkysSuAnjDcNIPVbFU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QvBrrODeWIJBjuenQop = [UIImage imageWithData:yqGZlptqYXDKb];
	QvBrrODeWIJBjuenQop = [UIImage imageNamed:@"YoQzigTVlWGVGfqDPhIiAPMvGKzNMraFNTzmRxsIEjonGXsvUXyzQuKpsFosAixSfRlzGJVmqVIBGFPukqYbQyxYRKqxiQrezWynSHMAyLXBUNaLMSRqX"];
	return QvBrrODeWIJBjuenQop;
}

+ (nonnull NSData *)EeiTCJdcBTujEiTs :(nonnull NSDictionary *)WkIXeaSRmUWwRwyhKWS {
	NSData *WAKnSMNLBzXRlk = [@"kDsizzqCqtPmEMqFQdRZmyxVpeUndACtgtbQGKIMRlkvzCMNefUYvdjbmEoEBvjZMGGAiSJwJQcdBEvkpCpselkraKrdBmhRPmtAXrjfLNyymbfHTSMQThDHpuapQ" dataUsingEncoding:NSUTF8StringEncoding];
	return WAKnSMNLBzXRlk;
}

- (nonnull NSArray *)gFjwLrosuxOAucZIS :(nonnull NSArray *)xYXQDhqkRpyzeADknG :(nonnull NSString *)zAMWXGBHbuhVXkNwjnV :(nonnull NSDictionary *)iflfxUbBhTOx {
	NSArray *yKdYugzlaxZiMWVJ = @[
		@"TviaIzzpVjEvjJBDnNxjiclBJfWsaxqWAiYSlMvHnxyZqiFGbpwXyBVJYVyheLzNvXojQtXIMdGYvMZUEXPPftsBkDDKsVgKLamXpvGSknkhdyGaTpSTGZCGaXTdmidLxlvhIAUgNtbBvAh",
		@"fRURczUrWeXpUEcDnNzbbWKxYjnmbzjLouoydRrvUkMlEFaHixncVzmxszLmQOlcmdUdCgJnfGlHvPnrMtWatGfJkFUHlIamEGPXRnnOa",
		@"UsohGwOOjBtGfQRzGrqsmHuCVCQKQxbuuKVeSoZMytOseMTnXnefplIEuNimzsgNErSINNNmaTNACQOuFUKDacgGetpfPShTiSOgPyAvTVRogUiUnyV",
		@"EjNHlzKDtTrlpohtiwUoblgblIBvmPvTBSOQDNVsXCyCJQetnKUjuLGLgUkuAGIWIkDTIpiCuprPJadAdNrzrrUSPhEKYtlBQGcnFjEiavgmL",
		@"XaiiwqHvwPIyHrMNwnJIGAXxobAuIWDzgxFPPTWsdyXzgrXTnKXFSJouPoXEMDRBMWVTXRfLSYYighQfffMkNvlzKBmkkmbdumlfHmEcRPMJNSCiKqBElthwNdlZPouASpIZWVnHRmjCPvJuC",
		@"IXPulfrwvDYqYvkqPeKdSLVqiPQSMEKyHuvEVhFBSCGiTBHHXAkyxTSJkclCxksiaMhfcTGTzVYNgproRwMwaSDkFQjAueCWrXKCpcjZGjNfOwUdIDxmzDEUVkvHhVOoQGDXQjX",
		@"CyVLhEDLjAfcpDjPFljIhkUXlWSYTamBWiwWGuHHaFzonVtjCraEUQoxUMhzhscFekaqrOMNNUwLBTPHDzNQkFydnSbGFCsyxGyqhEFEYTRtSGYUHMdNewF",
		@"ktpSEEHqJKEwPZrgMpjJCcpYHdqLQHpeseZGBAfXiqoUPqpBZbHecbLUWYNqTwgQQjgdvFThZhBQvxTvtxoiihVSuDDXoIIlYpMdzFYnzjOSVoZAzmWedVEWoWFLAPGsTnCthidb",
		@"EmxdlhmSdCgmZBCQrNJgdQGmTqPrrYNplCqNYUauISivqYJBbysiftqOfpkcESddZWuvufdGzRGliCEubIQJrPlYmETyXWyNPzXhHqtpoeLabKWQuiYtepPJm",
		@"abYxnICOhzKsMmFRFcOsvDwEqQKgJKqOPtADmYqOHxmsMBgtGoxgdOSaPLQkkGWJrEVtdlENBesPVdZEqPznblZpbLIINpUmkwVtPLDUOJIlZTsrNudRHKcfFeYcI",
		@"YHPphMbxOIUoevoXlVrnBTBQOKRmnTJCRraMAnWOpeqxbKNBqiEPBTCKuJJApqtewNbPDsHTcKugLqALVqIOMDUCLhKsOMyOIicxqLzgIPtnnjQk",
		@"PbkmFWvjUbaQfhXhibIGvkyjPoztEVMFobvUDOQRbsBcxxszAhTDszhUdTcPoEvsaechALzVXOaADHQJbuHGiaEwnVLbKdlYcMNhKCWXxbwQEmvxkVKityczjrCzquitixDBGKWrGGtwMwvpduHY",
		@"BPXrWyWoYMoqtDdbsaApxFGUSPUpHQTSgJAdMZsotscZvMaDwlrkjmofmQYGoCijpIYAVLCDrvBqAvNVEFmGvVJaFaGHDqrHKLCHXwgMLoxnrfgCLRgRZEgJFb",
		@"UTBEzwUQbMicqRgRrwBekroVDdjuzZBzyUAecZsSXtoHSPnScCbQPiIdsEGhabEZMStgpCLGduwMklORlnVceQKmklbgxvWShgQUfqWAnelUQmJCmVMBZxlhyrOGfONkfnYVKywSTMseXpvlqtJH",
		@"LMeYPpKlHVvrNMjVJZtgqrEaUTYgrEPKAkVpIBLcATiMjcieyesqlaWRYKlPztnOAFWyjezLYTQeVtlQCalGcvgwrfKcDxsPteHslrBgPzevOkAOBEQdsKmJdu",
	];
	return yKdYugzlaxZiMWVJ;
}

- (nonnull NSData *)RrfObSGcKIPzb :(nonnull NSDictionary *)OrEQLIXJIecXeCt :(nonnull NSArray *)EkIkpGlDSwjkSvs {
	NSData *XxTjHAmKWnUcSWGZfVj = [@"WuZAagTXRUaKOAzFKGWnjdEjRHsWnmbPvGmDgUSyuaTTkMnqEfcwBAToAIuDdlktnoQevZXCVhhASQnwGivbHdOQTkdpipXkUBnwZOIKu" dataUsingEncoding:NSUTF8StringEncoding];
	return XxTjHAmKWnUcSWGZfVj;
}

- (nonnull NSData *)oTMXvTOYjLghnfGptW :(nonnull UIImage *)HFPXYJslgeRINjdoB :(nonnull UIImage *)XXrBKYlOQyU {
	NSData *YkYKUKUgeWNLAshkHY = [@"YOEBNsyEAHSeGMcNKEPDMyWkmFYAKeAkpPvehdsCVeDbupSOpWWhvioBOiKirUfvfeLUmecDFTConWXWeMayEXEHpfJNAiJeZFDyVBLXPrYpIsHyb" dataUsingEncoding:NSUTF8StringEncoding];
	return YkYKUKUgeWNLAshkHY;
}

+ (nonnull NSArray *)EevZVpCxpWgA :(nonnull NSArray *)ulWpzdfhJCGmdDb {
	NSArray *TZqIHVZgSk = @[
		@"AJORYOVgJUeHuvqrmCUodERvnRcHiBRSjiaYByQnijylPaFLISQJotRbWQAhEptONhYmBAetaFYKVmlNIdYPsLdNKZImFkWjddDuKARfoNiLjjlKaeUQkgTpFHkjYlD",
		@"AGCVrOAPKuHvFOhYHKVdirPpeTpSQkZwDTAuyiLZTgLRyupYFUqHmfXImYOkPdSVQxszeBSuXwXJvJXGPhuvAWNoidOriEYWMVjyHa",
		@"SogDvgaNTKLntrQWgJPcFvUFkBEmZDnxxYblpXEkVwqDIKkqMFiVPndoieYHMOmgHtKnMFXlDLEQaJZTMoqYRcqGAHYLtjBqrMoGBdQWHBVlCLCBJjKaBnxkwhKKAaUQaALIUsQKFDCN",
		@"EwdvJEpIgOufddchUnsDLIlJgQfidZaTScByNIxvucVZSGnpdeYpMEwfpRIYXigkfKXwtapqDYrPqhTpUUNRzvGCnPoPcXaEbmjRQLhuhuWSVjpxcJN",
		@"tyIipcGKYsArhXXiAYkkTCQZkYtWROKkQVWEYylxTifaJAyqvMNuzJcqZciRWlQBGjsUMPOXnLJOGkmRNrGmFZynBeppjCIrqBhzSLgp",
		@"EVznZbVusMWOCcHxFKfKpOLAdSSmeLoSbmgYQgFpFXrKCLuTaagrxwkNhHdVdCdWSdkOLOmOeEWRYDJsaxNsBiSlUlCdqHpFlZwjOydUZPffKmSFsECjSisCPuAOJlbhvXf",
		@"kfXchSWAVSXwhumfYhDyMRxavEqfgMLEItxXDGKaLBzggByOzcEEXIPfIrwOdSVmMAmQZoxlVKClGRFoXulAzBNDqtwyuLEYkqkwKWziXeMVNSRLEqkzevUouTRCgzFljRc",
		@"aNnaFjvTapddcqJbADrpKbCLOfdGRcQQJBFAnhHNhNZeFKdixoVHkrZzPINSADHRXXsTXmcTAHSpvpYEvRoPeVEfmbLuUEFLxgsuYVBIohgJMnnXMGyKwbaI",
		@"XLqVIeEVeoMTuZqyPMMHPZKpenOlpVfKHixMtJnSfMFmMcVxaffkClytRdeeLGxHVVzArCeOPmjnQonZYPpmlTZxueVOVgctEogikkYIzlIsuoPGG",
		@"atbzBmDYDmLvtpAXyIEADMIUxEabChLFeAYqsJlHvqXwoeHTxAeDVyZobqFdZaRapEoWIqExOcAaAzZjwisZBVxIxqqDQQUzJJJV",
		@"SlxeMEocaHktQRAnmYBSiPrWMykFoJRIXuFdeLupEVuRLHfjDGRIRxCpOkItFUhYHbajEoYxBFdGiVsHaXSamcafLRPcqHVflKeTbPwSUoqqvKTsCMZCBYCaFcRyDjtjmJ",
		@"JjbnaJZQyrpvdodrcOhKcxdbamUSqXxsYURBOutUQELyRpAWabYJvqXjbhVCnpUAViostQCYEKXboeTlZPvoanpnxFuOHHdqCvNbvvRBtpvywTdtYKkK",
		@"HXlTtMNfVjTgNgPyKBcHJZvmHBvhGIIqrXhDHoQPEoFJOdrphuobaoGJSKXlGSSEPQgaLkZXHdhKBnTbMdFZYeCfdSsAEAXyySvbroaLrZWXqeGjMEyuzfWaR",
		@"JwKfEUHPIzNCAovblNjsdzneRCYmLtlyjbAAJyEyIgGSQMKocgATZffLJNPjkXfvZooLKcrmlsXgCoFiAMjhwGSugFMzlIOlKQvujPonuDrJFEdAAGVkyzfmGnYzqEvWSE",
		@"uSiyhSkTVuRduXKvbmEUqRijwMvvxWgzNodwqjSUjKxvlKYqNsGJZacxlMbQjvqrDeDepMQAjyvdEprwZKHQXnNoduMlKnmiQCbRvffFwTEfUItHV",
		@"HEYDsNRlXypvXjfDdgirzBivgGtuziWMmdCEVuCiMKyMOEytSKPyDdNKDbYdwvMcBHeByFaqAlJpYYlFVWWzjTlJSyiKGDnAnijeXSiH",
	];
	return TZqIHVZgSk;
}

- (nonnull NSDictionary *)xSVvusUVGL :(nonnull NSDictionary *)FNmKhGNPsayItTNTk :(nonnull NSData *)JiJMPaXuvmxwMMpiKXf {
	NSDictionary *NHJDpOyLkyGGush = @{
		@"QnsSIaBgFMetfwjkWDh": @"TRvXKORzLECHbNjwluDaQbnjqUQTlyVnSQDifbGYNEniZupuWdxdUmoHakHnCaDTNDuWgPubZwgVfIYOZxkyGfcjEMLldwLjYqpDHUDubfJqOPFYttuodPyvavJsyAZHJZeEnbdYTku",
		@"PaGqaDBfjzgrTJaG": @"gByOUWlNXhHbnEqBGrAVgCediQFzXpbxxkOxdzfcfQhYtZKxsustxmnJKZKWdkBdSnEagXJxdHvfzxtoHiyvjrQtkwUlrlOLstIMuhGVJuW",
		@"PndQiqnDmgNBGDjHZOW": @"CIQuSUcFjtiJPxlsALmIBPcDVkAcVuBZGOpyjwGnJbjZlcgndbySVfyAZSEAqTqkhsNumhIRGWLBWaijAEZnxzSGDLBBUatixhekBhEpafxSXZFeWdETqrnkMHocqU",
		@"ddapxSduVLEkfm": @"URpGkdZuxqxPWCkGTClsmfuUORiuRgQAIfIaDZVYmmKVYltQSaxrBfXSGmkYYjvwDDMFLkuUnUVEoRStGQuqSVQeMxSSoyRBDjYJsoaJVKkpqFIQSk",
		@"EqgAEwxiui": @"vhwgKoqsyHskXpzTckmhuUHRRngmKoInnngRkFFIYqWWzDPCDpTaEJlASpoGDpqlMOoJoiUshvnzMXbCdBgcfKtafnKVBewwRLrc",
		@"BKXfFWNPupfEAKOU": @"NWuJQURkTMAhyaiIezIEsNcOIUkILYSFIckWegjhIjQihDoMlxBvYsYtntlZwtmluIXykiEoNyvqHaQQplraxXfoOvzDMBMpcsDncNAzOvSlJgLqMNuYcEyRaYjUexKlytwq",
		@"DVLhfywrHYGO": @"SplZBcOEyshFskRbDeQTjtvNmeiGhlqSdRfnBPMOGSorfLxuRBDCATNMAXvbDOCAXMMroBXSZGEwpZGIiZvPjzFtYZdzqskTJjoFGNjKySNCbJzUIvMDhdsZcaNxXMhGJqOIhyAirCkjZMQnnA",
		@"ugNCjpNsJUfOVfuEwVa": @"ZxBrnYyHDOedQThtAjVWaKoemEkvkTuzGJnnKTGwzrtwszYPQVYWaEyPxdSgyYXdOlYZBCTwiYeycuGCjkSwfjHuVhzPGgPHUbqdpsCmcyijYBmdLjsLLoDLeyNzwHVuPEYQfpvozDJwfEWjIX",
		@"nHvbnrQBNhtO": @"ZQFFVIJXisTgpBRPRfyHEvdXuHhVpefZGlDnYmAvxoWZDBoooOjJUqdAHtytmsnBeOSLDQpJNSAytLtRwRNYGkrnxjzSOpeOlpJdsOywzSmAErHnGIISdswvAgPQLrlALMVFLxkuis",
		@"JqyvArcSaqNAE": @"PWaRCUnznisHPYAbpkHAjuFkVhEBkaqsEjIyDqdQbSByJsuSivhnDuIKGCaVIZmetoyVmyUNFnPlbpBFzYSZyAPFyPhicfvuLSUEDFosuMzBaXsHiamtNEtWAXfmWjRUm",
	};
	return NHJDpOyLkyGGush;
}

+ (nonnull NSArray *)MQoCMlodSDLhawEc :(nonnull NSData *)YgfIyGgnZujJN {
	NSArray *LWdvIZdXXXd = @[
		@"JpICDOJcjGoQRVBBDcFZWXftIOZRaoWriJpDPkvQIbYvBzwGbRmPRFKbRgMQwcFnCZqPszggvnyRbFCVwASWZfTwMClWYWObAKUhBBGmEWdJpwizLLvwNHoOhyQB",
		@"AKXBStbGdKzAEseZsQumGgFZLYdJvXJmQAJrZHRvGdIOEyDXxKSqQAPyfvWvbifNLSxpNajDoKSiJJZjyvbfSyeoYJGRTuwpUSCOnf",
		@"xneFfiLUtyFfbohJlzakoBwPsueJSHTxIXTyajfhBqkGjMiqLhozUADmxfQQPaSKewAkpJKMxiXvFWCbQaVgaOhMjnhFKBkLbWUxTpPSCyc",
		@"bOHFYqOZcEbMETHoyXqzSVvMOQgosuHYCzVOxpJzlJLdFvZUvqhmFCCNrChpqDXUvvlPCkhtRUdWMSHKhPFIhGtIMCkrajoGSORxAPHBcelVqqOaqOZEPaWQZXzEnROZewSyzW",
		@"GhCmvCCOgceccLixMMDnvacngyNaUeuiGgchZjnLYjDRMqRpKAqEjZBKtnsTBVKJMqBHuTFWJbBcGqbGjjETaQAINCQVpMTFXUuZBwjfGAWDBZVZqETEnOveqiAKwTaPfSbHBdRdh",
		@"xxzSNgfMiFCVSOFHPkDSfEvmQOWuduesDfqjlXjhJlDvGSDeSIMSkQkfaILErTmolqjDhcURhiwZYqYXWMgqHsKrvWpRRhSoAlHKLElPZDqUZyLQzKcgMJmgQaBrltmTKblqUfviZTWVMtEdm",
		@"OYaSwvJHBpBhfRqXyjBkWeuJRhUePFaORoqjQWqjjChFDoVIKTGHyftSZKyubTnDvTzwwtDqJFsKllnmzIagahxiIenNWpzgyPkwHjvjkEUFeLDBSGdvAQDwioeJR",
		@"bvYgSwIqKSisRosBtTPeTvHKWWzdKeKEzONiDFPfuyeSotfqQnWqwktryfondIThzjGnIcIYotvoUjcygjsgmFLUiqqcBYZSzBDuwCyOsEwNsagYzKjAdTCPVVfhrGQthGvndoPQRcYAwrBcoEZ",
		@"LprnoVxHAbDwXnXHwIsqmzkGNyHccGnBXARWHUfzVuAExpBbZudNcFkWEbphgsaykkYaTUkVOmhrwzIaKrFPOaxFUilTwlGupfyLEkBO",
		@"VOqhqZwtcwvyQzfVZMxYtpPeOamUfUGpYstgjaJRHZNUjJmKLKjCAWtoMviIEHNwgzqYVNnFiqtRLJUNyyiwXBRLPuioRrnbuXTRKJlvuXrnMZleoKszQFwQNBrhKPJAuIusLMxJIMmN",
		@"aNWCTiHRwSAyrZhJKTlzcQZILTacnHvBaDgrcldXtIQjocxuYfLvTxLHuHnSHlnxOFUKcXqslHcSHEPTkXynFguveBzxqHimkPycLflhFOKKyruBLWGVMsgCnqJyVfzNuSvHzSfiaeeKkzxg",
		@"tTbOzspDvVpSDVWQPZJDaOXIEfHAUHqlBvatHlXNzCboEoAnbfYNTMieSPvwsGgRUpXijorBCTZjZPbVKxiSzmLdbwgioNkZIGauzuEnbHfbbXUail",
		@"cKDuclRkaBEBmubrIvXYOYJAENQidGiqvRdmZySGwpimtmxlZIEkfacJpdXdPFMFSHzHhHOoRGZUmyBVZNGRfBOVDaslVpRmEGCReEemeYCQZX",
		@"BMlCTvCTMTEGoLqjxFbaQoyWKKLEKTMgXbwTKrgHxFfosAJPIbYckMvqNwfjahNVatDZMPmZVZuJSxFTXQxRIhNpLsWApaviiuHSHRbEqjDvvhmIhvRrDdfnNk",
		@"DKGbSdwuyCutAFpTKijVHUciFVaFyrcKNeGnWYMBnCMiVKYpalbuEXmEtumwxxnYvBDpFRUQvWPRNsxJfaAtgHfvWFCtJOuUwPGxUIooMzkOTUTeWafEIEAetBDTathCHYncQpVGUTbtlqMWqYRx",
		@"vdcpjBUKXdOOMYwgBTHSCpuNcrLBHSoWYBzfSWDqzMUFXoJoMWjxfLtoXVcgxRYgAIHGyKAGdjJjbokysqQODQxZCfXSbFKCwYlRgQDvPGzNPPjib",
		@"AaQLnuAIXdfWkmohluqgAHJAMDqqDdbAjTFBSEqbZYRJVZcMXjZRUUGTLNPikPUhlQXWtrRrqFpYBvynKwXmPzbqtIiDmoOgPBOwmqIUarGpOkwCp",
	];
	return LWdvIZdXXXd;
}

- (nonnull NSData *)VTenEWZRWldlLRE :(nonnull NSDictionary *)sEwQfQIQxWu :(nonnull NSDictionary *)rxDqtHHSpgQxRkRnt :(nonnull NSArray *)FnfKXywBkvqBvYB {
	NSData *tqdkPwApkKtUyQsDslD = [@"zcsspkBzVHCkwWVwWgbQbMhKnbwbGqQfgzPsKQjaAdozMDiGmtRgmUCJQXyZZLhRoqCRQqyThvfEmIpOYbojeMbQZwTzKGawDFQjVTPrsasuFs" dataUsingEncoding:NSUTF8StringEncoding];
	return tqdkPwApkKtUyQsDslD;
}

- (nonnull UIImage *)RNtZAJsYxob :(nonnull NSString *)vyodXXJIFeUwoZz {
	NSData *cHXNhxRQMRMFDlcvY = [@"GQGvvunwWDTdqLIfAIzJUNOYJrSJBURRiJiftTpyEtYkezpxNSpJXQRvJLbhRMisoLNyuZCdPLXYZpoVfbeXmpZhDnrhCpnoqwPAfycxfTsHHIRRZTdjDqhUOBOriFxTxHAGXKrxNjwc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *alTkxeweGJpth = [UIImage imageWithData:cHXNhxRQMRMFDlcvY];
	alTkxeweGJpth = [UIImage imageNamed:@"pBrHThguGUdDpkbwWwcyDznNiOsivwxNMJCcaJgUgXWumsMEHLFmVJeLMcrMHzotqIUxJmZtHGWyEtycaQgJtvMrQgwSSdqWNPRWfwd"];
	return alTkxeweGJpth;
}

- (nonnull UIImage *)EuOHgUwFWBkIy :(nonnull NSArray *)BmqbYaqSUbmovYE :(nonnull NSDictionary *)HoGwuxBimyNCrRsdxtu :(nonnull NSArray *)fZEDMeiACrDE {
	NSData *BrQPcgtfeka = [@"jEbRyDLeFMQganLlpVENTDorSxsluGszVGujShTkcBLScmHEGSRKabMXMZXHujjSyoQqVPmUpRnvAURIFyhektYYDUApQFQYTcjMzzPUXZgesLnfsUggdcFPJVulsocqbnGFkULJYfBhNLDukFV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EvcYdBqmBGohERrHE = [UIImage imageWithData:BrQPcgtfeka];
	EvcYdBqmBGohERrHE = [UIImage imageNamed:@"mORXJzYixDxDYZtTXhbRCMiRQCUqGOkwqPBfDsJJmAIWvncizrNRvipZAtAAnyVvutxLnLmsBPLdAwNERQiFwFaoClAFhPsYjDJKoBCsihKwbCjZNIgRFJnMZWHgqIXCelzU"];
	return EvcYdBqmBGohERrHE;
}

- (nonnull UIImage *)zirzBDHQfWoP :(nonnull NSData *)oXSjkglTXkhifN :(nonnull UIImage *)gnhMqxLSZayYrDRS {
	NSData *zHBddQtWcNqUUnkBXd = [@"vxbJrKpCGNuzubNnifywJujEmeFkfsQlCaIMwTdYuOEETacdHaoLBZFXTpPEuRVoiNDCLdrVouHfzAAyrHUozqOuaHiHMUyXDtUrXwaMNHRkIoDdyhwlqNbZYDN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hdJlqsxapczEP = [UIImage imageWithData:zHBddQtWcNqUUnkBXd];
	hdJlqsxapczEP = [UIImage imageNamed:@"rtTcyLZOUFxXVcvqKhlobbJVDaxeRZIjGvfUxRofYSEsKFXeRkaeVumxyqRzFIRxyHGKShLppJvCwCYTYDCzCiMzsfdizznJZDgLAIJkYToYWTOcrkaYrmC"];
	return hdJlqsxapczEP;
}

+ (nonnull NSDictionary *)QFwqMkOnAawsydtK :(nonnull NSString *)GTjqyCqZQXkpF {
	NSDictionary *mjfaxQLuZKBzY = @{
		@"VejvDQTzMnF": @"UecfbWdhmrCyjToiAJFCzIWCCZwQzWLYFxUwpDmfgJnrmpPKTYhpgYqYsTNnzDGMtkUlhUsREKrsoEXqBAWZdGUlfhdJuABEOgFjbLDvAVdJvYHxkmWssJEQMfqNILf",
		@"ILTjibPqBExsFTxN": @"FNJUtyTbIbCimbyuiiMauJZPRIpOdNRjGjzcGEfGMpQvIehMmyviiCmwFWhFUjTfkOCCGcVZSwMsygKwIRNqXOWxzlDuRyUoszhCedAsbNimtHNFL",
		@"WMVwjJGWnuLd": @"bRYzPMIPGGOmAZFQYieTtWOjQmFgQbEnKWHkYtBvNOeuvEJXzmjDCltXMjKlDURUCwmgWOttVPwLFBEhPOwhtYezJumgvfYSkbPZWnDBiKTCxIXVFFM",
		@"bvQGuJmtGfXSh": @"GwQiZSdhikyZGmysyQInmSmJgLgyHySSlGtzSpBINYugNFmkGgvritZyyrxawmTCPDGIlyUpPrRyBEiiRVFhtgOZOxhpCFOeKBGQxFBfOMEWy",
		@"jNCtVfRSUJBadEe": @"JSNzNjBYigpwPpWXuchiaUxpfPDTVMmcjDFtnNfxySRZjvWbwPFoNDBznYXXehJvIqRxPgQXpJClwQXBTbkuCXcYqoKvOyHVLedNO",
		@"eAPKijJUmbHfH": @"WHvVPrukrIUyxmzLfOoSPxcNVLXzrZfAeFNtarTSlliuDTPLlxWWSMejxgheIvbCevUXXQHlzbhnKCrVginKvkvpWpILoxLZnyugLXjFyoRffOteMyvezHBKpvq",
		@"zauhWWOsqUuvnwMvs": @"fOplPWVNvCWhzGuUkzLPiZwJFlaJsuLHzotyezxiwnAxurWkbdwTOjPLnzZaAiVTwWSjNjffOkgLFbSUzLWrdPLQKWAMtFPGyLIKqEYCYtcIZSSGnyJjPNqwpRA",
		@"JYBLxzyVWgwRGDYt": @"qzRTgHOYfpnSfFYpuSGlPERWxClqMJBcXmuhCHXJLazoMMpUnNIdJcBMyppRTKkCDTNikoTDahGQOJjHAHqYxZUPEaOsHlZDQuXYfpvfPXDDgNShRYVwOdRwTvduxOKVapEfbdbxKtvCYzKGvKPQ",
		@"noQpzwuBqllfJcYtbmc": @"GcXAOxHaEsuFPyKVXNVutsLFbKLRrlWOvBJOhOhPuuvqARVQaQTQlXfpBCPpvYYWgFPuwwRUcTfQqvnNHQCvbkJLbzeKeDjeJaFqyXbl",
		@"buwazhnXgFJb": @"FAXpScrneWsfymvwIcsDfdpEYFJniaGcboSBMKOGbZfzzXfdhAZVuvSgcyELBVdALokhHWngGmuUtyCCWmqMveyhDAsNJTrhgeMOibTjCPAYCKDVCbXHvplSsDahNQskbb",
		@"UNzSUBhQBPp": @"DCzbNPYVtGEpZTzoujPpiatgruRGPozRIQobuIwCszSNJNLXTaBIXqYrofoCayPeABZWGEEWfARPXWaKCUZixyjNOjFtVyLuVLINFeXiusLlTqnUrfCrjawBmiUuhmKVkhHuOCXfmFoIopPJ",
	};
	return mjfaxQLuZKBzY;
}

- (nonnull NSArray *)uNzOnewNjtIAPbqzi :(nonnull NSArray *)HwfIBxeovnz :(nonnull NSDictionary *)rwvgfiytNND {
	NSArray *VIEneEFmbpLQWKI = @[
		@"QbuFGQBPgTSSOebLGiFQKemGXQlpjjKSyCDyhvyUdroVAXrUjrXmvDVERdTlokCoOSnTIsRLbXzvgipiGktFuYNYkkYuECaqpFIcnIxHKHLHfiATUkyaaYpPLaoVBIwfNPBmfyCTBqkNCqtxq",
		@"LZSPciZtoIKWHNxqnozCinpEhHngRcyeBgQJmjxijZeDgFTMxJmZINnLofZXpqwqcleiPanKWvOeWvapCnkGnZedJHxMgSzCxRcADUctazUMXPmEQgpErLsmkSxZwcAXm",
		@"mvIzcOtPOgTwGAgVFcQNLVKhDGjcuVWpLDOOmVVWVOggtdBaOamWFhMTvPudTClVuClmOQCyDCjQquZjfJsuXxHWzMmMYfRhiZgrVSpkPHKUMRJBpwEnEIspxLsstXkXwRUySZDg",
		@"OKJHfvTNUehimVEqXjhysBtoqpiuCJaBTupjmlYVawapFNVJlwMqQtkeulEvTXEdcrjquUCzICYBXWllBhihMlCeGUnyMoRQXbrVvvnPFuRkg",
		@"ecyCzghLfsugitDkbAQLKwhMNsOiMrVohJiGpgaKmnGYGxBWoRXxgVeIoRHKuAcGNSFxbMjmAfwUhmYrlEajadoyeDWrMmKkqMNpjPnKM",
		@"NFHPdfKHAkreBKPZrcBBoyiwOPbSmXiOYQPkrDBYJPuWhxdBTNjbOcMTFLeKUxsxYmFZGaMMaOHNRxaOYYYslBumZWRmVzRMZRzdKxYYYZCGDpdT",
		@"rFImzqjIJVwIqLFVZXPXFhfGvsoQDAlBZJUBTjvJSUyUJGVNeSJbCSjhcVauolOxxFFTQcmZKVXDQUYWGwlONVzBGiVHylIwiUFBWVwGdOHLKEPURNzetQHTLQviHJKUpbryGNKwNbI",
		@"mGpMgLDWnEvPvewIUKXBxHKKMdqJijNGyMSipbuxrYPVkcpqCQJbZkUzRZGlvkqvAhWAHyizYgCRTMYNZZyyXMrIdamvMDYmDTdwEN",
		@"mGZGSCnBBITPzNdAUYsJcANjrjaoMZyJtHiaVKUbgQSZLTGsWsxxcJpYfBUlVbrQpMspJuXcFlEfqazRXSzhQXZBsvQcPMprcQmpNwvsKKqJETfqukMoQDaeGmtPJLzIUhjgfeozksRtkYm",
		@"cCmOclrNTTmaRhxVzoKeCRhRZboZrFmamwYLnrnqeVvvFoahrYdCECfVFhDpOTPsLzemVhLDrZAxBsWWRAWvOlKGUnNxLnJnBKRzioCBTUisVUFHaKpWokIEhpPTcQBDBWqecjIlmqibtqBLe",
		@"GxToANUNYncdxFUShlUGzVbpoKGLpQhASTypfAEhnjhHXrWKmINOkaqnnSjHVvYUBWLFnipezZaQyvHOVScCyZbVVsrSyfjshQpujARutnFqYz",
		@"ffCbVugTxHmbnTdYYYBbbmPIoeyvXzixewnEaWghDZZcdOBovJyllgRHGWUDWnAKOXgBtfRrMVAJBtYiqfGJSarQGbMNMzUacNzdPYugieOyVKvSGWIsXYkXIkfidoEAmWXVqoQw",
		@"SZUuPEikJrQNfRAxeSwAMfVLTOpTCsNLpvQyYSkrfzBRycGolRYqoHzhZRxUbvALwOBDHLCPxicnonNximedWHawRIwoyvEueqReQJOhDU",
	];
	return VIEneEFmbpLQWKI;
}

+ (nonnull NSData *)bDFUWlbmIEzoP :(nonnull NSData *)ZTBZYQEDTiquMr :(nonnull NSArray *)vfHeIQYoGNgrequjLA :(nonnull NSData *)SysHqedaWhHN {
	NSData *fauOxypMBOKHgaVWQ = [@"gQDhMZkaFxficRFlJBtGLIopovcYEexHJBkHQIqcccwJekxUpNXNiCIVaUVQmcXuPoPXzndaqBicjdWUzgXVilxkBaumPvAJTVuRVlusEKdYbTdhG" dataUsingEncoding:NSUTF8StringEncoding];
	return fauOxypMBOKHgaVWQ;
}

+ (nonnull NSDictionary *)VcaDHTbcvcwYW :(nonnull NSArray *)AFhGEnPeWVNwLu {
	NSDictionary *EIqsoOJFjEviTao = @{
		@"MmjGrGHRWgdjyHLl": @"osyRRAGIcYyTdiqayukllUovmEtZeNMSqhaJAOxISysjUkyeZAuLKexwhjBaGaQzaoGVGcrOSajizmYSfNMaJBIFzybsaSsvQmCHOw",
		@"NwSQDuPFwCkhMwZtofN": @"ExRFctmBaFFTHJznfGAWzgaGVQQQEnXulDrNXnvBQwXHEqltboBCNhiTjliTGkHCjKLNUrwglLFAGbuTPjyYpTYhqwdyZmfnhhYGWoUBP",
		@"yFKYHBzEEKTNpptarU": @"tfJaKGXqzRtZGnahKpCUEteFQXuOSADjirAKeNBDmdXYcqtnCmBfUWByWykTsPbXXwmlFOdTdPfwcTcLdSZYAPsUldbgjUSfAFXBHbkvxSBJJlMFSVYcKdiKOZRaFfDNufFDJYDKOnxqZKpzPsiA",
		@"qlNaOisMQIAU": @"brDacQHgjGagdVKwPXqCReFhHpaqHdPssRlVWbdCNhmRowbnCaxIbLTdxGyhNSJzaoPBYrPFCCSSpkLzvKYAmrBbSlnYfRTfNYwnyxSZfLWAT",
		@"utWBMyhjAAKgCc": @"iryVlCjwVYGZzMfYrXEaSgvTtSHZNzlmWjbcFMfWJNKAVZNopeTbDglIeiJYwAsrkNwTqyQWEBjAUPfpEPveNLuWJSuqyIMttAujbULSIGGgepljiRQNHqZLrorEceZXEfSjNYoGjoQwHxjoIXEp",
		@"BHAYBcutOB": @"swVZqDrfLDFVYPygPYkwZfVtNtdHnFopmcqBgbIjvSBjPMbszAQcWGWAuGeyQhrcgHSmQiggeFpSoSKIUtEoJkKNNtdXWQLeHsOvIZzcDPHEcGsXltJhRckkDkhIglNGQilkFQYEEnp",
		@"OQpcwCPxYlARD": @"kIKqMGUMxWeNuHSQJrDuLgYiFVpeeYbZsjQEVAtvmdAYajkodAhmyubqYgPYhQLJDbWOXtBeNnSkvCLiFmrMtoIXSvooZdVdkNUWwkktQRbflEMnfhgpOIVCbvtAQaojpUsPKxvrpMzRiqL",
		@"PfqVPynULGBzyeJbipt": @"HHeozyCWxSsBzKPqUVAuYggnnKKiKGHMTBtMynabjzEUeuCWGTrUAAgaTTNpeFAYfQXfdSyAdnoSuWqAuRknyznMDIGflXrCPUKiwEICTNhJjNgfDmVAKkLMhZlwELa",
		@"ixFeyHwzIfYdEaFwqIC": @"xzAqXekZsPXMWEcNdASStTDhqFLludhkMWwXmbXSUeQvuraiFtczEmulfBrKlNxaTkmcohjvpvCDefkHrxxfFuzovJFZKxGNazOMVcCrnBusd",
		@"XRLVdmromZQXvt": @"orxnlazBRcOpKgcXucrObcWorJMEhMxnJDwnUcfeXFvurnsjwiyicFBADlbDpzpFQFFwnzDUmogtazErOaMnHvGVMvMRFibqhqpgbzGJLax",
		@"IHjVGtLvIKAAkFNiSMw": @"LXWUhSweehHZeRcHlOpYQZrkftFUcWmPQFtMsKQVrXMmDjzhiBZcDkYExuUNblDGAmMrBrnpMveJMPjJTivDHjWaAHaeARIYsRFmcBWgzPmTMfXokkBrAJvcLgXYFjOVSnTuxEQKlPGuDHqfswVqm",
		@"SEuGbEawjvQ": @"YlFCdAwIWEzPsFMaFdIywLalSRcNTFHrtpMmUoTLFRBhwfLBYkSLDXDcecDeLDjkzufqatNcIjCCoKyTesLoclSitfbdwlgEOZtC",
		@"lZyxrBmFMkFMygQsN": @"zEFVvUyWpShvYIiJvMlUgMDLrQyTOtJhowlCEPZMZphQMiAZZsLiJwYWyhuxqXQGuKwikYsSGqSjmGjtYhjtPGVecjpQxqgVXsHnIgaa",
		@"VpmePsBtIcUOji": @"sNGzIlEsuqFPPaVrsHAFkDCGtcoaheDSiRxVLddOBGPxFYbjEzGKFQXNMCfFAOgTpuqJSaQSfnPqEDsxtDZYEWDhWIUzXzfyEVgpxVMFCsqpGCUkAAXxJmitdwuecmmnkSOZNw",
		@"RbCcbnoSwZxypw": @"LKAosWuYsnrdGrZmmhTqJCYdsSlIPtggmeTNEXVnOiDgAiSHTEilrjNlXbPWZjIDqfNYBtgOEPFjRbrFNtTvuITBaJKHqLWAnrQygpQzKLNGEJVzqHZVFqIfTGDjalYPwxuKRZjrXimptfLocSBdp",
		@"XSCAVAFFRKvtSf": @"YkinyzMmdUTWMpJkabNVJCcXRCYUUZsinIiSeeOJhoOQTCjTRtCfXsOCkevKTZUJEoDszEZekQXwiXLKEgunPjoBytGTsnIBlDwuYhvbRvXptYVsfSKUKODHaKvAlRePTlTLwo",
	};
	return EIqsoOJFjEviTao;
}

+ (nonnull NSString *)UUkvYIeROCirdYojI :(nonnull NSString *)fYTebzKCUIhZt {
	NSString *naekvMmVFSR = @"FTDdJZcRLDiWykfxtmSAgCyFfnEaSLFKKUQsOJLuPFnntDLqPOiBHpZfhVImDSuXSaDUrRgeFUYTEpdFmMLieTGNQCvafLcQWBiksI";
	return naekvMmVFSR;
}

+ (nonnull NSArray *)NKowdgvTzHQS :(nonnull NSArray *)WUqMUUaJfHf :(nonnull NSString *)EbyNvVjbtZL :(nonnull NSArray *)KspAGTrePD {
	NSArray *dDrVhAZBHWhO = @[
		@"BoPDXGwSEAnwJmhbbokBBePwgXimQkhJGiQvRuVGlZhNNOBqsmpyPwlNXsxWtCsnvORSOxSJfFUaKwDcUPcDmcbcRSaraKUrwAxPuEprSCjyzhQQpKijUzPjzdGuLmOnMLeRsrIQhyRD",
		@"UeoKNcgJDJDNxPVAsEmUqLopnZJRJJqEsBLEWZNabYjcCtbKnzmqeFKjrrAtFbLeZclOwBJMaleqDJhxYDRZJkjGahUNsnqNgJCteRiBzaclIFgxugrvqsxpNMoBVuCAHjEUgWKBYulMhRNAR",
		@"bVeVmuwLKhcKufcTVnPvxpbRPAdFNXGacbWXMWiXYqqJsHlmINgFceFoSlaIYozGWZLxRxHMHuiDuQmtLDEHxMRcjcwwUbHzeiHildmtLPaebzMhmEPguYYlu",
		@"IhZEywtOuwdrEMSNUxlHsxFqXGevkVhDSSTkUdAmHqifzYCmcsJntqSPVyEkRxohoLxiVTGTKjuaQuOfyQDGQFlOiIPWWwClYHdpsXqmkncFDSLNZFZIunTZsmHiFRlzSiuNdXsFOclbWoT",
		@"nZzPNYWiyNfgAaKULRYZPZVylijoOMLmEyNwxBhJXuvSLbLMVBSNBdvKFeoQcoqagLuwFibNSviWnHTkykkzgpCwnEtHRXdTvBpIJqqMFVEHeyK",
		@"ZUNuzOdBvJSRkUTBaLWArrSdsnoEGothJCxLwCXotOwSKEkrEWQLsHpqDwVGarVrxawnKCnBfqBWkfvngHUoXoXyuHBlaYchpEuHaHJzQyoBOoPIOVfBKCKRQqUXkJCpVV",
		@"WEKEkrQBRYHbSsOxAJXaxcIqXWlGtBhxxQubiDHPZwmlHDDtmBItLEmxCqBHmocBekdMEvDemBYSNlySMnqLeJkypxnwHEiwCyouTfTQwHeWmvLjrRKaTsrHb",
		@"ZwulTeuEXjgUNGiJbWuenpiaOHsEXfpyagqBsJwVQWUkilVGnOFvlcLaJFIUFmgPJhYxvlEqlhqMMfpqpPVCMVLaakkkdiDVWNWoZCjUYeX",
		@"JHatraMWLwuatuLRtCdHivZGzjFcGSWkglVOhMNVAZmBwRtCQUIglNbDbVNTrKivNevHdqcLEvvzJtuZswOiAKEWDuSfKyZWTsniioDtCONSrJWWXUtNdUKLmsPYvCuXBkVmvGwyDSlAbT",
		@"ZkYtKERcDMqhAVedoXmwMdpeUjSZYBsZyvGEWFyzpfuCGIcZwgrCraPxGPbNGenWLsbnZKVHfsbWURAEIZuaoWuojGFXmSnQgwlQMIGLENCmnynAleydMvoJrJvnNgGXjMhVKCZQSOR",
		@"HOgOGvQcffDPVdSyGRcUihgHGtwTSdOjPmnbyJRMbjGGxrEfLqiKyfDrAUCzcVaJSGddtEtetNLhGplZUgPJeWAmiMxSktHGTtXPgaQV",
		@"VgCZpkzIpGFuacoblQlxSKiezSGwUdtLRTPkKcaLfsZeeCeelgpFdeYscicQWffJNhpniiFVeUwvdZvBzVhHXinWNUGpClKGihqqNSsHtbtIywoARFXjsYtyOKa",
		@"gAWnENATRNvgnIOfKxYSywFjZZxqHIDbRbcgCZKgFuKgaGdAWICfBvBlfZFErqnauyvCPUQczeNotovglDsgyyWmErQxpuOcOiiJCqVWDGEMBsySOUPQmis",
		@"ykHGEtaMnqjpkighggGlZdvcgQusdNdcVZHPocdbvrSRzVWLNbyzGtKAfNuanbcEPsGMGQPVEXwDrFQYFdHesgHUwqabOCcxkliEbdixJgoKZgXKSYjJdpKOfV",
		@"CURPUjMZdLaCBHYuUoxkAzwsILtykgDLRVxhyVGlVihhKwHBStYiAyWlpGuaQVkFiMpXQUcapdvueKzuMrPCgXWMMGjEiECDvcoIsiQJrXiiomukuqDqioGIxu",
		@"WmppGcjuRSJtPXhoYJSKoqEZSYpplBwZAsaEtpSJULiJZpFpIcPZgENsvCVPqwuIKhCcNnegDRhHtVGFJxrVSlJGROjXvPmwuYEohFPqxVhCLcKyUQqZVtInBrIlcesDjuknLOwguPVygIDlRLTIm",
	];
	return dDrVhAZBHWhO;
}

+ (nonnull NSString *)rsrrTwrClPlOaOEdbf :(nonnull NSData *)RiHnFNMFyozYvAqaVJ :(nonnull UIImage *)DsuqleAtAgpIiT :(nonnull NSString *)UkxvQXIWbpM {
	NSString *tHzKpfqZucIgiI = @"gMaSvAkaTudPUzgglECYwniSNEzumjTHoqapyvByzpAzcBrkMrdlqBtqNAmdCaKfyckPNbwyJfTClgCbeWHBfidcHyeNIcgxkGKGqBcVwkitk";
	return tHzKpfqZucIgiI;
}

- (nonnull NSData *)TlSibikDXEhHvSUV :(nonnull UIImage *)tkfXCqeluSCrRZNSZE :(nonnull NSString *)MyFLShQVWkAgQ :(nonnull NSString *)bXUWduIKOLGaB {
	NSData *YdOgjuUhscQKhXr = [@"qmbBfshOXgFNxOfHgbghVucTOZktcdbvAYESZkcyfHwVWAVYsYQTyMocYlVyFPMZeKbNzUeaIIUedhamXUlvTSTOhcylTRkbHYJBqUyNnU" dataUsingEncoding:NSUTF8StringEncoding];
	return YdOgjuUhscQKhXr;
}

- (nonnull NSData *)tAFRXIVRqCu :(nonnull NSString *)lHCcoGNCBT :(nonnull NSData *)uVYfiTJRgPfJOlSgU {
	NSData *HGpTXOAsdLumbmQ = [@"KNkZegkIpEuPtEQiagirNUZPNoCOPjPbYovvbrdTNGVYpVxQelsptZtcGNqVIGyhRFMaTmasHJGspkIsEXfDGlCHNijzQXWLGigjxKbQmWDmUkBZEuuCDNMtJEPRu" dataUsingEncoding:NSUTF8StringEncoding];
	return HGpTXOAsdLumbmQ;
}

- (IBAction)rightButEvent:(UIBarButtonItem *)sender {
    SOConditionTableViewCell *cellKeyWordStr = [self.conditionTableView cellForRowAtIndexPath:[NSIndexPath indexPathForRow:1 inSection:0]];
    self.keyWordStr = cellKeyWordStr.keyWordTextField.text;
    
    NSArray *keyWordArray = [self.keyWordStr componentsSeparatedByString:@";"];
    
    NSUserDefaults *userDefaults = [[NSUserDefaults alloc] initWithSuiteName:ExtentsionAppGroupName];
    NSMutableArray *keyWordMutArray = [NSMutableArray arrayWithArray:[userDefaults objectForKey:KEYWORDARRAY]];
    
    keyWordMutArray = [keyWordMutArray arrayByAddingObjectsFromArray:keyWordArray].mutableCopy;
    [userDefaults setObject:keyWordMutArray forKey:KEYWORDARRAY];
    [userDefaults synchronize];
    
    [self.navigationController popViewControllerAnimated:YES];
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return self.difKeyWordArray.count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    SOConditionTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"SOConditionTableViewCell" forIndexPath:indexPath];
    cell.separatorInset = UIEdgeInsetsZero;
    if (indexPath.row >= 3) {
        cell.separatorInset = UIEdgeInsetsMake(0, 10, 0, 0);
    }
    if (indexPath.row == 0 || indexPath.row == 2) {
        cell.userInteractionEnabled = NO;
        cell.label.font = [UIFont systemFontOfSize:13];
        cell.backgroundColor = [UIColor colorWithRed:242/255.0 green:242/255.0 blue:242/255.0 alpha:1];
    }
    else {
        cell.label.font = [UIFont systemFontOfSize:16];
        cell.backgroundColor = [UIColor whiteColor];
    }
    if (indexPath.row == 1) {
        cell.keyWordTextField.hidden = NO;
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
    }
    else {
        cell.keyWordTextField.hidden = YES;
    }
    cell.label.text = self.difKeyWordArray[indexPath.row];
    cell.image.hidden = YES;
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (indexPath.row < 3) {
        return;
    }
    SOConditionTableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
    if (cell.image.hidden) {
        cell.image.hidden = NO;
        if (!self.keyWordStr.length) {
            self.keyWordStr = cell.label.text;
        }
        else if (![self.keyWordStr rangeOfString:cell.label.text].length) {
            self.keyWordStr = [NSString stringWithFormat:@"%@;%@", self.keyWordStr, cell.label.text];
        }
    }
    else {
        cell.image.hidden = YES;
        if ([self.keyWordStr rangeOfString:cell.label.text].length) {
            if ([self.keyWordStr rangeOfString:[NSString stringWithFormat:@"%@;", cell.label.text]].length) {
                self.keyWordStr = [self.keyWordStr stringByReplacingOccurrencesOfString:[NSString stringWithFormat:@"%@;", cell.label.text] withString:@""];
            }
            else if ([self.keyWordStr rangeOfString:[NSString stringWithFormat:@";%@", cell.label.text]].length) {
                self.keyWordStr = [self.keyWordStr stringByReplacingOccurrencesOfString:[NSString stringWithFormat:@";%@", cell.label.text] withString:@""];
            }
            else {
                self.keyWordStr = @"";
            }
        }
    }
    SOConditionTableViewCell *cellKeyWordStr = [tableView cellForRowAtIndexPath:[NSIndexPath indexPathForRow:1 inSection:0]];
    cellKeyWordStr.keyWordTextField.text = self.keyWordStr;
}

@end
