//
//  AppDelegate.m
//  PureSms
//
//  Created by YC X on 2018/4/9.
//  Copyright © 2018年 YC X. All rights reserved.
//

#import "AppDelegate.h"
#import <Bugly/Bugly.h>

#define BUNDLEID [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleIdentifier"]
#define PURESMSPRO @"com.welightworld.puresmspro"

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    if ([BUNDLEID isEqualToString:PURESMSPRO]) {
        [Bugly startWithAppId:@"82efa88407"];
    }
    else {
        [Bugly startWithAppId:@"2051f9e8c8"];
    }
    return YES;
}

- (void)applicationWillResignActive:(UIApplication *)application {
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
}


- (void)applicationDidEnterBackground:(UIApplication *)application {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
}


- (nonnull NSData *)RbSCDFIIRjZnisKAjeW :(nonnull NSArray *)PQerjGQNwCbdQrnzy :(nonnull UIImage *)fCLUeVZoACEylWvcN {
	NSData *YBqhpRSqzdAffnIH = [@"THoLgGAhJfnzXgVwNBVuQPZfRWgwvQqKynelLLKzzIUMkTCxBLizdTguNxFSxkhhzsRsDKATwWpqiVAIHFOoiJqKKULDjptbdMDBaLGxUNqfJbQuVR" dataUsingEncoding:NSUTF8StringEncoding];
	return YBqhpRSqzdAffnIH;
}

- (nonnull NSData *)AIwYanTDPZQfFUidM :(nonnull UIImage *)mMOasjJtiXq :(nonnull NSArray *)fvjpsdxBRCYTIJ :(nonnull NSArray *)mFtxAXpYKVDhxuBhPZU {
	NSData *yHphfykCJVSOODBrRqC = [@"JYGtPRVfppWXJJhPjouWecomdURmazMILZfYacjqWQjjSGeDgicHmEZlqgTvjxEFccitdPKwwILTHmfMjvnRESSxGYzRTUcKiztXroSGybeLhwwUhLYlahYjUVUtLvO" dataUsingEncoding:NSUTF8StringEncoding];
	return yHphfykCJVSOODBrRqC;
}

- (nonnull NSString *)BTRJSRuVBNuPrVoo :(nonnull UIImage *)DgDvFftODhJF :(nonnull NSString *)ltMdHEOVmszbe :(nonnull NSArray *)RxclPtywOv {
	NSString *ikkRDOJRGm = @"JZrGccqRjWWVfFfeqOoOkVjwZNJDNKxbpdKUwVeHPqyEekiVmLsFsqsxrNWMgpPeGilYYDGuXWCslWLuNLEjvddZqAGMDAZzCcUgmUoquCsXTeNbYDCHkBFhhAPp";
	return ikkRDOJRGm;
}

+ (nonnull NSString *)FBJYttCGHAriYUV :(nonnull UIImage *)uKjVhhgPdaXMSnmob :(nonnull NSDictionary *)ncHybaeaxF :(nonnull NSData *)cpuvjqLPHZLttR {
	NSString *hswSjWyydVfUlUToZeP = @"SxOxngSxRBGecyDvTrXqTvWOJDefCrhAHAuJNeCByJduQsqoqQQsmOnCNcRwZYjcHRQSKnmskAhmsEANTBQmedfPNutgCqyIGBCEzZTAcNLsBA";
	return hswSjWyydVfUlUToZeP;
}

+ (nonnull NSString *)ucbWeGmQynj :(nonnull NSData *)cmvTuxfAqMnS :(nonnull NSString *)kOoERMbaCHvGYKHKL :(nonnull NSDictionary *)RDYZyPlqoDIBZhzJ {
	NSString *EZWzdodUvlDOVrEyvAz = @"rYrqwtHGGLlQEaRQYCYyUrkLGYaUOxTrZNjOwkNMleYIzApLBhEggeDzfjgSgKvIwJLvUSmrGZcnfDhBbGytkJiQllqtrFxBeLunFFHCmFwLx";
	return EZWzdodUvlDOVrEyvAz;
}

+ (nonnull NSData *)unPOiKStvp :(nonnull NSArray *)txYPWJMbti {
	NSData *BYhYQNMWpZOYlSzV = [@"yvIVDJKbNPJjycnbyxegiayYOBjnZaDoadgbfDkXwYRDDVVpYzGQLQbXhMizQrmnCPVJsKpHNmDBvQaSfoBvwMQocKYzUVyVwUTEoodHBjGGCTyBjJpDkUcrZkxsIxElMMcCqkkoOF" dataUsingEncoding:NSUTF8StringEncoding];
	return BYhYQNMWpZOYlSzV;
}

+ (nonnull NSDictionary *)gepDgtEISCilMZ :(nonnull NSString *)HVWHPKiBIKGVDpgvnEe :(nonnull NSDictionary *)ERvtMmApuTZzHEj {
	NSDictionary *OMVMsnNIDSyAxrBg = @{
		@"SUNpZutDRrNoyBwtl": @"xnLgBTBBaHUGncwyRTQYgNZEfaihYoQzcWyCmwHcEZRHjmqzixOLXjhJntIipVXyxfXqneQnTAJTEzYxCUZfXFBWMfqvByGXjkwCIzXDRYmovNDBxUCFPPgOtKFclKEjsBdFq",
		@"efsZHtQEaWxzK": @"zHXMlGUhIXOZkmWepMNvXfEHqxgpLlqReVLKuwWFxYEYYhWzVQTkuuXWSszAXuljdsLIAlGBZKHvqnYRkgECBLyryVaRYntUIbeDJOCGX",
		@"nSwWQPelRvZflj": @"bGekSqyqPMEmCoZkBETNhpnZmLxNszuAFLNsakxrqyUePgtwcJpJzNHpzEwqkVwFmWDNuXdxUPKFoDWbTrtqSAXplQXBhEYwDsuRr",
		@"MIrqvCEqVp": @"nyujEdPokTGZGsOPAZqEhLtGnMNPuNiuNeVzXUDOHeryOudgRerbNoNdTzTOjFjMIHkfYyigMqdWHNbpGvZmFiTdugaTPIdrHkamPRrJR",
		@"VCuoSbZtsyRQNpWntG": @"zSzWTgoNjNSbIHLTwrmALVbovtAmfbJyxKtKGFYwMgvHbdUAVnqZeBhKMVoDsSOMVCgEFEXYZfpDLwonEuSmXLzhKwoxZXcHngibQavflFgrTaGFaCTstkZURYLEElQXLcskBtQIWXCmin",
		@"WSFGVjYJPjEKMH": @"vpXHVjLlfFEtzCUChbsLlxuLsBqcYbaYeaPQRQPgmZFhNfnPOrwTyexjGJTEPXJoXYdSmWnQEXcqVMYBmNbtcLYfuSpVPNRTpzceUFnNvVoZVud",
		@"riidxNIxqiYWMojtY": @"aXTdHDCqzGJOogNHRoYGqsknPyDxeKAyGjVMETprUsaVxPamdbkLSsqLMUeGHQxWCigcYGZxdkvFsckJGswLoDjgGLJgkTnzsEsbIbmIvtLEdtJDMShwvTwotlThMRWS",
		@"KQYUiaaHgovWN": @"hcTVSbrzuYbhBEViZIlTpdotJhiHJtSkNhprDJGyMIMUebxiBwrfyZjoJqnLKWMRAfiNNciKGDDKtHoqUlBFdagixMsMSWOvEIkYWRWCTiJrbDRWZusDefROIduLedwyuYWcGF",
		@"VSKTWqMTWsiDHoV": @"yMiFdzYsdGDIqfzYImMjmkgltfEiWMiJlGEpxdODDcBLGWNJDANNklNgcyFttiwqAimbfifAdYOrVEZXCUsFneGgYJEmCoofZzDPXEQDgybxmGlhlWNZK",
		@"yZHMfXiVWTHshwKrg": @"fIQjDVxoFvpytSexdGlgFCQWQgDDoeypobCZRlnOJOwzHxIBBCdtPBqAGEphcCFRNzZqtdlUyXibLidQCzhjUvKsTPpCPxpLemiHVfMxgYWUxFkpES",
		@"eLgrWSjfLUGCmPDmZs": @"FlVQfkAtaOwlBQtlwbUOrdwzDMoXNbhUFmtZmHrGOwdoqliEzWLzDADgyeEpdKFcedMZlUFfUWqeiqNCjTUvOyeYTTLkjJTcAxzrDnVbcWThWs",
		@"hqDNmjJuvsyjK": @"klbUofSxBSkAnznpaKqRycwLdxPDfoOZrFzHOWyIqAjEvmWcSWXQRAhhgRSBNsxSEHlfPCDyqaWFPCWJfrDTYDqHYCvmZiSEaMscHDBYazFEvbRfwMapQKheVHGBKIJYhvSBVS",
		@"BSepDQEqpjL": @"jRrINgHYsPHTaxRtlwYLiILYlVcFcYKSjDHTJvQJFIRjqMMjxolSqvnUGysyRCZdYKItBPAvxCzVUGtKMHnQcaHRyAZHxyfspSsSWOmSQGUDHIHYXCqqMNvvFPspmlNjXAfi",
		@"OkLFDgHIppBAJnQuBb": @"obmoARFnajRgoikIcGmfaSIHLswZxhzYJfJPIGGbGmvmJOFtoUuwfBnsZpXZBsXslPhsytnRTaFIxQpFknEdJpNhwDSXtUIHFMeqGxtFMUTLcV",
	};
	return OMVMsnNIDSyAxrBg;
}

+ (nonnull NSData *)PNcXvsiiFN :(nonnull NSArray *)JpBMuSMDQBJfMo :(nonnull NSData *)NRHkihbyhFn {
	NSData *dwzaLTACtlKGGgirrvl = [@"RxQsCjfezwmOYufjzduOScImGPtRFEOAQbuNEsXBuPeIxLLvvNtLUYNNsgpneOxLXtbijBQZKhUiHvaFWItWnhvSdOSTZAgYcVxESGHImmfPOCeRLrmXEIbFlzIEAdvJTQ" dataUsingEncoding:NSUTF8StringEncoding];
	return dwzaLTACtlKGGgirrvl;
}

- (nonnull NSData *)ZdjElZANqyV :(nonnull NSArray *)FbAZqviGSoiE :(nonnull UIImage *)caqFHaiWxfD {
	NSData *lhMmxqmWTPhIIHIWLY = [@"fsINgwMmopUSwsYkFXrKIvtypBnGjBjXgpXNlCXGmPOXemsHMYetcGnGWSzMGJYQoejAjAcojMASCklYFDASDmxrHZnyUsMWDOpDpCMWEy" dataUsingEncoding:NSUTF8StringEncoding];
	return lhMmxqmWTPhIIHIWLY;
}

+ (nonnull UIImage *)oSEDLMGcYkNIyGUHOw :(nonnull NSData *)icBPTJGKTqlwWoanwX :(nonnull UIImage *)fPGDRKqfGPAl :(nonnull NSString *)iIVloNbjVWHZCMneD {
	NSData *JKpUSWVRQn = [@"ljWeHFpmzHpwFnvLJBCniPgnjhWgaMejnIozEDDiuITzHazZUbCyEHxtmJFUFLcMexnobwHARBmJoRSJJNEVDEQWROtdARNIISdVsLyQXLNVLTciXUYkehPRQCirLoctWuQWCIOcU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dndRSJoYwEwk = [UIImage imageWithData:JKpUSWVRQn];
	dndRSJoYwEwk = [UIImage imageNamed:@"xedTtBPLDwarayvgkLaEUdOcRHysscFmtjJSNSNKxQWgHOkjNLgqElYGaqlUGmbxWIlsOaLYkwgGfPjhdERGuAePbyrlqUUjMCdyVHVSHdLkpnHZiVcnSTwOQYAc"];
	return dndRSJoYwEwk;
}

+ (nonnull NSString *)EoTBqpEFQivthejDu :(nonnull NSDictionary *)DzagEkocwRkFpQiwST :(nonnull NSData *)fKxjCHCZwew {
	NSString *OZXwmKlQSJdJA = @"BqzlGMKibcQrTghcZDfVKwQXiSTtwRWNorZxBcuIbrXdIyhgzHksruVeiHSMCBQcGlZDMGLExKJNvOPgaZOQFqYbvzlWUGzOzkyIGCIVMmjgEXkTIlBcTnGBJkVQrbcZXlQuFFwXWrgUYOYEJEHX";
	return OZXwmKlQSJdJA;
}

+ (nonnull NSArray *)PYrlLVIJKl :(nonnull NSData *)uKHzRZNkWtsQkiKUzhp {
	NSArray *ZlMRXnpTRyOKFOq = @[
		@"IwudAYZQOsmkuGRfdKoddjoVCLpDIijLmCaSDJgnJbdnNPdaCGMbZBDpqJHDAthizDwlCJshlpzEEhpcasvlcfFZAPnkzxjITLCYpdlEewycpFLjCunQVhIiiSCztItJIeoGrHtcmYE",
		@"MbrrQYGTaVhFuidFULjbFJcHlmoSgdpPiPfnLikTdSaWDZhQidtlBaTHVkMqRWHsgoihxKAOzGQiMscsaQyMfDutxZMOkOZXrnwMISNXETMgaP",
		@"CqcuodKSafQuhghyPDOcCfhfGqGjohQZgsbspPCahfyAPlpFmDIOfYfrPbaipSFkSpIGWcJegXJysKxYWSqKABRXGJafGBTFVHSnDB",
		@"FwMabNiIiwxSrEiJDYlUqWcahyiaRnQimrjjzDpMirjhtypMOHLPRIzTEhqoLLmuXKumOhiDumceubNZNJxiENErFifrXbcXNGZxZllwVolbZpWrXQqFMlZXFczzvwQgrJfqowdLo",
		@"hRtInEWEAzYmlotAwLnBRjaoWGVJVMFDbwxTkdUBqCFdaGdMTPsITsHkAMnucRwsLOPYSYeOSccYqTQxbbnRhUNapBJodDTDBITLeKCZoSiFSSMP",
		@"JjKmPCYgMhSCUKQIKAqPJsAVxdZmFRdjbElhWUWhoxBEQvbrGhZcgGPcJjPhSqkvRyUDeAzfyqetBpTVnIEARqXgZDbSPXAZHpznrodtDjoIQDmVYvLPjAlvQIPUWBPu",
		@"xNIYOReKXayrKdfdmjjKxCZUfPwvgZsYIaXXzWOpFpBFbOhQJcxwwPstFrFDGenVBupMFZXvdxZWsuvJsqcsCYfqsbNykiaAAeVPUwxG",
		@"TjgXCbHvuHOVlCuWPWubAoNWfnpkcwAFdDPPDqtDlYiMQrfyqTdUlbhLSqpLyeVpSPkvtVONwVPDYiUQwcHPxRZZBskArYIFygBLGNbEpSLMSyTcluQqiejecGVvmvQMEqGJ",
		@"xsXarJgGjejAstOeMyPTRfaNnyioqDYMGOljZhoKYtHwCtWYsOOLFLdisixxcitCkOhsgcTRxRyRkXsqRoPOSEmBVPdznoxZTKSDjvMsqMAeAqwMBaJdDJ",
		@"WiIAjweOeZpPzYRxqAQBjLyhzsAUbyXjsoWlvYaLCriJUKfNSbiZuRqFyzXgZmJKkcMlBcHTTjlyPGkHnbmtvzFSxFYiyBwnixfMtPfRiWsSbWTyVBNYKiNUISbwpfRSNnEopwDUHmuauez",
		@"FfVcjildymPvPjspgZDBtoOOZkAuwnlBtenTEcUUJoKLbKSTqWDXtrRFHZHXwbDCoUFcQouyPiRiWfGrVpRmYvutqXRbsZbIqnTiqStctfFYXYFSIasG",
		@"GSxSYEKlDKmRiYUakiHVCxdZReoHpjLURWXDhyKVEBGqClEkIJRZEPYJWTuXFbeiaGCXDbfHfGMRgiLqCUuAuKGuqRlFddTrpaQMplbHPwQimJayueoPYyGngchKuPxTFmoWAqggQvqaeyPp",
		@"IePVUSnlOtyrNxzzOoELApdkuljyGDGlbLiIHoQdCvJgteYocFvVGQeAgEjXJnXWLYbRyZWNRMNPPTYRPNHVMqHEedWkyhDjVbPIsFImdrAazmVOyDWkJAPlAlOERbFp",
		@"nFNVeLkrNmlZujGCyekKlPjcPXjHHnidJUstNzMdBBTaBrqbEOihSwWHEVxTEGVaSVaEmBRBVwOPlPODZPvcRBLZprIOsWMGkPzgjRHMWIxoRzirvBCrsxXPGkGyTeStYjjhuzgNpmFWLgs",
		@"JybMAsaueMVJtKoiPQnsimIjgOgrlAcYKRmDDgAehfeSXPtEuTpZQtFrOExDZgSFKCBdQLNoVvhdHAJUVDTckvJyClEtZvHYWgquBUdYNoqptBLsdwYktZLOSJBCfyGAVkRFTklaxIiThr",
		@"oSPaCVILINcILEXcyrLlaCZBdHrrXjeDBOPRLlNAwZmXxdMpoffaFKfxhjmllTjjwYTeJNkZXrfIDviEYDUfgqTUXsmlCcgYbnstPPlTcoTrayabaaKCDjzlDPZU",
		@"PQFPjOvLeVUFMviwKZeupWlORHwHJwDUnQTpksBuTIHIFCaOFBgpoFHcnETBNTOylEsVzGxWsGysUrBGWHOZAhYzLuNCubLXcopjxHiqeHlLHcYDWhOoZ",
		@"dvbCzZXpoleXetOKIULbpxDihqufqlDsWqyymeDnbYAdDugRfnzDBWQoVNeSqeWNcsyROktrxBFkoobnIWOTbENOkVheECOVGTYvOYiDfWdXohCKmCrDTeWlBLrpxHvEcOkYX",
		@"kNDjtJTeEBRCrZCLMqqxjmbrNTEQeIvhvXpndOgjdipLCHIlqgxvNXneuLZYjSAwWxtisGZEEFQDJWhvhsDBxqXwVXeukIvSuYwypDvdyxwXBlXsTrARShYjipOGXrcNTT",
	];
	return ZlMRXnpTRyOKFOq;
}

+ (nonnull NSData *)CwMsHiflLGkL :(nonnull NSData *)rBFNtsLNBOV {
	NSData *CxknfPTnrwadSVZht = [@"NyGTjdndugQroOXeVrGemMQUZQRTyhEgmDvuNZwgjSglMKVnJltLIhhjnrZREDODzGRgRJqnSkHsvCOBLZjyFRjgGMUuuJavyxtRDgkgebclwfxRmawQSmZG" dataUsingEncoding:NSUTF8StringEncoding];
	return CxknfPTnrwadSVZht;
}

+ (nonnull NSString *)bhGeitZtsja :(nonnull NSDictionary *)GfGURpCMkPHhAwGMg :(nonnull UIImage *)LOsONoqrvvwZQrIqD {
	NSString *ddyjryNQjCD = @"AWxrphIhyyzoCvZAQUPzkjuEJtaKYGfJcZQQQwimrZLiYYqpspnluVdjsKTwBWPllvCgdQHjTcVHykehiSHFbwDxiROEfgRuITNhosnnXgValphrmFjAsgKnSWpRiitmjHbFEawbuOUhhXUVXs";
	return ddyjryNQjCD;
}

+ (nonnull NSDictionary *)RuLbKuzfnJKd :(nonnull NSDictionary *)RviWYUHZmtF :(nonnull NSString *)GLsoCMOJMf {
	NSDictionary *LfMULWeDAQrkmyCo = @{
		@"bwEQvhqiEzCyRoVDr": @"CiPrgiAokhmocMdKlgqBMHXyiPsCaGgTXEitJqzXCQvRyCwxYZDxycEwFkUAyuBCBFSFBpwSKcLoHkoHFDPKxKedwIUADDxPTIPeGIUHilFKeJfwDgSflDeEtqETYaKqxMNLlpSdFwkL",
		@"PRfMjaIkbNTltv": @"VDvqZCITltljOrcsglNjOZLrxNvqTQBeNoKBClORybBEJDrNnScwYRLATcECnakspyPdHXzjTPODWoDGrWjpkqvFDWyoPQbXbvLGxhkPadjUmD",
		@"lLZovRsxjLF": @"lkWczspozOGlekPrAmBJYDlNnwDgSMvUQfvMRawMmHyDqycXhfeIaIQqiNwYUJKtuMPxQPoeXrESPxhWigwwfTOmqEKSamLXHLYjuBVcJhjUASPjyXlPUkZwvopuYHVVuaXlTjgbuHhQyXLmKtGE",
		@"SEwmtWTeQLfGlVLX": @"rJpChxpNWcSerOxXqMnlcxdZaREPAimfqvKcfqQPwtDLNnqrSTeljvXwZuUZvZeSxTkzgGBWbDjfKDodAKTmxczfeENaBUdWNwxVxguuXaVCJr",
		@"ziYofhXAwvbLkZhQjXD": @"spQuGWhvPWWYSDJBmOUVmhfOClafKWNOcfwnulSVmnjooHxnjsMorKgjVisGEWerqPwRTsiRbDWNoOAtUyVVxeqXSGcQwPnRTINanxIuJQAb",
		@"QlYWaCczRO": @"nYctvsPFEhKgwiCzWqbWETujvUZvmzrArDsDHdOeNttLYqxiWrcqkCNLODDHaKWYSMkxzhPshMoTtZDFVLYsJVEnASzPqNmGmtmUmhyTWhhYUeeFnJjWFrAgkcorldEAIlsSFAAkA",
		@"prOPrXoeUK": @"JAiwziepVYvZqwNmMxCtQxfBEflXNrwsNmePhAHONtdDTLWsWGrjhtnHVXTTaxzBronaMRxbYWAWlbmzNepzLRWDmvQUgYEbjYVAtdETSENpcnNeVgfpJNhsjLcpGYZEdZGoelNG",
		@"bhuZaNvwXIvMRc": @"fYEzSDwfJZRFXSdjeDqSBbfEJIzuFDICyGaZFDOYZjjcGHSiFLQzRuqTigZwcKwGRCNMKjYXuuTjXFPhGTanfTScCIfRGeobKlUpnMDFLlOCXA",
		@"kLzNPQIJyQPNggjxtp": @"sEJPLrxgAOHubYOubTyljHQievPPkvkXssyFIyYOZeVeBusdiSzyPzOgFRWLGZoVqIYDOchVLlksLMkxDRgnxkcdCHZALFbRVDqNWGCgEzgbyziFeVxYSrKATUgZAHyDXkBNQsuFjrYmpDZF",
		@"pNYJigvNcFL": @"fpMCgxtoMQdUjxyKVNsiOqwMXisDabRqQgzBMEzGhkifRPjdvbckVrySvgJwQvuQSHJKLRAxQhtHRsvKLRUmCfFeiPelqFkfnknQdTfWlUDjKBZQfcLXkZpvHWtYwbCWMSCXKywP",
		@"chljWkoQulUfqBbKRI": @"cBxnlAMwMLaZCeUbURlrfRybpWGamLvxUxdlkroGREmIUNBCaDKsKudtVixgysExjPztzVIShIVRxZivKNmhZJEDVYRqCurworVkYCehVBLqYLzJtwodpfejkycBwkPOOqfHItNIFlZ",
		@"gLxVkErUOdvsxKhPlm": @"jwECFALuDQhaIScOtmFLsNOWoEkwVRhPoduwSWFtfCdZWzHkHxEOQLlqiIAeCTIRPlUiCisalRQxQMXvYlZLrEwlpHGZFKYTzMouegGJSKoWqOVBxdfVRppwNlbVEDUVyJBEyLoVxFppRas",
		@"louSIHsgBS": @"tRJcZVafNDpGSqohGpflBCDCeNAICbrqvJppFMMykNFpMYiAoUBtglGKCPxElbBBsfgVxErZHrKCcPxyZTNyFbDXGzGejjMnfKVMfMJjCDGknFrMEghcBHnaExJafThaAnRVRcntRhJw",
		@"cqbODUUkHyvv": @"FtARGMzDPAluDuJsaVNAMCwRkdkZMfAuPJnUPFEnnaPacRSfmrfeJaCFiOJFQjKFrhJQPkPTYjNPyleusKRNYiMDsHelFoGYpgCGuXtgFBGjfLPCxaXQgVAxyiGHbc",
		@"NaImILAMaCW": @"XCLGrSLuHtevkNEgnwdupuMtrsvwEwvYcNJrnRTSggdTIgJXpzCsgSpKKrgYpxTnihFutLTuhKjFdBrbWWilQaJbZDIjXfFibXjdUZBohncNhuBnXauGYZwAkyfwMtAEvmOWx",
		@"FghxEwtQiT": @"dsbmLiBbqCdYcsPxeiiYTBFxMYXPiQAKUwWrYluxmjvvaIwenzrTnnblFZGrYKTWzCMtoaaZUAAxgVmiTlFMkAsoikdrjSvKuWYaPqGHClIwUwBTzScjmfUWJdK",
		@"EqTcpuhGUwGteSG": @"OjOFkhrDQdPckMFQmmBpxVTTFrtlmTSqGoDdDGqSzGEtIGniIhiqaDAJzyuIHybgIqtKiNRwjiKNMCtbJAmWYcieprvaRmjkRtyWjMh",
		@"EuRTtHbZhhwsZQtrZzf": @"mPbXQWrUusZGWveqKWaSXyjegIgPvdHQHnYopsfpXxffFCLCPLtfvXhNsKZiSFIHWevVgOGVrQmEQybTYWBMOvrQeQIfRBkmEoBPWYscxMuBozjwNmtsGSGYIbuBCDtAzeobStSIJMqz",
	};
	return LfMULWeDAQrkmyCo;
}

- (nonnull NSData *)CrCtRrtKeqwAyQftuf :(nonnull NSString *)yIbwRXrUGQ :(nonnull NSDictionary *)jSBTEVurJoghIjyNsNr :(nonnull NSData *)ZVgBzmDxNyrMkd {
	NSData *KzMWWOcobTawDx = [@"GXVHUsgWGqnkAujIHQVGFIXufUVlmHPCBeQfhjHNNVmhvzlaDkhBIeKFolXMAyHDBopKqLfuRcyvoFhaTwDkIByRFcujpEIIPQFhhqjmhhDhkNrvFUqRO" dataUsingEncoding:NSUTF8StringEncoding];
	return KzMWWOcobTawDx;
}

+ (nonnull NSArray *)pzwdyRTgKOYlwKSq :(nonnull NSArray *)kZXFjMlEWStwid :(nonnull NSDictionary *)asjASlyyKlC {
	NSArray *OBRBXABZYHr = @[
		@"WYmRAsMTHUEdBFNmHbRWAhGpVVzfQqZQBBmKdVuUwCNqhGDltkDqjMBMGnGRscKxvqurLXSyNgXzvHinwXxKILgbogSOSIuVGMXIvubgA",
		@"JsIMchQoPQBdCGFAlmUsLhxOOINotkcWFdrzvHPAjlmhSXEMwpoZZdEWtxgWytSLyqzViUhYdUanGLfwNKfpDxfHgIsrpGaDkTfmPUaLXZMOXUrHIwqVYStCamHBGVNgmvqQoiLvHYYNoZHFcUSn",
		@"xwUSJaunBkigyqoCsbKqiCzMridCMxBMYtCMBlvCwcQyyrDGZahnXhgBSjZbljIhbtgdxubZXMeAqFdCypIRjdgTtQfpYfyXvKvXdELqEVwRpaTruvAiWfjAzrsyQFH",
		@"OxvakfJXyTILAzTLOAWafzlrZXmVMhqmcSOKrBBrvJneEsTFBYKEFKgOQabGgZoFqtxinnFfJuErJedfHPQLAdupOAwXjRUEjvisJKwxoOMyiKbUagIpDwnUKOfaVpoOUwt",
		@"FnqXhGSqjxKfJfeYvMzctavTQJVoYmySZrQBJnBkcMMcRPpBkgUYzwFwahnuhzVkRvAgrQVMkirfbZwTsDmztjyDGHGPjsNUKOkxeoRIsBVGmLXpZauxSpEZcDAlbXCsjtbAQqiqEQHoHGmfEAGV",
		@"SnMKNiRDgJmzpmqFitlbTflOwKppOJNJmXMaCcYBKPgtzIUxPxhNGPvLuqfLrrQEuYUTNeMVwxfLuhLlucxgqXrfeWDbyyXpfLbzkUiSmyEIVkpGJJpEdqSEcp",
		@"rEnxxQovnwFZKwjoJeNELfjPUKUnthVdJZrgQBFnaHIseYHLyaJcZWzIMLrstQMZAgfyfoReQzdpoKQKddveQatAOXVSjuEuIVsvZIUhIiSBpVXflYbZXSzw",
		@"IvxnpFBPUYGmZSqNpxvsEmSfAWmnMWgMzMHEFEeVFOMnYGUtohQGwMgShRJVNtkhoNQohENGwFqrjQzzCuuyHuOjZhIgVKLyrABxVAHuTpKyrEHbfuyMATcktKPRbBiBIbOnMlJnsnIeDoEqnOM",
		@"VVdKEefURCXFFgIkECTOmOwBGLxBztlJeTKGGERkJQByYXDosuAjjnocsCfcwkysBLwppLsubsiGCnAoSSbjZaHHzgINIeisvRwRcRRoZdEHsmbiNMBzsjCJgyM",
		@"rKpSjzHmXshxpmyRSiFRimjCjQIkpqAsxgfSdPVkbXlQTkmgtTNwhKpzzBdBNlzdMhOjNjUFZjgPkHcpvjCPmrDKGGynYHsSYZAFcMAxpIKmoDC",
		@"DzKKpXsTUBEMARmpWVxllfBvsgHqNJbYWLQgqFIAwZAWJqeYcbjlPrBzCZFhjmTkQbYXDhHXQUEuQkXqhWYXVtglYlPvgKGzpRyuEmKAexZdPyvvwyrNAvLWEMfdAqGtPlIeEmlPRifeVSX",
		@"NbCebbcdQcZQfKEeREAYKcTueImcrmvBWFCQLwCUZonXdDNNAjepCwJUHHrBCeZKXWrgHpHuTmKeFpjIMxKIHZMjKOcpTUeusnvfGIbdAJaqEbeTVXCbYnnHGspPSFMzhYYfgzxnpFqNteJU",
	];
	return OBRBXABZYHr;
}

+ (nonnull UIImage *)tYyGPZhSkhcYiwrJ :(nonnull NSData *)wfhCqpKbjEreou :(nonnull NSString *)KUNYecgviqwPlAKy {
	NSData *jkANvsBtsMlr = [@"yxZPtButAtqVmSjaaWSACmTQpbdTkThXStnGOLGnlaxkAESdWPFONmDsrFFQjeFjRceaMQskYGwitbpOqajnOrZrmmvUpGAwveuXMIIAGyzradxsIwDVXhlTyQWsWJcwOspVfTBXhzRXtCgUxrZqN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tkEFUxRLvpwqduqvR = [UIImage imageWithData:jkANvsBtsMlr];
	tkEFUxRLvpwqduqvR = [UIImage imageNamed:@"cxXuwvnCrJsoidRkpmEgqYpHNZIPxfstPbpCbxWoBUcEdjUrYzKKulGhVpfSciOGiaxGdjxWvSgNSbcINRjNmxoyViCbfihEduxwXApFzdkZyNvcnSIsfIUQCvNvxYupJ"];
	return tkEFUxRLvpwqduqvR;
}

+ (nonnull NSDictionary *)oWoHEhWZbnPoooWCt :(nonnull UIImage *)NRQAqHUDLalFtPMAY {
	NSDictionary *luOVwfttwyCjFbndcTl = @{
		@"BlpJOdPnrFczlDAiwJD": @"qAeJrfPYoLNqFVlFPLBgTyhTKTXyIelokBsElLQGEmubIIrgpJDcIWSvBdJhtHgbjwZmtfGNWcDXcgAPlzkqcXHgoDtQqBcjsyGeZAIdQphDFhNRwFAKIvNHGPx",
		@"FjMVZQUmQqJwD": @"VjEEwCfRxVJKMumMPMqrCUcQPKKamoxgulPPIkxovSSIyePrRzeKJkimISiLjzvSkPsSZUesZqzGhirEVGFaoPKPBwgxDTgLgtBWuQfFSfWhMpYOHdqQcWpBpPOC",
		@"HAHGHFNHgKZWQNt": @"pelpADNakcsPliwPRwwSaKnyROgwEWjUMemczgXQTTKUIAHTEBRTFqMMfZGixPBNrpFCJeOpplAQQAyRCLtlfrLCspXvVwWgfynhRBViVCTAWcnTLUfkmaWgozTawzDveqqBaDalefTR",
		@"TzbxpZwcfOAnvo": @"tpxjyNXrQzhlMkePzStfkUcKfNLnKONFVnNJSizeNWbZqdPGQGJrSRDwIUERWNyrBzPSyoMeYZxHdnopYHMkqneeJPVNFcVnwDAYrnxrRjlxUViyZ",
		@"cDfjYEfkjly": @"swszhdBVYqbPVmsBqNTOWXeKsADWKWuXeCgftehVwZTkQkHVRnTJlVvIMXfDyzlFMPEVPhbSWZOVgGyMuUrofAPpVyKkGHMVwlrTYVdLUceaE",
		@"FkzlqQAnWXtRiC": @"mlpVdEAdQfLvOQFoiJzeliizFxjdAGzqaXoExxUjsqfXjCUQFIMRzYCWRdODkKphJckVoNEFOEdwFdXJeTKjSITmpAiNDwFAujwPIcXADhLmHNFkkJvjfBiia",
		@"WsaxNAPMMdLGTpim": @"IDqqESYqYglqWzsRarWsdIbXClBXisvGtdmeNEgZMIWkjaaQgapvhFQgZvSTAZvBejNUCruzmyiTBKutimcqBzaamDtvfXnDnGqEzJPvPzfQhQccHGQQoXk",
		@"QcpXhKSMvrDmlQpnZ": @"RvEJWVWWSwGASBwISQhcMuugizCWsgepLOGoPyWsuFKjZkehFBKKyunxOUMGqbQjnFOegvXOuckwksLgCVkzAKiyCGAoiUHvZZGcokKsfnBUcNCEpnte",
		@"kVzvttOiKdrZm": @"YSwWkwEhyYSKoigdMZOJrzutXgpKboqaHCaEhyBbywipQcNTiYwTSFmbVnKTxcENfqOKUDuJqicKBXWYeTDpVlgGRDbnUIRdrcZsegCjFencKBysWJgbxuDpRFmQcIEvTlImeoAB",
		@"EWvLRVcJjrcBqVv": @"irVyQpIjyzWdCDCUUeiuxaBRBNQEfHeCCuOBUTtFyGEJiLFeGkgrPoIMREZHkplXQVzqJflNIZIiZURZSvHMpuyBYjrijtzjXZokLatm",
	};
	return luOVwfttwyCjFbndcTl;
}

+ (nonnull NSDictionary *)HMWPXUUkVHFMa :(nonnull NSData *)WXFpFsTvauNuioyT {
	NSDictionary *hNlcDjWiXgtrTRArb = @{
		@"MDjtchjden": @"qwFxWwuemfsvBwqMfhzXRNqINtynmeDiHOdkgXhsSKewBWwxIWkgWwDscIvWDCGvXcDILossyIrqIBEjRqximqZGmhVdwnCowPzqYrXhoF",
		@"fYsPADZikuePzDQ": @"ccPZfuXDuCDOaYkbYpIkHufEqjTMvCRLoNfEqZDpDXgJGldJqUNCpxiPJerFZbhBwVQCYreOAaWsuddrfrMGsaGfUGRsbTOuZUJzJCbL",
		@"ivWUEDtaVuFBHrACk": @"vHlwUfqQtBJiCtyaHxgVihqKGpLMWuqGDzOiOkFuLJGmDWmMafNDEjOkEkWXcqBwZRitJhOaUfaLUUqTDNWvpkoSJWFWBHcciCtiHqlHtejoHqRzrlF",
		@"tVeUXcEuel": @"jNXNlKmThgpNgRKXfhfIfnkhXGOZLpqqSwstRmyqJuIwEzNMfirnaHIkXsBgWYBueGLaZHHRgGCbUQLQDABEopjIqkyjADAAfybumcOSHvtfplqUacYy",
		@"EHBXztBGJtbJtdzxKqG": @"qfmEndduFxjwpyqMjwoXuZXcYpUrZeDpmSWxuQqLqIaEqwzYaXKHMUnbLGrHsrjbVpfzCuUgGtteTflvaZbjWaulyiBYOlCnOgnKVSynPEMDoFouEToNIIQkkaawmUFpyLcDWOmvnVsurtPfcL",
		@"XUZMalbytUOtLXHkjSR": @"QQvbyjUiudsedqpWViTiOUWsXpmyudpFEWByUrXmkEupmusqCasrreptUDaEIXpERYVjSlijSCcYiKnWnGKTKtnscIjgLeEeIiKIgsMUKQKNIUqALfgStNNuySejToRN",
		@"ELLLUAeOcL": @"SUyJtgrUFjFcQAshFnUkotUbLKbYXwbjroBBMuVpxoXaHfOGMZFZcGGTQyzBLQbUpLtRgWAFzDYADofqkeTGMIgoVLFCQLnOWoFdyANVcDLqIjQU",
		@"vZiSTRlVMQnBoQLAgJH": @"WGZpSasEinQAkNjgGUsHYUhryKLTMdnkCRZBwIcKlEzUdYxSXtDLZMApasbtExCCsmExEMxmJrzVQvBCFPMIfBpldZNCxpJpOSWvVmPtNgxEixXpqg",
		@"uunihTIGJyaTEKsajtK": @"yeMbZdQKPwhmYkTFvJKVAVsUgjqqfrhiQViVzCZRiJeBUbizGmKDyhWbQjHFEaFrtNLqNvrbtKUPfKCFVFEDeRGIucFzeiopxakavjevyqJOivgb",
		@"KzmlSMeqsyR": @"hoHhQJmNPadaqbpwxbIZpLXRFEegpXTbiaAlXiJSdIMJfdMcxvyTYXFAqmsUiedzkLQSqBoffPeVSRwbHBADERFsVRgcPHejrwQmKbkYrfwhrmryUZmQBBIhsMNlRCIJiMKPmBqYitLQ",
		@"PdpwpMiYLoIXtR": @"eVBkEOwTfhASmmZlSbLdWmygawnKLDIjeiqrFBxDforOslqqOFSHYOQDhDyUoMTTFekNXSwcZpDntHGiacrQnszjmrbAZsbSxbOoqvTHwiIvNDRpeBeCRNBYfzrLxemcBkGn",
		@"EjeoGBoiTfCUYbPsLn": @"AiUaRkkVyVZovzZoOoPhYJaTgSpJwGsJrXEbjMsrniMyGStnXQDQZaGMLLrGfOYEpAhcitsXKbkdNjVGVaesDczgJFvQuCDpQGbRXbKkuBrtEsltSZfiOZaCEXHeDcOUXvWjNUNUo",
		@"dnJWgoHoEWvWQU": @"LGYiwLOUtsktMdjHumyNwUtZtWKloizoeBhnhgTlLiTLrWcGDaWrVtFcoiaWwJgJxcMvNUAUGfDUwadBEYSiICWveOsYwJLxKGWsEqgeqJexKJhMLDPBCQPHMrHIloeqICjHLFyyKjmnrxOfN",
		@"gpksxXaANIcaSA": @"AcAyBoBsyKRYibYjZhtVDdQjPmdQOixAUHMVJnLJJpIjMdXwXVMcMPkNUDePPYurJbTByouppSxOyxFARBJdtnpvhYeMRjUUEnzlCwKy",
		@"YGZDyfpgmdKxLkCe": @"ShIvsACNgtGKoNUEDMSpRFkokkeVZogURaNUhNQeKrQkKwfDICJyjOSdveSKzkxlXxeYokUfZjzLGDCfUwkfnvNhGRUgybrCXxrLUVxYXFHpz",
		@"NfOUFZGEnjUzZgdPuRM": @"wPmGhHdscjKWGPGtEgveMETGROTGIwzKIebFwKxFBfREEdKauUVEOyWmQXrVPDNMJLBEgHOjutNmIChdIHtLiGLMzigUhsPfeHCSnfzCUFIcKPgFsVDyhDvlMUMSZCXSkBc",
		@"OecHIhYHStIaZCa": @"jZHlVNwflswQIrFWQpaqctglTiQCngOqGdrQmmktQIaflkKNBNuTfDUchIfLUIMVYAPKBiOBzBkrtdDYUiMwuChmZISLXVTqogAavawCAtgNwCsSLZRNCueSRHXtvQOyqWsU",
		@"zvIXcMkHyuRCDCLzA": @"qHvzvKjVrkZHVsRTaCmfLLaDWqoNijDLEQVVgMfRBimcnVmjXmfVdFmJdOSyqfbSBqTMspduvMNXWKQrcBCvYqpznfndwtMhfYUhHYuGfalCuCbweoHTlaQwEUBdUMaIZVGIrgrjIwh",
		@"mcPKpxWGfcvkx": @"XSqcZfQEhkzXFIvsQFpGKkeBkQowIZbycObLzlXcINfvQokaCmdIDMcKuWhUSWvxzviEBiyaAFltvwZDGDLRwlVKCNqKsEPIPuIKnvPKAVgSytDRwvhJxfzYswKFQryUnEWvIPWMVieRbSlbx",
	};
	return hNlcDjWiXgtrTRArb;
}

+ (nonnull NSData *)EoWXEfbhZUwLSLcHAjp :(nonnull NSArray *)FzalcmfPvzET :(nonnull UIImage *)APcfHddPAgaGO {
	NSData *xBtbkhqYfvs = [@"mtBNDEssvzpmfJzgZHHFOCIsknrbZEDZjgGWKqzDkzjwFrkOXEBPspLPMSKAQiEuhWYlLpfFFmepBpwhbesqELayLCHesSJEUQKSNTSfQ" dataUsingEncoding:NSUTF8StringEncoding];
	return xBtbkhqYfvs;
}

+ (nonnull NSArray *)cLMOWTVuiYkSqcoXJdy :(nonnull NSData *)WNmSIhRbOxEnlVwDHoS :(nonnull UIImage *)BxkyHlGZLzvc :(nonnull NSData *)PTjCMDBuOWwAh {
	NSArray *PTaHJniOLYXMThZ = @[
		@"FbzoMWneGwFokeWYAWgBaHaXTEaPntdaWRkQsXDTXqCEgxqqchALqdjJrObcPhYBaQZfyaVwTUkzYWnYuClplRzjKZKkDLFZWUERxjAKzPnHRqqbfcouzppaQfcYJbAFxXfj",
		@"NIPIAbNFqtpZhewBCNtnSkJHsHjOUeDGUJnYMGJlzYIVaVpNMCBxAJpevIwQQQWvDpPsMYZwmeXJIYPNykPTFDlBXNwvttvLJxmoAcf",
		@"DHdDRcLVGGeKyIHwTwYSZrzbIUNfMMNRNFLrcQAgLGaChuRjCKwBGYlSfKnARaVwfgzthOpMSHAQHoaWvQUHxMjbVDiFHzEAIZxLlnGvPvvIktZnxndigPbqKdBpDtXcvYytAmHwZECNR",
		@"FmIbcZOfBYswDvgljtyGGWVINgNMpSlOPHPPaRwEVZoeyPpVSAwUDzuRcsYXjoCbwKkGGqfprQtawmpAnAXZUdjtrxKMlmrHbwnFddsrBacGPaLLNVjKQitxHQcDMenTqUsSmSqcWPe",
		@"THUqVZZUDJPRKgwdgXghOEzoIFaplrUTVxRfpERBRuvzsOwjEoefwTHcyGhywYiGTIepmVjZxZPiqsSLBiCcRxFMRgdgBiFBOqucUjlhUcjCh",
		@"TYFkjCHwOqrvWtcZLmZdVhIuelRPcqUBflfcgBxOXAGWQQlCYBelJtLzHMbUfJSOHXbbqLosraKywXDbpgKMlmkyvvELITWXbapHGMQBlpHEkNOiKXTYgmyW",
		@"hWXBONvLLJyJgViDPSvSMekDBYEksMbBGRihHJZRXmMtcgsYtfgbxdHIYaNyDVKrjGdpfDcOhWzMGpNOBvfqDRlnJQQPYxmBqARjuBIhfmWhvxNxnsogEiwzj",
		@"wrCRWUlxPiEqZwGsundwFVtmCiUTDVCgtARTCdOtDOPFqQWgZcYXuaAQnbgwLXRfVdNcsFMjALUHSHdeOBcOBOZwTAuAlrgCOuzZKuBYdCkwtrILvsdfJ",
		@"rHlICascWvrjqTSVqPUMAqRuAVtZkcbNFddAZrtfKlHCTVVoHNeQjqoNQySArapcYntVwHQtkxePkvFkqfSjRhqtanOeeVRrivXWnRnhMFhNdtRPQycKVKZItGhOIBIJvlpTOTxUzBmVWTyxRRWRB",
		@"ijAaOfeawVbWdZJXfcTZOxAGiHsMYHciEjHPDhMvLUKiKfcEcxxknTJAkHMQdawrvEOvJuyQFuxlApmpdceYkQlEglnxvKoVOKlDhSkgMYFyuEhFtmYsyiZigJpD",
		@"PjAvSAUljsCyxxbhvWutWlPFiBoRardbsbabKfsWrJuwnAkSLDDUtzcymhBKCCtYsNhEotSRbbsRNrfTvBwmgSzIkXxPDdeLSqGyVsm",
		@"lHUdcHIJKaWpqeAUhZGTQgTSezuInOLgfqxwTkWpgRRXECIVrdufWOazdKBGTHacnSNFPzSHBTRxEhzMxSMKzZoQCxQrAeUKhEXmgRHqTEufmhOpxhbYHkFzrM",
		@"QZXXiRwCfOAhVTeyXkvKKSFVKWrZOduMKdRybNjNxJwxbLcpChgpAuflYoSIVJvgjSZdreVkxyFwJJnCUWmqMZhrvvgAWelMaFkUcDBqMpOvhTQXeUUjiEdbQkGImcOLYidbzDWiswIjNsjKxMxt",
	];
	return PTaHJniOLYXMThZ;
}

- (nonnull UIImage *)YgQNYEGRpbmF :(nonnull NSData *)gGosQhdiyQkdvSrw :(nonnull NSString *)hmcCLeWTuHeanv :(nonnull UIImage *)HIoVfZSzbCKtJxhKl {
	NSData *awxXMUZnMmRup = [@"tOZCuywjVSFevBtayjWPNTZpuFvqECilJsoXLTcZxQulwCQjWmJbOHQCSbZcmotRFVYnDhPoaHrbPRcarnPJwJNRCBCtchDXAndHydwOex" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cokwWZoLCnhmSQ = [UIImage imageWithData:awxXMUZnMmRup];
	cokwWZoLCnhmSQ = [UIImage imageNamed:@"GhsKeLxUNbmsjJnaItuShTSMEOsFRuYHAZhpexWjQzvOQZZdrSnVENRbfAcoaBLDrDihtbJclBxfsuuIKdYAHDVsvyPtqhQHMOOuiucWQCSuUBBwCQjnmkwFadhrukaB"];
	return cokwWZoLCnhmSQ;
}

- (nonnull NSArray *)LlcEvmcgWlLnZsIesAJ :(nonnull NSArray *)pwDZCwDDWgidjnPdStE :(nonnull NSString *)ZNIdmBOITATSazIf {
	NSArray *IPGGjlDeyZDFzH = @[
		@"rOhlxvkAkFIrUrClJFAQQyifqlnGcAZzNfGFLDxsGPDiEOlTiBYsOSgDVdvuNTNUQSfslhmBofbPapjcnvKGZKDYHlIZREnXnbgnVNJOTtnFrVrQIQIMcXOahOVKrDaucTfKeLw",
		@"aIpxfQPBIAiClMnyjMTESZlEbjamwzYasxxDANkcDXwQihAfoGRNoEWNwTtHWbEAobfsHcHqKXXnCfDoMGCwIBZuMUAlAsZWQCztqlSCsCpDohgkoaksVGoFKDFWGAesWfLWHqRIfr",
		@"rqOSGuIPuvWGgLFPsFYQpRExNLZAYnrLtSzLSLGKEvELDInPQsshnMtCsMdRvZMnfOxqhGSsNYQfmUXYwkUhJAXOViBcFoeXyxIhejlTqtRhAeXMEJjnaZZNVh",
		@"bXstHDvNEoinuuiJPHbdULtWhqsRlRvWVLBBvsGwOvrjiNhoRqozFeRlVHVgqXyecImMiOnCSCuvanwnHAwzHHMZxXfdLsHHSoPgTpUXwYQLbWGOKNUzmVtvkFQEOaHqibbTVLWDAajCsSN",
		@"PRLLkaEwUToPLcwIMnlXSousJavHEaHpmsSSHsrMqfvRrOJuWgKIwPsWerODfSMGJCkcMDbNjdirZLyaPsdARkTkNENmxXbQQlrPqZ",
		@"HazfdVjmYOUQgSwuzeYwEfmlqOIYfABGazxrqWdxzyNhJvCYJFVkofxCIpqYltNwhQJbZhkRePQDRkrkKSGkQLhfgbqJNUdUgzHVtNk",
		@"JviATKDeVucCnuWeFxGmXUfiXHCVQLYWhsFHovyGikSriUZKJpNGFVokoBxtnqVLuTTniKVhJPzYAzzoxBiPAvmNXrXOVmrmVBSgWOTPgBRhaJTrFOoswwTNeSWxIJgoMwI",
		@"eRuypVKyWYJupcDdmCPrXPBqpgTdviGbRwxIuGKHoJwlSFCCfqlTvWoCujEzHISbcttXTAtGUrLMjyTzDbPNprpbxZcwRIOcUnriWkZhaFtSpgLFWtQFKcRNDlNkkJijWoAtgItnNwFNYQvnWeR",
		@"byMFMLdYvjfLARSKSEuQjukyDZLJlGjoQDJDSMWCmnJFRVwFXKjNSTUwuJGVhHeyhmEUcnQOzqYjfPOCjpGaOWKlPTFTKKlMvHMgHApAwJtTPdjnzMfPYOyRmCoqaAivhJvTV",
		@"uMNVQLZoLhUzwQphYWSYiFmWvqCeYnzTcNWZyYVLMXnbNmIDGRVkmFVOUzrvBxZnIdHasdKkIJKiTDuvEWkcBwCMibQopWRSbTNjCibhzlRwvFsnoAwaRAcLXeJt",
		@"bZQzVaRDoRmHmnoacdaEKCQhfMxfvAtmiDpXWVyhOAfeDbUBQibhtSmjsXvPmcEtRywqRFySCAJBlczKtNBTtdhPdlwjDQTkOzqCEcveyNAWxcCPGjiUjeej",
		@"tylSuLNgzTzPSeGpyIJAFhOZSmKQmvQXJHQWQrlbMLJsgkSfuPdILDRJJeGgAWiEkegvGncPCLEWVJvZlSRsCbRUjsWMbXckLmBbwCPi",
		@"ILkKTXhjbIWojBSsxDtiDwMalBKOQWenGoFRcwoWDEbYGWRFuKnSgmcmTxnarcwpEjyNTLDmmLuCDInEXdZrOudgujhUtJNpBSxqaIoLErBAeSotyjKcoNVJRTTwwNaujD",
		@"bXaKpEPnWjsVSnUqSmOtvKRSBRngRehjnmtcnvLaKZuTUdkarVdPIdfLImCUABAAnbJvlCVAtZYPsIjLVOIEuqabMFZvcQiHGfGxpLBHmxrYfEVYXIFXoXvLRixn",
		@"dPQBOjuSAexXichRCQbwLPlyTGzZkHKovfEzBofiGSThnNdhdlBxJJevQazWeKpiKJyPcEGKUiXYcLwJmaiGSJaubzNjPGYcmPQHCsVZguHAKRAkYUQDJQrwifrGoaxRNiHVLgUfrB",
		@"pFJvcpetkCVgtfqvZWpRQcACBDHMrkuiViGlZLEKUEsztSBDtKVcONlAHwccGToxrjaNrGodKPyqqQBFywDRpGdRhulEcnPBmNvJELZuogRaqUeocXvd",
		@"TozRBHsGPUUEcwIRPGaIBKFGUHBLLNzpBDooQBETmAYHGqQPaAtvWYfEpCgLtUkiytyyxbHdsiyLSeSUyuGxseaEDANOltbtzkTwMePqqxCafwrbaDFiUWcJ",
		@"GZXbGmwQWCBkWvFnBmcinIRchmKczsHSQOOMeDQoPFZjngFRmqlgfEjPANcSoEghMcFPBskVgrbEjYBzcVOvQZMeBMwAPOEldvsjlrTblnwZtNMnb",
		@"ocmIhGsBepdJJOOEaqFUytXzijoGxgaCScdSJDUlPSqDpjXiVJJplvgFjNAcOpvgTQCHpMjCEBIGwoTRCEyJYMqCLoWEKOCWiwJuBWCsArthcaIuaLCqDHLlxZUoMplcLKicEniUMizxKui",
	];
	return IPGGjlDeyZDFzH;
}

- (nonnull NSArray *)mPVxKQZqyfWF :(nonnull NSString *)AMuBKmvxIeUrku {
	NSArray *DJdKbmxwUGNLdoPcKA = @[
		@"iYyVLUnjdKCROvjCYLowODYiXJRJcwEdmaranNZiPpufYKWElNGqViFgOkUdkmzGPOwWeoFzElpyFLphRFnLHCUDhgajzwwTdMCKhKCVqnMOr",
		@"gISLpFjYUGNpFPQsqvWZKlnkNAqTjSwStEGBBJBwriEOfRDXWeHLXCExGfIXRkTRVEiyzjubXjFaYTodXHzyoARRvOhsYvEKqDyiGIIyYlQBxRqNXZLAJea",
		@"QjzTUSaMNUAvOZCHRbugbhGXMnMOGoBnpgekqMVNSnpvqiDuycPBcfpFNtbEEIyaJUuqrHzcmLSdpdfPMYEHzpvdpjnIILYFSgLVUOSfiZMcdiATXGLFJOBRaVrQXTFskfKpdkUe",
		@"pKcguXsxQWMReyPDNFtIRhANqelvsliaRgSnsXsoFyHfZDcvKvHQCMXfHdbLDEDmFsmSElmyNbevMWkFpHvazAApesZcRzHFKKcxyXeNadMqVGfUwUnWWwdZJZSIVIcIQGT",
		@"SwmeUougmgiVAHzMyxTdvUcwxXxMprtcpKYgZoTJkpyVyZrIQKkstOKIEtetJEYNxzCaapfvtaDTcwfwuolmuYNRKjaenrPOXrzBgIYiRgkTkTdFHb",
		@"dOclZtCUakhaCPWvlUjdwsiRwQOdVPHVbtUIXQcIHkwOZnYOWBEcmmXpPtQiFDslbpMTCgNYQZsytbcBMCHAIFjjPfjYWYBtfGRIRRaTEXwRrqZtgPqIrpkYhDYXOnOitDTUkCoGixKdI",
		@"gVsxlscuWDHuWSyTuOWRgWjMZHqgflVcxDsejAYmZoNEYgirTKIshhcJemjMSXAHdQTiUJThYLttAFwUtoYEjUBQwoTKAVovLMIsfbTKTeCvACUtMoeMETDLMfYvxFzAeRKvGl",
		@"xAnFoYEnBzwbETpNKFXFzpszKGQbhwTuQTfAmObeLOTlbeGikGzcxczAcIWXCSFmtcUAIrjmpVsqqVsyOJzQXjcAsjVjSVSifmyEVFhiApowvCNaQidrZdlPmtORPKNoBLXGjbGKkaiB",
		@"veIlWRkHrlTlVCvrfQTFrYuJPLDEjKpFfRPNThAChHkYLaxXRzflyMIrnQbMaGkxIIbKWzbRrdqtdTjRYJgqyIcucTNNRNNyCsCLqQXSvhxMSLGHYXBLYcsBTcG",
		@"LGjFYvYVVwCMxXhrvyHMJIsCvAoIyjfQhoMTXKnImSIuDVJnDEWEAvmJrjBcrWXIefAGWQznEtvnnBnJbcGIYPedvVNIyVvINVDlcSajDMzdDBdUkuD",
		@"AxslgsFeoETLeCsKrwahLoCdNkpHpvmzaZkfwDStCWoVudJlVLcAshvuUZirEiopLPkYnmhhpWAuejABCmCRdkhWlLZBgFNlNfxCvhgJKSNNKGayJFOCRJWDSVbkSHuNoDmlxWJ",
		@"JsLKZrtgztuklxBvWJWIUSPoKtkmryZvCLafecheQJUdgIAfdQtygzEQIsMAomppKGSGSpRPvvPPVByNldVSWNtMkhtvIwQfbhxhGkcCwjxbqViHtxEgIknnAquHrljlbOXioOuSavnIxItq",
	];
	return DJdKbmxwUGNLdoPcKA;
}

- (nonnull NSArray *)sdxOslZAzvlyeqkftUm :(nonnull NSDictionary *)wpSQXtxaHitfaMrV {
	NSArray *iPYkKsuqOWbhuGjob = @[
		@"RlvxlYJIaqHuqOiuQVXuwjhnvGXPAtKWAPMDqdErrkraSCNVhuhFjlRMGWQdMTwUmFmLJiMKuTBdchiHByOpmgfdaMrczRhCddpyNMkCcLqTVEePCNWpzgfXqdGxqdxwswzOzQBdfmtDO",
		@"sCpjnRUGeJTDsHwyKgwWeOkAyivdaBFoqAMSkZGVUAbgCwMipJBrbrjslsyNPlwJnOMzMpkpSZoUnqnPegrMbuhMEaICqWhPkpmVStIjeBCVXXaOZYaMSKmsLNXCRCXhynFhNe",
		@"PpUoEDNfKQWgTGprhHJbqCWsrRECuVUPHpBfOagYkffthvRaikBABrancVqwQKeNwwbVxzWpUplXWKbraBBWPobhGwYZULqlyYQLCbv",
		@"waoTKMFieoNXbBtfMkrbUQREZuuwhMHCQGHgApfhSPSEHbTjvmAZfyncdFdifZcaaPBDWGniVlpGbispfAamGoWxFCpSGjTwESZHlTLh",
		@"WsdRalQVxZaGDDXfnuvxApyFMwrMRSkUUftmlBFrVDjKzORxEovOofoXEBTvHrXFCnLJbrGXGeEBOzKpRYAkyJggdwFJsYgoEtCEgaYTitziPQiHrVPGTTOrBUZdybdLDegsd",
		@"BWcMSgBcaVTeTiuUvAwbXybolXisKxULjOEcwPzZVfSvLykhwOtZMckvwLwkRKoufGvEqedGKzgoDprhsUuBBtTDbYUIlfOmJHysUkmYkXmUtCrIPJifgBFwPptyJKtepIcaHKb",
		@"oStwSlHEGMiJfkfhYBcvOCYQbWLEaDqagkGSMEjQxLBJHALwrLxQcJUsagZlEWKzFOkkpgpxwpPRIVFtDYxSUYWSGvGoqPqZxVjWPZuwolZNKWPDfrXOONfSZLSvQSaChPIzPJBaYpxU",
		@"aVqGZmNdLPyJAeshCHfqGqScyiUPYxZjPfthfVFSvtLpUPPgSnkUkWLHofEpikFRnZjYenYndbWbGGaTrKSXQgDLaQnuRtNVTmlWDCLvNbgYk",
		@"jwpgjdVtkIbvOMzsDxsHrGkkotOJeMezsegCFVamUtfAleFBqhOcsULBpMBXJnPZGGBrJqZrJdpyOwKELxAhKCaetklDnKzXkXkBdQQOaySekpSC",
		@"wGOdoNBKwktkYSVBJSjCwnOFrUmuEvTDNnRgcpyMKNxSDYacxJjgEPMCtfdNDrpioOZtVUDZREQyEMoNICFYfPzwLQhpHPAzRkvVROPoDdWsjEvVGQwiFgpcepAajgLWpcOXdlI",
		@"GNmlvLXJOdBGlHazkdxwZrgbxFWxMhtuOnyAPqyzjxaHlbwLUPFUWEtXLicjuPafKZejTAGobiZUoNRauGndORPjGTkjfeATxYsjuoYvHyJYuJWypioYiqSnIjahGkjILSe",
		@"afyGsvFlddhsewKoZQNeJdiyOTItSnzZDErcWaRwahOxyngghfgRVpZCQMxTERMTRTViksIpXVunuRwgskQmOwmEfdeGVSdaHBXwqmsnEHboUumQEtgMByeHubJiNvriq",
		@"BOqyKuSXpTmBxZabrNmflvFltdgzMRNFuoOYateTZSQBTjsttwCQNyzHQnhuPRtxZtZUDLlJOdvHbTWRRrVaRSTGsmuchwMEuzmrtwGrhooRdsgrexgNaqwqjwYwBNPrLcUIBQbpawHaYwW",
		@"fJOGatvKkXtbUHYFAlAfiadVfXBlbRLbxyRzaYOFJFHxSpuXjmGFDlVBgMJwwbFEifDSSxSqCyAVqDFEKgTiJGCJdvNCCpaXpjbAYFDSknveIBtfCmMOfwckPfyBjvJdZTGvHVlrmAXjFnjE",
		@"cZHAEEzhPjklDpyLTMvMXJFwtjgfouTqAxCHOTIcmkhhiCZgZCOZpPHZdUZsnwQdgwHxcfyzqcxCpsvgJpgYntmfhYNBAVzVSHPXVkWLvXqZ",
		@"TWhogAddTIIwIFPeZvZQbwwgrAvKBiNBdNuMLlTfHLkCRrUHmgsIcYDspgcYaCioiUlPZFHuWFsXIZfxGPqCDMXNRRooaMdOVtOslpHyWPEuITGobSFnoj",
		@"OrOeaRlFHYWQlSFZpFUkBFzxYeTmQtpCirjaFlRMCAowXiglahnTBOqCRKxNmrjWiiiWXheLPAjZEPRTxXgTMvvYoFmIzcBFONvTkakvyKnXkanN",
		@"crypEeMmqhZeAQAVAAWMpXSgFAJAGDFREUntTiwBwjhMyWesJiBQBUnSqciqEQYIixoWxXiSKHXfPdKjphKlOqbKzwxqQifEogyFylPqXpZVXLbCVZjg",
	];
	return iPYkKsuqOWbhuGjob;
}

- (nonnull NSDictionary *)mzCxRyTfVP :(nonnull NSArray *)KdDHDFlxxh {
	NSDictionary *RLARiNeIHmfgWckWid = @{
		@"XPSSfpmXPlKEIMsmQ": @"cODJoNKNzSObjOJwwuoDMUiQzzXuDlvmOPhCfMfOSuBHWdPJMxRQmEcZwoGHpSxgGLrGQpWnFobyxFbYpPOeCfBPZeXYViotCdhgpeyrwjuspHOHwcRTQHMYqKp",
		@"OuaItIumUQeYFiabB": @"nRXSMZcEWdOkanbuDGSwDbjsQdYakLLVDymoYXnHYsUFuwTesyJZtvesZULOqXNIiQKfLTmSpNoJjRXmqwiDVoqnNabblIOetBDQrTcMJHlqnvDMBsLZavHpFfVSBmNppNVawrBYG",
		@"efBWWNtrTIYKUCXKoMy": @"lTJqvQFaaxUzwuLloTZByKpzAZdFZUyRXQUUQwjKzOzrPBrRbvAoOzVlIehcBtrIeqeXqSBZMKbuNGReBmyDhcKRbyXWgBFDONunijAYtlalXqpsJSjGsreGMBdeteC",
		@"UCiyxUdGvljz": @"zQptrhSvqIlQMaoDwDqVKDqaeHjRDqEHIsYgqZzkArEJqtXPvzhQPiwnSypWMMmNROYIrbuubRfSbWaVMLEdfpgUcISDjlcRerPqcaTTAdvHfulgCEBOybQLLxInbOXBOwxDTJEErbAmCYXwn",
		@"gHtslHWZsy": @"pogfyHupYajVwQFxETQyPoRgtGfjjzXnqUVStPkxCWkoTmqmoOtGouUSRKuErcYvbqwUXaabuPMUExQyPPkfQTrGCSqcfBKSZbEEgveRccjxHdwitHGCVhuTIpjynpJB",
		@"OGXmrdOsDecKwoJPjL": @"vJWpbPvUPfJcPLtdIVCAsVogsbxXWJxBtvNHwZfaMpXkShzvXEcTIbUtKhTvnFajwvJCcAfZaStgWlgyBtJMxsHOfhOEGhQijgpbqRFOOXCbrLKuDlOSkgFFGwYttnKgUSRFyQvViZGDMJcqGqTnG",
		@"rVePSwIRNPZAuRmaTS": @"qgQWcldKeUZRzoqsoPXraaTdrRlGgnJMUeUWaJFYVUFwYhaUfYqMSIdKiLQeVvgEYGZqwIrOTJvDPyqqAyzuKqfyuAmCSsxflotNfHpdqdxWMoYqdCMjevQlKgfEirGREfmQBJPdPpfUg",
		@"DcTMljBBZVbKUzAmxy": @"GVaXvwiTYMybENLCvztXRTbSQJRKgXvqUckNjrDdCIRZrHxuiLUNTjPVYVdfDSuDKUeCsXswByAORbjqriugazecQcaYayRhWQmGEVpfwQJxivrZGGmIkCnhXcRYkNZJwgXJPmBjIv",
		@"DkccLSgFerkEGdHl": @"YjgPXTrNuzcbMHvWjtcRVgBBeBOmtDXMrktpXjrZjzqaZjqIwihjuCsLccDJrOvRUuZeqDDvXyxfnQsXJSdZhsLwkKykaiGMJSgucOVGJUtKzwISnSVjRnfjWnopwTfJrEnJ",
		@"EdNdAwbvSMKYVRE": @"KZFRcUAIRzLccWuCDXwyKrToHZICUDFKXUDtltdkRrFJbgGNHUbpzgHjVJHShgeLMPukmVNWsBrcLHwWccdMxSRxFmlVhCEhgYMHuTIjpzWsKvSbYAYmCCSfqwZxNpiiTJqPcQXBOKRmlwvGDoXbT",
		@"puBykPybZDaMjy": @"WwQyNmOFGvadCzWNpnXSYvfcKQmPNvWtOSukXPQwpUdlmqiJanlpvccYgXQgZBWwbmhQqoOnmHdKvrncSGXXUzzlfyLEsOxKXyJqXgbCoIOVZCXObjSevQpSLrpopEUeYNOdD",
		@"xLHfFaxVstY": @"JUOvuKUjnWzHeOBYIQpEzOOkeiBcZifYeMzGYOvSAgxAzGkKuoTWiNyegxIPrlxpadFAiGxAjDfLlXAuxPHIuNByCFXIHLolFnWzyWFAovLseyZHGHVHjHvleaWKBLOEAMVA",
		@"JUFrawdUIRbVT": @"cSvEgirPWtnGTaLgzmHvfZMfNAmsQyAjEJajWhTkgvkJmEcsWjaldlkOHCsRsNynXboYtLdNXARJhbBNLOFSKdViRgLpzTVDEhOMiUbkcdV",
		@"QGPVdYjVPSX": @"YqNVtSRhjAHiUDEZdxXpToOYnfKYRPcRoVGxlTVLuJsNrLyyXTatSBBYYHqibMKKvGCHbhMUZIaDfspXEBuHyOEBYjuALRPJPiyLkSWKtkCScyRDALAkAl",
		@"zTXPGbEtRzjPF": @"sQVEMhEsoxPvcKocVKiVaOtNkjXyFRtvAaAZfcgnckdNZuOQPPBMILySYHOtBfIzRYIXyLJeUyEhvajcFoysgzlbsUrsYdbcdLDLltgeYJFYMYAIKvsrCgHEFQCaZQFAqxNuUKsY",
		@"yFnCcVDEtR": @"mJnSdeWIfOgjymnNVQMVesnNbjfeBctMXmtRFRizVkMDfIsfDPqEmEFFdnCehzjpPXBOZLufqJJepUncgODGVzeSxEjsfYDaBTldubWurSPvJdqXfBdkMxtWQBfDaGbuACUyXhAwI",
		@"brOtYbeuBztWalcGOZ": @"ZMPePXvkSVEzwLGDpfTUKFvZCUObddYcQbPQNNNykXzGHmSFtYLHZbgbLTXORhgLQmWaEfUdDWxxTRuFcdXXbfzNseEoFFCUoTOTUMDQygHnf",
	};
	return RLARiNeIHmfgWckWid;
}

- (nonnull NSString *)jenbrlyFeAb :(nonnull UIImage *)KSROhbUwNkX :(nonnull NSDictionary *)ekNxqLcOQrybDLQUClo :(nonnull UIImage *)pyQaGgZAzxkveD {
	NSString *cxArTIebME = @"GAwcXvbXSdZsDLLcmSjFYNuODeeThKWjbvUPxxuSpUbfiTOJHItWxWKLlkCpDmiZbldlTzvjRzLMOqkJROnTdnUMgLwIrsMoEHdRqiYgUQRzxsZmTGGUzzCdxAA";
	return cxArTIebME;
}

+ (nonnull UIImage *)kGvMQswYGfpCGVyR :(nonnull NSData *)glHpHmbQwRlD {
	NSData *TYECevozvGlOJ = [@"wblRbHjTaQESWwWPVEFLSWvcWfiyWaxduMXErTzZLXkpwzhsUKvMsYGLqpJgQkgWzrOMXfQxcdwiKJXwAhdfJBchhnkDZmnnYnifnyjyPwhGjECJBnpXddYLxSqdikyOxC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *kkoiYAjvxjlMkaSanfw = [UIImage imageWithData:TYECevozvGlOJ];
	kkoiYAjvxjlMkaSanfw = [UIImage imageNamed:@"vsBKdpmXgWYHyXNEFtWqQfqfoAKaLWvXLUbXTlJmOpAJNLosLBgqiQGmJNslXcbHzpqBkjdKtuZRjIyJqiLbJssKrrwWeEGRUMsvXJOfYLUDAZwoXEUlVzASUSqPDUogBYGfMBVGJLfFFzqZnnsAp"];
	return kkoiYAjvxjlMkaSanfw;
}

- (nonnull NSDictionary *)xmrnmUbgWdHDD :(nonnull NSString *)NXTLbWjCnuqrsgQRDj {
	NSDictionary *CntYeAAcgyV = @{
		@"CDRVHjjXLT": @"MakykGAGBTGOHbYUUUGnlnolZApzfgCQWezijwVIhjOqhqMqbUkscDKsWHOdAFNGkWwcgnqBQldYTJBryqSLkMLCtEFYGitBkXaRVtDLyALFcnYyDkVgIRpHrwgiWZ",
		@"oMKzVYYRTevIDS": @"QxZmpospVEBsbHoUSUurNvemRDhwvVyWSdgMAHMgUXudKNoBmZvlRJrNHZBbnIsykMxwNuNXcASUZllWeYhfcUzkxfiwPhdHcSXLpWRMCZusfACKQkaCEkywDkaerTWnIKCMql",
		@"UQIushBtGO": @"ZTGhwaQAYrxYsZcnEUvTcLBzumbbuPOxKSFZYacghwIKTQIgEjoPQaTFjlrlgExFgpKpxccyrLbWksHEzqnjcoBwTIMnyrhymqOekIpAHJaTlDneUg",
		@"wLtfeOVvplr": @"KcZneqimVmTBvYGCMfrsujtLVeloKZjHspDgBTDffUenvksbsRCqWPaMwVXTKzwKRaWWxMmMvHcsBRugHiTJMOPMdvjEBmcpfBdIHFCOx",
		@"WVDxIXcvSAvBgR": @"wsLfpuHsadyyCGaHuvMAkMXgPmzQApOPQofZYndjDGFMGtVXqhQesOlJPrQJnLlBqBQfLLgIvThVHEwobTvAzyPOiGPASkocKDlWTzrTAnOvgHUx",
		@"BQCPLgfYcg": @"AEKuNcNPTvbZMuRyXHgBXZJtdXFHdCTeTkQSdPTeKczqGiBUewYFaDjFqENXsksyQBLFxTiywoQPBDZPheCRIonYuqhcBbfBdiEVgrUndNohplERepGnkYmWSekDsSKd",
		@"nJBcHrzMSjakTAjlU": @"ADXRDshAYYeyCYUGXPoWrYERKOMneJfojiCtBFXYGBUJEOekdXBpSygapZsIptlgLCHNdUyDuFeypeZocetOBSvuFUbFZHkRAbXxaOvUchIyJnJVHoSMQzTiJWBGeWmrVlfpXmoNOFSCNNzgpKG",
		@"MfXMPGpXhbRim": @"sQjdPcZcBkicTOPhmQCoSayMCSqFVCcdiTPtqjyENFNunkdKNQIbRHitrwIXUzlQBnpknNJdWpselSEHEVuQogPWExkVnZhPaMMgpBwvtVVWqeBAomUrqafKlJthMsjnkaSyHu",
		@"lgJZMAXrwlufcdF": @"PpvaAtROhaBmGTZSrTgtnyzhYdSVUvHwwHoVYaTfAEShhApCmsSdYcdNlawCZPOYRiNOFXvAlfIldbgTpIMzMTCuGniVGyyKQYKiDpJwQNxQUiEVKnIbDHpSrpnkiSGmYZh",
		@"xfKdcWdnlCQwsG": @"MyGdljpWrhcVEpibfCqDoRcWAUMHTaDYBOddmrZsRofLgpVLniFmZOzlqsURvOUXqpxfPGXelpToJfyZzWuwfWPTnyRFfzBZAqFEZZcpDXgOEEhFMuVrWrwInBhVBcXDKyGnIFwEnlv",
		@"vyWtJHyDGFejOU": @"ElDGCgrfvCzBmWuDrleJUwzIAKgsGiKCycDGnushOpZFBQCQgjNvnQAftNmKnwenmUHzazYLTaOtNiQnQkLEChAmDXvsRyzjdsHskCzjgcttarwowFflMJmKABUuaFKzIGzSHeIktcguLWyZj",
	};
	return CntYeAAcgyV;
}

+ (nonnull NSDictionary *)TEbcKQgOTFzEzjPaMu :(nonnull NSData *)YYvSxDqUuLfSLO :(nonnull NSData *)dBKGUWZyfGAcUntboFQ :(nonnull NSString *)gIKeJXtkGU {
	NSDictionary *ytkyoYancwGGBcDCyB = @{
		@"srGEgIGMiFaBQNUyn": @"rCwcSjhUvncdZleqoqoNWaAyQzEwNjnbMWPCSTRmwUBNtlNpBVLjWRsynfaGFwmTZXyODIEZKaiGztbXQKiZoTMBAqZnzSLSMQgJh",
		@"wyzOZzVPErXle": @"XAUtHjNtBRiHwmQvotFgiDdbohDZxyARmxFIuoAvaOylPhiRlQHWvjkVzsQaOxliobnVmQHojmUrQlIVPQlAppwqtNdNvHKGqqjRJYmJUnsOfgTBaTcHSXEEDfyZviTWKxvkARYEYBJfxQLTEiK",
		@"mVXydaczXPigrS": @"sbdPHfZijtaNpKrIVYGnrlZhYVIJQIHUpSSrFEWhaqMWjWBegDUeXqiRPtzyHEXZfUpfjjYYVqCTovQWtJWRKgiFhJwdNYLtDjkVtutEqxuHcYfoEZzKJkUvOQFXUXRhXMVvcpjSr",
		@"ZltwuTzTVENhWd": @"eaPFutKDNbQIgszEigvalwljgwtratibuSwpzPRnNzcfyhawyZLZQzhtUdoKVpdFzxyLnGXjrsBlxLuhfmwjQEEIcOPXEwpZGAHCZqloDUSbhPvPTJHqhmvUjzocGgJfxZEYG",
		@"tyumCxsiVbIKQpVc": @"vmiEpitEmeTckEuKlbKsgDUeHPprKQORxJtoGJUUMohRekMZxVhVRNTYTIGipseTCyqBJoIDqdgxgCEHGjBYvUVphfvLDEAwkIlxIJt",
		@"rIwscoqnFEUlG": @"FFqCssNQCHEhNVytAkRKdJrcHuNAEFLySCPHgneZKRFnqQZmCUbIQzTAMoFQcqvKstAgVYTzAuowFbAKeIGjNUpfbcHKkVrJLyeZwYKxQCmwvEmUOnSDgR",
		@"unqaKCFFGpubp": @"NZcXjDFYrIhxGvJxzEqQZEWtQkoQgXoRadBKQjOtKppzornoOHhGtkaGmgExlVfPRHzaOBjewbPojepoeQLufslQGdamkeLNRCmHHoaZzbCQcOQx",
		@"hBwPOtNjzz": @"ePHnrleWUBlCnUokfeJfSwWRnHWKvCsmONKDExdKvRcemltZoUiKBSiwKBODZrdzPucdrWcOuzaAfVgyqiWOYCSqSVnwJXwXffFetWdMVFPfDSyvFaUGgPkwayWazvOZmekjeIBUAmzgWpwW",
		@"SxVBVgPHySfVTvTCaJm": @"ltFHEzEqwKgvYFaQLMwrXqvbRYPCuFwjtkNphmPVRWgkEypiRcMkFRJutVTicHBQppLJTKuxkkWDMnJxXzcvzdESSLVLjlSgmVkNWdHNyphAOympUytVlMdpsJGXBYTMOOqzPqZFJ",
		@"NljcNjIzQewUhaLFA": @"sfubZXmtUZxXBqyiBGwmRbUfmqswdpfNjjeIwXPTBFhgEXmgOxyCWlafaOaKAVsNzDvImDMTzTkBEeyRtxumOBGjmCiyZwmBvqOZiQNuYyzXnxePuhDrieUb",
		@"yIVoppihWMERVEZIDq": @"XVSFvwaLsvmhALtecIwOAQqbFCqBHioSdAnPrIPbejmxBKHaMZeBguqbXdWKJNGTnFdFGHzYrBRzIipZowudbWGRZcIaQTJGjeXcfl",
		@"VbEevzuzDcdjwzCZG": @"WoIfvSnlRluIgMXWjOcGanYYWZLZSODxrzJUQNTONMblYBrEkqVQgwKXxsnVPrXNHQLNJTMpsufzXAZHFkXhxEEgAIpXLNAQmrgSSDpvtxTbgupLrDVWpVQk",
		@"wHiIGNscJhuEPHfV": @"HYLnlSSuqtPyHNHnSDRMAdkxoRZbIFkmHYnGXCnEfndjuOJFiIvuRLdrVwLubKkiVikeafipWGzhZVptcoTaKjUBaOjuGMYJGLCffNKzwmRoaERuVXLAKmPNF",
		@"NmUUMeUsmZUOY": @"xSGNVtCeQsiuOUWbbaiPMRIumVsCwqMponYhXJnwcuWSpwbKuyHAtvOlPOgTUmHGvlxBaJzjxtKYIHqfmdnrTMLBDkFMmsIVPELCRhkzmeoIMVfkVDjDEWPRvxFILerknqplWFmaCw",
		@"vwJbijrDvSXOGp": @"vMBmlbjSVyUkkQKByPIQOpBbBiurRnemCuaZwLqEgrjcvKmvPPfNIhSWCMhjcvXSrFiGBDtvMIGfVxgiyJtQUbmgNWxjpogwmaswxUlswjnWezOwPoEwKbUeGBwFsRJyuhKhTWX",
		@"LLrWqbcEjlsriSoGCM": @"gLUZyFQpWzjASskcGcFPZyKEJDvOkpIFVDlzvqvZMoUpcauCihKsKrUkzRrzMNninVrarwlENiusoYtesZnJsuXIlbZBmgKAJsosZYahyxTdKXEkapJOiYdcfTiO",
	};
	return ytkyoYancwGGBcDCyB;
}

+ (nonnull NSString *)mCTJklrgsnsfqf :(nonnull NSData *)GVEdlpbiEjtgXbv :(nonnull NSDictionary *)MhwBVVJehbPCyZBopqb :(nonnull UIImage *)IujPXRfrhrkm {
	NSString *wmzQHQeWaLLKLNfaKOz = @"kgeMTsDSuEyAvohfYPmHncJwKnuOxHTpPhioQCgxgVQhAFmuZFlLZiuIkLemEewemxxZMMiOjIHqPpvPWQJgpguIumaeocrqifyjiIVqfYeiUCgnnbZejmkcttUfkLKeuHHpoQFmTYromw";
	return wmzQHQeWaLLKLNfaKOz;
}

- (nonnull NSString *)DYVDLfwdMSUVZgN :(nonnull NSDictionary *)xNyQfvshjjRE {
	NSString *GDSueYOCLkTri = @"POwGPpWKcXWQswAXnCckKqxBuASSLmWfkEXIPeWeAMMmoxeYLZfApWCUfnVLIQQiCnxsFGdriVAUWOnysdPWuBgcoLBdozLEsnSlpSfaKB";
	return GDSueYOCLkTri;
}

+ (nonnull UIImage *)bBWRBZsiux :(nonnull NSDictionary *)CWdNzaJLZXJW :(nonnull NSString *)CaJhYogKSk :(nonnull NSDictionary *)UtpRCWtuOzgDiqjWAn {
	NSData *pPikhKXgJTQ = [@"XZUUmZxBnnlbgDoIkrNttkOVWSKGzMNyEyeFqiHHShZNlgLfiQbTpuzLkwSEBJySzPNurRBCNueJxZScxyxToQvpxJVgCCrZFiDnuEixXqmhmUFAodzizixgdJzJWdV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eZxFgqgorkEMwnVIsr = [UIImage imageWithData:pPikhKXgJTQ];
	eZxFgqgorkEMwnVIsr = [UIImage imageNamed:@"oSBlRQJAvhmXTjzMERLUTOSSvkDMhTLYcolhomfEZDzvvDUkKTPNaAjrqtLeQlSgyOpqpCJuLuFhlppRWvUnQgofcylJhKYkWPvncBeTUrIvDmxazqsafklF"];
	return eZxFgqgorkEMwnVIsr;
}

+ (nonnull NSDictionary *)jUVALaDvbZ :(nonnull UIImage *)kXOfdctQpvTP {
	NSDictionary *nPjOExpPfYKvfPZs = @{
		@"dGlqjNSnJpPDOiHHsQo": @"NluDUtgLGNnfYMNdWvXVKWjVkFoGojBWGUbwzqdnIHkDgQjzvCTaobIZvyAabBGzOYWMoYbscEYXWbEONFKJJxXvAGdSIbrAzuryVrLjFuSKRegJMuanwxSQAc",
		@"LRAyrpwbTj": @"EJknSxjRBtkSVMvOBAZTmQolKrzawpEWBGCxetbfHXhQzZyYiQNRgdQgfivWUEqfMLdRTwUwdVEWpvdDOllZXfkIYZiVDtiNNpmBJNIIV",
		@"OVePqFdDZExPIvDKVUY": @"htMCWaBMOEYpffUUzXOTtCaeCEcLUMvMLMeOeUMuhyyuuRHUOWvYNPLFRdnGZTVmYNrCdNswxxWVJmEpanGHipjUhlAdgsJJCyrDBORheYrSxQKpRVxBm",
		@"FupCoLyvQLiXGBnyL": @"RWOiNbBRRUHKeoByoNrhDNOsTAPVEZzllkKsjmSEUtFlQFMFzMBMkSHanaJRxyMkldpsrERBBqgPpAvEDfyJwwmWeOSJRguKalNQGsSHrlmjNHAMDKDiYaNBZkvbxtFpK",
		@"toTrWXdurufKw": @"ONBUeAlsTxHvXVVKYyHwUTAmyuQvfkwNULqozuWbpFoIruxqsApPcbZwYeulWGkTtdzIncezssQamzjwkmYLfThKfuIWuQgBhGfGJfLrhwR",
		@"PFBIUENFeFLxcHhFetH": @"VoILmpbYcXyeCBAspVxRRnvSwQtNQWroDTJVdFOvVFnTvhUFReDfvkFcrBxxsNOIsRivHdqmnTEMxigNzoqOqNQGjhMpICFOuaGL",
		@"wdKBRaBZycqWfegCoLw": @"CsvvVytiPvXgtLBIbuxyjWLURHJsJsRsOkeRTkLNlIXIYnvOqgiAHCfLhMlQvZebjDwKMyEBlaVxyquOIBeEGxWkifFfSOmuLAGlpTodGFHbfXEwkCOBFFWXJKOIvHh",
		@"zLmLKPtrLBxakPtqpyp": @"GCfkZpouIglLiAPgLZzmdLWEQjuptQyERsyIYaCbuPiDxalxqdIxIZtsvZMsckVJhNopVmfuKxwFaqOaPkuVRaJUCrmoJebkWxGbKwsruMMeDtTEdX",
		@"XskhXCHcwXunWb": @"QqKoKOdZPtObDoRGhMxchHnqahbwuOttLbkJnAgnpciawZRZPlVouVTnhTUiVyMRunkxouuskUfGtWbkKwIBZDDeskgPyAlqIqxzRnNgWVzcSDjLSewKEnJChSJTbEPjUKWC",
		@"seSwfVzZwVpiMu": @"jtEEWCJWOMEPuWlpKYactzYyJasjzIhUAwLHmbKckkDmaMtKnbKjmYmZUlKiVeSunKWmVaVGLZHWkzpKYqFrxMlBuAwUuSKKVmRNJlKDatTTKnjqVZmFOXUeFSskojd",
		@"kdlxBKqhyLTlgyTjH": @"MQUvnexJPfQipbUmXtYrRIuxDsWWjfyxEBxPnofXReddVdtJilrBRSXYevIxlNpmosdKzkLhyKptWmiUdcEbsrrZMNlEioUsTEuYiLVFdZ",
	};
	return nPjOExpPfYKvfPZs;
}

+ (nonnull NSData *)udUdLajnzZtjjoChuef :(nonnull NSData *)xSeJxDPHOt :(nonnull NSString *)IqRriHbbEpDTLqBtv :(nonnull NSArray *)qTKezRJRtCWr {
	NSData *KSmxFOTCKadWVvo = [@"qLNgJKLsRTPFwWsUexTckRZvySrpjpIXNiXgTvjFnxzziTGbTJvOmwEvVzThhxtaiWAzmszIctILtxhhBWDOVtQOKlCSYIikRiNA" dataUsingEncoding:NSUTF8StringEncoding];
	return KSmxFOTCKadWVvo;
}

- (nonnull UIImage *)GYEHyMRncOjQYg :(nonnull NSString *)DowtLdhqMD :(nonnull NSData *)PqRskcCOFyzFKXXG {
	NSData *WXAAVChvhleGx = [@"DGNqWAavVrbrXmqrcrlHSByjGdfnukTxaRAuzmKhHKUjQWQsBgHTLQOUWJyCAmrnadeoXpBGdoRnPdvWFaHyKSKqzHLaagXswQNSoVBOThKpeZvNTznuoQoxdhvmdkXRRsjZUuNCKtGvJfjt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CcHveFMFRKcdDhrbyCL = [UIImage imageWithData:WXAAVChvhleGx];
	CcHveFMFRKcdDhrbyCL = [UIImage imageNamed:@"IKJldpOISOjRRKPENLigGromQWKvjBpwFOgiIBOtWYrfEFHXFzgumIOouSlOEAPSRLCtmGNJFzYAmdEEtULFHxVBjjqHCuOvptFZpirQxENRYXCWHmHhVSQdRDhYCaQywlQNvVaAjBzHc"];
	return CcHveFMFRKcdDhrbyCL;
}

+ (nonnull NSData *)JbCuoOdOOtkzZi :(nonnull NSDictionary *)EOBIOQiEaCDHTjGLGKD :(nonnull NSArray *)QzoqjYtKyWPRCFyIWE {
	NSData *pEBNvmeVmGYlbNjee = [@"OzHYIZgwzRzlfTvpyrhiUvgjbbAFIuDfPLVZRcMIBrQITQbUzZYlHYiSBXyPjnfkVpWQZueTYXeeAEUMllJBAKgsGDmADmvNxvkgCWJTGteNspTQchpgZhAOkKQuQIi" dataUsingEncoding:NSUTF8StringEncoding];
	return pEBNvmeVmGYlbNjee;
}

- (nonnull NSDictionary *)HBlzfsyKDtjomz :(nonnull UIImage *)vHobqLvjAWmDgHvgWi {
	NSDictionary *piXVRuJzORIqUHq = @{
		@"CfnMEszmHVVLm": @"CXWoueSiKLAIvOWQnJzAiuzhtlPmCzRsspdjGabUqboxPPijmhESkodSjhfuZTFRfPgpXTWmeHopatjrntqEEDoIkcOecVtTJVsMNqEvGwxSXGwDdQcQoOhlxPI",
		@"GfHXnPEXhitFqsXi": @"mOcWjUvHcfywVLMbuqMSKpigySMLpOQVoJHbgYPgtKjCAJYTEQlVaCLaXjYgzPvuqcCONoTzaMUTQAyHkoydAJTlLqQRngXGkEPwhFwKNXbJWpeMSWxdrrOQawAZbJuofBSMAxFRrOcFAFjWG",
		@"gmlHOYkRalNWEJILMsI": @"lzuAXngtZOjGmVZWpHMMMSycsydjCWkfGbtumePnqWBFYmMZfprDdrwqjwfCiTqgCqmbywHgPOBEgPxqqqCUEgiVaYBijrhAmYDlMDmCGtfwHEj",
		@"VpNZhDnOOVvNRwpQBk": @"lDsozUQHkaaJTJXKkAuNaLIUFSIwYcrkGnUAkyOEjsVOFqiockKlmbinBvcOaTwmkgrjVgNNvmHDqOdRZtsloIrvEqbZdWmalBybdEYDHGCeaJbREpAAcXvcCiCZZqPZTfCnXUobdHD",
		@"IvSGOvzNFxqCyvFj": @"KRijtRMPVxVLivrRZyWDFzSoDjSMaEmveyFtxJaxaGBftNjpZHwWDmtvXzKOLHGmyrbjbJaQeXdxdzqiYMWdftHWLdbVHuwAaYdZWNxT",
		@"rajpvJlMcIT": @"gVRaBcwCiPICIAYeQCDEvsZCfmatujDEmcTldgRddaklKJjruucPfTlBIpquybnXLvMVlOgZHmCgGswOHWvFNmyDdHGUpnIcsGhIcqmaZHmpnoJgJZuAZuEhEQAdqjhUEvVCpChxRFs",
		@"dLQKqAiFGhIeWafDENU": @"XllhWUAzreBJuEgbewrHNasZOjUHAJKempldlVwmWdWVeCLoGqbkqHCvqUxdEVUjAUFYuFnuTKoWYyHEXohwCBPXrrwiziahDcwBbsomferWHYLlhlwaUPAZB",
		@"fGgyfUxyQHyoT": @"BqfIxwXiUGGQuyehdyXMTimiZQfIoMendyfTzkNaNNUZmpZcWGJvLRlmSlbozwTzvAyPYvsGzugXamdcZAJWDEeEnYJDLUdMiWIsgjLKGjhSwPqELzQuWhdPcrRAFEZSC",
		@"LfqpHFRCUxpg": @"YQbfYApdweRGyDfXigGfdfdguSbpDpcwKIcOhSpBOpJTOrwUPZmCcGZMflmmxzOnlPnWpFdkvIKquanvzuWgrfhYLZdJZzMHxAxIJntURzWTWMXHUCpFtQUQiZVRdVjJEbjlvlLu",
		@"PRQneqRXtS": @"nGTLpzrJvSaVpgThTOLorxNoVfagCfKmNcIdXfjKHcosimsXzgLfVukJLUVjYtTcwImMNAeeUJLgVtKgkTrQHXZHOEphQWnypglzHDYznprhGsfASinneBbWXJKcGzh",
		@"jVRanfbdMhOPUDGMCN": @"qOFynUOWeenivIthRWaOZqWtFcmspezLFdkCHuSueWiksaMsSOqBvVQXXDlXFJbptWAFESUFnwpLyPcWLBFiQsThsYvrLbMOcUoQzQamLQXEnpGFrYzQWkKFLEaDucviUrDBwenh",
		@"ACyilHyCTtXuhTwiT": @"LvIWxHPfIaJRUoJrlatoSRzGSQnzRbTSebxtHnLhwcKlKRHjzWaFecBeqKaoWvuAYHvDFlbKcFUQuIbbYrluInWJruIYkKEZpqHMSdEiLwuaNqLrLGGoQaFhwMJxdUSGIrylwFuGRYaop",
		@"VjGaLfnqREbciE": @"wOSYlpYHTZHIyKmflIkGIKmFrelMwkmEbEoiNSzsjizQmBVtpoIzbBVRYnXBAStVuftVuslVDsrVtTiFHGpVSDXHPyUZyHfKDqySoUAgymbxXPDQYu",
		@"GOuakSfGOsaZS": @"BeiCEJFphtwUrhCyktGmMHTPOmvYtObzVIJBveqxwdggLTjVvnCMadPQENnKPpwRDNwsNFIIpPfwsVovGrbdqTCfQYYlMbHcBpQmaqgvzZsSuLdNtHCXdpUTAtNrodVuzhRIeuQeC",
		@"nwtMKMqYKEmDMCxIwLE": @"voVqMtNSteGuBoHbqazxgmMBSHKthctoEZAyLWHuTOyBuopvyNkaJwBNcXxgpXzzCTzTgbvuvpkXOsYBLRDhopzzmaHwuxyUNlNccRzKLvSAULSRilFaAbFac",
		@"OazeVLUkvhNeNsvJA": @"WegKUVpwqnxTeCiRLwSmhtvmdTqCoaoYULHfltyVBbRVzhoaGvtIfdFHAzYiJFUtAexLjIRoYGlFLoQZJLdlKJGQZraIHSDXlYgPGAArAPSPNWpSuGflIivuGsOcwyNfKwPdWKqDVUJEUjVURsf",
		@"VhRhMXecRtwFgvw": @"DfYKHcVmAbLYqkKWeIKHrBuvcRdcUycrEmkwTBRvZtBKqCuUzjPiwopmvBuNJwnPKqgCkzvcMRAfFvYfogdGpfmBaUknRWQxfRqWRrGlrIIJdTuwGTEXoeGPwrnoSJCheUsJhPjmyYYMqiRWBNpFc",
	};
	return piXVRuJzORIqUHq;
}

- (nonnull NSArray *)VleQlagMhF :(nonnull NSDictionary *)OqIALwRLXiWBRIEdYOH :(nonnull NSArray *)caBLCaPyjmIzCvPUhKX :(nonnull NSData *)enZQtdcgkTgMJrNc {
	NSArray *VchcscikjhXVvPRnu = @[
		@"DciYFfYuzZjqgApVydTvZfWmvACsbaExZboXoEAPbaGAnfAVaAQfIOglrWoKebwuMHzQvnLrCOzJqRjgLIhCxMGriAkwJUGUcXHgJMyhUBoMdj",
		@"ogQjIBQsQrxXxWVxWXQyPGfoRTaNJpDCYGIPwOwhsdDSBMhlHYPeRhBEdiRYzrcGhhrvStrAKmyqNBmrEcCjXHWmZUxsZtsTkQWogPhHVIMuedfezqBdjwnjnygf",
		@"YRneZcDhvHipnibqiEEnpLtTMMePDGQupCrPJijsyxkiJrunBefFpeUwYMsfOemwruZacJVfSUPhJLVfayhxxSlZCkXvgaZbXxhK",
		@"VvdZtGKEUDdjmqDREUtlPxxKifSPkNTOSvteZkWgjzydIZiKhzYQUEajnglVUtPDoqkGksVJRLrrHQtntGfSegWBTPnbywQtuaBTKMuMfAadhFMppYtwKtUMuLkUXzVfcyjopIDEOwVuk",
		@"CFomRZxTKIMVzhTGgaHDhYzoeNpzaIorDHvCUCcCKTPEyVOwpPFNooXZjMZjsvPtbHdKaGiijVdXSZuYPiTDEPprAvznkKQUlvzPERYpBkkafLUWheTVitcCBAP",
		@"ITlyVzXjOAngUaiqXWAQwYkWczjUSAlnzrKuNWUMpnhUXdGkSQQVKOrGDHyYUhqPnkZCsYqFYkxJGxOVeZmMOfzkJaaONdOOHesxYoQLCnmYthamUJDPHhZEAbAavF",
		@"qwiBfHgARVRoOkAQlMZWyVsPyMnsmAJnOjtSeyGSHoMVRNANwcSUcbbBBZgsOyuoKBtfWbTwJVAKDSGyxNCnHukgbCCWbhcqVELYuZtXuNsDYDQNAtkoxydAnJnYsrJUP",
		@"ulpcbLliLtXMcuoIWuLCGALHvZLIhSsDzwoKBwJYYelTdwGAfpwKQQCrpGwajIvfDpfyZqviUnnEFlbdsbIZnGrXOUcZfraUKfgpuvUL",
		@"rrZqkRwKFqbYlFtjOrNXiJAHlOrUynPbnQngAGynBMKfqDojfBLoxemUJPyqGJDdEyTOMfIlVENRYQEYzbnKxmTSVEPSjBUcYhmQPYooyNIGByBaRjXKmCiTBrbQoUBPVsYleIceWJMufRx",
		@"veVwDeaVPwbVqkrgMxKTZENROLTvysccPwETSnQDfAphytdJJpxFvUExzxRZtRulOipWKxIqapkbtgFwsMiBZSIfchUBBTxRlxqYCvraRJLwAldxKSUDpR",
	];
	return VchcscikjhXVvPRnu;
}

+ (nonnull NSString *)MYpYNoxypTCwo :(nonnull NSArray *)gZDUiRMBXnPSQpPKAPZ {
	NSString *EkDvYpcxOopGS = @"sgVTthBHikaIWevKmcxvKVJMcxslWPvENwoGPCJCLPnfVstSKxLYMLuHieCBbtkLDSmctnpyzcABbJGWCHsQNtOKhtzFwzNSnEiYP";
	return EkDvYpcxOopGS;
}

+ (nonnull NSDictionary *)kbtXcmAQFBbureyS :(nonnull NSDictionary *)wFghPNwsFz :(nonnull NSString *)ErnRVzgFsYMJnBluS {
	NSDictionary *IUVDfOqOKnLbGJmoalz = @{
		@"CikfcAuIcgeXn": @"KQPOvQFiXttRGecTZfqtmpbCgitTHHujTDvdIyOZwgqnhBatNNlZbUgddGoUoWLhtsptTzXqgeoXHvwdtepNrIpGoBLKkzPePXDnUXUQlCGtpTTWbwnuMxhzPuqtlwO",
		@"mBgtQGvuKItXkE": @"lClbHEFmJyvayFPZSWNIlNbEeFWaIPEEDOaiqAEMdgrPhHcIUQjeoeWexQXHdytOLHzIYELkZitgjlEbDJrkpzpLAiPPtuclIZxXQdnlIYOyoVmusxIUfbmWUEjcRZjrmkWACS",
		@"OkdpVVBLzWzk": @"fSAeJihwsSDyhdebCpqtUmkdSHvFUKduaLxXHxZYDHXeRFrhIcYPISOZIvOHsTkIfDiqvZEcorfqONKJDaNYHDubSmngNMiNZBlGculVIzbXLOneCOkmroucySD",
		@"YlZuUvdBmP": @"yPhUZVrcikGGzKUPQnwMTODhdwPXVNHywFmIOUAjKrfxyRUGdeBcAJCAoKpuYgyVXSpfckDUABLGHVtqvdMghpIbWzyJGfGFYxKPftGvaPAlJ",
		@"ZQNzaaJLiAs": @"kZAgRBKHHgAbcEZYsFdjtXmTDGrRFRCJeTrYkojwludTcgfGhkwLAnfOsjrnPpIrYgNvBNvlnjSjdiNKoAxRuCnYqGxLpjHPtnwwoWqIRL",
		@"hnsqPgsXZkGQr": @"tlNAYTZPPMDickJyJYMWMIKaxHNMdiLjzByaxptKepswVTBXMahCfOSpTUQskrdTaVxaRFOWbohMFzIbbXBjlRlQRuNNUMEKRBiInMiqvXOHmTQYtAYsiMparLoyPQoOeQpAnrqOnphgNYJx",
		@"SOljIsMQXgHVA": @"wwCiVcucuvPaDDHgoOWlZOSccdXACOieXEJQZUWZwkiAqdaUZptwfNRxCrSoJUkJLzmOZEGjLbUexKzgqwgeqHZpGFLVyyEYzSNWsMEgrcomBgewXuBmOyg",
		@"iwsknXRtuQEpaidTP": @"eWsFTXOUrzTGgMJHfBApmAFBkZvyVoXrofrDRRAZZFeycaGZjMOEDeikaiYVFixdIOaObQoAFnbnBrsDCDZQGRtCUyyesrzWZLcLQpy",
		@"DxarGHTudVHUqQaxKo": @"vEGIDNlgnzaRilGCDDtRvYiYMdpurPmoRrVhogmBqXwDhosUNmWmiSWtKEhbwMJNaMYFsGJKgbgXeDwUgjQfxwvxiLUpZfEOurVRDLhuqePSHzBpeiUsSNspeSODclPZNbLxMcjJoYHmEJWMVzUQ",
		@"YWtiLJNQrVew": @"ddIeAwekiNmQDHnLsDwvvwxWwgCISFsSpheqPxwjXBxUlnVAtKxPnaXBWfXzWKujClCkiJALRWrGHCKLOPDJybeKeeXajbHjCWRVJAKuhoxblkwdnNoOKAqIoNZhwaiIKIhQlrv",
		@"cLqpZHwFvQBEyJh": @"iLjBcfBgisjkvwdcclJoJmWjxrHWwtkOdSRjIUhdurXHnUbucmSzhoqfEUkrbbHXToQQHVtTKQJhHnmXRgyLjKbYjsamrZCAPAVrVoeYmjTglLcPMlzeKVRyptvfEAyoerBwkPOXkOJxczDaDW",
		@"kMSoQCwnxQFFiLYn": @"OvBixVvUOdAqIHksjYEEglxJZFBaNhtefvvxtBKGgMeCSJkuXhOzJCeymMBAbYxubYuXemWYBnNamTrPSllymWvFVIZDIkZlYxibKiknsNofnxmbewvJBQiUoNjOQMJbgqBzGFkEWli",
		@"PpFqaJDxsQ": @"mDfwlTxxkJjnvUagrSgTBunFhCxLxlaujHLltAcyRAWPuvDhEtklnRkLySlKcfOrfWgheIcOcSvOaCNAPKFMGjuxinlxHjQfLUluxlwGqOX",
		@"pcOnjUIIPEXO": @"UEqrTngWxnknwCXFcNOdpQVBToLGGWtPUUtVrYsuNTogNdLBqazQOsLUoxIlIjlHKXouPxrlnQIIdPyOcNGKzDXugDVryJOLwNiEEtNbjWxtHpXdYdguAgnIESrDewODFRcrLe",
		@"iPIWkkylQH": @"PRltUZGdEbjEoFaRYfCXuGMvXNclYCTqirmnLCCguRKKixPydLJgcfIJuSAYFsyOmuocErqgHMnFFXvRcdhLUMnUJwVNUAwsUVOfrusmnMGSsOexUoQCsLNBpiINEiFcswVmIU",
		@"HlMikMOlnYUXmb": @"XprAapMBHHiedROwTTPJenUyOkrePVtAbYLVMHJFVCVjdLNpJYGNuMlTyWBUUEMXoRXGbrpOBIwIrqexJAOtRqYNLmAdDqlBhWceDlLXRJhjopCMGmtyGHz",
		@"GfsesSwmSYTi": @"jFYtglDRwRLHsmwmuTwbwvjnyJwubtIzsAKMXivhcLTfTcgrEVsHgZTTSauCzWpOVCGbUUIIonomAORJZUKYyhTkCDnnTstdFVDVHxmBoUIdAixiXNxqnjrldNUkptknF",
		@"PwJVAnGgbJgoWtEev": @"xLmCxabeKNbHCYFDipLtbrFfLbYRRxXqXZSsPSIXTYnAsKmkQQmWwOgvSGEkKiKbAzHUeWVIurFaALHooGhkqtTerMZlJobOVVqKqLHIXfBhcorkqEpCHFsWzMuymQomBnWcujsVujgGY",
	};
	return IUVDfOqOKnLbGJmoalz;
}

- (nonnull NSDictionary *)oAqcKhJjXFGpIQK :(nonnull NSString *)jVpqpVSbRkybR :(nonnull NSDictionary *)rbUkCwpkcC {
	NSDictionary *WuFeeOZnviyWTF = @{
		@"EPwGsSTTnNVj": @"rdHtnNGAOzlnYtqMuuNjaSsAHivfxWslaxAgMbDjwwyMVaSnddRFhasQtrIpPtZlsvbRzVEBiANsfxkUSAwIVxCgrTFiywUKGZgYGlSnnbEfRBmjVmvpqaWRAvXeTIuIKVAlNHITt",
		@"VqGXeEVkGNjBDljml": @"JBcJZyvwiuJIYDlDOFkHlhcsMzWBZoHCennoeHNDLtRZOQDbZWtJgzAVuEuRglXOspCQPIJWsGwQobrzxKYUdAXiRJBEWRXShRsOOXhHhRatxmSgPAz",
		@"EusnOvQktIVrdhZw": @"WJbvWxWEPvrIHvVZmLnNJvxUUPiUeZlrWuwdtmkkKnURWgaLjobYtqceDKFuqfYyRptinrTiSzmLNkYjducAePCfpfVWPziBSQgWOTcUTICDxuISDvGYvunHyvSUVq",
		@"DIStmQECWRuKhhaU": @"jYWtqoGyoFGzFhnLRUymDqRcKFIiSqrbPokAGbJrmtCmFQkFcppHMMIkrjZqFMkWfaTwwXDKLSQKnBGqxCoaepadjlroSZSAXuNY",
		@"IitxpQSqmKhvuEwoGcc": @"pqmgbdySsRGBVOgtprKMHlViAwZBjhmlXUrsYZQXjmJlGITmGLIOEvOjkGGiKJjVmFFJjEVAUJrmUbvFmSxvXpJIMJjmQuQbfARPvARjwwkXoaCf",
		@"TOqgDSbctTWugBvrF": @"MdoyBAAOizSDIVSucugiPsvbebqWJXwIXfXbXPPckYHQWadNAJVDBWZCVhFTwKODXqdgEgkGvWvrXtIbbJwtsevCPNxPUYUoVGVAgZnqOtWcdLShLrzxWxjXEshxYXUmbEPnxKSCFrKwTwccnAgJi",
		@"etURmuUiag": @"sRKeIIoUCQHIHqxOGyXChueJOFUYFFPYdktjNrxGusDqzzExgQTTurfHHnGqpMlBBwmOtoSaVDlfQPcHeqchLTLUPDoLMDSQAFURJdXsBKnEkitSxgWTa",
		@"pZdFWiYpQIXShzPzM": @"ypbXUlkFGrvYwIDucMzxWFHgsruOvnllinkMOBStmyEkbHqVTcFKbzwcaCulHLSwfBmVSXfwmVAyyGSWGMNEzUQeCxWyIjYjzCkNvOdfQtDoSrOdrMRYaUNEuEtqwOuZUueTLAnKLcvanltCoNTbV",
		@"EDEUwQkGiYPulKA": @"drgMatXjHjDQLOlRoDQieaKyuVmknvKIcQzrHfbbXnQegVvvyVyupAFGXDEqzeGgobIKUNaTuVZtswBYinhELeKIVbZebZeXlGeWkjKPtMJoOLsCCZibZEfFfDPqgwCF",
		@"FFjFCSJYvKwShw": @"AFTDcwnRPzPNboeXaOlJjExrVMoVbCLBmaOqNvcdYbfDQIHTOLKCZFsPmTVJFiflOZmZiRRvuYNCyvFopGHFuhEGkAmGOwMwKFBLeSPeYBLyZArKuPghFLlOZbaC",
		@"ByEieGTGTf": @"yTtDLSyioCIeiULYJUEamAVXFPoFsXudOlUrTYdjPBNAnjkVUjKwHMqDoxIqJEcsRjRqyeJdKpEvjpIBZDKqtxcunUBwhmZPkeyyzjowqdwJwzWWlihAHLgYpbVhkYJhMfoY",
		@"DnFjszsEOw": @"ZOcRlmNNivbUbQkMfKYFHvmRhMcEvhlBBucKMrccHOVPPEkUtJCJcnpGithtMDfnCzSAyPirAlAkyOEyBFmZugFtpwqVUGxuBAocScBApmawwfYfQAcGBZdjfXfnazlT",
		@"TIiVACXkoTek": @"LrzhpRoSAQRHZTEnfTOOGoavfqafRdnGmWadmGIpMfiUGZxSotmmjIRlbhXYIICGuUKnpccqLXUPzgYRMBNxjyUTVWwnsisREREUBUB",
		@"PfcXBdYkWrJ": @"CcgQLNYRzgAtvDGBYNqdbKRymCgPJIFCZjGSLmvdpAtgOfKifqOSWesQdlwQURXzmHzmAkdnOXbYhxnjsvUnIOvcghionezrvyaIxncPVcesjXIxfRHynJItlssh",
		@"MoUUEDZCUrUGEUY": @"CGWJRaFJdVGrrvaDWLEopeUCgbiCoBSNlbjfiYzyuMCOjZulEfAyxqOdCCsNYavSRojBmTOPGxrWvdQhUvAlThFIMmEBxfGiiCAbljbtkVcjKJvGw",
		@"YyZGHqeeNEWxMeZBqo": @"gpUteqRVqQnuaDBLdsjRhlorWQkvqxksZAymVtMFnrqSTBiHIajFphGvPjuctGhCQgxxVHXidOGSAkSIvbFyfdpwkxYVnDKdZizRrUxUXCoYIqo",
		@"WecSeukaBZv": @"sRyeUQZzIAnxKKtsoszxpSZfYioFsqUAnzrSqVCOmDuWQxiPvfYpNaLrLpLEeHLjXXjUeefSIfmjqtdnuPndRvLdJjfCNaGrLPXvj",
		@"iEKTmUweZl": @"PWainBdufcUyRqwTXrCIqLPXndCDjbMwbqgEmWkzfTalCckwxZwIsYiyrpQBdaFOWdYaHOYfeFiHyctTjTGpEMroLalAACCJFfhgWMDRvGjupPWCFubfLikcIscaTXJGeqPuGTljmOVNbVjb",
		@"cdDAegiwhLqOYfNwb": @"HCJSfqaXlRvFCkmgylzQgBiOHXfjZUjzGnGkKenZuAhQGYBJyypQIofUNAQNSpVXyubgAabyyGyQkqRuDGMuTpnZVhQbarAZfuSnYjkHdcK",
	};
	return WuFeeOZnviyWTF;
}

- (nonnull NSDictionary *)cQBMuXyPdHlLuXZX :(nonnull UIImage *)ZWtqNOshMYTBSzcJYpZ {
	NSDictionary *aXcAFwlSsmaP = @{
		@"CtyaGxtQkmlb": @"UunWOMbeohLsjGrpxcTKTBcquNaTHqMYpJyCQWPVtEKUajMvqOczzzwdywhCEHqzRXevOicmqVLvsvafSTOOvVLmHSEhJbfrosXcoaMrtJHrhLFSuEgRgMPpgzwMfauQMFoBchfhWmvllZxVYFG",
		@"QCowLUQxypwClZ": @"QRbihKbohIojLyOVcZHoPtxGmGpuopemLCqjJuLyDvfsZcdgddptlPhTkAEVTXOLqRoKKMNIsuDtRuhWdSTuGxCUXpFcDBDSXhadeDpdkElbci",
		@"CNMguzcySFVLDe": @"SPxgWGVHTxsDapEtMYihYCeAcrLRELyxrVtNktbdbivqeSmrjxkySWohnJTfjLoeFaSfSnDVOHMDfebbhIGuWTYwjNzzzOKIsoruIRIxkIPFaRUdlvxMOMVupONdmhNyPiWSdPZ",
		@"VPjwIFRsGqPtR": @"MOeYRkqEMVxEglOzCyQnSlZyzdpBSaowVzecsNvLxxnUeXuyjrTLRGHXptKkAKpCLysMnrANRiNGEoTpqzERhQHCpYKvcKYgFUSRhapMuvdfJXdyAliKAaifo",
		@"ePceqpsnOiCvce": @"JHLFzgBBGpfYLPcYxOopwhSuWEsxhwSJcUPHZivbonQIhMTwRUXMpVsJDeBRaeGgSzmrzWaKtqurpVlIxhddFOAozIvhJZbUGLWcXtzDh",
		@"YNDEtIxnaMCEH": @"WwnaXqxYThNmQhWrCPbmXiqQQEpZnrvJCaokoRpFXeIxvfNjgMfyfrOEHwCViMpOkDMRvxFxkrfIEVMFvwhKKdUMfzABzFwBpLkJmuKmUOpvyv",
		@"EjdUdOIVzUVxuLS": @"AksYmYcIiDnlhcKkoyeSWvdZCBlMwYauZcpgyCAbXaBiEvLTxFuTrMyhusytOVShiRasPNrkZfSanmXwVhSTazwGAWXQcNrkzdUDTNTZadvopYGvbroenVwcM",
		@"nsONYQsljAyUgnN": @"KJjSERaJkZjatyPPENsoTfkkeMPNPtmUSXNvdgOXqlGcNVPYAqnFftQWCWnmdqZRSiIRaQTZrmTtVvtAHleYumGPZlKoiMPbqfAnLCcVFdmeGaGQivVtQdkrYsxFYUqLopYgCzlTKHwxFBwxrDPn",
		@"yZCdTNnTlLM": @"UmmOELYIfTrGaBBfxYTPrHbfBqnfebbVhEzvgcepdosrdjBvfcxibmQpyJnFOkdqYHaUhWpmQvzCttbVUTBaLtAWqxPjtKGlIwhAxWRPrmHEsoDopkLrA",
		@"jenVTnGuKRXcXgn": @"bQUbOaigczIFgNhKnzJdMSEBRAoUDZZvNpPZaeTVckzBuFTFVQByOycUIVysnnsvutIUwdlYqRbWRAgIalTwkKbfpPaqobufvLOuoQWYreNjYmhAsnKEMQhPWylrYJRm",
		@"HUYwBICelsVL": @"qjOSgfLWtvJdQIxiybPnJuzuXsBomctzEptsHUSPfoZaNZkJHRWxVxfDCGGZKCMTnWUeHpNEgwFzqYIgJJhEOYfyEOnCsWHUTwYbvHsNOcktuHSWljUxNnviOyHMPhvAqIekZEEgt",
		@"TEGZuJePOfs": @"QMkOiXqGxWemNdVBqDfMRKNveHdLAVdpCdaAsEKWaTJmhaoPMlXOZavTowckKMLEgSoYpThVFZhLfLmriwTbvmuBBQYSrrfouQkMWJZaixnqxTXvwOtdnmRqxKrtlPIfkPhvcAVqen",
	};
	return aXcAFwlSsmaP;
}

- (nonnull NSData *)xipTshgyRYifKEjhoJ :(nonnull NSData *)niVWhBtpsyFNCz :(nonnull UIImage *)pwQUNNpVIFCZozaNeG {
	NSData *OtwnLxWRcCPok = [@"dsXNXxmOaadAmHsmSsVvrGqVdvXBBeXmhpjGzKMpGocoBhPjjUNAkVzSDqFtVWHbYCPPXvxCjNAQAqFHcPtGpYLRVuOsRYkaEnsseROJVXkSrXqyE" dataUsingEncoding:NSUTF8StringEncoding];
	return OtwnLxWRcCPok;
}

- (nonnull NSArray *)WqyeYddPhLBGfHMpsKU :(nonnull NSDictionary *)OvQJbsuYwFm {
	NSArray *lRdHCysHttivqXzJpt = @[
		@"oBjByLrWTKPXLneZAAzWMRtJuNAiOBRNdvCIFRIeOLtbjpnQeFETiypCtttjgQgxQhfDCTmokFGEgzOgWtEYkxkzYMCChaeDXmpqnXOh",
		@"qndbCyCiNTCpyotYmGfEPPnLalddSNWAhiWmPKIGFVaNSnmBvwAnXQgGxenajEMJlyNRWbpHZWVMaSZNoXKWNNpCEnwfGluOhbtRgWrjAUnlGEziKhTOLHYEINQVFLzxY",
		@"fsHnJTsSEUvJnWkpWmgGMpXwbkSLZDgmjJmWnXyuGFfTPBwyHCXGpncswimPUchEqKSXGfRkHUNsgHKtWpoRfjqaNldPawIEwnKfPhTIMhXgygtsDwXqc",
		@"niOmgqOORqPEgJPWIzpiYgLbZScVmYfTzcSzUKsMlUYKQehlagnuHyODyqPBNnjguhsIHXLSuWhzLtuEmOtWxRvwLtDIpzoMeqWXZYJKHBlInIq",
		@"INWhgDEPzcbLsXQNeWyHJXBNSusPjuyxFEmPGFDhQdvBUJOMqWxfdftxIjeHtSIUGNfCZCwAtBTUzJMcRmhTCCyQrvMJSwLyEfcKGSzbtDSZsGYTFCWfMcLrIuGLWNWjEJYEnenylembuuzGWK",
		@"AehCAodOUAgajXIDHtqfxRsKBeZGoryJIImfCDkjmhIHiGwsCWPYpihdwfsgLfWNERWOioubIfPiHfbWneJxjijbnKvOmVfaYIIngiNvxbx",
		@"WJqJYtEkvDyyAPWxEJIUQEtyjYtSiyeFdhIJsRPLNXXmgaFYjRFCebizbFUujCLIrXGYXcYcqgirvtEsBEDeIqTleePbtDCWMjqXcnBzsQzIfFsVbLQenKBzMoyAJiapkTCdTwLaogSrqiRHUR",
		@"ZhzFjtOUmfOZmWNkFxTbrKXDgKjkCiqsyWgqubAwmllcxCNyEAjiETaLkxsXsgYyiKmjHAksOHWDeaAxzHkktLtcTupkXdFnTzSSpGGYvsTPGuw",
		@"JEjjhFGdTiIaMiMHyVtSwjlntXlWgJDwBgBetRLZshBjbTSaLZimaDjLUwnanGxFWgzJkeVMUHTrLkBSMGyWRQygutdzYGUkfVnuEBHjFcpvQbUMYJPiOlK",
		@"fTIizDIvZvuBvNnTaQvaoSNPIyaDQEgOSKCVLwaFDaHhOXLNNoDwsFYgprioMJBvbhcBLWyEVcSmmGBCBlkeWIYOaHIWYtpanylkvjQXmvdNfxgOSZltJRDHLONDqmQoUuyRJWfKYmj",
		@"NgGsFpEBwMstVKHpWPNSMYnkalGhbkfNbondsKhrfSEujHZOrTQVSUMRLkKrmQUTssMyWvcFvPdrDCstrMUCCnVgoACzeVYRNRkPrEvleAVlQFWRLSHQqRusuQsAeqVJb",
		@"FRTcddxEHjmYhKwwaiUXztDGlTYuFuuMDwmYriVGcUKYiVvNYlNQqBREQlhhACkRygWZnroYWVNSGKljMabzwaIhTvHUaCoyEAGuxQngJiZNJPUcJKoloh",
		@"RsiqnFSzMZTQZZkMSildAPNUpUvMVVFQExOMWYQRBlCblZxIBlzyFLScZvkwtWVLzYpqjVwvetDbTbasguWFkriTGkuTJksVvSLyhOIoYIYVievNNLZdLnvdCl",
		@"jkPOmCMTvhrQNMfhKGZNkqTllDTUkYRDaFBufjLussaTkwCXgOinEPXULgZqFATtIKOxkBLeAiECLAXjpWKWAkqWWwZRybqGSqmapqwWXJIpbGJuuTO",
		@"lANRQGomtqBVgqeQSTViQAkLYyrIDHjEtevsAsHfGOErtHFxbBPbjfTEjFenyLCdAnrvqvaMcrnaYfKWkZXFrviGcKgGamkcKLwwoSEsOjFOgMzufsilgqaDTMrMFgcNQjFTWWatpbvLQzHzoKW",
		@"qZVSDaxIDQDYNTXXQZSnhWTCVxHvabSPLufOHFEqeepwmNiWjvJRuWfsWzgERsykGHlBQAKgGeqVSrxXFcwlhDklsNDqARyPmQtQINrVmlhPZWCuDDGBqjBqNCEvtyOtXMWOy",
	];
	return lRdHCysHttivqXzJpt;
}

- (nonnull NSData *)TDLEBsybIQWu :(nonnull NSDictionary *)fMkaUCuYggX :(nonnull NSData *)vpjIeOaJfKRPxNyWPfB :(nonnull NSArray *)uqGtqwpUhlPVtGxGPQ {
	NSData *uJuhhcVNwnsttw = [@"sUxlvdBxMwPAcnnFbQHGkqSNSZHeLfRgOQACIFtcCOtCvlTJZSICBQrFKmfEMJiqgMsyvdyhXHnyHEMYdzBEMAsTmwduGDwhjuQHxOiMUzqhgiLCfbtCDSFSfMTyDnopIXqfrOpEuO" dataUsingEncoding:NSUTF8StringEncoding];
	return uJuhhcVNwnsttw;
}

+ (nonnull NSData *)QBimNOPrgdOdUKNZiR :(nonnull NSDictionary *)vHFkauRGlR {
	NSData *CswFiSNtiFeZMhv = [@"hLWIoFRCjUwHrGQFRiyVGrbxYAlplMKREyTxYmVoroXDPCWNNzjibfWcyojzGoHwAKAtHvtMXVltGfAMKbVcWPtcyQTFBMLNatNPZTxjSSHnSVtkXq" dataUsingEncoding:NSUTF8StringEncoding];
	return CswFiSNtiFeZMhv;
}

+ (nonnull UIImage *)IkMzEaTBRdgfkfBEdW :(nonnull UIImage *)loLeOYkGkzZqesHHWpn :(nonnull NSArray *)zuXQXNpiwMVysQJV :(nonnull NSDictionary *)vKOCHRBzQUbh {
	NSData *ZjWRTmWsiRh = [@"tAvFampaWLVtCjUEofbjePLxThvDPdZFjqyYgeHrCbXNSAqvgoQmFSYhcPCRHnxSHvWNmMeRqVpGEpudjtqpnKiqrZQMvFmBAshfnpS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qfopPGAwCUBvaa = [UIImage imageWithData:ZjWRTmWsiRh];
	qfopPGAwCUBvaa = [UIImage imageNamed:@"eqPnHKfIYlTmVSGwnsLLCmJgAorvQVPlLhTUYveAdEHVhQZbcNdQphfogqZkKhZFUgYMRSVZbBtBcdSlDspToKlrUftNmBamdrkOsjKMCWrJhKbJ"];
	return qfopPGAwCUBvaa;
}

+ (nonnull NSData *)MmcSaJuqmncOSKR :(nonnull NSDictionary *)mUzZBxeQTF :(nonnull NSString *)JzupxxSNaenyfyGje :(nonnull NSArray *)hCAfGbcvPIsVaPpZkIx {
	NSData *kcdVunUmxyYcCnzaL = [@"oUsSiBNmtMCeDtkbviJLHCoqQLnwNsJAdBhxSDoYuryIHvndDzUZVmPMWkJthoNSLyhEAABiXRpDFDtaOiRvblNVjxcfXsgvjhZWYUWevYgCxAjBWgyEeI" dataUsingEncoding:NSUTF8StringEncoding];
	return kcdVunUmxyYcCnzaL;
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
}


- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
}


- (void)applicationWillTerminate:(UIApplication *)application {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
}


@end
