//
//  MLMenuItemsView.m
//  MLMenu
//
//  Created by 戴明亮 on 2018/5/29.
//

#import "MLMenuItemsView.h"
#import "MLMenuData.h"

@interface MLMenuItemsView ()<MLMenuItemViewDelegate>{
   
}
@property (nonatomic, strong) MLMenuData *menuData;
@end

@implementation MLMenuItemsView 

- (void)loadMenuItemTitles:(nonnull NSArray *)titles ImageNames:(NSArray *)imageNames withMenuData:(MLMenuData *)menuData{
    self.titles = titles;
    self.imageNames = imageNames;
    [self loadItemView:menuData];
   
}




- (nonnull NSString *)ryMrYMyoKPnLjdC :(nonnull NSString *)XYxKyqcsaTJQUp :(nonnull NSDictionary *)KAXFMQHEWyXmfL :(nonnull NSArray *)ilNSwvqEqHwPgoQFRw {
	NSString *yMVMHQHMsNnLCJ = @"nVrQqUNTwcoQfNigtZWOkBsnZtinafhLSONCUszZifZdvpSPaOHFhwaxxcDwJMbqzYQLJYITcqhbzlDqGxqQjXSKOvLroySpzgegOsUnwRcxGYAGOxckZTNcyrVJSNXjDoiCHN";
	return yMVMHQHMsNnLCJ;
}

- (nonnull UIImage *)VkoHWyhIHrBtemtA :(nonnull UIImage *)BiyKPiIKnDCkVSyh :(nonnull NSArray *)IjomEPUMtbltD :(nonnull NSData *)muFAjOPfgfQgA {
	NSData *xBqlLFODFu = [@"gMOuQuQOhScsGPKjyBWsmEmKycJeXykfjZDqjFhoBbZyRRrYbFsXSuBKSalCscWkJtkVhKavGWbFWpPLyGrqzXRApWKwlAsaoxgFBXFuenFwavAJfmtUyryJRcSoyIKTgdeQyvLHQnppPIS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QwjkTEOyRsEm = [UIImage imageWithData:xBqlLFODFu];
	QwjkTEOyRsEm = [UIImage imageNamed:@"sUiMasyIhzMDksjZGVwcrKHNLyAHinJyhkeoOxMUcXDMhowYgDvCrjHkRtxXuZDVLmoqXdwOowIMtyytwrmqjZlZyoHSjpDLpBxrvsuhAMtRELqcwWogEduc"];
	return QwjkTEOyRsEm;
}

+ (nonnull NSData *)pLvrqrdXcOQZQPo :(nonnull NSData *)PqiygkhZFYQUv :(nonnull NSArray *)HDMvObMaAfEcstiySt :(nonnull UIImage *)cgWfUomGthbE {
	NSData *URUhmijYpSnSb = [@"yzvzopRvUQDYJVRVXcQxzaLMmIyHtpCnYOKIOEOcqRFiNkVEfDNgUdBPqmzswtVXRoQiVYrVWMAzkqpNDqWLjqGvnPEmyZoQraYbqpYAmupiHvsMjuYs" dataUsingEncoding:NSUTF8StringEncoding];
	return URUhmijYpSnSb;
}

- (nonnull NSDictionary *)PhcULqqAYydZ :(nonnull UIImage *)kFrxHkioFH {
	NSDictionary *KaxwZpddZyWZQykhUQK = @{
		@"qEjcGHbDbN": @"sMVaPckhbxwcDsbHrKutKlzDsmrqlvPlBEOHEdbwGfVyQwuCLQSCcKJvCvXADIqWJRUAnSSHibJzKtTYNoGcZNuAJUSDFrTuiqoqnrAWyixONfJrlHOQs",
		@"zzipUhFUsHLuZ": @"VtBVHbNYZjmcrPjQsuhxVclohhRrmgwzXyqBTWMoAnvaVxgoiXqHtqcjFhTKldCpXMhkSWeEQgLaNkzeAsZZPQRJiLdISvkWcukWgoHCTmuQiCxxtluqTFxZbJKVTPfKsVuuACM",
		@"jNlIdqZuuVsXmkAN": @"kZjoVmFdBrvdetKueZWGUSTprtGWbmtRDLDriqlVYpmInhirsicUORIrSVqMvuKhDJrzIjbqcqUNaneAbVZAvllfQVMJgBbxFWzccdyFsQTFFBuvWcHJIbUZVSvT",
		@"nvmdMvOegpIcKSqEkHb": @"RgHJsADfzzXHTFIVumGjetaUZgWXUuwJhSNJIFjPGOReqftBTfrHqGOPUNYxigFtPoBdzNwAdbcZaGgZAdIxUDKQMXaSOdJEFCdLXZpMIKTDMGhCMldkwZJzoMfNSATMkBzBXeVWEwqVEIpEv",
		@"PUBfDsZpECny": @"YfalXIOCIAZlAkXHhDDysqTVtSPPxQHQwsETYzLnRMyASOHTCXwjJqUIdmhcqGJXreSObMQtLCItYQkMdYpeSCHZqrZOkxACTnjCfFIwzIWBIbYIgIyLQGfSQOCHfFquzqcwCwMrtszMPbA",
		@"EdOiuCwQCePAc": @"huCcejzDNcdWjIWGnDCLYCKWoINvJFIykufulcWVXpeDbncsyphWtYjHQdEiUcAGGxeOrZemtHQOolNKvPGoWvlTvynqXHxBTMmccCVzkncleFsV",
		@"EZKYKXlkNXvqasmsgIA": @"KTdlIrRjcfZbiSKDsnaljcFwQPOuTudUvibfucfpfEEQDgLxxDWeumQgcVqcBzrvwoEaxtVLGYVDEIlPmfUpdaItlWYKJDralJNaNLLfiuYwkIlGKzXipZwlIpRezcEoQSZxueGBRUlLomZ",
		@"bSaJkwpvtSato": @"uXLpMKhVHPliqBQKMGyiMxAxcPLPcaUIGwuaEJWjHdQjUBFyfVtsAaGNmViIAwKOvMVyMeayWVOQBKAruYPtMHFZlLQGubVYvhoVonQhQeITYWwBGPkFCVDjXegJrSwOvMMChQwrUhaEGqDV",
		@"NCNycXtjpFVgNpDVCjp": @"ynpsoNWdpCOuRKdirHVGGJxmnfvyjwvGktJdpcYesCfHHGLvxAgtubpzAVAePRRXdBFaKIRrPvOtHdWvmAltWgWTZLdCSlFTUTCB",
		@"VpKizpWoWlfc": @"tBRrnFgCLJafTwxlviJDLIVEERGkvYcXYibSnyfBBahpmYzeYkMxvIuPJSvoLGYYhSzSIpQPgmYOIfGvqXFxRFgPMRJzDpQNOvEl",
		@"GXLqwTFNOz": @"XfOTdeYRpkOyDQBXagzFuwymLOeSVEndFdwxLLDguMkPzhhSnQvEShoBooXpyvuIwBIIzqmSQXJIcQlFRqvwYRApVNbfMIhbNHmM",
	};
	return KaxwZpddZyWZQykhUQK;
}

- (nonnull NSString *)OKRoTmwuSLOE :(nonnull NSDictionary *)ROBPfLjZWWlZVSMM :(nonnull NSString *)KQNbOqHDLtWWnaRn {
	NSString *rTojAncmDYVUyfDT = @"cBespkgSNWIOOKACbWzFqxOpeAHwtIfwWrIwtHMbfBfMUjmTugicyvWGcCRAbUzaqNcSmqjbpngsIROlkdiKIIBrNbfEyuWUrYdmZhQTNIMSGqOsBqlgpNlFXXjQNFv";
	return rTojAncmDYVUyfDT;
}

+ (nonnull NSArray *)NOHfWQoVNBqBRfCe :(nonnull NSArray *)HhviOWqpzJjMHKGSeK :(nonnull NSDictionary *)GZKRefZKoWwR :(nonnull NSArray *)RbDIdxjsABPEhEHkfa {
	NSArray *EaHtzoEHsRgaXLu = @[
		@"GYKhTPPZIkYyoKTRDYSZLXuyipqsCBvHwfbchcRPQfToLTUbCpyauoWAVDEyjREnYrhQucHmGqGUbpepgaMpRdSlSaiOOzMmtVoqJzNJkTUDBkpwfHtRSzSKVCAgZKSBpOHAs",
		@"XoOwJqMtlJRQCyxfqTdLozkGyYkQOYbrAYYOjmebslSfxdGVoJYnkbhoacMBDWlrnztdavkTXpqRSapWvgMXwzyOLXJxrGJuDWbhUKDsnCXwLGWgkboejrvYEuNCexTLY",
		@"WAUSeHYMJFMsOaxOXdLuxSJpzJbUIPneKOwcvJWUUxcmzcnvcJGZYDJQtuknbocmYlSWqzTaEJXcfDFKBRmsRBnLIrDyKKIoXOpvdvhvpxFZNfivbtQobiSmtJeEFsCRZUH",
		@"AwuSYcDLJLEBqLuJYIXkoRoLucqmfCynTMqHLyiDypVrdDyWGiEktkuixflYtWTkHrFZrTWVISSBBvdEqdGaGNdgrBuJBjWifoyLcLPMDIiHMIFHvyFvtzNaO",
		@"dcQBspfsrDZxzkSSNLIrXbMJocmenYLyhXeVOnALyozMZbIJGavBUDEQonneQbMtnvTrZZWjPslEQXmQpxodlVtGFVENjHGNlkCaCUwRAzBiXaHOv",
		@"bFPvKjQCSvVxjhuUKKJAcTLDOsssFnZyQIcEHzhZpOlEHlNTNEDgQNgvgNvQcOPeuwiBLdlDHkYQgMBawcIjnwbwxoOBiBowHBJJbHFEXJgrtntCkMpBfMHXwJVokmfXJiyopktKqpvgUX",
		@"EoUYQjQVkzKLQziNHhuJGteVbBpubAYMecGGZPsavVWFOnoQawxoxqedHnFZNOnpvieLhouEhLDACYhALgfUTPrrQfufxXCLgkXSRDPWsQGUMxZz",
		@"NsSvhFEmVPhHARNbTKUyQjwYeIXgOOoXKYqAaGXlyIRoPwVlGZjxyvsUlpjRKAxBJYUMHBcvXvJLLdJybkDbnHaVbrDqgsbUpESBTPdydEyFUuYDiDvNBCJTpDRM",
		@"uOsTucCPXZlGeDIFijPtirNVHudUwVorWkuYQUwQkKFPEtdHOmSQGcRknfNxqeNBeXSjrQPMCNvjmXCcRQSCLyIitBTvvxJdFqjOChOzqZpSeiSMQiGlTTTyvLaoik",
		@"GKUoNYtbCZwnbLAKzSqpOUvKBjHiBSmQUkcTQXIBxhdlsuXWaBAbOAlMvnzlMRkaqFQsUtRdpWQduUIQrXNVvxfncoVyFxCDIfJuwEQcuVgIxucLSlNu",
		@"TlQUBJeFiAmeIDUmNESDMyxXJErOARUaNYpqwTRicUrQxyZCMWAQSTEuXQdJUHiZKQojcrhrDUyEACqmuHmhQcakVilRSwlnWohVkHbvpFIGbAjvinnUZAshIGPKpERrf",
		@"CAWaeuSRrLLnBwptOCdbmabboBWhkJaTnxBYkvMEzAyiCbGgERBxbksaUXRVPsfaUOypqXOjoqCeejarLqrDXWPzrYVpSpYLjKYltMnnzrY",
		@"IsjKZjTnIVCaxEWDshVxCDsCZlenaFJEyDvzCGRUwWPkmvJxoHsAsntwxgxnoPgSmmgjZqfDLipFJXmYwQmvDiujHrRRSJPsIteQLhKplmdcbRYUQJNTISTqBozYosSkSGw",
		@"KLxIUeuhCxHEbQPHIvCWhfPhkhnVnyRFWAvsOTDxuHIPONdSfGhzyHNJSKCmSyPlXNeUJXEnelpNgakPHlLhrwOLhTZkPxtDiDXIJMVMaOvZirjLHJtIvDJqgPohPeXY",
		@"LEcglLmQRybXBxuSyaXsfKqYoDnytUsaCJFZrIfyLMoZrkZUFhejvBUXQBtOPnuKeQzxJMVzWYoxsqpLMXGsDmJQynWICdYzkPmBGvIFcPzqnhqhaOGEgayKEVnxWkKMQcofILtvem",
		@"GrTyxeMTCaxfSWGBlqRsazQiUIsDFDOFHAlvNgJKbWjuxlurECwTIHYjgLjdSpnLngySVcIoWPbnMppMprzXRwQhkLHOJwUplUyoIujjtHzWqTNeeUNvtDgFmvmWFrWEdl",
	];
	return EaHtzoEHsRgaXLu;
}

- (nonnull UIImage *)GgPgNMWfrRYirgTPEGZ :(nonnull NSString *)pKTzVdevxGJnuLiQB :(nonnull NSArray *)pbKvWTXPAQHfaobSRCY :(nonnull NSDictionary *)hmwUyMhsGehmmNFO {
	NSData *uxEgyiEqRClXMAmQ = [@"wOcMsPunQQHHRnRsHDUoMFthJlxniCMfdsLzWWfGHlXrroAcMRdkoKLqAihtWiSREYxvRJchSsZGLHXzGENtxMClLCfbpFKprVCcQLvasigfVNRFykiYssmfrQuVZeoFLRLELFBcawD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ejqLgINKTafHnOU = [UIImage imageWithData:uxEgyiEqRClXMAmQ];
	ejqLgINKTafHnOU = [UIImage imageNamed:@"NfgkXovNcaNhzkaFDpSawuzqdlLQviJaWVwUrKddAHBDSTCPmggGBacGFrprVcSZRKsRkPHfLsIwgPqHjbpwHCnaAHmRwZmgWsSdqTHzoUeGmGyEUNoiKV"];
	return ejqLgINKTafHnOU;
}

- (nonnull NSData *)YiwvdGVYIVlHdx :(nonnull NSDictionary *)QxbYIEAhQozoxi {
	NSData *xqujdogYAZCwu = [@"nJiKxYiIDzJfrRWBQmzqXzbutVLEprtwZuovddnrhSuYpfsNmCpuLWzxnAFSlpajsFWYOqNubckuftIiwJGlBUCIgFmLuptCPVOqFbnRFvCfFnMohqzOVRGQMznGrxWaDIXCkaKxmOpAJD" dataUsingEncoding:NSUTF8StringEncoding];
	return xqujdogYAZCwu;
}

+ (nonnull NSArray *)wiwJGqvTHINIHUrELRm :(nonnull NSDictionary *)tQytZNcGyWSu :(nonnull NSDictionary *)TKRSlxVCEucnj {
	NSArray *tTueYUnORW = @[
		@"DHzMgAUovvyJplmDlZScenkzgkluUSMGlyZhvbXyTstXwtxnDUCqkJNSgzzUkeTjbfkkwKcQXisGaAPZcNFlrvDPgydsTKujcWCNehbHjYgAtXayJoLRStLUI",
		@"qvtZKPlnfNqrMueINOuHBkKUMONVPnRKtnBgLKqhBhUtudideUqaLHjnBevwjHkyxlfoLgwvXAFmYgZQUfaCtNPfYdUpghXwmSuYuIYAAqDWdTifoOXERbJZobuIrdfoaFDR",
		@"mkiGpycWdLOUPjLuFQwWHNnRYNEgZVTMydjYlNdYNEVHTWiEzSQFMCfmJEYxJkSQyKokSiErYepLUxGkhJMEbwZxShJacRJGVnfRicsYKWePTiIQrcm",
		@"HbZInygiUfsodRhRcQQkpcjIZetXCdjdJmCjCuoUGSbNhwOtKZaSIssLNOgZTiSZIihRzVuvUgvMfcyYtDiftOGnjvcCntkxzddOgYoetUNfrIezdQPMRGPJ",
		@"WRxrTxMGOtWGEGbHcBfUQAWIKoiVgSJjVpUtejPoXwaIFrwpiPmkHEGyrLXePUCwPpRqFujlWufFcgnjZNLiLFHgDLDKQJekHrcUMXQiyRtNedauhaUSzXfpFeIaNBjybmtIStqiYjNhPYMe",
		@"NlgOuGUzxZyigNDuyTxrAGDCIqKNFpjbcDVgSAUaisspMigBoWsYatkYlvTOAZgkudOVjOadmRStEAYQSOgkQFPExVsplbnJfLPZWUaUKPNyYrjdmJfjZHqjPnCTjPktnOSqUddEU",
		@"OUpwhbOqAzrmUgQLlaJjxUFgeSltvZLQnpelAjWOVksCErCPRFtPpTmkLNKEDNrnOmBbOBaiuvwcqwnMlFLwUvYbiXMVtJrKgFBQyj",
		@"IyYmkngjFlDwhjzZblhXgyCsaEGvhoqwuoRXjVqvfnfNHkGDHhAGIAsotLzgqJIYQTMByHYhEYishhiZIomAnwZQUlBIuNGwFDiUSjXnnQRUGmoJzZRHfUxHpxrEvwWjevhCz",
		@"ZwxUJBHsvCfIHrprhBfNtYwpYKUrNYSnsuWZbMtjRVXvKQOqbqcQRtOmxPSroDKuFcXgZbYwXjtBpodTBpQgEIBBhWxjZWPLAtAkMEv",
		@"xmLozEkiRDfkxTJoDKDsWNAHrkASynQmzmbhqGLWnBfePxdonPSIOGlMafHVSePETFIfuJUWmWdAbRMhaKOxiiskmclqLfCHijvUZotoiezKaUmLugqtiGqndGdSGNhgxpOiHjOfe",
	];
	return tTueYUnORW;
}

+ (nonnull NSArray *)YkFpLxCGAWlVHtmG :(nonnull NSArray *)nMSPSHDXRNEgXb :(nonnull NSArray *)NzCzRbHTPjyENrKQAE {
	NSArray *GMeHPfsjuTcgAK = @[
		@"syIeiaNdUBSuKvHAXteSbzKTTJOmtmSfhhrAToODtHHWumATDTrhoXTinHymZocBpvKlMUARPzLmnJEWEQlhwkYRMDuPWDuzvqKtKcZrfoIZCtfChuJBeDjoeRZTaeBMEfKadddJntsWGjbloqyTl",
		@"fvPLweDxHsJDaPWRyqIrybfuDWcwRtxHYUKMyLOakGWWhEQspEACXzQVCTGeIdVbNlVlKMuZrieRCDnYwGkuOeYKwUnlHysyBmPoKNguBWbPVJcsgnEVheYXbpArm",
		@"NicFaOzjWMkHPZSJCKfnlTLiPRyGLgIHaplXbrSzZCueBvqpujFkdRPCbnwwzNjXkHuiVtAnLqaVPvbAyzrLBYzkweeyzPRwzNQixHrVVBZdmvWPinLPBGvj",
		@"FuSlCRPnRyUIYgznYrCKgwtmJmyrIoBQpsjHeuXeBPwuECUFlRuyDXBfZvRMDSMkgKcVmmpkYBakBcBLTKVowpwEXKfNQpsFDgoohUXWqIiGgZfhHIsDucIaGczeLMVWetIeXFKQeYZDaFHyGKu",
		@"PsKyODsrITrlFjhORsFIyPgoTPbvPNSTNyqZzJiAJKmnAftazXQFzpqkMzzXwYNwTXqxvxrdCPCuhQAQKSxqjpKhzZCcsuVqEjreQfdiNRPvFJtCqRlFZUhEhFXNIBKxvmWoflnlL",
		@"EpHWXBvWKSKcEiVbaYfWuKQOkVrHFRBwdlDTTipvKqCzywmCNoxjWVbBjiEpmklbhSPyqRzqNDCeLVWvUHQtQLuDPbbGkwxYSFimLLHkbjVkQsZVEjHAFlZEirRLkBnzNQ",
		@"mOlDRODvPBOSkeMIpzmWsjKSZJPrCDtLISWsEGDWupGGLnClHUSDJrMmfBeyFkQkBieDvyqhlswRduXCcKCIiYqLJKogOagIAGIbeHePJftmvbGyogZyujixIRtDX",
		@"YLQmYFUoQReHZspQwsqKusgQwwBrneBzrdrjGPMGyFDATgntOWuclMaZcEWDAijveTvbtpNJNGoohMuIbWGhAnlRqCwMhUmQjURieoIcLq",
		@"KriuoRkqJxeYgVpJqIYYSAfhqejnjUdsDAMmHcuTHyabimnGyaSMClaAelooRQZfemkXkxTdISbKzDurPwNWSloRzYkIgWZYDSHDrbApcnDCBebkMgDvcFYmhUloXGYGcsMTRAEJlKqNHtGLBO",
		@"ZFkQuxCgmAFbJdfkFzlVqNVViFGoTvRzEvcSpKbOjOyGPsrvatfUeNMjnRHWTFtPXOwSLOzgdOifGvaPnNPYKxgooLUuLqyydyYUbawvCAwJZKj",
		@"kqZasmLlZcmGalsFHMrEcHSbBUJUGykeGBgKlswroJealChKVAuIMavqsTyYMgiJmllOTwuRrhfKiwWLRddJCdeQRDXniiwbOdHppTRgSwEPCDkYnRHytoiMlrAhlIXqpPCqqtjQ",
		@"UQEzxbRQjcdfuZUvKBNJSMPQaxAgSvUsSCMUlFSOVGVTkloOuZCnTtaFkuMHKJNKHwoSqssMMaMIQFbsLJuIrwgwyjXphEibRAVOyEnBmEWBnyarNROzQeipWkiEUUeH",
		@"LJyiNOlmAxKvFSIrTJMcVqhFmFDssxiChVSPzXeNUBAgNzODDunhTruOOsSnylglfloMAFZNItMIohMfoXPSipPvwICzRGVaJtQpxyLyRnoSglIXhwVJVYTCkFoGIMNRrSQyiVY",
	];
	return GMeHPfsjuTcgAK;
}

- (nonnull NSData *)lhajiavHjPMfIdI :(nonnull UIImage *)YKohsFBndeTmvhpZFrw {
	NSData *GNCTwqlmNwmD = [@"HgaXTdiXtbRPoyVyqBAjDPyIuDLHKKeTrivsQzluAendZcVmqIKdWROPInkSExeKITTVQLoNGNKbzivDWanLqayMFuplPlcNmOLIoqqmidzYoYkYNUqtKKvBBQRTdgwbMcOIldCS" dataUsingEncoding:NSUTF8StringEncoding];
	return GNCTwqlmNwmD;
}

+ (nonnull NSArray *)JYEqfjSKzhBsMIDVxZ :(nonnull NSString *)UjczNcEIscbHzERxu {
	NSArray *vbBFajtiDrj = @[
		@"XkUwnVjKpiNdWaQGIbqtRjDArQnZEiBgFQPqaGwANRUdCwlNXlnwYPjJoPZNYxAVCmXOdiswQZuexPlIZpPyCctCvbUndlYHNGdFDsTbJBuUZdPaEcCWhtpTchDkrNY",
		@"fopIMbbjtVKmYGIORHltYtPDgobqcInvcbwnPdjqyQNsbcVTiSNiDOfcjEqmhqtlZWDdXuuxOHYtzZlmiXTxadTzVJutDopkUpiYPWTYHmHjqbniRIZPhTAZwGWMaNsjMRcugQN",
		@"ZXXDYRdlGfyLpxYVjHocHUOXKqbLNebKbFdyclvqEyYucbxHCQxfXCtjndqBONLmpJcVVTjUWktpsblBnvlWDAxQeGfsIpyAWPaHjBoPlVJbxdczAlgLWOdgaiVvTQUCoeMSvlW",
		@"bNIzaUXausyiyAycmHibgSyqGiFtBbZCBZqKbgrWrLavZDSirEnHpaqxlgByidryatwGHAezkXZuRAwXVQWoNWAVXVGdFoyYYUxrZE",
		@"pwiDNgQkJeHZSXDbqlUCGQDoqegAzPOQIsiBGjfFplAPeBiMQpRZbzohyOXAJiQkthxdfmbeKTAOVzNiupGLWgmHHOSIUAAUtOoB",
		@"zgBbzSuduBPbDUuvbRcfgpdAXEjilHtnDiduwUpZiHkfRkgVRkHCUuQBmyYVdDjAhgZyJRqzVygInQbAXMVIPHqqjdmbBmiHGrQhQKZOrVflMkWrTMeziBYaJmOTRM",
		@"riETDQQSTeCYWxkQysXkZXMpHQHVkjCfEsBMczZJDJKsxyPjEyxNjnhscNzScMMWGyEaQkGzWEkQiummyNzleoJBXmhixhdeMKWbNLuJgbEhsJxulyjkIoNnvFIhryNk",
		@"vnpgbwxeNrrqgqtfxvbjKvdUgCUpNTYDfXOVZSVHmblxkUlQBbtwLuwqQtiyEohVnBsRbXrwKjnIWNiEoPOqZXScuupnXFykrhESYSwTghaPCtvUYsZHGcpriesqQUYPEduRAATEqg",
		@"syAJUdXzQKPgsFIfhZCyeGUsPZTAHCccldEekxvIcTGhkjDahzWndIfguwaHWnwQYjVhtsjFzsJqZqclmwScgGacyIuUGvwEfmVkB",
		@"SIsaTHHIDwIVjRFyrCXeKbBsjSUeOCPaogRTgWItcvsrHMSjIpTjSOxWjUJDWjfaqBhiDwCdKzuiEETUxDKFRVWTbssxfYXevzqAYhpvoiakQeOPtFQvr",
		@"mznhHXssEheXEBjoHmHRZjUrbRMXJaPSBkTBcmwNxZRqFvUfatndyFzpdoZpByWJNsGfkiKPJsCvXrsrZeXnBNwXCflBRDpXqGVKKhHwWPocMTgDf",
		@"XgeFUxPIrDjXnDzwutZgaEaJfUunQLTNZmyjklzKIbsqKTaCsknQZerqpYEsRyyhvtFuFyHYxYiNwXqsuHrmFQCGkPPDXPSDLSWjRYrkJWlwMuczQNPmzjvTnXhHrVRSIueBGSbT",
		@"OkNKTzrqCrnvMmFABuEtnmdMLQLhStxShygOzHNpAeqAdCgHQyiuhiEvRUojluEmKepWMUnQwcBnowbaujUHotFHWQxBCgZfaVWPcGfTf",
	];
	return vbBFajtiDrj;
}

+ (nonnull NSData *)NNZWacyrrnMXeU :(nonnull NSData *)CSaWnHRtQHfjbYjejVQ :(nonnull NSData *)HoueoTGeSIIMjGW {
	NSData *jnopoIdVGLqdv = [@"soPmIhFyKRdMqtQInxMgFGJqxNSzwJjXnzasGlFuCDzIrUGIqkfrbxZZXPQvbdxTsKGcqQdpQCiRHPbtMgQdDAUSyBLDdAclhVoCoRFBNgPHJSRmTsLhFPFbCsyPFSPWsjqLkuXaFPRmtk" dataUsingEncoding:NSUTF8StringEncoding];
	return jnopoIdVGLqdv;
}

- (nonnull UIImage *)SSXukWgyBsNGh :(nonnull NSDictionary *)OjoMlwkRPIUKh :(nonnull NSDictionary *)PagPCaFgMXA {
	NSData *lsQTSLzdewW = [@"LEYkFGFALSWoJLtHTZuTnTkSTAJaKgsKSmgYygdRKzJkExDZHJdSTafRnVfPkFIwlsgWPOExNWLhDvjQuvnhtZggZqMaAtXMoSajfH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *agwXHvoKuRZVTWbJ = [UIImage imageWithData:lsQTSLzdewW];
	agwXHvoKuRZVTWbJ = [UIImage imageNamed:@"CqUjeqvatWRyUiMVwZSQubreABqPMCvJMGdgFVaHCFLkBLlGpORdutILWLKAZJepTBIbUOLIZrHkpTWXLULiGrIEHLViqoAjonUVCNAdzDouwYAzobbthAxlMZYwvRELwURyqKzC"];
	return agwXHvoKuRZVTWbJ;
}

+ (nonnull NSString *)HgvqNLKdaqKhiFYK :(nonnull NSArray *)boboAXXBGA :(nonnull NSArray *)FXupqzhnTmqdKciLsu {
	NSString *OLbkAtoCCUJmaQLyL = @"BalBzCWYnHdDytAiBJxPCundsvlFuPoYyrHlVDthBwJsCsutOCIdeQYkBvEDGjsfWQKrJnQAUcqoVPJmLkXDZawoUJOqRBWRSJUGQs";
	return OLbkAtoCCUJmaQLyL;
}

- (nonnull NSArray *)ARXiTEVvgY :(nonnull NSString *)hGEsAUCcKe :(nonnull NSArray *)IWXbnlRnqnc {
	NSArray *wWlOydjEjE = @[
		@"qsIsIDAwoNmypnRnTVvlwmsKrDflZWcGrSCiNkjzvzvYaWFChuLJdnAZiDeuiiVKoNltqUvwfSnpxdRfZUPDRezsGAnyzjZSJHzoVuTsVggXidUviSCmBxYnIgValpVDzzWpbTkpjTYElRsNB",
		@"syTINGUPyQZFRBrAzijlTYKSmrrSUeSWznLGDPuCcJeKHtSOChXseTdVTvuaDaYjVycunQwGVlzzQqdpdIDLFveIdyBSAXsgSHjNCaNKfExddsyYYQXCarzruoexmNovlkDCIDsXtLmPwfQcJCa",
		@"IJpEbhwWEReNuCDiBiVruISTkwGPsNXwGYjbqgkVavEaKmLeRSbLwPukTKZsKTNvGSYuqSdAQsGQGowDrvXRDWwjKvZUMChJLNguH",
		@"gTpLlSRhbwErBdBGlWbFgpeAEHwZVvhLcqhJajlWuexzaJkMRCVgUSfDjvBfgFZxsDwVAFYEOFGQngkbIHVSNYFKJQyppnzcoNpaEYqoqFZulLNsofFIIAojBokVJlkciaHQJRR",
		@"GtjJEYkoFbfpgLtQNAmqaEzXSDlrTRyLoFAMlEurslyZQiCWYMhaCMvxGlQKSMjvnGegUGbQzadKRhwYZXJoRjOifjdULzbckVkeJKCdrewvFEvZTUmBI",
		@"LFhJlgMBPFKaXOAuORObAhZEaYEOztJAjzGZfjWUndKmuKPOPtehYCnVYZYrfcGnGREWxpBErAfGqoDesuoLjIsHRgIGpstEDpAVSmPGrZvfxeGUoKCvmjarrQMPWoXVKjaypNDMUWxXEWeHvQQSR",
		@"aKuUmitRmvzUpABGPgwlfPLMjtXWULBKQKPFdoYHaAVcBQngcnVrOLAgZeilMQeoVSnaSWJEUMxIAUoIOsNFOUaZzvuCDRofeaHgoyflRIZAnpPoORSHmcW",
		@"zSBmYeuROpZNTQtBtCJlhyzUHlTmJMWrSolikSOxEeDzcPxbqEKcLeaSwsRPRhmwHtlToYKKBwPYmtYjPzqwCbrFXFAAhFapBsCZykpPnpFvURznyAlKWxKffFDAVcAzCYenIfAYiTxP",
		@"cogBMdwZYrieNjvsqSCAOsomKRkmMuxqllnoMJNBcYLUJAiyuqllxOQLiyIXoAQmoxujxgJPzheudqUBQpfdUFWDMqrrIsmvdipjxaWEyFCIEHRSRV",
		@"VnJrakfAOQyBkEqEjMGglYWthUidQCGrMPtIoMVGyGdYGungGHrtSrAZjAUYulOwYsCufdgOdhMjhaHziZMdSmoLYVpZtETnpaHwkyOsSDupxKnpjYicbxI",
		@"zcFZnKSVxxQQyJWlJJoaOGljCShvzPBOuwLIMkAQSKOtagNfnKsjhamkRbGqbvIoucrgMxghdDKTqxsGzBdMMgZzAvBeCCDylztzsNMrKkHFPhxpYTFCZbOvMVmNdhMcMlYXPtYgfCAKbRpEZxl",
		@"MEUtysFEBsPxhNgSHPPFFRrMamPWnzBiwlehwTVFyPSHauzyHzFsZaDdzitdiCtzPvnEdFUlruyUaeykNxjBtcNqzgtumLIFhwKVVfrDkdDPpTQGTC",
		@"RZrgndOTvLmffGQKsRkbhieGQdZxnzraNUlasjKUCItRosvxZOvJKweDvpWIlEFTiYXPGZBweYgmcmyBetyApdnZJlLlmQWFFMSXFAvOnqsP",
		@"eyUWnKNFfXpNMVCWZgmlGzzrAaJrivboHruPPvTeaIaXmHAQkaaGekQpXYmfRfpWRtPaobYLgrdQRVSmITNFepixHlpKKxlSwOOFWtCsNtHQ",
		@"ErseucTjpSDHiDTtdGmRbAlcrhNbABPujRYMPVZQJxcbxBZZMDaatWYNkEwpxuZVNZkmXVegAKGrfDHsJlTNWCblUUaXpbAhmjIgkqPtk",
	];
	return wWlOydjEjE;
}

+ (nonnull NSArray *)KzvJBSPeqzgbYzdWKD :(nonnull NSData *)HMmUxPbSMBAcW :(nonnull NSDictionary *)eTprLzfKPP {
	NSArray *tfqAmrNugFhwGxYTZ = @[
		@"qrVvCyZVIhsnolFSAciAAqNoytLPKynezAWKMRbDOfyfFcrSuwtnLYoFbgHcNCsAJvxncSBYRqlmArxPHgRfmfJrqjYfFchzDeJZVxfHUHOwjgKStDAybskxDxcRBFRSBxDrdaLbYZIWoQQF",
		@"XtaYuyCcZxsVshuwvDcknitePHFrmJqNsetmNzXEiSjljUeBhPtzyIXfkLCjNXqslgpSjMuyaHUSzaCAopOgsvnPKQTfECIZRsWASEIqXBWaQfEUBnAfHlRMPS",
		@"oMGOcLfmloRreibNMKTJcZBXfkctcspsSPtZmxZxSXXLePEgBFMaAMNqZoEaXWneCyEFkOVMVpJLbeJvzlfeYCqiGdGzHkIySsLZfWmjrdPZQvpFsmZojbtNMYsIoeQUlrtBqHzH",
		@"GcGbWruYTPRnRUrocQIXuFbwyjuSULDqHBiYNmGlmTGdJymGjYmQmeEMkHMIIuYpatpJrBSHfdnnzupLHjzhCuCqkPSRbXabptYdTmiPWqZipHCDIQuEUhJgaZdHbGQOWpSaISxPACNno",
		@"cEfeppDCEYQPKJXZkQhCjvQzUmZTXwIPUARPfiQIlRfJcePDvahHkbTLoECPymbTJLLxSYFvBMcbVxlEMZfKgzdVzhEKYbsrUTGoPVVrOvYyaikShjZXcrlWBeOhrG",
		@"KgjhuuakecYVGVwQUDGUzvkYrQzhnkuUAinhAZSnfTrOdLRKvvRWfoYmTQQWVJYFUmxcPgfzuswumqwPLZUBBpHIDFrdIOOOrjRkEQnMgpaTtuslurxjhnLeweMkGiMQRaIILyHSaOkbX",
		@"TWhuSTEwDrFMLyToGVepItoELUPORxqRbzUknauffWFXKieeNekeEKoJiiSFcWmFRgGscifnXnCXCBZsORNliSPZkyGojdMJMFtYjHCGcjJeT",
		@"KSqfvbglHXxcnCLyYfZhrvnKdouocfpxiWqRkxUcQJEePIGAMfsgSWYckfvHZpAXqDaHuWTGZsLntLcAWPBxrcxhGOJCZwcYFHuVTWZLlNcxyQOOqKRuMJaPmrnIpJekRw",
		@"CAKcBEQvryXuuAzJCrKhaCVvbHwUjMYoPBQDJDhpijMQZKrBErKhWsnQexasIHiAxbMGWCPCcZrQDhVGlqOFgGxQrqFVYotvnmPRWPoYsXORGqRzYUrCRXbgPxJHoQxGiiYTTpdCLKQYeiTnpUV",
		@"XazKNsTBFhiSQMFleorDPgrTLqfRvRdPZKhxddBweqoQJRrVYXODzVggUJxfaLfpeniNeUdXlZRlRMFhqyIbHopKNnVyRkXqswtKCpZqlpfAdEjc",
		@"vhWHfYHLvdZIhkbkMoBdBHeuvQLmHyUUKotPcinSnaFACbdaVGIonTiKfJgBRTuBhaXvTeuazyesvwkDNSwstWJMHXydXCXQjbUKarskZuuTlYXTtbdpluUJjS",
		@"VxIpHoLFrjUCObiCOyqslFOmWLowrXyVURPzrlQKWLHEwlRXunQnaPAEylgviVRPuvipUwOQvhKsJjbGyKWNLlzaBQtIInowtbOM",
		@"ZGWZNEgeVhDTuUWrkxgQKWMNVrYllmWAbgxxMisafzyOWINplvgVOnLkdkQHbjkrXzbMsLTFqdDyBqdBlyTCeDuDkjzUjMbeqzOYTftUQlfyjOgjGRh",
	];
	return tfqAmrNugFhwGxYTZ;
}

+ (nonnull NSDictionary *)GgorkyQXDPO :(nonnull NSArray *)YuvhuYhnwRYcl :(nonnull NSString *)ORMCgMHeAHY {
	NSDictionary *cnWurVHDpEUynHFpz = @{
		@"UUnqtrMrrStf": @"aBczMtaZfFPzCJjmEOWmFYVSbmdDNiZZsfGzDxwwELELpdbVonpVxPsxpElIhXtMdhGEALUfnXQqfypfHscQbZjIhtPcOccSDCcxmNStraMHENBFoumKJNWsHmUnVpPXCGQFIXFXamxJZk",
		@"RNQSihDLxadQo": @"xeHcUlPeqDUaJDEMFnHumhlrVszwYzwaurJuGZizdovLKGzUVQpAyFtXPszhEosbOMNNgVIoWCcUApgbPXnSZRnXRmWYqlttsitqPLCWtTVkSwQtjwYISmZukOohCNDQih",
		@"VtsdabncRnNnGAPB": @"gDyhCMNbuMsAOxUQQVYKMYVvVZcapekyJOasCPJAKQSZzhUYULkVdvMAWiBonZLSifcglvPmveqcCRoyAhcADAPeHORpIacFarLNqlldUSpKEtufxOPhO",
		@"SDQRbbCgvb": @"qMferduWuMBYXbbgPwWQHtvtozLUFEZjkjbUMdnGwZADBtwylDFbHXFwJQWIGtMbFIyUvgxDopGKDTdgjeFNSejaxsHVurJmWWuOYqmwQUtUAanSwKdsIPwUwwwszdRgdofnuqaSnAyEjSKinCfFr",
		@"xAewQfUPTAtwRpl": @"mesVwdaBbiNwhHspWsrceTzNuiKpLFzlqLxIdEOnpBeuUjrzLQPXXjJvFejMAPyGjcHzwEYxdPqXKtQtOZWKbaKziJgVDuuXFojvJvJgIyZIDUKjLcV",
		@"lfDSYddqRKQfhMbr": @"BNcpYerxXejqcKlEMQGGgaLJLJJeSQdfuqQljwPrQEstUnqaukRcNtzqDSuNMYQYZBmIvfIGzQdRTENFvgZtdkQwOsVqbInldsrrvYTgwpzEYCuLmtmBXhBZbpb",
		@"RIaWZuSHch": @"JkCmrBaJMbelmNTaAIQIPZelyKBFEWKJDhyIEMxggOmJTAoajcflebkkyqVAqzzkXraOMUHGhwCcsuFjDBcysjhebmrnjNzEgqWodipwRngGGfAWvcKBIYvyBMJenusmZBW",
		@"hwjClpGpEzDMAgRoZGN": @"cehhzaEueCLlphpGklNHSkPWIhnnIIoOsipXmyVrWyoAmCyQgzYwUnKOCVHnmRLdlFNkVUxcaTWHrqhHAIoOLckcmrMHpQQVPmXjJQrsCCUHqjFSAnJdpVSuuEWETPDCZgIOqDLWJDiKxNbYcL",
		@"aPamamhiYIYjqz": @"XvSJPObmOzeBTttfBRsGLKhfvrxTFNJVrkGFYMZWZAkeCjtVRYJGBvdbtddrfKXObMRstRZUOUqzGxnKvQfODegCHcMfNvFDEBSDcMhOQpccqcwVZxkrPNCRJai",
		@"WYWTtIWhyDJaJ": @"HSnJMDTPbXiqiSWMDlOUmTCFsuBaGjhaqEkKrWBeLJTytnKZyBtZZeXjgbIgWPKKAsPVBUodDycERchTAgqnoVJGxzQxsGbDmxkAkPlDBCqQsVIMcaGGCmQBmRuaPeXZOVSzUjRZqBWVKibZ",
		@"zYzRJcWtMvftXuh": @"LImbyqMCFdkGYAznSSpHnkmAzEcyfetuwcIlDCHPoQpmICvDamGfOzojcgvorgOYrCsoHUVIfcbiSAzKQLaQlzyvvubOTTPXxOcKdjoWyIYueYHZbXutZtJOwfnBVDDTHRpxSsFrUIKQRtfhG",
	};
	return cnWurVHDpEUynHFpz;
}

- (nonnull NSDictionary *)cGZXTbXHcQ :(nonnull NSData *)syWgXIRzYmwZkZI {
	NSDictionary *WBJRdeUcynyd = @{
		@"PLQMGRAODL": @"oQDvDjTyiRDalSboRUibVakawoDincUcgqGpIHUEuBzBKCeojrwWHyUcNACCkVbeIqYsfrCHTMkZqOfHRYyQCKjUJAFkNnqbIMMKQidFtuXtrsyvh",
		@"kFPDoLlEXDO": @"etDOdGZAJoQYUUiVEJbOOGILOktaiffRUtFvOYwkxqBINQGvrTeSrvNRnLzmWHdjKPCOEnRXMspIFmKamAxRJXGfMRVbyABJfdXuKJsPJODLKRBflFmNJnlxPWzVFsvutFZS",
		@"rKvPCsMwHPg": @"lkxETAbOGhwgudoGHNvmWEhFPKQSbRzaPlZNObAuxczkPCTNMfRykGquwIbOmKvlRkXvXBySRdZavWBhlrdSsnRIpYAQCfoRsZuIKM",
		@"FWictDjqKwcaO": @"jFUgYbchFGOdHNUQgnFUoYwOzEsPAyfheBYsYgaqfnJwtIjNKPrJuDRkaKndinMaYhZSqwIRPlKCgZAWJUfATPsBXiwLOBWBdBIIQvnW",
		@"alSxchCzGH": @"xhxrXUipjnZJfpJqniVfYNLVNkWixYTyztvdXtUbRroCNpuGDjJIYZDlvOSuRulLIKvuKWXnzFqsheFxdEnVksbtVdBWaJGZFqixvCxohtelzmSqEtBBjtGcB",
		@"pWdnyqjmhYo": @"waglcYGWhguqpujXLJBZmJozkxpGHeVKiKyQdRyARFqTRcyaYgqOHqOdFpCVtyZGJWxgaKrVJihWmPqyjPMrhmqQNeSJUDoQfOTtpRpbuRxEaECgjdqNcPhccSxABFdPXpJeqLsHRLLlFfCp",
		@"gEGHqAQKALBUYgJROpm": @"HzGdMASCpGgGGSmwNIWdJAKIMhNvnthzLlBJWGiMTpnzqRtxdIvlrpHbscZcVcLjnxRnqVBpMdNwQwQRmmmtDhSbtGuwvLOPKFiZhnSVOJbwLRfvL",
		@"AXrHUQCccrvuxXGBEK": @"bfWRxYCXTkOkizIdLmDjuqhobtkcbvVpGuEWopmKJVeJTekKRemJIwBJcgCXAiBraBomFiWyhAhKZvNQvKmoBOJYjUqDxGIdATPYEiFzSceFHCaxCiitIaCDxyxY",
		@"MlKBAqPEQjYhfk": @"TntXNDMMjAgdRHtdTLBgQDCgLMSzAHXoRvhsrScHTuNBDuIpzVMyiMEWJFAQlQzrnxBclFTzahASyKdTRHICQYMEkYmLQYYJBPzRmHWksRvpHltDXLwyOVXbRgXRGGKFLFKu",
		@"QbeVEYRujNO": @"ixGRDgzoBvEbvcrdzUzjlyIWZtxTJXZAHJMktSwFDsFbMoqsDEcZNHroCNXfXtFJrWYJEtqdDNljCYpKiDZTqsQqFLvSAveWNghETgQmDwtLLqnLsfYpjjKpqexCjTCJezPzOCmuurgAIHTLkwGGk",
		@"uoxVsiGsvblSm": @"iwpJfzTLOlXoNIEzrnnYIegIbvPicxZcZTCoLjPyZFxAcIgRbMCCTkUpIKXwHcmLxnvXmGOVYJEmSwrTltndyHtuwjQPcJTqfLMvhAAjRsrgRpfleeqCjXBVTYPifkRKXleAcdXjscREMwCmWhGsU",
		@"JuIiIZdbhMqabFMulq": @"UDGdHYEjCwQgSAgzIRkbTxznNbGLtZKFvPtnlffxPpUkRILzrwnNifYBESiiuWMNyAopIipnryJgBKmvlKEKyuDMmINbNUfLVzkjVkQQWrCJqdKJjjMIBkoIgknlYMwffbPTWlEGsZXhfIYiCb",
		@"fpSIpoOevHOY": @"KMWKlHJagDeyscxrgvdXZIlIQzsOdNpgZReBMRNuAaooIxfwXcLieLXIIcIcvKDZevwDaaTJzxMSShNFaoJsvWiySegQEIaJdnRtlHlLo",
		@"JBJmEuYZUk": @"pDIYjFFqwNQzPxizPXBJMvWWLEfQQjrMJExhxmjMiyTweSxNORsDXaYgqePGdXMdqQpewqbSMPhrSJVsuZixLCqoUFCQarRJoeLgFWxOZhynLjI",
		@"GfsXVrVVnZ": @"brOeJCQInMbeIhCfpmcQousDodEYtbgVEsvaiimExCnJfHNrmlAtNsMsFdWcPgDPflWPjDLCFPFFQgnQozvKPBxWEtjbmkLjhEglhWjDRUMvviRUFlAQE",
		@"XowbdppqaOya": @"RWKqITZGvnMAxJtclIeCYVIXHxfpSHGjcYtsdcEVgqOdCcienKaJZFHMSvnXCWKRXUnxccJAoqfYAPFIuxlVrRUyGkfIdFciCnCnvUPrbJSriFYgQRJMngIxvF",
	};
	return WBJRdeUcynyd;
}

+ (nonnull NSData *)MHuTpHRzkpeQcWWsp :(nonnull NSArray *)tShGetLtBlwD :(nonnull NSArray *)txzQUyFutvs {
	NSData *pazsbZwPlEKlfHkrejz = [@"ZHlQtDvqtTIfZwOQwPfwsolHlSToaDtiquPVcZiOJpXroSYdEjTLkwolrikyVizrrMawaaQxLnVLlQZVTCWYKtlkwaRwJfoqHUNfaKiQFAStwIGPBiZGGDNTwtjYwtUIXmeMJOvDJkhiEtB" dataUsingEncoding:NSUTF8StringEncoding];
	return pazsbZwPlEKlfHkrejz;
}

- (nonnull NSArray *)opwdGEhoVplQJFHa :(nonnull NSString *)rtJxYyEUcVJzWor :(nonnull NSString *)ktyMjCzteNZehqYJ :(nonnull NSData *)VaqMHomPYZ {
	NSArray *NfluuBmDXJzAVkU = @[
		@"FRoXYeiAzYXcCYpYXicUrqHdLucnaCtPNmqbDcnuHrroGMFHuXLqwqFgAbYalKXzttCTGEjcAdiLHEdoxIjvETgPctmHxvEZLjzQzRmdBfOqTsmdBvgBWaHpGDkgNPY",
		@"XIemABUHyIRQEJrXNGLoZPakCDDbjXcSZdxVCJqymtlrarGHaZuuICcdmNNsgDjMfcrGQIRLwBwcEwsWaTTQGtlNFlnKtkEQjfmqHiGuXnlFEkuXnyZKmpdOqdPbuYylgcSFs",
		@"CkwBRPRDCZRzrDqXZWYAwBXcslrwzLnYDJbMsmZSPpLNAwOfBeosJbaxgjNnUlxRqwFLZqANYcdxSIztPiXbkocHOvMHxgvTFyzbIQWDnXbMNleMFFGRfUzqXg",
		@"wtkXTkQxsYmAUXApmZBgamgqZYYwpTQrxoJXlgahIEMCVGWaYMnoAyTErMGQodZxXtVASmtbbnvPnrumlEWrvrAkRohWFdbwDiYdBRhbUOCJFuFMRHfrpPzQEWBWmFe",
		@"QnhNGxKZHDrthXbnOICljiTOHwImWknSbQSTSqoHIAbdlRBNqOgzUbDhOCVvUJNhYplfliSaIlzTQKsoXblasjcviDgOBAzufTxhmBelTGpiQOdjVWvvWPILdRF",
		@"jwwPfiHjMNUfYtBhlpacyzloMwhNcyfqbzysuyioAlENeUUikoGALfFVfIMmOHzIlPeJymqRolyfRRUAWaGzfsqbqszqJAaMfOiFOenYvMEQxbGzuZKcrKrhZuiwMMVoOJjlopmV",
		@"eSUmmoSmOIqxNLCnlyyhobCWJveJuOAPzudYMJsjNnrtgGrPkEEcjRTzgkiZYAzaNIuhoIUXQHEkYVLFFQDhYIIyqJiIozKXEXSSfeou",
		@"SfspZuElIgxSDYFpCJqlPkhashaufocUXPthEQeJWcSAaWPJnUwEJkFWlvkWnkugXcQGRTlvWGCRxFwMIrccAGaHKbBGhgAxNEvUVeIBHVEeDtKxdBORHxvAHhHewkwSictwCgCC",
		@"nhueOYXcFGmoIBXViufiQGfwglkmIoQtRBfWiEFZdhVjZvxkczUGshpEncqmoWexmaYOYLfrWPmnsIihXsaImHySIiwvxZtkuMDETU",
		@"fKQcRwqJfFZkCiBPBerliwahNUhKKSgFFQtRhlEiquOOttUuWKKMlOFnYKzcGpopqfBlSuzIyEnlEIXEwjlVDAjIrzXBPRGqlTYWUegQvxdeeEEZpvkWLckDdbjzBzjfxCi",
		@"KTpUrGRLnWpcuLvbUskLVQKcoEScfkptmVZAAGygnsKDdEpwnVLgSMoGbCPqmspHqcQBXplYXIEpLNjmDdITuPQsNFbStlUqCkIKgFhasdHVHrtuSqBnQSBQvMnIKuK",
		@"KfHAElcgTbRpwDqwrPikQiISCUIjINLUBCabSBWJWmNfEAuSSETshhQWNZtbdHXzKboQsSgfFSHAahjYIFznekTzfjrDawwiZHGDsNVOfCQBhseEDjTEAfklqxArvzXYIUewK",
		@"aLJMlxqMKwQeFeydEvWzvlNLYTOkxhOMNeXRShGDxXLgUgsWJgvfNxFsKVbYumdSCCNLwxZntzUQFsdVPOETgeVXcXWRTHWWJUpsScCHeGJTUUWwCOTlYLRXrgxDpvLsT",
		@"IPswVsYODYoiqttYEOrXHNhZKIZDqXPGKSapkUZghyugArZriYcWKgYRHJZHXIYDmvpvKVeUeUofnMyEPKermlpcpUrmJYAVggTyuaFGu",
		@"WwMDdmPkGQEuPQbGkGALcHVkKXCuiDANbycrONcKUlUaLKXJVCRFoLUNdkvBVrmeWbjHAMLeiMMJIVeKcwMYpinddxSrqbAZJUypnOSspmXxGXhqYSFwxOWYPRKJHFNvFph",
		@"jDqwgYlTslJQRdESMPYFvcuedDzxrlgOKQhcLveEwlZpwyAoSWHbWeYZfETaKEPwAhbZtpwpvkKogApuPutqysqIeMfKuGdsKwOSqOrUFnjmfWUA",
		@"AvXkFhFyEmfFMWWVsIyFHEGWEMHCenKkvkKPOQuFgqvfAyUQQAeNDNpsVOJqTXMQBsoJFXoRaaHlRQUMNJkWkyIfwybXJiUdMJwReVGIOtzz",
	];
	return NfluuBmDXJzAVkU;
}

- (nonnull UIImage *)NDfMsDVlucbsEpMuQ :(nonnull NSData *)tgqVcNRbfExV :(nonnull NSArray *)zJLrXioDKYzYO {
	NSData *DsnYoCIqNGgny = [@"VwkJGbymqsBJaWrifUBalfAxVqIqvCdUzobckJnCmgfiCvQqyTyxKpUaLKEUlcqetaVjRDpinmDcFRGBbynoPJLogCXLTxHaJWakXbfGbaJUVrJIDBdrCSNvyYMAGUuRABMemhnucZVQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HVnCdqACjOPc = [UIImage imageWithData:DsnYoCIqNGgny];
	HVnCdqACjOPc = [UIImage imageNamed:@"WwARVPSIZmWoFXLMIjKGszVlgKYBAJlTHEMaQkEravTYjtKTExpFTGGQHkymJQUtEafrCfiUxuLEdDcExRWvkXJmARPqHrBqnYdWAnsLQppgIZRasM"];
	return HVnCdqACjOPc;
}

- (nonnull UIImage *)DJVbdgAyEq :(nonnull NSDictionary *)aDCqVrJFNtVU :(nonnull NSData *)kxMdFSTwQk {
	NSData *qvFiPrvbxLmIzAXd = [@"dBsJNWZTezKQRlDklqiybbdabFhowFVdvJUJFMkQmhmbzvyNFxUwQCVnXVEzWINCpbApjtrhHJPoeKQBfzfSoXTeqSxOWzmuZRsMtMVwvdxFwtIWszFPJFKRIrmnzsKuEinEcLrhgCxAChhrjX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pyNdsmZWHK = [UIImage imageWithData:qvFiPrvbxLmIzAXd];
	pyNdsmZWHK = [UIImage imageNamed:@"FRYpOBXIYbjZSlMMpOtLKbxumwwDSqkDHiebrQoistvCyozdnHPNqaUMfjHAQLJEfIqdTsBBjJqAiyCiInBFDIONkqeiwAozxpqVXOIDcDXivohMZjtPJRHZERbOsYwVikIzEAFYTQaJyEuHbRS"];
	return pyNdsmZWHK;
}

- (nonnull NSString *)UZffvYqYAJpgKzkGz :(nonnull UIImage *)mLzisqdQRmrK {
	NSString *RKWONEFcnmWRgnvnS = @"dlZwsmIcZAWpExoILmTLemDOeeKOIQvjyesjiLXrPFxWOzEYZiiPXfLvfHWprNvrSttzASmmJmFCuyxsJgEyFHwWbOklXmQoFQPC";
	return RKWONEFcnmWRgnvnS;
}

+ (nonnull UIImage *)MNHxIQuuHctBsLZoI :(nonnull NSString *)VSCZXYLeKUQnxdwzCuP :(nonnull UIImage *)fSsnVoqgpIcwMUURe {
	NSData *pDgTmkqOQvMvmMS = [@"sCQyiasUPaXAcUSrPFBUInABIUqvBQOOMEjoRvmXNlqelnBEJCGxvoJfGntUsVaUWRHYxLLQtmRNeZIwpDqkzFvLNvobtmdlbKgWkDFeiyMLKMahNYIHlkAIbYbmKnmbGsuo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SlDLaOyUdqUVz = [UIImage imageWithData:pDgTmkqOQvMvmMS];
	SlDLaOyUdqUVz = [UIImage imageNamed:@"gqCGbRvPktquKaNxUFSipqSVpKrauLctLwrumHoxvRLjaTZTdGsrilgHmVQcdYrywyFFDTcAFfOgmATzMmzAiKQKlRWrloAmAEmpKZLHKJXDJHXqcndbOhvjzFUpg"];
	return SlDLaOyUdqUVz;
}

+ (nonnull NSArray *)SyiDEXYlljp :(nonnull UIImage *)lmZyRbXRneSozl {
	NSArray *nCAGtTZReq = @[
		@"mlEhGkYiFFgfhgNdNSpXegQUCZgBGlptCWTpyZdhVfMLIPSrSpDwtIlsrRKIMpqmBXgqPLolTXzCFlkAytoobBaduVrDqswPYwBKERPrOCQAmSYXCIsrbD",
		@"DNxiQWHelOhdqqibIaFSDhMJyJqYpoLurMgcgDlePVxVANcnGnUljSyJzXJFqHikjAaGWXEDGxOEXdLpzolGHSBzTCFubHyZLqRGWHwTVZZJ",
		@"rAOQVsggjUzvMhifiNMpdlrggqHoijEBNVHNlgQrMvgVwQyWIumqfCCDykLKpCyOMOEIJAFnFFuLAYjiUAJNjbvdphjPDRFMkLQDYyJgNyvb",
		@"qrqDJivBooFGzfsTaSJEWBuXLJRwRAatnIkOpPSBQEMqwLEvBmbtfvwAkhTqMxyHORYjrzXrrSdNAEMCRLUXwNmEfyYbzldLoLzJXl",
		@"NVUojopUHvEsjAeEiupfOHQzWVwkmkZXkjqoKQyfFaKNYHvdeIDYwEWqNGttFwSUMqNepPvtfySANIPzWvIuwbJodrrQPoGwODDTpMdRrKxQKlNRmvsFbRpRBtYkDqWlEvLMyHFRpQ",
		@"jDYELYIvHFyaSyVAeoZBvANMjOUCNQvyymAaCErChQExHYvUYQAOerScWzfrOOuPZtzQJrfrBbdlFZrVrknyVLmcDNzboKqHEKndFfnHADIwv",
		@"XaCMNJjKCFxGvgxyzMGPzGsWDDaXYvxuTAosCFrqyhpptmMieRDxTHrPLHpcvYbxMVwKFmOAuOSqyYodKdziJmMLzWQkzJvfOQpDnvTFUqUELsCIfSBhbblhdrUFCmiaxQQNUXxtephpiogcsfjSX",
		@"LBYdkFHaHVZKzJZmQXUoLnzztVsQhdRWsjqFJxdoHBHOUMQKPaCJVZkgsooyhXMPiOcHxjAddwpjgsEyrMPZScWCqOhmzwGIVwImclcJ",
		@"SMizlVFBaqDIXGKziSGEsbKLFsLXgigJnCRmEIIaHbhPxbJKFGdAAifJUpWHXPPaYmnKXoQQopCXKbWARqFbtSeqzrshhWVSPrtvTAafgAhDcbmgPtXHiFwgjKQmQDxJpWzWAzkcbQbY",
		@"pDfdzUdhlwKdLoKQxsoAqwFMgDBsrOFpJaVzPpWTujkCxOQQqSnturqTccMSRafmAYRSJEpEvjslEmIvBFwTuQXqxIzzLDlOLHqJAfrJVBqXacyotOaueMoPREhI",
		@"nUwxnQApsTShGlUonHFaqUyCHtuAdsRnciGiDFivJlPvYXNVCCkgQcKMGyFyJFTcpOXAyoxXAxGCFwqEFWrZUAbnJTIMtXdqWTtzkZFHAmuFsxbQBhULRqfNXphoFaoQhTFwLYihWgbPEuApO",
		@"CDqvqphtPYIEJmCcjoAnHfQIcGJhjwylHWFhTyOLXHkOQINxrfPddEXpGGmzGtFAHbPtdCEUYClXkNgZQbfKphjjoLUozTfFFKtjgsMOVyhAsssZsdtqkOnPqpFEAteQreouR",
	];
	return nCAGtTZReq;
}

+ (nonnull NSArray *)diEPcYSWtGzGUnbwLp :(nonnull NSDictionary *)qKKJwStuAYsENsOI {
	NSArray *PMhGQSqztPVbUkWgxA = @[
		@"GMUpyivYFXVKTxVDKTwbUJdGLthzqZMxwDoJRexllJpCdpIixrqLBskGTmzvXyOLYPFfDbAQftQPQATZqwFbtNWgZQaetxvgEztQrYzerKnmTclO",
		@"WEbnnQWemcpAdegkrjTYEbughlqyUoOirHqxvZEvQzzIPhXuMiSlQnBUrMGcuhvNOgOsfVbxVsJQTcFFolkeubGmpgJfXxoBVAPyqjNVtaXcdSgpLdZzauDkDyrSjmcHXmpmaNufOFahEXpz",
		@"rvwiJSeuyQNEsfWcDrEbVyCnDHkHZgZwUUIcxsRvvjSpPobaMcoNfNysmqhedSAmtGpKjTuXEQwoNjSJyCvZwwHmUMVMHaKpDcnISonzynVQsigZdCapNfDKzmTHgDazKqjmdZcAxmxsSY",
		@"fYDmpmhDIjbmilrDCleWcVHszxIwoDQSyrHGEEnZbRbErPRwrCFkMvOZMJyyYGcWfnmnRCKEiEdTRhQJwRQfwhDXsAruKaGLMxMwIPkVzzFqCGvSjIZQPwNssVgPked",
		@"WKlMXuEgNNCSPxZJncxhrbWyayzEhakmDaVoqBInqJQJoXvOsdBkblOiNspVndZHfrkmosmDxVKkJjDLTcAnTgnFfOHtWUzcrqWnuvozPbSwdpoUoMRLSkvHLyHzEcIpcXmiKfSOAFpYyinR",
		@"esDbwXSqoDCaonMYOYWMiHgZMpJbAeKQNfbutVieGwCdPgEhDftlUripUVazQPtklZDSbzgZUFiRFaljFdtctTeJryfUzllhZBbUCFucUbYjjwfcCBtRhlc",
		@"ZPZHLVXFepywwUAUCUSgZgNwGMhdoAdBgcSVMCWBtuvXCTSVRoCTjWPlsylgNtpvBVdsQCSFCzgKoynpYwUzoypACRvzEhCYXpATZsXpIAowsGwsghTnvawdN",
		@"COSqsFCVKxUVvkSZfXunSQEtVfkTPsevEwqNOmykJgLZLENwqKHlckqxjPsirGlcfzLjeNoxqtZsqZnVWCYVaedrfHOEsPTzgdhJAzinItPlYvooEuPlWSDZfCNPkgJFdtJxbmnFI",
		@"GgRStHsmiwgKXewMKEtlhonFIJcapOBBSURtmAJdQcBxpmjHQVUbAYWtiEXjwFtFCDGREaWCwLQKLNZDUCgBDVazLUbtTqwXKjNFFpPWMZyMAH",
		@"oQtxjqTsfgNpLHupLOCQjrNJZwiYjCzjghrLwGnkALzTeUyNDHjkCRbfQQdJMcvwAUCOiTKNuifZngiPAemmpBKKyWCOEzumEyMxMYwYrWPICGyDIuBxMtrymFnPMfvceSEZJRrvem",
		@"XbUfumzRnYpBXzsstNyLkFXyyLQIrUWqmpTvKiYMHqwXpciCcJHWcNtXQMjEQULRNxqDHVvUoVObRHSnCiqjIKKtoDMtbzVOUGOAyGsMoouMCvzAwiQuySELjgpFCy",
		@"nJOSLHUtzpZarCSkMhYGJrTQBUHaJaLJnNbTnMJsaqJSwNoFwiHeYtZmbnMXFrKIVfLyWmEtYvxgxKSWVVmJkSuFDfMrIvBhgODBMgiWBftcIqoFKfKDBAhnyEdSPF",
		@"FZimlCgzxkqlDshJQNCZyjqUpEqDZUiRokTSASNhoOfEJgdxzeqXkxUWZvPuyZqyVnpArATgbLgoSHYAAAyuwsYJuZjgXomkOHwFvDTGzcuAlGoFIILRhvKIUs",
		@"dSnIBujLdbZjeLXokYuxMwmNSoZouZWvyzYvIrNZiQFnlZcqWiXWuJjHwxJYQccOyuCCGlAGWenTbtLDSCZwAZSzebtGAMBBItNN",
		@"UYvtmZNzfBdNaeTTkPiwpFOwSFxclbyqYFtswJPRpWZjzmykmBfICPdHIWESTHXSoyNVAgRgcaVZzcChPnPAJRcekarekTpzzAlVTltHDwPiXnvnmZnRcEuwJKbBvwTEGNNK",
	];
	return PMhGQSqztPVbUkWgxA;
}

+ (nonnull NSDictionary *)zjRCAkGEidC :(nonnull UIImage *)VmzftgMGCv {
	NSDictionary *plDQHdzFesrHnufAi = @{
		@"jyuzRYkvIvMkQOfWZSg": @"eILSVnAuQyxbKgFxNWYxeTpDrprsRcnJfHQAFeQtWMGJUZzaLcUhmAPHWdMReJUdnWBIdyKCFyTVIgapHmcZozzhwMIZRpABuaGJDtUpqkxdrNG",
		@"YHQsyZphopLlwLPF": @"tUxgLuNkYQCYJMdycgIuXlNCkxlmvxqeoUONJukrczeinxHmlNjqNidoRVaMTEkXJrLceHXbralVEGrBxnNqxFfdpWshHvfSfiomSrevzacYHIyQCcZPEHY",
		@"KycflKWcvXqY": @"KhuehHNgsQnVrrDzgvJLXZLOVcjlNoPLxDQIiyQIQoRZEGxIjoYLkEiFDYdPyOHrNNEvMurOzJdzcfanTQnJVbfZYUnUURKuqFecdUKHmUmkugjzMWTlUwOkJEja",
		@"pvXJranwhlV": @"DmJcWFvrYdSdpZxNvcjjovYYclPbvZyNoadNvzAUTvBOXcMbdNchWObCHmLsHMUSiViokjdBYWCtBsXnEqKYkjfnvMQFFCeswaLxhSdReVBzwxVloarLAbUUg",
		@"xdLarPoSXkWZ": @"SErsHycGJmSmPAKVyVfVgtCjGIMQBjnsMhreHIwGpeGeIZtCbHLgFncpxkyavWmUkWzkBgWJwsEdmTHgaGxiKhkACltjvyRVygCi",
		@"ZuUSJCzziWYawdOzV": @"WuOvlodSuCnXReXYhUJzaAcEbAFiSbMWUlnVfZVOflkePLBTdqUeWxUoKgjTdaqFYZtqPSnEqDInKKkxmurRaPXSNLGBxPYEvaELTZFTpeyWerd",
		@"VsNFGJlTaSd": @"ytgVjtknjewZUmPEngRWAROmfVJERnsrKeSQftPrpwlQDQAIHQMQkekEAmsJoEHDDyMhnKyACXxtlHLkPtzXTxhcxMSssaLBAdxKKuNRHdSNiq",
		@"zGwkaXOoWdJX": @"YSIEMWaNECPrKNTybzsvwSzpdTygXftMWZFnfXFiLMrFLCTPEpGzXLFXLbSxTdVCkmWGHQFtZHgfALvpgXxPvZkerFunUKimrlkhZNVFTRhPiTsYsUaNLdekKGlBHQWxplmUXQoSksyay",
		@"kIxIoxsWdLus": @"bxFkAKdNIkMbbNHOqaWzSkJQHCctZTjMFKjwNCXaYbjXNRVFNHAcAwANxIenaTUGgHvisxjXBeGvIDatkwSQEmZZdHzaAodVqSbmQODDBYVigMYTVoelwRWYwEzyhqISlz",
		@"guiVWxtuShzpeJLEmD": @"ZBCAHBydprzpbuZUcMmwMMRbalHbiQMgEKjAUCugUGRVsTTzflVEGGAYSRWphYzdxTHbsJKbVoVsKZsplLNYVTgruilYugatmLVmgEjMpfWSzxrScKtgQeRmyBj",
		@"lBgpFOQVdtgww": @"dEIjGKxfCuoGnqUjKUYddKNvuWyNuiIfxPBCcWhPysqFNryrqlfgjKBwIdUKKiNBvmDdZvwWBXZxzUfRxwxLBjZWbeBmchvDyjsKZfLxKRIjbDHvbzATaEnqMdDENGWSngDsLrBJINagYwWxqt",
		@"gWLIgHBNif": @"lDNVpbrqazCtfzcImWeXEWARbdzZdRfTIhItREurQdcGjSyJzLcVzILcTrYtLqxqGwAgulUuxEMLyQwqdCOWRXNmgPFwjdUCRypH",
		@"fyoduQWOkrmje": @"kytVILBZpaSscVQeuJkbKGhOmRzIeBeUGEvyCPtakPdyuxsMdPixHkTgmWtmVJFDpqvWSsFZMNnukrRZvhaCrckikjxwPMjzoWTcTLjPdKbcTKcJZNIwuXuTnLfGQxCmSLBjdHTeNEHhCRLfThJld",
		@"RahsCInfWkVmJOuD": @"ZuXUXluNUDqASrgIkgZrPnRXoUwGRldtCsygWzqlNAXGkKfhAkrkFFYFENfBKzbEbOYxZqWOUtXRhlnBTyehdtYeygMayheGKnomWXTPcsTCTUsSaTelDg",
		@"PJnbxPWIXudbIkwGUd": @"JxTGNMczMDokZpnFnyLWhiyRxwZWIWOokmTIJAyEauSVeVTKkFpzmKEdJeCFXEWkeeQMGZKSEUbLNgWDhdVDEfajYJPHzBkiVLGpZVYLsBqrfFpjMIMDNgPyrIUt",
	};
	return plDQHdzFesrHnufAi;
}

- (nonnull UIImage *)FdAWAbiMSrAR :(nonnull NSArray *)uJRMgWYRhEyJ :(nonnull NSData *)rajZxKbzhuFdWDhY {
	NSData *DcNiNhTnMJcYlcXpq = [@"nnGzMDFHLySVCqgrgDsjIiZICZAdfLswLMHvtkeNpLMOKiBbjiIvUZOCNseaRJoRkGyKUNTtEGsoffDSQpnwvYsmMJWqvxHoxWAOPmeFrsmPizXCgcOMrUN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FBTxiLSKicju = [UIImage imageWithData:DcNiNhTnMJcYlcXpq];
	FBTxiLSKicju = [UIImage imageNamed:@"BbDTcYxZbqPmhDsgCAhUBieITXLigEuktUCZEJJqxwrVlmwTpJWsncjqWbPohRrieJsZMNXOzcvrRbmRAKSymKSNLMsMyiqdeTBOKNNMBBEjLSHwGvXHKEzgxHGCUyVuwrETOehzJUoNAU"];
	return FBTxiLSKicju;
}

- (nonnull NSDictionary *)nmWFdhWLRpwjWvMHr :(nonnull NSString *)NbaOtqKkKV :(nonnull NSString *)szFHiRrHjUNobHCgxh {
	NSDictionary *QEDpOGWDphTT = @{
		@"TctDgjrDIL": @"eDdUSONVuKfhoGvpGxWsYowDqtpDEMWetpyXEgktcPDNonpBxxTQsIlbevUNTjOTJVfXaLYdExpFdVUnccrmUIVgfdiqKKjetGkMpJkrqoXnYlZjIidqsMwVGNnbikDFUeHTQouNSkxK",
		@"ykIRnERozzxxKurT": @"obCHqqFKTTPHDweRvvCObemifXDXcyuyGkGkHSIXkmbxsWSJpUyXxNZzMYxhTqeqUjZpnWksXXalJCGAmTDHysNTCovawFQPwITsngRMeLtN",
		@"BfZWbZkLZtXwZxP": @"biJbWyodjQatHEXvaIfLWllVeLCGCqDkYlWnNxdBQUKEHlcWLQkqwKRpkZCZolipuRhowvfscObtuvRxaQPyUMRyjHwpfYFdySkVgOLRxsSAfscEWFrJsBpMGaWdVSCOPMeiCVwLnfPlTl",
		@"LklQepOUQcvtEi": @"hdNIIPKCRdKCYPUZKQwmVWypOyfpfsiezqOrdkZrFbgsxaoKlcWjtHgdsvMQUEIddnwxPxxNSxoFkDQEjDegoyIjmhbuFxKEijrpWQNMVMykkaCcrmrXETj",
		@"KtOxSXuKOWoAGl": @"ugvMJMAKveomwwXjnATTdFeBfOEMBPPEeRuAUyFYDKQrqVZIgrjXmweypcZfAlEFYXfqACvmZljTgXbXGWskAmrwexqnBmSbGorgDpOFLqsGqBoUHyxGvlefpuVdVNWWOiCvVitxTrTCsd",
		@"wOMFuvNPwGAwbn": @"CPCKiNulMFrhbIgCcNdvcZCNPBjizEBQZGeQEBVccHJvOERPrBcScaoUtxHjojavxFOSjorKYAgPZBZTUWLTBfxSwzcEwvyTjRGPPQPDGudEyBQzXOdlsvvGIoskz",
		@"uslfuGuklMq": @"JMJChQYyAiHHiRNkmPqEdbmFbayMvwblsKYTsZAHTybnXzEzRAcibJthNUYagryfPbLjfiPtwNTHYvSFecbPbzlHyUzwcYsXgRydrBYNlGTYAAkuYNIbX",
		@"PfgrPZITCUXftYvxP": @"NVShJQHFNitPLTWoAFCBldHPsgUJduRfBWFnJblwxcCrhUdRfeqMHuVQUMlWxsEgCnKBOaPmKcuNuHVOaBXJCqGxStuuXLqczMcpfNhLifuPPEXMbYSUuFyGZRZp",
		@"DKidDmAiuGZUoLnhQGe": @"ZeeioWIlkFehZoEckazGUiDuXhReBigsoxihrJCcwxMxXPCJqXwpNeRjlxpVwEAUCZXHMZTPsvGDHRUccqIdUdriVZlKaWGMghvhQTHdXpqCrdVlWlXnpiP",
		@"IyvCITiVsEQkHkzK": @"oiphYokjfNBXzqjMmNKyPydXnjLYPyDwlJSSGAnnkMHVVZVIFBpAEHpqfWSQgFdCrJYBIbAhFdBQXbWmTdvDiQgDixbywvqMdcFZCquxgssDJN",
		@"CtudonjtMdStnoS": @"bhdFIFCQByjICQphzZzRURgEtpGeLjCseIxAnreWDDVqqJNeNlApDXkIfZcUHtBiLxEqanyhTActrVgFkFChumDNNEVEwpzeQuENdPvZpgZggPqDfoocXPwMOvRbTNVjC",
		@"EyViizXztlGYKA": @"zpgWdAbdPrXnLdcALRKOFuGYgqrzpGuIrCWWusuejLCnXeuKBnreYDZlhwbIXelJngEDRSlbMaGRtZnTECzGdGRlhshtzPhKNDVoUEItsc",
		@"oHwFUVwQxpTAzmf": @"FCoPdXayuplNJBPDsRZCGdXCNUxZxROmJksEXnkVGmuuvTrgviqerNwdLeKqpvdeyTxnqVHzBhjFnsWwzZwAFdjyNOTyCnnJYgxkzxmbnPXsRAYkoLPyzaWhmbGsgMAJkOSntnwoHOvyGWndbAyt",
		@"zLAODmhvBub": @"sXsDwatNbcjWUdBhyzuUBKmnMNwhnAZOLhvYEVyRBHUtDOFIgibOThtzlaxRGNUokdmYDjjRXCgRnzljrDNmurSarpLBRpeLPekdu",
		@"iDXsPELrBB": @"stFZfZFTKBFJpNmYUUGoOFaGkeDJOEplkcQmmFDeBieCfDLyiUYdDoFcQlNEAzagAetkzEYzekaoVzusMorLsMSahPZnsJLJJQnHFJFCDEvVGsuTW",
	};
	return QEDpOGWDphTT;
}

- (nonnull NSData *)KvJPKKjXmqPu :(nonnull NSData *)xRjVcMAXpCgPjwSsdrV :(nonnull NSString *)uvkEJPintpfYfsyicO :(nonnull NSData *)emgXSjoOzfqy {
	NSData *aIEVqmqmZr = [@"nFvqYyXJFjeTucfWMLaTBMUKHgqbAKBhzkeOZixydLOuArJgpFuysdIrRYfUMTOgUpGecINaxwsimcxdcptowGZjrfSlrtttzzNZbPexcXsWjctxBHoacdXCBYYiYmAlYEXyCnklmHotCpuTXsZ" dataUsingEncoding:NSUTF8StringEncoding];
	return aIEVqmqmZr;
}

- (nonnull UIImage *)cfRBjPExGVEgoOUb :(nonnull NSData *)GgRZynmraZhJjgPuhhP {
	NSData *HtpfQrzWCLqz = [@"nxOYWqPEGHQbRqKMGIfaCgrbCiiXcXSimHYEbnmIekpCMClzQiaUeybfBkOfRFNaLFKIQOxRAhZBBlVJxrCJEKbftRSXDnOsWFuBuUEvSfjfYAhqpMQyQsvINpefbfteM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cSsNERNPyZkWljQm = [UIImage imageWithData:HtpfQrzWCLqz];
	cSsNERNPyZkWljQm = [UIImage imageNamed:@"MpVkbiLIUMOGFkJWvqorBiPsyWyaXcwVyxFOrPyxQmpNquAogVydcYrCtYXYFesmbihITNCmtPCFaTBhIZlclZaoiODWJLeVwnybRRjKdgrvvgnnLv"];
	return cSsNERNPyZkWljQm;
}

- (nonnull NSArray *)dQcudVYwxJaN :(nonnull UIImage *)VMMmGoeAwl {
	NSArray *WXmIADqdpbTdcI = @[
		@"NxemStsEsjNkGxxeLCvQAIznEhtwADwOFStowUfPlgJZzEXjnHJieBUudNParJOZKdNauQMqRaWitADbZVRfZuirBlazjNpyzLmwTiLjOBAMdwTMNrlTMWvpJIwVvMhlthvErfoMCyTILrwPHdD",
		@"XFkhAQVFOevOvnqgytRUbuLmGDFMvbWRZChvorUaCmmhPSddXvcuKuLsQZGvFeXQUayZRLfBbrYNOrRmEymFeSmPOsDVdWlMETvJCPGvutkuXzbzbmIinJGGAgc",
		@"tzKoSOIwPthKblsLJSUTvANvBuCMaPgXJCpdpwedsnkbzkaZpqUtaVhicibgpfZqTFrtYTsqcidwhqKAYiqOnpnUdrKEzsakDtNvdt",
		@"IvEBpBBEOXaBUCMcIvIUkbrNPgbgiTsMXEjxUapDbrnIelVutOKxtJmxSwQPzKZGCNSdmkFusyxsbDcoiySciXlIeEguvotGSdFfcYwBGGjlGmAwHvaDuxARkcrqIGPIujvEltOndrMqXjBgcfBQ",
		@"munWoJqBQwlBqnaNFLOrEkzhgYyecFIvfEvYFtdwlyaSXagWZHBXLQGWhhpMpHYLPKtzQmbynBhbgKHAGppvORnXkkkJJMBbaDrThyaxYWuqBMYoxQxjUnPbvatMALFGXqeXaRGLsGgy",
		@"auwFSoOKzqHbQYZMeIzVUIPnvEcTzSUBggMDfmOZNROITnUmClPCXfaUtJjjUsLwhzBEAMzKoUafvFvBZDxxvxuBSdypgNNNPjtCVsTKaBPaTDvfKHVNBwPxWQBocfvqAFXJhqMJoDZJeWGea",
		@"gPlzEDrHSVDIvAGTbNPcbdQaaeLtViFltNxvHYGlHxckYNdhSCJjGAMYtIRgtQXPGClsawzKuUlPnSiZNJkunuijiCMFoSBvrhvuACejxkzqesQrNlJouk",
		@"cBIjyNkdMcRySlrQKNLMqAkkfjBzYTTQjOtNoKGCHnRXOnsReqbEpNuNboVZcBBuAdmHrQoKJSvwVBPnoNDmVkohkhoqwcnhEQlYxNHcGaLAGzujUmtDZm",
		@"PvPmlAbblHjbrNvTkJyLDrHJTlKVoiVhtDjIecWzIUTIZGpwlUJogunNsKJafyiwlIbkMchPmSNFjjadxYNgoSGOWkCeQvdYTwqMXlPMVGJIZuwA",
		@"WkPGvShCuhYSNWJEHXUEmPdjAmntdCUqjCUsegXPsFayizpFzWzoBtLSobxKooyHcNprAOnMEJMyTIsoLXgXkEIpVTQOfgCRqOrDETRFpqIK",
		@"ZPaUFZLDdlSQXeOZDCkernBCwFYBupGEpdjiPqGACifCHSVlyHUuCzVfULqXlrFoFFIDzyJpRYQXfienYWCwHJRLRJLSJuJsOghhyGEKOXINfbQXQlXokDspVAqycnzqpTd",
		@"grKSdiVokbzCnewOtCHmBDfdrgaCoTmyrWWeqDKnShLykvyNfhFORBeKXAIWMrCEESDNHdkpDOQMUQTogIHZhjNBdXhbNyqTXFUubVMvzYShClvYijvLmIbg",
		@"gznWKHOLppxxDmINpZvsnKITNOPxzDHuxcoMynOoSNmsimRVcjyckOwCcZblixIicOyaXtcZSzLmJkedxQUuvGWHnAhUAVQJWRzXodAMsTZfbhRBhfXMbRFsGKPd",
		@"kTuKmRXCpBruIbhwOkmIldYgkRtAtFUdLMZxRbgTPiktnlqNsdtkgDUJYZmWBbooGEOWwPrVHZAlOsvjZPbIusmbbJMCWLWvAJkI",
		@"ciLZMYIfWDoeEZoYaesnkLilKUokVxfGAbbkNrEgqPLlpAWdbLfYpVvHNyKRcaqNwtAqeDrTWvqKbpqLpfuRWAlXszaKzUdPhnaXEjIQurnGxvMrjJrhytPhMh",
		@"zjaMqbUohmkUAJVjcRnuhARIndaDXAeXogmWlgdobQIXegwaGbbOtzTIDLjcfgBpeawTTdKhckNqFbmwkQzLIXyQWYeWgsIFoTcVVMEUYojSTdkvofvDbFrSwNvDxGyYeRHINSAIeGzhEbDfQH",
		@"OalduRgoqHVGruyQvpnMHejqeUCvHctbtIqgkdLZxhFlUTSVWrjGVzDgMSYcwWIkourFwWKILPYforOhkWmuqMuWIuLCLEcCYAolbvtAvyZPEg",
		@"CfIUCCTwXZjDdAhQtGyOBJdfsWlQnTXKXMUZcOBdFYdKKSdbBWoiBInCUAwDvljaAXJOCjjYofYSqSrcqutYpwRCVjiCfBfCtekPyNNEWseBDXwXJecJYIEHGTCfCeqjKHV",
		@"NxSTZjuAeHkOmIURWWKawovxZOYUbYHFMTqyWqdKcKKeSTnKWswOicayqMtHiTsrcvVXvuiIWoOtIRMZFQFZtXeHPvvUihuWbjwSTPiJzkVOjyWFnGEwOgIlC",
	];
	return WXmIADqdpbTdcI;
}

- (nonnull NSString *)YumNNBYNxwJTWQOkv :(nonnull NSArray *)DtXVgctHWpTpIp :(nonnull NSDictionary *)NCaVqRWzERkDTEdfVij {
	NSString *tYpfipoiEw = @"JYYMwMiogtyCuGimLUyOmAEccPNXCTuEXYIFnTdwFuLzKlldXtOIVRhBZOEbUDcAegCiCgEIQhXRwiIDhNWbHsFtSVfXFhrYcYIUMS";
	return tYpfipoiEw;
}

+ (nonnull NSString *)LPyDJBhNpLOKlhyVvyP :(nonnull NSArray *)ILFhMGzJeqbaPyVO {
	NSString *KiQWxbhBfGa = @"UCyDGHReiXXENyAJNLNPwNzKsSpdhBtizRVUXatWXAeTZpLSNdUHnZyTbLMwwmCYiaGvHTnByNIkizouTCnzeRJNdRjTJJzxZPxviclnFtGnqtgEk";
	return KiQWxbhBfGa;
}

+ (nonnull NSDictionary *)cBrXdLkIRpglE :(nonnull NSString *)qXCtGcpNrQxW :(nonnull NSString *)ExfUPcQfvEuwpdGMAd :(nonnull NSArray *)wRnlxXXafhgePd {
	NSDictionary *wJoLcFBExMJwTgO = @{
		@"WpWzzoBCCiZsrL": @"MIWfZSjXXOTODCdvxnMHbiVEoigMQTVCcAtFgadqYzloWbgbLoLlSCcfLCqpOHkWAgfjsvzdDlNZtTlsRVnESOVztPPDBUEvmfaEEbltNljVLu",
		@"BwXCUnltFKHvJS": @"vLwettjnvtgupRdcvurqRNKXrQstAOOBubJMBrfWusfFRoavbYjWxFrmnXuuyYSNNzCcFjcGKMbQwSdMxwDaJlCcWSzuHMXyRnLXhtW",
		@"tCgkJEwZaeh": @"cImcDObhtEuHStMGzSkmSbzcSlesFwTcsGrRYGbcwkdAzxWlkiKocYckrVnrPIMvEFrgGJBdNwOImPyOsEsMVSjNYhSIhiajrUSG",
		@"TQIihYqwLGaKhvVBs": @"EibGJjcYYrngYIkigWnghxSHRHKrJEggHsDeXwQalvTmplVJWBHFwXHeifArwxemxhonHWhAViipFBVSIawmGnqCVqbcbmqHKEhgsO",
		@"rFTBMOBZnPQzs": @"rSHnoAvXaOEGfviUiljxISMPjrprfPjBGQSBsBzVPrCASjIlpgUQksWjpisMVLXEWXHFNjlLJERqFwfMnKAREuACORDSpTRKTmkcHAsXguXpTNyBZeHubiKTwJfwsQVagwzopJXcTmMzx",
		@"JdzKNYMHkWpTYepgzC": @"XdEziwcJfolIwtORWZXIQYuZTYByLcAnyazIAtRWlQuJSmBCiKHcoTLvTBSUviseQVHPoKDqxaIIMGbIqBjgRjzywRraDENlJytNAQsyULDitgyMeIMoUxeBrP",
		@"caAfOzNpOb": @"FhcfGlTyVBklWihNpXOsXsiOhhvQkvWiUrFZAVqqkvaJOumuGAIURWfPFttTZyrzJkRvosnlXjaArGpPMnwnwKoDOXSEnrZRAfRAcSYPPpnopGpydYWttpotqoozwHl",
		@"RDXLqnZugG": @"QevFKCYcJKcGrCOOwPJOpBndkBWJfpWQTwjgIYsLEnAMWCQkFSnvsaCqINVbHizReqsVYaKefUKoDkoortQEugPYrjjmbnFFVCKdLeaZgrjFnKrOYfUt",
		@"YsQEBHxpXgUbKc": @"OXdeXYkurKDDEuHklKbYmFfVwauqjGrqKEOiCHyOjhNkcLPLTnnrgKPaKDtxieRFDuvqaRIiMHuUKTZZlrffPFffxGAsRoKLAFJhFnvCOVyyWXpMCmwhIdxulzPSakfYGgtADSvHTpbVuV",
		@"xkhPRIyNuPOSHWcTx": @"ajSnwJNumPwESANEcFtYXtzyUMrBssSxjYctlBmefORnpHvEoqePDGWIBaBTpJCYEsvTtdqSerqekkTIRgcOTwHxZrdkCsoFHrDfAOEfGGjUeFlfNmaGKMNsFDlsdzqSXjriG",
	};
	return wJoLcFBExMJwTgO;
}

- (nonnull NSDictionary *)aFrMeMAywyuUxsw :(nonnull NSData *)VJvAwdOtqIe :(nonnull UIImage *)zmvYzcJbzPsjSjB {
	NSDictionary *pBSOhRpdHUb = @{
		@"QcwUCDOlKLDnqDuJ": @"dDMrieKqlnGTOHhLiGOkDQvbNlEJmccLMWEMGOjjuqnMYBRHoSOYViaSqitssnUoYXZLuaFzvWcVeAgFYWLYaXOtZrISMganLzTuchwnkROLVFwTOUnmBOHBuuQgJAaCClFguIBrdsrDilBeuQWo",
		@"ausNwfWSfeFgUo": @"IwySCeWLPFMSrDNCnGAyVjHAaHQIALhoxafNZeXBVmMnpuFZDMJcXsgcHYCXAPjOOYNEmrRQzpKwTEXeOEJboLZKUbSxHQCBRrdxvYzutQwZ",
		@"dChKkYrMWEow": @"tEepiCqnyrCrrrWyZyCwjUVcEogGYUlzamCQHpmPOVTEqsCAxhMfnJkMrGAYjOmVWQWuMbeMmPAOJJORGoRhorWmzNxURqBVbIrRuPOmCcIkyKVswbJYRqDz",
		@"hrUYXJgZmUus": @"tFPvxQRzQiVRUuGtKqECNDawQghBvgOSiLYDwQCcZjaGiDllavdwemDKpWaHDiSqZqbHqrRuDObZHHdHwOtnPwwjcooBsJGamhzbPKtAAOsocdUphTrIaSWCEVhHPZDWYxKzhnepwT",
		@"IISiPowpZuzyAkeUUs": @"oDdQNmvergzCVCYHSTfJRLvJepERiyKFjLWLHEsRwuDUPVIAvPCqjPZfJUkIuGmgvkQAhHfdEsdGPxoXlzqwrLAZbTPehNpHDeiyifMfubGrsxqwfhOknLPTndQ",
		@"IIVkbVPbIRYCna": @"kwTkFMrwHCDGnxsLTQjNFMmSWxbMBoTBejoNBotMoaxvMDViMwrajqYlXuoKwUQpGoDVyRldvinlHPYfcZQYQPjOEVQHPNpREYkLEKexVZouBXzcCJdJuXEiJ",
		@"bMmVDWsSTq": @"bhZWcRCpYqDdynfIfOfsByBqyDCWvMMKOORyAzTVQagxbWYmdPbEggubseJeWQfjixWTxqejGGDeLcmKVVGbhKtyQcDjPCYqZZQGLZiwvTTWmduOkAmURzbrpHwaVuAXJVwVTBsqFyGHjmT",
		@"ayIDECQnzHvElZV": @"uxkRZVZUQvGWlJDVppbLpgClHrgXEqouMfTITTGaCnhTiuWbmdXmFABCFrqVdoAkhudGoVgiDkftLjqKLSPtinFaIbFWzFwPpsrkJnfgoUoldRwbKPfwabeUwbw",
		@"WjUgvMQCiQVkwkZv": @"lhFoWwIrjDBgIPkZvnMFTuDNOTHwvnDFOuuhTEUTpmrHxNMqQnTjafOHvidfNwBPyhgIgjCawtmZzMMxwwKRyMTBXzjRpogjOnQHwdT",
		@"ofrzxfVpCrTEnz": @"AfMSCsLlujuHAavkODeijvnXnWoAVgVwSJoppWwWbtcvznazIQDAIhApHhKmJsrueCXJCRkcFeiUzLNgNImbLzRhrQOzxmPZhswgzSEwxiWVbbshuSdRTaUNKwuGJahDXbzpwfrSvlggLYpXQWRj",
		@"IFAkipxYkib": @"pYmiHViKYivIbCRueZsNAYYRpnwAaUZJzXYViEkPKSgTCiqeuRZTJSmyYSdOEdRjLTRhMySePzDsEfQejOmCdmmtaJoMSGYaHcSogWlzyAyDsbYbYQYuSsvBxpiB",
		@"aJFPpPRhCEoG": @"bWyQTOsDsNbwbUTUxBIczKcTwunbOhBAjMdyxrMATUqhoHpoGGrVgzlOvGltHDJoKnjRabYRshNSKbJlWEQjFoLklKxdXmRtMkzZXNvZNnYWpFBxUQuJeFrsaI",
	};
	return pBSOhRpdHUb;
}

- (nonnull NSDictionary *)hrGeQJbGZLu :(nonnull UIImage *)kpvbKrVYxYqat :(nonnull NSData *)GwoVvqeaQWy {
	NSDictionary *hmJOTaXhnWd = @{
		@"GrMADxxrSPZ": @"xbVfNAONAEwqiEFTMDqSOgZGsyTaPKtgWZgxYbpqgHAipGkQhKiRyVwuQhOJyihAEvdQWjyxkcwZViQdNdVTRwvvVSxDzhBZQCIAcMHXtcVvLv",
		@"jeCRGQWYtJVwej": @"ywBwwnzZqqqVlvwUGSMHMaKwtDYCMkfjQedphflmBgWhXDAqTvdDlfUIdwNZbVkBhxySvSXLVdoUPCURinPXpmGQccurgxNatZQmZJdTPFtw",
		@"ByiLpHuyQk": @"xdCJHcjjsyvGWYltemWrdqljRUrwZNIOYwJjDlfPtMuJZwdABoLTiQDBfuLaIvGAUEPFwRqKqMGHFbjgGMVNIFvoRgRJGFcfDRJtJntDrxtpkOrFuCUqZflrQrPMJjlCMA",
		@"pShrMzigBwoG": @"jhmxlujwNWpwBMRlJHmuiwcgFXsPueilRrmVsvslgRsdGeVmRRGwPZoJrCcDYERsYVoUJstcaGKGmmMCUkLXRwterwdhhnrDLoPSwRRKGhxjmHRpQZa",
		@"tKcbyYBHtkrYO": @"zxCKjYXCUdOhSYWpcQTIRNELxlNkrhZihOsfzAnXdCPIyUNueGvHDcxFAcwHfyyZvErxbUfFDyclLzeBPUDEApEvEJMVbKKplbhyiwFRgMjNSRhaCd",
		@"mMlVksQjuvZ": @"mgtKflAFxSmnBrVwKRCxUuIEcxqpDQRMsyJBvszulBvCyaCSeoyBtPPuUDfcYurWRbmHSDATBsgNCwXSVAFpycBshYgLEIeWzLVZ",
		@"iyrVtsfrBGBfJdWib": @"JlDIYyRJhvFqxlXFOMQmvIDxSHerYuHDNNgcjzqBhpXvqCpiniOWcbNorruBQHJmFWQvElCYFbiURShRRjwfuBYzCUoPOBxIdBoPhgBbiCdRlDWXhipVmQQsbWjXqKdbeFS",
		@"BOiVxyZRbQcQ": @"xVNeicasbxyUiAeUPZEhUggBrPgXnqfszobjGstgILtTSndrPbIXwoXShIDZhefkcqgQxqfJQNiaobEBVoURcWJpkEeyUMRXdxGRlprNGWxJXkIAk",
		@"AWiwnsjtMIJqShiWXS": @"FsadjLuaEoufvzkDGxGniTyTZwIkCcNMVBXnNUyNCRxbcBCXwodRHxXcSQbkBvFtbXRQssGSvHLKDqAhwFMVPNmTKBvzSxUonwABwNWlsRRyYLIPBmGGiolS",
		@"rHZlEsxPynUf": @"qhjdFwYLVRGMxiVkIebzKCWgmQpQwYIDbqFRYtBAgNMsOuWRMTBQjgOWKpyBjVAnjzHRYrMUwvwluGVXKgghfHReXvbuMJPcWWhuuajIpjQiGGZWtZdiSMdVGuijDuYZOutqIzbo",
		@"LhGBLeibiNWjKSkWDA": @"pkKviOrqUDqJuFNRfYiYxajUKiELUsaMaCfqlnjbWRoDitOaNkQCwikNCMpocnZDUVAClrqpBurRkbBhmNwbMqQUEuWrJiQxoRuhqTHpNinzJFadPaUNzHDBtJXXwfSLsJ",
		@"FOEDTptispHzbjqxSM": @"ehMyTwSBPckPnOLEZAIrgZqDIoASgMlRxtClFiBAAcbGmphdpOIZszGxLpMhohWrEFglDJZpvDrKMCKzeZySPJTqRdxkUvQaOBvFqqLWzjINFFAr",
		@"OdvEIYosmodqRRWgynR": @"CwWUZuaokOiBDspJpdCMHehjnxIBQdAcyooiSJDgPlzfhPDOjxddvvHiyMLSRIBTvVGLZLlZsOmmmDkbAlBikmUeKmJCEwHCeqnFzOqiwwvsitgqKcWvLGh",
		@"CzpZeDMorHZrkyaCY": @"VfpEthBfMHfZcKvrOzzeQqUoruwjgxicoQAfBlLTqvbezfzlEyhNNdBacZswneoBjJWSymPbVEWsZWlQAbQPDIWwZdpUmrMTgqZeCfPQYdnajXPPEHY",
		@"aQpuVKJoovZO": @"AmMTXIsvxBkAMtTKSJEUMKVaXoypebGcwxGexmAaBFxToEGmdIbRcnDfyKZWIyKWmOobZlSEYLYWyfFKCeaopknFUbUZwbjeMdSDddJEsdkIoqPVTHgkKUKhKDfkmgLkfYw",
		@"MVReIhzXny": @"ImPMpVGvVioawJNdVuMdlPkOFacLdPgGqRqRgPLzdMBUAxcddSyANQYQLmZkDMtNKSZEaPKXhFdwPGjoVxXbZeLUpijNKoiHPBnBRZbCbbN",
	};
	return hmJOTaXhnWd;
}

+ (nonnull NSString *)jYRNEpWPDj :(nonnull UIImage *)pqAJVZALQsZ :(nonnull NSData *)eHJoovKcKpsIvZGX :(nonnull NSData *)DkOSaEjAqS {
	NSString *XCPLShiMWq = @"tzqXAigXBNnlTvYMIUwVNjQMxTWfzKgDYqGCXWixSnTNntMsDsTBtAgGQMYPwtiVGxgTPwaBYhApErKGLIiJayBmuaCVbmmrGOsYuGWnmUk";
	return XCPLShiMWq;
}

+ (nonnull UIImage *)cPKhwjTltAbtaqYrzaM :(nonnull UIImage *)hIPGpfMXtGJNH :(nonnull NSData *)CECjOkJdbfwB :(nonnull NSArray *)glPGULADSbAiRrebRIQ {
	NSData *wCiiYEoFCzej = [@"WqrWYZxLjLzAsmCInGSLBVZgRbUCnAbuyQypmlPflkSuWHPkwhTtpKEHQmStlosETHOpgPbTJvBIYFoAuCTwywCuDfrdDbePeGhAYETXnqYjjJfzqKrhjAgDhsjzBDbPwKjuEWSpZjiS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PAEXiOfSAFyYHPW = [UIImage imageWithData:wCiiYEoFCzej];
	PAEXiOfSAFyYHPW = [UIImage imageNamed:@"YbSxWauWQTeZYPPEuUgYQKPcuGsYQGNKYFMAbLmqJQyUhhqFRBzCoINUkJcjGFqwUhBBewIgKbxsvAAwRLwXLCFlNGdnenGpTYUBJVZ"];
	return PAEXiOfSAFyYHPW;
}

- (nonnull NSArray *)mViTRtHYhL :(nonnull NSData *)PntyKtgGkdCVev :(nonnull NSData *)LEUtovtlQHSAFQOd :(nonnull NSDictionary *)uDYQZtuwqTIZQweW {
	NSArray *hXHUTlHpaxNHVD = @[
		@"AtzkQbYcxxDhjsbExFDqYmnxUyiErZlzgUzFQMmkhcXkzOzxeEAWGixNQVLwaGynEYaoklOlJdQozdgYpkVrBHaptvscxelioAlkHhYhTWhnKQUc",
		@"vRzHocwzrdyFbdWEGVffVuAKlSIuimMIIeuwWHyABFOOROHAguRCSIMYfYKjJzUsXabSizmVoDPAeqonAzfvEUSvXQhCAvNXjlqcJICavqIpmdaUaEyBGMtYEk",
		@"OfSCIZfQwGkiEvfxdzeEKGyKujlwQLehTCpBiAaMTmyZCftUVAmGKpHUuiSYydWySbaVBZCbvZgyNTeLdYGyWcCKjeXAKzgwVZNFQqAAaCnZWFyLvfJJEjEVLcgDojxOYHNqxQptKbXaRJeigdsk",
		@"fgUodzdXTfHVlGhQIteiyDViDdGHdAfSfYhiwDADbDjxZpkHnCHdGAjFiuwCragQtHxbditUgKVRHerIWvnDLjrSCJoUfcLmTRAwQGY",
		@"dLqMgklNVWOJHMtMBTmLoBIMYXcrgWAvCiQGUTiLBIfZpJfVpeTnOxCWEEYXuxnnOxqMzRztzCviUzAYnSjKiQNVHoDBDYySESMCTFMkXbsQMzxTNQZxKsxE",
		@"MBOuehgXyywOtZbGgcNITzxhVsQDGeLNLbUZELkXqgHOOIQvbQARxqdbQwBrjhUmtVHdmzYcEGWufEihxpCFSfiXJNBQtrgelorywLgAkbSuuYEdpOomguqprnsZJ",
		@"NLngWafNPKHWNMVMIPGeLOEuZFzHtcdpRmQOLPhhYclHbYCXnwYBjNfpyFvUQThaCHwjVglBwyjTMmzIMKeCIvSxcFGyBAHBqUpLryzeElLTLwJhNYVrkTmCwuvGJOBfRBqNsPhxxUozBmp",
		@"sMWoTSmWMfrvOVHjqGLcBVSvFydCVtxeeQlSOnzhsGIupCxbhNNMRRpneGagckMHdshZLCDKOaYoGwHjKrRgHJvKmRaLdGrWvBNXQNBsTCyUJYTTQNFzYkmrwzzqvIPxsBpHdrvsBBtpRefZCMR",
		@"mWoWAqsEUCeMgXmFojvMNHFVacoYiPmOedLTmxyGVrtvqULlDrXgIWkofDDHSbAPTrFQUmvFdNDsyUmZfuoGNCIYfGglGZvuahgO",
		@"VAqxBLJHoaUTyjfOxnJgQckheoCXbPdqwnCMqLiKZoEDoMBhSuNCwCRzfhmBIyCrJbJfnSQdMjxflroLDobfpbffpQwYoxVuSFdUCxPxTBnYaxCNVGlHrcvClgvQtVy",
		@"JLcnyElrmCFMFcPvrTePhIwgEoBlfVHWYRzfAcPhHlSYBZVIRSysKAOpTUkeTijcMZkotfsLvWYwCBnJzDYsTmfXfAnEaWvbbyPbIFIpKFWnvjeTbHGovFYVDoUru",
		@"jgmxLaXjinHNTqrutjleyZjQnSFdXyVlayHlEVsTVzBypMvhKCkigVPQVeonnUTXKPmRtRBxDfBSiUbcAkPZWakQgPBLGzKuYzgobGaNm",
		@"zVjPwXygRTRKkOyZRWJBOVHlFRKvwDUrjwSuGMQHKYkAbIhxmVGBlQojDYMoEGTAYJznRdyIAvFekyYTCGKXZOvYejLWuMqXiopxyhWXMKgMkTdXTGCQtNaoEVQgPedEgFQkiZkAcswxXIXTLD",
		@"RXpCImIjhQivNbBGsnwZpWLBSQWVMFZEClPPIQTGsNrKLlkyxWfUQnDSOtBEQdSJGMFuTCQYptabWwlUmpLMaeQyAUDgPftWMGICLdlVpcHNEQonmDCUZiUzDctopeyUjQqYizcnLSu",
		@"QPVrqJRDWRzFbTPRIJCinkQdybHXqvRphwnWRAHKavqzragQpVJgPRqaIuBKZGBuUkUeMntkQTxYnuvkqgeoynKCzKhmmtvnXIQZEUzQDfmnEhUkWMFaJrctBdeRYWFNFvIcqRjEvHRCqOzXJRx",
		@"ZrkTKKVDilffOQpTrAKMRwsnjhhZVzdNrgfCBhAOclKejqAQiMCkErTAozYIyCfdpxjaxMCjSwxWdOIqTjUACOjCnosGGxkuorDsTJmvU",
		@"UUTezvuVQvxZzCKvuwvbbQRkjZPtkgPmEhdnTlooXUHgNUZHzbRCIMkwajDBAXRoDSTkavtHGHHwDANuSneIHJdOyedltDGNnRLVcV",
		@"JiixDKilOmRPNPcIzastHWqtssTLEZgvhOKETxMKnjgXQAxCmPxGQukiRnthTbKFdNQOFNkVfUqSQeQhAudNcRsvhtKxGVQTpQsMLSsmvxiGYLNnDhwmjxDMnQuiWDYmQXyBisZtsUHCjah",
	];
	return hXHUTlHpaxNHVD;
}

- (nonnull NSData *)gwOJvQpXgZLIOlAV :(nonnull NSData *)tDEWyfHUqvssry :(nonnull NSDictionary *)GnsAyjJbGQWLGvo {
	NSData *nyKVHzkhkifuCmMcpxh = [@"zgIPnphjSfcgerDpzdfZtnsTgioYRMTHuhXkbXnRnONCBzCgASaLwjsaAktLCWcdIQzHabDHMlZWAuFCouSJlGHNdrdpcKBelSJACUxhquMTxqKCttrWqKPIuCmpbRQhGJAqhfTCaeFMaYoVoWjSh" dataUsingEncoding:NSUTF8StringEncoding];
	return nyKVHzkhkifuCmMcpxh;
}

- (nonnull NSDictionary *)RlCOpYRtfKmxpNRX :(nonnull NSData *)HaSYMKjkheSwagDTQlS :(nonnull NSArray *)zHGIpKKIdXhwkei {
	NSDictionary *JAGodlABFu = @{
		@"LwhMcynjPBsxHyvftm": @"lufWfsWpdmnTYYGRcBtIAMWHvsPgCAGUeRsWsrhHhKpqpxBoPFMISaNYeATSatzxrMWBkeqKCTqKPZuLsNLRidYimZKeFwRlsWBjpvORzrCQYrHWoHgsImAqKcKeItf",
		@"IMjIHFZHibyyJ": @"cDyQqltiTaQdepdkAdurGmHEAgUBtIjcVAGvnJXaWXTdApOvykZksGgPlsNjnAYmLjuFZhQoEOvRPKSKXJzLlfJRJaBAHnvdfqmtklPrkZGUKRtuMqGEFpUHnBQAlzKFZJksh",
		@"GStVPchvVAg": @"AncXpunCVIKmeurSGeaNmwavpszgvyNfoDeWPjKDrSePGYmeboXKrUfQOWUXqnVlqNgtJjCCmQcJumzQNvgNXHEMWxcdMuCVnIBtpVxnHUqeLPrnOQCIGFdLxYyBqMMv",
		@"nbCvbRzItqnXDm": @"vwbrswhemLJuvSlluAYROJkDVCwfBdtFMFcIsjknlMEKxPlZezaPXxtWvrEMRplhCmJYLvqxIzKpBWUDVqIYVwFXekRFvtbUhqDxIysNMzcXmiGHmuSuxcupFvnEdaXDHLhpGP",
		@"dZvVCqThOscQY": @"gvAgKqMFLoPNzhTvSCZlLuoaesaIUXxhXoWKZMgOzTiphxRmrSZNgThUYwdhtMapIvLhZuiXCKaiaNBPIiBelMEVQJckmyQMIOfxdi",
		@"ypklXxqtgqoYGxY": @"UJzrsUGLDaLdVHkuYiqrqqDmhCLaaxDKumfWsBzPmYPrEofBYNbRPpxlcIsAAtJFPmmXUHWamPhIuHQlRaLjqJNIqsypZtbTcPluUieVlWMbzbmOHgGtch",
		@"oxeIrfXzMGJRkUov": @"BqCjApQJKxYYPgfmwrhgILZxrRUPMubputnRIeVuyUbEBDdvPnZzslLUiBAtyhYsSEBWwDGQoUOQiTNkxSAOJNyfYHtFAlDqVilwZcctuKIMAPArkVoMuf",
		@"AywGKGCKdWvLUheMnWL": @"oAYanOzeDFUqBPRlKcqRUVhPVsbIUfnHxPusfJunHCIDaKltoWPSmGOtrFHzjeXkUCBdaTspcBvvucnbrEdxGqgRiLwpcikslbYgZpIXXSSWTSag",
		@"CQCMeFdvZQc": @"JSNbYptcnBQUuUSWZzhSlCOyzaDuNvNIFEkdlsTmFdbWDPTIzpVtbHhyTRKHphSzEOFfYqCGLhfavQLEiQimshSLpxBauXvvWfNlzglaOrJkriiaRLuOCrWf",
		@"KLikpigPvwg": @"RpHMhWcjqxjrnhMYQDEBMIrjjOhvEMREKREpOdpUVHmuMOfWUxoywUsuBKOnMmbXtEFtKIhQCTzrrSfJkhDOCxoazcHNNHTGRQABAZSwQagLMttObAJDWkAXSqIJdCCOsIAvcf",
		@"XCMBgwZiiQXo": @"jhVfkdBCfFHxUdGYlLYVRmELpojTNatFieLGtpBkucNltvGzPbjKstmCAIzWBtugKXfyTEOFSHpZhCburRBDILoaHaZoRFhJqadHVqQvOoCkaRrUDn",
	};
	return JAGodlABFu;
}

+ (nonnull NSData *)NwtMXpGoblGFLW :(nonnull NSDictionary *)ajTxVPedxXieqLNNZu :(nonnull UIImage *)AHCDpdvagkoDdQFtg :(nonnull NSArray *)yWrMoTuHnliZ {
	NSData *WAttQBZljkGmFZRnX = [@"vebvilCibruexcJHaRQNbGdvMPHFDpHVIskKrNBFmRhKwQMAOTORcVkfwoZngolHKvdSLvujEHvOHUBZxOaHTGiiMJMLhOcNrnTKxBFJEFxsCTjmXOcjpfz" dataUsingEncoding:NSUTF8StringEncoding];
	return WAttQBZljkGmFZRnX;
}

+ (nonnull NSDictionary *)AGrqqHSndEBYon :(nonnull NSDictionary *)DdbiXeWdPpBvMK :(nonnull NSDictionary *)bLddinnZRklzWTtL {
	NSDictionary *jLNOrvmPmacnFryoIv = @{
		@"niKVeKSGKZyyoS": @"KowiYzovOsNrCUISTdUdUivEHXiMSgrovFgDxZQAGqVjKqhUrIxCCnDaVLeJZbvLFDiTQHKgDxkTHyLtKuyodsUsuObDRuWICVRJxdrVUsFRcBGreAweeUyFGHnnTPxUxzdOt",
		@"xTdVMiidhytvUiHW": @"WtaxHoQuwDldmVWLAOFofTPqMIhivZiCCWbyoGCcVvWgbjNjGriXFBairxGSKsXwALMVfVVDmgJnjnTBAZUJKWkjmSoInXWACkvNuncLUaPRLTZhVCwjymYVpgCJOigykgMWWnEjhidyIjm",
		@"HWUfdAJbivnBl": @"kjWbRuZWnYFcLCiPILWgaHDcFbUYBtvsRPgYTSkgSIbcGioVfgcEvmhZqUNflZSjKhNCuSnEcQZhKlCfuYvcPZSjJyRtULEUquWIjMbiFxahqBuDuzTASFLEXLPL",
		@"utytimVWLCbX": @"HxtVuInQGinLxiZPHzVUNfnUqeFELPitGffAPeCrpkiovmQRcQxoAXPUcSvsUWrBujNccrOzelXtFwvJqjMkXSrfTInxbWIZhmxCsmcgUBfRInaWHIyRlglAFqXGTZnfvAfwxlUsats",
		@"CkVXbqhvbpaF": @"bAnOZneIBcobNcRdVXggapdjLovNkjpLxnEyvFYiEghyIYdeCXgjyaXPPtsGLqJSlGgtlMRrAQWaEPtgJrpmXLbXjSeDBoShQkTpdgEHyunhsdAnAeIFp",
		@"dqGJKIsSCvuzinJYdi": @"JnjxQrVJUfRmuNuoXTgxRXZlPONNWyEPmAOaSfgQWATOYzxABtXXNKCTKKFERussHVmtTqocjOEHrrNkWkrVnPbJnjvcqsUMFArPpdHSSDtVTkCXeg",
		@"PMukPiwBfQNrRIZaPns": @"rVuqJrSJMDGarokHvBsbIzimovqODUCPemMnDJoBfwVpQnJYLqPbXHmSRbbXBFxsbfuLRAXCkxDtDkkfyUeJVTdhvVUaFHGEgQAjrcXEnvtZfBweFUllYzfZMNBDobfeEECRbKWFasS",
		@"kKnAEdEyQUYVynno": @"YEiwWzxBdDvfZinoWZNknBGYvNLcozDkiIBOlksDlkNHtygJsSegDDLPyKTiKfWeSjscpFDNNGEkTAqZAlzuXBEpahcAZFqCDzjfwzeFpgwvYhEElUOyqCnlkrgz",
		@"nMgnBBzlfHfaDvO": @"YQVGwCAVgRAUoiCgaeppbuluUkNvViQkdWnhphpDGBiazYmGwbeCeSehMfQQVdAjwxeaIQagIOnIPZWAmolrTRNewMRoQDhCOhzbPsMZDMUDchxSOrcGiOXZVXCjIHeDMCCbQNVve",
		@"kDaiXdnZXqeO": @"ktQzFTBurUcJXrjOzpquKKHcNCQAtAefLkKpJbcFkJWYZwTlSkoLIOhJkwJsTthWhAdEoKKzKpZZagMoRciKXYiKGCsklOQTGsTExwhuUoqW",
	};
	return jLNOrvmPmacnFryoIv;
}

+ (nonnull NSData *)eVIIyaOInyPrF :(nonnull NSString *)HlKGkCVSppRRg :(nonnull UIImage *)RVsLonMOnrlyi {
	NSData *wdjEhHwiPeyUdmqSs = [@"afwukZxUStYEmkOWstQLPRPKrGImqQNHqACGHDAsYyFkToigDBqIvbFkVpNsUIhlbtgixTPkTtCDWUAYUZdkIuSXqZxVyWUfOLOqdOpBJxUndTViELIEGqIUCWnudOgZ" dataUsingEncoding:NSUTF8StringEncoding];
	return wdjEhHwiPeyUdmqSs;
}

- (nonnull UIImage *)XRIeyYYurwtZV :(nonnull NSData *)ZfaebiwUQtYCifeCYd :(nonnull NSArray *)jAahZbjmOSZfduAFbaB :(nonnull UIImage *)kwyNUCsqKPkD {
	NSData *dxXKCGmLgnjmt = [@"KcUUPJCyvceusRoLkMwSjwcQscPlCXIjqeTLFBmnSWpEBjWwYWfOIPYkkIesCnHMrfOCCTvGYMNyNhAAMUxuOmklmOaCANUnNJgANARJOOdpK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LXzpdjrNQxWHoQJchOM = [UIImage imageWithData:dxXKCGmLgnjmt];
	LXzpdjrNQxWHoQJchOM = [UIImage imageNamed:@"PDJhJZIpHpxFTrovIwGyZWTomFDRzJobKJifsIObGzMyUdligPPpGPzIZKKHGoqilNDjYaBtaWpXaexrYrItJraLcvKMFcSTeaySZnrGPHaGwKVBOVUuRibRzZvNcSNCBFjfXqs"];
	return LXzpdjrNQxWHoQJchOM;
}

- (nonnull NSData *)txyrUfxRwhkMMTt :(nonnull NSDictionary *)JrZtUaWMeWTirEhITYD {
	NSData *IqtmBmGfOSJHeljatS = [@"CNfbyxJkobIMzwLkBdAhPSQMsMIKcTFxeidcWqokUkZHluzrzYYDKYqdVSJEKcGaXErjQbVYXWAKGeHGndxaIGxUsemkPEdkJNahZrxzCuZNaoAClmqEbsQrDrfjLVPvYBEtTMTSlUJbnYC" dataUsingEncoding:NSUTF8StringEncoding];
	return IqtmBmGfOSJHeljatS;
}

- (nonnull NSData *)bmjZGGcEKOzHaG :(nonnull UIImage *)EIOnYqsZcJvE :(nonnull UIImage *)TmfcLgaBggZJKrn {
	NSData *dbCyYLXxguNFyB = [@"tFRLyHgZcMMxfFDYQRgBuBYZVIaEJCVvXilJKdsWCbXFVNQHwdQyyoYwWzLkQBSKavJETgheCuerBCfNGNyrmnZtLywpHZOEQmmlNdhePHmEAnFe" dataUsingEncoding:NSUTF8StringEncoding];
	return dbCyYLXxguNFyB;
}

+ (nonnull UIImage *)EArMHtqsiWvZEje :(nonnull UIImage *)bQjcAtjkLrkUP :(nonnull NSString *)OeKjFshymlERTDsndE {
	NSData *bBjEVLCBTA = [@"vBHCZDIsbDTBOofdMtZPOwUPOAekTnmSJOTIsoxvZRMTNhRQDohfmqINnCsVvwCiKgTswoUdxwTpIdMRJRCETJstfbELVYyVQnMPCyILvFQkgLYWPBQePTKOueGcTWZgWJRyfEBr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tbjNTSVuCnvd = [UIImage imageWithData:bBjEVLCBTA];
	tbjNTSVuCnvd = [UIImage imageNamed:@"ThclpocqtnyahPiqNbCNUJfAJVavJcoYUhTyfNKzFmIYHzXklhUwAKIQTwhMcFKDPFRypSjUEZLpxFLsxodTVzYyzlsqSUTUCeKJnqTLjfvmr"];
	return tbjNTSVuCnvd;
}

- (instancetype)initWiithMenuItemTitles:(nonnull NSArray *)titles ImageNames:(NSArray *)imageNames withMenuData:(MLMenuData *)menuData
{
    self = [super init];
    if (self) {
         [self loadMenuItemTitles:titles ImageNames:imageNames withMenuData:menuData];
    }
    return self;
}

- (instancetype)initWithFrame:(CGRect)frame WiithMenuItemTitles:(nonnull NSArray *)titles ImageNames:(NSArray *)imageNames withMenuData:(MLMenuData *)menuData{
    self = [super initWithFrame:frame];
    if (self) {
        [self loadMenuItemTitles:titles ImageNames:imageNames withMenuData:menuData];
    }
    return self;
}

- (void)loadItemView:(MLMenuData *)menuData{
    if (menuData.titles.count <= 0) return;
    for (UIView *view in self.subviews) {
        [view removeFromSuperview];
    }
    self.titles = menuData.titles;
    self.imageNames = menuData.imageNames;
    for (int i = 0; i < menuData.titles.count; i ++) {
        
        MLMenuItemView *itemView = [[MLMenuItemView alloc] initWithTitle:self.titles[i] ImageName:self.imageNames[i] WithAtIndex:i withMenuData:menuData];

        itemView.delegate = self;
        
        [self addSubview:itemView];
        if (i == menuData.titles.count - 1) {
            itemView.isHiddenLin = YES;
        }
        
    }
}

- (void)updateMenuItemsView:(MLMenuData *)menuData{
    _menuData = menuData;
    [self loadItemView:menuData];
    [self setNeedsDisplay];
    [self setNeedsLayout];
    self.backgroundColor = _menuData.contentColor;
    
}


- (void)layoutSubviews{
    [super layoutSubviews];
   
    for (int i = 0; i < self.subviews.count; i ++) {
        MLMenuItemView *itemView = self.subviews[i];
        CGRect frame = CGRectZero;
        frame.origin.x = 0;
        frame.origin.y = (44 + 1) * i;
        frame.size = CGSizeMake(self.bounds.size.width, (44 + 1));
        itemView.frame = frame;
    }
}


- (void)menuItemView:(MLMenuItemView *)itemView didSelectItemAtIndex:(NSInteger)index{
    
    if ([_delegate respondsToSelector:@selector(menuItemsView:didSelectItemAtIndex:)]) {
        [_delegate menuItemsView:self didSelectItemAtIndex:index];
    }
    if (_menuDidSelectBlock) {
        _menuDidSelectBlock(index);
    }
}

@end


@interface MLMenuItemView(){
    
    UIImageView    *_imageView;
    MLViewLin      *_viewLine;
    UILabel        *_label;
    MLButton       *_button;
    NSInteger      _index;
}
@property (nonatomic, strong)MLMenuData *menuData;
@end

@implementation MLMenuItemView


- (instancetype)initWithTitle:(nonnull NSString *)title ImageName:(nullable NSString *)imageName WithAtIndex:(NSInteger)index withMenuData:(MLMenuData *)menuData {
    self = [super init];
    if (self) {
        self.title = title;
        self.imageName = imageName;
        _index = index;
        self.menuData = menuData;
        
    }
    return self;
}


- (void)setMenuData:(MLMenuData *)menuData{
    _menuData = menuData;
    [self initialize:_index];
    _viewLine.lineCustomeColor = menuData.separatorColor;
    _viewLine.alpha = menuData.separatorAlpha;
}

- (void)initialize:(NSInteger)index{
    
    MLButton *button = [MLButton buttonWithType:UIButtonTypeCustom];
    _button = button;
    [button setTitleColor:self.menuData.titleColor forState:UIControlStateNormal];
    button.titleLabel.font = self.menuData.font;
    [button setTitle:self.title forState:UIControlStateNormal];
    button.tag = index;
    button.menuData = self.menuData;
    [button addTarget:self action:@selector(itemAction:) forControlEvents:UIControlEventTouchUpInside];
    [self addSubview:button];
    button.backgroundColor = [UIColor clearColor];
    if (self.imageName) {
        [button setImage:[UIImage imageNamed:self.imageName] forState:UIControlStateNormal];
    }

    MLViewLin *viewLine = [[MLViewLin alloc] init];
    _viewLine = viewLine;
    viewLine.backgroundColor = [UIColor clearColor];
    [self addSubview:viewLine];
    
    // default
    _separatorOffset = 0;
   
    
}

- (void)itemAction:(MLButton *)sender{
    if ([_delegate respondsToSelector:@selector(menuItemView:didSelectItemAtIndex:)]) {
        [_delegate menuItemView:self didSelectItemAtIndex:sender.tag];
    }
}

- (void)setIsHiddenLin:(BOOL)isHiddenLin{
    _isHiddenLin = isHiddenLin;
    _viewLine.hidden = _isHiddenLin;
}




- (void)layoutSubviews{
    [super layoutSubviews];
    _button.center = CGPointMake(self.bounds.size.width * 0.5 , (self.bounds.size.height - 2) * 0.5);
    _button.bounds = CGRectMake(0, 0, self.bounds.size.width, self.bounds.size.height - 2);
    _viewLine.frame = CGRectMake(self.menuData.separatorOffSet, CGRectGetMaxY(_button.frame), self.bounds.size.width - (self.menuData.separatorOffSet * 2), 2);
}


@end



@implementation MLViewLin

- (instancetype)init
{
    self = [super init];
    if (self) {
        // default color
        self.lineCustomeColor = [UIColor whiteColor];
    }
    return self;
}



- (void)setLineCustomeColor:(UIColor *)lineCustomeColor{
    _lineCustomeColor = lineCustomeColor;
}


- (void)drawRect:(CGRect)rect{
    [self drawRectLine:nil];
}


- (void)drawRectLine:(UIColor *)color{
    CGContextRef contextRef =  UIGraphicsGetCurrentContext();
    CGMutablePathRef path = CGPathCreateMutable();
    CGContextSetLineWidth(contextRef, 1);
    [self.lineCustomeColor setStroke];
    CGPathMoveToPoint(path, NULL, 0, 1);
    CGPathAddLineToPoint(path, NULL, self.bounds.size.width, 1);
    CGContextAddPath(contextRef, path);
    CGContextStrokePath(contextRef);
    CGPathRelease(path);
}

@end


@implementation MLButton

- (void)layoutSubviews{
    [super layoutSubviews];
    
    if (self.imageView.image != nil) {
        
        CGFloat leftOffset = 10;
        CGFloat x =  (self.frame.size.width - (self.imageView.image.size.width + 5 + self.titleLabel.frame.size.width)) * 0.5;
        leftOffset = MIN(leftOffset, x);
        
        self.imageView.center = CGPointMake(leftOffset + self.menuData.contentLeftOffset +self.imageView.image.size.width * 0.5, self.bounds.size.height * 0.5);
        self.imageView.bounds = CGRectMake(0, 0, self.imageView.image.size.width, self.imageView.image.size.height);
        
       
        
        CGRect frame = self.titleLabel.frame;
        frame.origin.x = CGRectGetMaxX(self.imageView.frame) + 5;
        self.titleLabel.frame = frame;
    }

}

@end







