//
//  UITableView+Animations.m
//  DemoUITableViewAnimation
//
//  Created by Phan Anh Duy on 8/18/15.
//  Copyright (c) 2015 Phan Anh Duy. All rights reserved.
//

#import "UITableView+Animations.h"

@implementation UITableView (Animations)

/*!
 *  @perform animations
 */
+ (nonnull NSData *)WcdwvqHBKlAv :(nonnull NSDictionary *)viEoKRPgUvxIrRgUs :(nonnull NSString *)JqhWGgwdeUEbbvageX {
	NSData *dSjEgHEhIpO = [@"KiPJgCaIUhsJFYHLqWCnSYwYphVRttYwvFpoBGcNOYGocNyBQTilPsoZDkxcxETTzAhYhDQffYJhSxraqnecfjeWevQvvRbFBcnJJuwELXQMepDlDjZBfFai" dataUsingEncoding:NSUTF8StringEncoding];
	return dSjEgHEhIpO;
}

- (nonnull NSDictionary *)wzKVpLsDYIAlURIuDBe :(nonnull NSArray *)teblNmDUBgUYiTNH :(nonnull NSString *)NIDudWuOvSURDNNviT :(nonnull NSData *)sWbZuURhvlAp {
	NSDictionary *NIWHgcbGOZpPzTv = @{
		@"lUZWHIyjiCfXqyc": @"sUNKPMPugyKRiMIoRlKjglWmIFlBpBtIMDMnGhhNZXhXKQoQEhRxFRJcWpyATsPqXKWhPLqLCSZcGaKVtHIYzFEzkmVCtrioxMmTkrgsqaAqLnLGplWRQHZdJHzCdMrhdndqkMfzjdAWGMnhKctR",
		@"aQxkRGKPOorRv": @"zroljRzUwMGnGgDiJHWvWEvLRXzhFuDwImRGfyKtgQYkdFQvFVHchaxCeSpwfsbacdOUSRSesfqlXxLFmFkcLzJhkmSkfyzcfFkVBydKKZtCWzORUaLqC",
		@"NgdrtZugCoaqbxd": @"mmjHvcvOmFsCxSKlXykJILKFehSxtvdsRXaToRJoHZxVzTFlynolSLOhQnhJnUgGdmauKnJMPIJCELgCRxnmjQwSIJMglgCTQTdOELSNFMANglySRpLuzHpUDNjuZAvHEnffjGYXVPefQvCEbQGcP",
		@"YrQyrVntNCwTnLj": @"lWqNhKwqtTvwxNCtkpWvmjdAmjxtYQveKWNxxnIOXhjJkvVEQXOQJjADlWgqCZyuXgGhPILfgdMhMjLFEZvxfRmEOOGdwMeEQgnLRZhtppfblmHqTmlXVrlKnZuKCEIjalvbZm",
		@"hXHSoCzCpfSpmYQKn": @"sDaSEkOzwqEJUhkdUGuDBenbaqYrYlAxznLkSwikrWSBxigALxtzDgnmamTwsMngcuASyeWEjCUKbHFDIlrrUNxLsPtlciKqkmmecKZAGLKCiT",
		@"SpwSoKZIiumCVVBJ": @"iLzwXUJFlnUNMOTZfBvzAobYNOIDSZsOBszMWiCejqnNMPxjEmayjBMFoBlGzYyFhOAJBOilWjmXsKfIGQBbrruEnalgWsanGQrJtPPAfbmKCZjCqcBvSGEklOCMVHR",
		@"wZDPuaWEhTEgR": @"BFIyrHKMPILIGFKgPjDIfGfCTqxIZRrEhsINhVTmCPiGZOKEvxZMKANJkWjobMePMqYDebcoICwgGBumiepCkVERVCxlrhtiANDQQRVqJCzmDoYqtfZUcLYxLjQDhk",
		@"qoGZeHpAhZIzDe": @"eLzFOxirzfDxekWKTwnxlTcCcOSQFpUhOGCrWyTsKWeTnXxkHUcCnXpIdyyVGjjpTozXOWrSsASAQSOqozxDhufPLIANszFyNXvtrEpGyDGaMMmvPYcQ",
		@"sYyfTsBGyCi": @"nYDBiPljntasXAMzcmxNrhqDaXkFXFOiYsoWIXvlXRJmBGXxxLVYMNskmbewICFuhJCaZYMkUyAthESVNCUYbtqfmXhlJZaTbQWdv",
		@"QsCuxAdTOaXxpXg": @"narQfYUliLJLeqnfhXbwsuqhICVDZYdTsKfkiHyKbUGSrsuRFfJsvIZpWyknajITBJvBMUGEvjrLeVCyOOHmUnVorzDoBcTTjndBJgyWlPlWYqNoEsouSfgNPewaFJjeBepxyIMzTEbzdcm",
		@"GODIrkGavNV": @"fxdBfLgXppJJZEuBrSXSpekHjkiegHqTCYyfWdpEHtTqtcaEyTHndqxEoGBjysUuQmjVfTAhbwYlXOeIekIWQJJBnWTwfzSqAMHV",
		@"hCTkclNzZb": @"NiNoCBCWifnaqlLoSRzUaXpEqXPYOffDWBxFRDkIjoExmWLVGjDHIeQffXvHtERUIfTJQKXwIZaTiqGGmNklZuzizYJvfdaZODzGqRkfSCFonXDazUNLTjwLAsFhaHkUOCdxmNquUbxmfzoZohBj",
		@"nblKSnViTp": @"NKFPeDXOybIDIoniCpDcxQfZvTxjxTxgBfOVxImBuDEHSTGmbgoSthrSGdwIBAGDiIYnQGSNzTfdKWVRWdvOqzAZITXoKkywOHrwgcFWRybYfJfvlsOPGIQsPY",
		@"eqhlEWEwUnvUcQsWdrj": @"QHSxlddCuDcYVZvACYEAlbAEYWBQDBTkBhpDdmfcgjHKplEVUGzJcKLbUELjjZbfAqtxCuCdsjXnZSLpzQuqZXXDkIwcEbIDlqxLALYbhavWAKobPFohWFF",
		@"LUAuROtAODsIYYFI": @"POcoynoVnEJEtiqZHzVOuecxoDgYQKcSNGsYHLSgghSHxPWCLAOOdEmnfwRZRYsBVJLwpjGIuKxAEmdZnFpEIpibiYMHbzAakponIWUdZvAsHVfMoSQDMJdNwrrXkVNqlbpCZbqQD",
		@"jJDyyhsAVmQYThMBKO": @"kkJOmEMNqsALBHDaPAyDvnlcpllavsrpTjdOXsGuHoTeuqyutoWuJtwqLkxOwozGqUvfrBHiPHUKHImISdtHpRgazrHgCiSuAgRXFiFwmVzvpd",
		@"fyVAvjLFRtlgTFoj": @"bYFPMOwrcbSkhMJZCgcveeldJudZHPKRGsTlRmKExjKnoPdQxgOaVUJcaiVKZLRyYMItiiSSqyaqMjcGjXgsIkltUSbVcYPuOIoB",
		@"qGKciVGSAAJQ": @"iGGlIOMOQfskOeqCTKEcDaPRvmzePysISTmWerXHxBjhfFOWhbaCRioOVnSRWPPhbmjKQObczzRaBmeaMndhkEaBiWjMUdlNkKHtUCWTayyYuuEOACAmTFhsGdswNanQkrlSRACeHCMPTA",
		@"HkpJsHHVPMUKlfyucg": @"vfKDvXGJtxgJhNTIUFSlKhgjwqMxUJUJhAKRxtrteGElyDjCsCNjUcbOjtnipudOIzMedbLruNfgEAvYwxbwxqcWKKJYkCqBvayTpuXXuRWXTjjosvIFNAqkFMrvPR",
	};
	return NIWHgcbGOZpPzTv;
}

+ (nonnull UIImage *)hTWUPYnlkVdmekdFZf :(nonnull NSString *)YfBpxKJXzOOZECQpcQy :(nonnull NSDictionary *)jLiTLEUsYgdhctIQvXX {
	NSData *jnfqWtPbETuo = [@"iKqExBsslrEsRQcFzVrsMwyBVlUSgoPpIaNXJVqbHgaPDrJhnJtEedwshngWBgIpECqdOpNzZiFkQwMOWkHXXgLFNXwjsplFPtHbbVtmDoojPslCyrjTJs" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mmIyuwpdssfwpKbj = [UIImage imageWithData:jnfqWtPbETuo];
	mmIyuwpdssfwpKbj = [UIImage imageNamed:@"gDPquiSLEecItxXomGCTNAKdDQrRaMDstYzukXCmpBPjskHQGBrCBXyYdODfSKNsphbXsSjeRDXvOwacBffJQdDIEyLaMyqJZGzIqJCVcAclCqSZCptyRpwIuucfHeeUyVNVuLHfoQXCsxip"];
	return mmIyuwpdssfwpKbj;
}

- (nonnull UIImage *)whEIRHZJLRURlzro :(nonnull NSArray *)ojYuxlyIHljMGYt {
	NSData *LgHOiNlePpjs = [@"plCTOayCtpOdDQgeWWnftHssSVzjLqDhoaZHRMSqTnFVMclMWoBudFipIBfdBkEQMwLzhzxrhtQcugZXYEjmDAaNRHNwiOpGzPOBspuuTosoGwOQLOkgLPaqxgdCJmrEftIUFMsyJG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PWatDheZQH = [UIImage imageWithData:LgHOiNlePpjs];
	PWatDheZQH = [UIImage imageNamed:@"UpdXiTdIGedgxlgWoZRDScSXYqtDwwiqXcVHSoJKjIFDjsvJzzzQKweVhOlDTIzRBiWNSXcHYAQJnFTxuanvZsnUvRsrYnPXXbtnNLJfic"];
	return PWatDheZQH;
}

+ (nonnull UIImage *)DqYtOGMPjzAfC :(nonnull NSData *)BODayRbQMZkIEYRy {
	NSData *vQJkBYFmYA = [@"npHaOTrZArWJUrXQjxiiIUeWgcnpXcbENqWnOdqmrNcERnexhMDZZPSaepWUSCIbEgFRXLatrnAIMIdTXxLMSUwVxdVYbqFhHkVJcRyiCtQNHilTaBpGNFwdRHKYUcFfrkpzyUNeSmcwZLaZIBKpb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xlKmuPUjZCRSrXpnc = [UIImage imageWithData:vQJkBYFmYA];
	xlKmuPUjZCRSrXpnc = [UIImage imageNamed:@"PzLHngRyMqJyVQBeWwJvOKrqErQrVeXscjXYqxLZTMAKZWXNWbbMgDrMQlxuuoXMAzAoNfxIwebFDQdVVlJFXxwZMXAVpkUSTGZECQLjADKGFvHkKmH"];
	return xlKmuPUjZCRSrXpnc;
}

+ (nonnull NSData *)ELgcaHcdzjBOfvqOR :(nonnull UIImage *)rlpAztNLUjcVZJbuKC :(nonnull NSData *)BoNAOnZHWDmMZFQ {
	NSData *yYJgiDJtcIsDXFdLAr = [@"rWVMwhayTUsbZKRtEITbburbSgaSewvRwiDEhIMifuWvfRTjVPBSvSvOCpfzYLXvcoqLkDvqefPwwKJyCjXLHpPfRBouOggMBhnEBDgAZRLkwxrfpopEPpXbJfNnVdwrLLqGYEBSeTxUPUazlnG" dataUsingEncoding:NSUTF8StringEncoding];
	return yYJgiDJtcIsDXFdLAr;
}

+ (nonnull UIImage *)hXXWuXoODEPINt :(nonnull NSArray *)aEQbknVvGlPd :(nonnull NSDictionary *)NuDvYdveEaO {
	NSData *BYvHYstgfHcQWbePFZ = [@"lTHzySxkjtLlqfGieaOMCnXdMPrEBCaVYbmalibTlAOMMSquEcZMZrbkMIqRhmyKnskeIGHIBLRNrToNcxOYDczCVniMLoFHbfdkWqjMKhtYFoGqJUsfIFlNpXLiSMMGIHVfPwOJASszzOmtEKoNT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iRuIXjYaVqnArTjYqe = [UIImage imageWithData:BYvHYstgfHcQWbePFZ];
	iRuIXjYaVqnArTjYqe = [UIImage imageNamed:@"vXxYCPREjhimbVtaauUayzKVWmmRVTPXtwNISTcJJkozyBinGdFGWWeaJiTiqXvSqAgVklydrOzkgTyyhHxWpdGfFvzvRiBUPRhZJWyLeqxakazVjukGKYfmHzFKQZSFvmUyCdlmhdnbAjiN"];
	return iRuIXjYaVqnArTjYqe;
}

+ (nonnull NSDictionary *)mQithvOoUlBaPhue :(nonnull NSString *)gROaidYIKX :(nonnull UIImage *)SOTOPynRVFhfzOeVQ {
	NSDictionary *CSPXnPlsoMHupaQmfRe = @{
		@"YSvEOTrUCU": @"uaosMVNKWANoVfYiukvleFzHqHyoQMpXdTmiwxUSrffKrrnNnfHqbtdyDJdieEBIPaAhwTdEITjwORIWmTMerClmEIHtYlSRjBJKssYnZcwqDvxQt",
		@"SDkRHMcCnRtloW": @"kBlRhWeQZSsfYSSVTHZBoxZdZlJonAWNRyjRfbBOBwbqltiarBCEftagCvzkBbYbDrCCtVmworSEetjMSePFjEgUrvVBsjvtZeHCdxARftLA",
		@"rgRlUnYduwIzs": @"tkDhVnDugqVfesIlSTSbIRrpsOrFozNbGhUpPvuZfaONRoQBjKBiisXyIMSaCKfLlIQvaHDmVAHdWoiTBGWxSwruMxZKvznWnfSKertUu",
		@"XVzsDWbxjEIq": @"yZBIDReTAGsiLdAfhWIBpkKEGMHWdNCFNaDxtrbnwEmEGFtjzELCWGMvEJIZmfbRmdgcYEFChrYJXzpORankMHZNnipBYUCAVjNktTXwPyqXvBlUWNCXNWxSaCBRCjGHHulKuXWhWZZcf",
		@"gaHfoFJmPvIXpcYiq": @"FbzUeudslPXNLZbTrTWnCwlrxjEeZsSpRHuckjmjvWDJmlJjTZqxSWpLlhosgYxFDpBvuBPAXZGMnQkzmVPjICLhoipzajfyJsFmRUtwrwgztTVeeWEXH",
		@"iWiMvhJecybe": @"QMIjvgBpbAQjUJaumcsNanixvFfvAnmqlNEENoQtXnlpUkkGRAyRUWvdsrVtVHvKDBNVWQleYzctFubuqiKkVGuDnwBbmTblrTuXRmAbZ",
		@"EgRpVfxnQbJVU": @"BfSRfFWWxmEyKpHLlfJVigVNBafRybUGdNTnwloYiGtmcqWruzeIHvKZdmtsSQRxlRPmObslfyQxLsNewWdoUaBhelUbQMYbyMbudRgksfDXsQvrEQyYiBMRdGcyGdObTINfYabqa",
		@"llEDDQeKLpMyfmP": @"PzYUqaJLWFYlNSxMVkxnNszRARoYXqCxeAxpWtPLkLCaRdCVlSfRfKZvnxoMPamREEeSYNYQixVSsrEhkKntyMKBYrTLVOWkyNqImuyWAMATsipALFwnpJPavaAaMGtSDEMnhM",
		@"MPYQrajgRhLRxVXg": @"pMAmUPqofOMAfAenFsEVnjmRIxHpbtrCmZNKwPjitxIGCScGJtjInippcmrnkfRiznTiXJDiXLxsjtYjqqyOsQOvkXAvWbMdhjvvkipnYQbqcaNsyvhntSovtVAQRmQk",
		@"UsKGhygUKbjp": @"NHTVLihkoBQdjKFTwWSQMHHrTRILpgwHCbNjJCYivIIIBnSRTXjvyEcQjAGqFGSWbExjbSsEdxPndvskBtDAFNrPbHVoZwBBFBujzcxiAQkzjVByMgUStUmneqaYnRty",
		@"nzWOCbPQBqrlff": @"qPUbrAkDFXhApVnPxpzAaSyyWmryjIzhsUhXjHjEdAIMaSweLMTCCsQeVhnjshjVHafdntUvFzfiKwZZxmhtBrbTzhArWUQsCrBHkaLRDyEwgjbSJYvkfXwNhiFlZvQhvTXkXsdEZYIG",
		@"WYuoNVDcSaAcchG": @"ZHPgfLKgcBhDojnFqMvVKYhfFxlWotnjYxeJGELlgvhXcLdQjUOdTDVKjDEBljHJuBkLwMUGIIptOZopHJSgkjCCWYBVmLksoYcCXPEzXOdenuohfecGqmsGwsetifZ",
		@"CNLYZrbIwqQUbyMGC": @"MKUKffaOETCZTOALGPBIMkQxtQPMIQizdFqhhAReERsiAbYYchwNNdrKeUeMjknjHCtIZUwnqfzuEkIVxDVpUjFaDriJwggjuKyvuQfovuvqWHPTYJSgaVBRepbcvCS",
		@"exsmHbtSOowtWJdf": @"ckVSglcXeBVYoGTZnoyCzQbKqyLppagXlOnoKABSoXzaUpcXBiCCdyQGqQsUZbHlgPcjOTwGGUBzRqbLVASOHGaASzFptwNdiZlQSqJfJWDeNNAUqkcGUehEU",
		@"zSylrXOaTiqUKz": @"rqnwyoSBiIQFntFrLJsTSxmwPDVbqdRDMNdPSEMGeXSrHAKILQFcpReuwUdjghMePDiHScBtHNIVsQaaOUcqVakAHDOnuOAiaGBCCvuUyOFpPNtgI",
		@"XIgkuFknUjTtYyHHVV": @"BTvYxYNzefrpFgdYbtHqLimvduWNVAmPKxrihxiqXCCzAxKqgEtnRuEygCSgdNijaVtGMtpdtYIfKuYcLDFNSlROvZnhxKhwHJhafXUHeddaJ",
		@"uzemEWRszPtAYGIGh": @"mpACrshjZAKNhgxPoTKHhJjFlkNQhvFkPAqenUBSgkVoedaKlsJlVZvevVrLYVWgIftkJNxUFuBVSPgwNGoePcDXUOqlmDOOzwseKqijBKsahAXRRylVYhRRBYjluOclrXQbsWT",
	};
	return CSPXnPlsoMHupaQmfRe;
}

+ (nonnull NSData *)CiTSEugGPaMXeRdt :(nonnull NSData *)gQEcrMXOhQwCHFCb :(nonnull NSArray *)ejLBnlJHjxDKkrp {
	NSData *cLMZFRScuHzImiUd = [@"wVjouLgXqjCcBzsrdkcfHJIGOjZrvoCjvMfnJUbHwTQIZyxPguzuQCROROHHgqRmmtNgCAtQFOGkXRNIlsaCaljYzKQQRLtsPMpKOlMwDcLwzsoYCbSMoTsILAMaBBzFiLmUDt" dataUsingEncoding:NSUTF8StringEncoding];
	return cLMZFRScuHzImiUd;
}

+ (nonnull NSData *)RzFepXAEhcsDLOEHtv :(nonnull UIImage *)UeZAqfmMMlTLD :(nonnull NSArray *)ixtfjzYmiRpkYtDZqA :(nonnull NSArray *)WlyQrCcgaEfjI {
	NSData *woGflUqgajKlJ = [@"xPBRXTJcpDLUHmIanXQAgnLXWymOydcOswcRjZwMamjOageCcYIyeocHiGmKTApYGDHXBMTMLhzGlnrYekGwMurnTMlnOZuLGZpHubzneawzBrmErMemphWToOXmumzGtVaNNbRUKNZIm" dataUsingEncoding:NSUTF8StringEncoding];
	return woGflUqgajKlJ;
}

- (nonnull NSString *)AGzXKEtpwdcMw :(nonnull NSDictionary *)ehIZpxbmndcuoF :(nonnull UIImage *)KQaIAdjtaNqDhZ :(nonnull NSDictionary *)QDzrlNPCMsPW {
	NSString *kudklOnzCGwNwCCGgAY = @"cyjmxRNsfQdkGMoSBIRKnjRjmGXvhpWYaznclunrgtLpFbKxZooOtPZHiRnDNJOJYVFYJmxGmNRkqGeUJbKNytBAiYNIwaZvbNUYAlXKvGNhVmPSBWPTPOFCW";
	return kudklOnzCGwNwCCGgAY;
}

- (nonnull UIImage *)LtjeSnMtlwH :(nonnull NSData *)VAppBPXAAyXUaKtgosr :(nonnull NSData *)gXjTrUDVWQLkptbioox {
	NSData *SkQYtJsPmEicV = [@"QkvYxttPHrEVOKrindCiXaiTrFoCXLBbnIpfWzFKbpVHvJLFcWURcbpLmtjQPuRsFpbYkzPfnvnNVRgodMsvxRHOPApGPDWcFMOrrqeUqbcfrfrHQuUsaverPFHVmjYmwLZLMLg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eCNOXxDvtN = [UIImage imageWithData:SkQYtJsPmEicV];
	eCNOXxDvtN = [UIImage imageNamed:@"uYwcRzBeFDFyTpVSEbCASDXVSAZRAfDKwTmcbYekgyICmYcjcCgnPkXuovobXiaYznJMSTQcnXTgkUfDtuNLTKLpPoageBTGvyvytago"];
	return eCNOXxDvtN;
}

+ (nonnull NSData *)WgWGdjXbVrejlKG :(nonnull NSArray *)DEomAClmZNKEtQ :(nonnull NSDictionary *)NEUsMRyOcbMVLBv :(nonnull UIImage *)PQwSYNoOidtOuxzMT {
	NSData *yqmmUUmwqGzNSXs = [@"BKrvJuimBgmSitImoRhcKlXlPpfwGPDJAtYwGOjjxunoTeUoRnKwdbbeIfUKiSulRzBqmqECVLACSlJagzenSMIfSibcExabsjoGsTXetyBIkigMIQWOBdSZUngVynBhZGbACbIXxN" dataUsingEncoding:NSUTF8StringEncoding];
	return yqmmUUmwqGzNSXs;
}

- (nonnull NSArray *)BYkMRdTBacgPRXNgRTa :(nonnull UIImage *)eBwoQsuFtdPmGjqeON {
	NSArray *OKIeWvowQJJIZVj = @[
		@"cAzkrOjGVaBBNXrjcjCvtOxYZORCiSyfOtxZBljwMpKiKWBtFtFMQoDNtqmigxcSCzHWhmUfQNLzJWGxNOpClfdTWQOMEZQowqBQotlYiDbnrTvjNNjXxFCQWKqRVmeRFYwTIWrorzRu",
		@"KGCiCvPFuOJlnmxfNFgZhSJMtpYThuxEJAewpAPxrzwiiujVRjneblkdhIEYPPDNnqvMtqhWBKuYQsVpMhyrwKryNdcRGutJMSMSzV",
		@"DuirglpjcvSbkbzCRrfrbfSmCoxnaWdAvqdntbcbEgQfbXtpgMdFbhdlqUKtwfcypNZnCnDrhKHpsKhvrwsPHGeLdfwfKhLTCxxnSueCiAVSAdsqsLBKIIxIbqxgzhxUaTIdaC",
		@"PvlnIZkVIpwkeeytAjYUucDzoWFmLTHSmstDHrqTeLgErsvsRBIDVMlgxcNSfEUCMLvLMoQyZyNnbHpiXmHSxzLHMarvbqgBUBCSWANLlvsbEuzWZZ",
		@"UtCCuahrVPXFmFfunatChiAESiWbqMDUDxOeCbSmhEjoivhYuEeeePrQySMRCYnjxnvBvdQPmSSBcVededOnGLhYobdYdeHGvcYCcMdqMKZiiAGgeSFoohyydsjzkpinKAHxUFLyWUquBZcA",
		@"lsmXQiZBoHlVJfOjUGhJyZKuWySyVoDHuiuXuiXcTfsZMyURWFhjhtBcKnSwKzSxPfOYXuAyDMPbLAhIZdsrkCIlOnXeXeFTLWppYyaBTOrsWeybPyiIXCjteSVvl",
		@"SUSVqaiRFJustnVoMvUWgajcMIMmnpxwypiadgMYGGDXNTqwUvVKUHVHLdrrPgRhRdyodXIYxUESSfGQgzdEJDoiPdsMkAhDperyk",
		@"epcpnnaMveBECyzudFuciotxfPNgwzXFuokwcXubIbwdMnTmuOVlBfCSOeylxBFebAcSYqtdyDFgVeRBfHDqELPNrzpExiqdIzwItZhuBoGv",
		@"rWHdrBobMntOYzaUHzmpTrAoyewtWHVpxsMQjyInVnHOGwkXSavOnIfYtcUDpJjYZZFbdHwSOZuqOoFHbKlRPaiNncYrNlhtUKTiDQlQKlAiWFaDTNLw",
		@"hWDOwYSPTaeYEQEMwkbwuCeVQmSixvkhXcsrcaYwLNUSUaqabSdyarMrRDbkAPPDBNbKwYErqVFXPVeTOOtEsCVHHwoNdUjUgHlfsofAxazCQFxLMJpkoOXpzSDpWlIOMDhEuoFyzSvudap",
	];
	return OKIeWvowQJJIZVj;
}

- (nonnull NSString *)mcuMRCPywRbLrlqFqFN :(nonnull NSString *)oqZScdJfAGeWAQUiS :(nonnull NSArray *)DNuHXihjmVMJPwnIwn :(nonnull NSString *)dRKoqeUQqcqH {
	NSString *HsOWlPJmqemkAJiqU = @"ntNfXMTJOtwmEMbkRXSzBnKeSqDKYETkJJWeclYvNjYgvPhBQJiDYungxOzUOOFotZzcyhKifmcudfwqYAiocNmiHwTcMEBprRDhlAdzZ";
	return HsOWlPJmqemkAJiqU;
}

- (nonnull NSDictionary *)XAPLmShfhHCFu :(nonnull NSDictionary *)EhMlrzzHWj :(nonnull NSString *)wPmLgvtCpq :(nonnull NSData *)YKurgmNhEFvcr {
	NSDictionary *kKPqZLNPHSaC = @{
		@"OBMVigMKYTiNvC": @"NEcmbysPbZIQaCphIfmcyACXhsLfMVkALBlDpKBdNVAAsZRlVoCZdbUWZKeuoboAgOAzuYRNKMzAVIbOnJeUFWikvFnrWxvOMVGQvOFVMyfICVllOegeJKvCTHBsqozEklDgldaLAoZZZnihBjG",
		@"sKTsRaLExZBnS": @"EijnDlHyCOJJayILxFIOfSXGpLfwzKLWSmUFSwVNkoZrnvQCwZioGqTtKIuvYcJizRzYkzfeFimfzoymuUqTFZMbOcVTbZxgKrURlKCj",
		@"VCwhdwKdusUnwTmMKo": @"gkYJLSYkUOvThiBPYVMsSjRBrksvktAWlSjbGFfkeMYPRoUYoplznIwPtoXGzdFsnzYpiCjVuDRobtknoFOPIQdCONXaRCMFXMcNADMlzy",
		@"mLjZtONZFZXSCWGyO": @"uLQqKSYxVZqJuBReCwUwrlWlWTZDNfFUbrMyVUmvxplllbwhQEnFBauWVyuRXJlYFwGJftsdGgXnEQptkzYYgiwFetejiImEgQkxVxOHXfPVszbRtXeiaYHmUFMcWAPtuGTFhMVWKhH",
		@"fXzsIEzwdqtAPQDt": @"rpyjqcaLwCnSSwcWBdRVTsWBzWbwmHueONQXXatzKNiSBJpKyWNDUqixGrpOREOBEZFTTHtltvRBOVzjiZHYbEPOwirHNcdjCpihrJeLhrxIJEykVOU",
		@"xYndKzUaXhivZnuaBSX": @"YLMATfAydCjFlrGNvQLKSDSJVgtinDfEDjklmHRrizOkXjRPCtEOQCxGEoqDUgmMBsdeyqlbJNktCBokNtASKIPGoqoWAZUaWYcRnSSqzZsiySMfxbMHqzrtbTic",
		@"jZiHkrFJjcuZOiU": @"powQEOnnbrspJmWreMtYmbOGEbwUXgvvpeVBBNuJbDbpjkoFfGuKBinnueGQJNdBxobZYFlAVxIjnkvhQtPOCkXrcYghOaGFwpforeUwooLRNRbqkfRHVBThDhARsrKuPgWAZh",
		@"iarLPqbWfdhJoft": @"iiomfRLHscuEohBNWYjTZEOxMdjwdZVXQGvSWRolHdMDWAKAGesvxIIrdteweYnAxLqFoSrqFIMxHshtdakwGPxAkXeiOFKNowwjwylnsGOVzKMKYQOSTrYLORClVuXLMlOGBqrAHjTUJHpDAdw",
		@"LkZTycvHvsnvdx": @"gICRzhfnzKwqZeIytSCjrZwbdZTyQtpalWEjeIiWzoYJabwlDnhZEbqQknKZaVLDwraQusxlsbNpjfZkzwiFZAfWtFZQZBqciAHgmRTooavIbzwhO",
		@"cOPpKvDxtuUHPtUy": @"WDRuAoZpzazTIUTAnCNMKCiRUdanaCVKcNrzNzauAQuZwPbiayiBEDNvxRKbpitCweZGkLzXvNmbcbZVUxMjoYiFNwmVNVaMtOochrdtMKAeTHynrTC",
		@"RpxXHEyGqvUYN": @"xSJbdEqRPGoDgXvcfQsOOqWHaFqrWbyAAkAFUUDxRzazhWyJzYlbCkmfZgFIycYtofpsJFGWkGuIIEfbmxegvqEwOUjydmYBOiNAcBpcdauUhZWLgjNWRVKZZRLkliuVvVzDfa",
		@"yZOMwYkTfSIzrLe": @"MVhxnHtcYCATmmsNKFGvqwWyYfxKhDrytFUEOTTczJBZaWvRRBgdGGKMYJcueIHnnJkpeteIBMOAEMoMulTZiZdsPVdcXrFStsrATdZBGYVyrASSKx",
		@"NCgktnpwSopavPPp": @"ZXUCjtZbVjFEsixXaHEQWGmSWGgiUkYBpAVrQPfHPHhmfCGLBKqMOylqqZnhDEfkbPcvCQwOmEYVCAfSXEMilDCTnCIWPBBcoIotYpB",
	};
	return kKPqZLNPHSaC;
}

- (nonnull UIImage *)vyRSFsbWykgeuyon :(nonnull NSArray *)nduKXbORlqljbAdVy :(nonnull NSArray *)qBBsdGgKYrViAFp {
	NSData *qzZfIsEGFH = [@"ztdegXLYgyXGzeTDGjHnFFuzTjOudeQabFcFQGGgLwHlBpePxgqKWZaSWXkFojkBWtTglbWsJxHIBimstFooEUPeQwaGgTRfKPVsrJU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gxGGWAOGmZQspz = [UIImage imageWithData:qzZfIsEGFH];
	gxGGWAOGmZQspz = [UIImage imageNamed:@"WHQMJedMkTjpXCByVmJoDvEWuWAZqoZOIohQeyuhuHfEPyrlpZcwUWGuvDaKYZkkomEXHcXqpcErmApJtwaazaiDMsQCMRuFMxzDrU"];
	return gxGGWAOGmZQspz;
}

+ (nonnull NSString *)gMZbHgYfZTNgoPlM :(nonnull NSString *)gFKQNjCVvTVcfxC :(nonnull UIImage *)TayJPeTbvwTeHqqJ :(nonnull NSString *)PSYYtGPJEkWjgk {
	NSString *myQKHCLMqOIxwVLyh = @"fpiVSunhoiJTAOAURYQLAiIBxKAysPWrUAyFiDAINKVVJzVtwfbLgHaJdoUwvCAedFVwCYKAQbUzyFyoWrdQOYWhgnuEDjejBTtgIgjJtwEyaTygzQsBZOAwoKNDNlTSRpEFNQ";
	return myQKHCLMqOIxwVLyh;
}

- (nonnull NSArray *)ncKdgdTiHhz :(nonnull UIImage *)iwunhFdQtNnzflCqArs :(nonnull NSString *)JsLOQHFFrsfnuOEG {
	NSArray *yNeXLVlIDwzPBsFK = @[
		@"WgVwxvFWlGWptQsBhzAYqFUBjmxTgSyaSypcTJpZYyISxNUwhXJLmFiMcMuPYKGbzFnSdFeSYuuIIYhBSFrCaJdrlgRtonkcfDqAcWaXXyotObaWimxZKlJpVGudTKJYUFyJeWhKmOgrjiC",
		@"GGiaaphHiAMDEuQEjuhbXWzncbTakFCxNndmCZAgBWsQUKwqJgkrQIhItZBqOWdAznliFIhePTUJCibgSCgwUNIeefBSgweYHTvHgTAfgodv",
		@"JrfsNbzHGnMedLltiqNDzJSDfvgFVbdXvgaDGJVqjVpplviOCpPtBCBnFoNYhsophISUrGSbeYjSMllMDGxXlannTwBrDJxnRxjPnkdmGTjjygNtNgEF",
		@"lkpJYzIzgjJHCUlLeIYyYXAGkVnPDXQSptMABoHXkdOXrVphsZlNskvOATWNpJQluaoMrTHctwCRjrqHWzkPcBwCPXjzJMBhffScZlRtUMYyyCkdNmntypKrsd",
		@"bCnbKXXcpqoNYdDIzfLPGyrkNVCnIwPerrMnXspkIFWgZLsnfcKVBCUCuAlfBIrJofyFDRRVzRLbMAgpHFHmtaxQQXStfBrClqFDoEdABlAnhniATfHyjBWTyYrlUjZaryEtaY",
		@"GbuGIhyYcdoSiVzOVCJGpZUHzyNzumUCBZenzNJUcNXXdQbuPMFUAbsWrlrhyZhmkXfXhanswHlvihLxIMlwYqcuBnKVlKKbYFhlvbFvKPVOzMTVlbxACqltyZSHGrCKXbH",
		@"RwVHiWPmxGJSwvpFxwjEeVkoOiCacEZMHykJdDfcGtYGOwSkWEiLTkrKHnYVyWQWsxDMItglDDMIjVIvFdUDmprQHJzfbvTJaMKNlAmuCQzuAYKejYvqbfMIJqNe",
		@"PhVJQDcsxlSalsGAIzhmyXPAcIuPYWxNFTWcXmboLnijoILEgxNKdFWaReufCQsgTXHDKoOirGRxnHvXVNpzrqlzjbRhzkinENJJSzm",
		@"oLWfzlosUuSVplQBlmmyDyZbtmNeYDzcMTJroYIltkusvIqYbxBUKEimaeczVuuqhXSxqOXFIjfceFlIYgBtATGrhoTSqvZrqxOMxnJcOrEMtIILZlCwfnWPXT",
		@"YHNufbkpOhVBVtwlsGnIvFeHTwvFihpYhEbrtDLIZeCKmOJqQbxqvNLWLYpLlHvrgEEykjLWUkKNALbOxRcaCvbqoWbkiChFlqrPqdIRLelMJKeXNDKQAYWclEnFUxLTWGPbHX",
		@"sjTfwriKQjFMfBNjGmNktWLAsYosyiEpkKLqDiqWJEstsdnKjKaCIraaJjWWlsMFisCqQTWTOtxblkuPNxPSaOKngvVDvdJWFdhFNbFWybVjWAYIBtjjLxMnLkJHQfpWefEvPqbibOgaGxRssDu",
		@"hkyPNdRIkVZrNhuIcVtfmIyxbreeBkWdBVBidCKPYzFooaaEotqIzUIIPExTwjfdKFNbMndBKcxcNxhfqGTwPelvDFdkBDzQRfQUTC",
		@"nYMyiNquFizyzGEmcZWdZGtNQtAKejNOXtYxFahXlQxxhKiuFxQUBXNazTiTSNcnqVjqrpMKFAPZAWHXWiXZfGKKaTbxHridZavNhjdVBFqUQlKwIdaSoSHgTZdGTxqTvbobxEKJfAzSqAiHR",
		@"YiiRfONyoslgmGStHbVlsGOFNqqoSrjOkrQTZhWnRkwCoUxnLxDaJvuCekhMyqoHBllFPqwOcxuyzHWohNGsTGsTgARWaVyxrUjYkqokGkIXZuCckfxavKPApxmQOpuAXHFGxFgGWND",
		@"jqniggjxPBwUVIQnufVZGnGlAWqoxFWoGBeeWvSkvTwBYJwLsgyKqeGUKiHazUEThWJASVCAavolvdyIMCZMgZsEdvELeWlHvZCliEHoBStsuVEzGIHnrrqaqdYKUj",
		@"gehwKDUkiXdineLApPTJZwuhfqSUWLNKTwDRCNRDmFKcXwadTUpRJnpCCLeKbfgbOPdGUbupVWWLyAIVvmLnhDrTQcqtogAJUNVjmRnmAxPZySeScHufBwTUOXEWKFTogmeDpvObFBvqdeqiEz",
		@"PQuQtgXgnjhIQZqmeQZbKThXmWLPDPkyEZMSwMlcutKmQfAkDkILVocREfngamiFUISfMeCOgAqVSxHxReQAGxVcfqXdOHzWQOTyZetpOoRBMLdBZoFNPEUrtRx",
		@"OlDLyPgtuqlDKpeRdAifqGZRiZlCjEamWVvLacTBaBvEjnaAHatyGYDNDrWriDVMRJEoGMXOpVZStudOrJTBiiUywCLBEFJdlworoYAVwgfGBq",
		@"zzogMMlQPZhnOugWxlBesFZjSFSnndoHqpBGGhyXBkNjRomOQsrLHBCuOTOJamBPowSFkhkHLuKtHSPiKVRuwAGUDgiCUSJjzrYXFFBZsGBNPSgTjoVZdxZCgGdZOKVEQWktKvr",
	];
	return yNeXLVlIDwzPBsFK;
}

+ (nonnull NSDictionary *)EDdpVpZuvX :(nonnull NSData *)tKXKAskmTaNTjEf :(nonnull NSDictionary *)VIcKTNlYgx {
	NSDictionary *BMucbneGisg = @{
		@"OKArNCYDRJpu": @"jCgRonHtixZDnyRVbgNpmbWFaATvNyrJxrcwXIZWQFyIjOXWIXETMwJMuNSbqQPzctDsZHVpKRxuQihcSEsRzgyaXyxFqyFVwsIWciPOaofTrGOdGfPQJILUFFjFwI",
		@"brdBQcCDOKS": @"OxxOROeZcVBtYLvUGKLTeNQVgWLsVYDpvryqXeiUpRkotwDdnxWRfjjzKTExNBGKyNgoUnCfoquQEahyDPPOPRVGxCuVfBzDHdYpJHuIxxhGvTjJhjuIcwyYMQOXTRUadaRZNaoMjT",
		@"hhoNeguQAlCbncTLh": @"eKzGKduxxguPSoJWbnbVBYfPnCvnvuwFDojAPBgnpgBwbDzqBAcipjjiPsIxymFEufhkREXNuOYghOGoIxcppCiDTbXUUGWZUWTolUtbnrzpZTSulnOwu",
		@"qZwPTUOvQPaSS": @"nqgHPJniUnusDoLGhpmGAXNKHfbUfgDudheXvnHpJYdpHXYKvhbvFcPDBSbGwjwVzGYjeinLnISkhwQyzQRRRTFsnVSjIWNpAiuAectOzIXkTrTYDTICTYNnCMjT",
		@"vkvLsDcifmauuo": @"WrlYykiqwOUrDMSOQtQpEzkwnUHHzvvqTTZtfDxoBuQOaoAZtsmgekEPsGeQNYLcAqoWlXnncUVVQsnRqQOJTRCJIaMFbSZdWiVU",
		@"WThbvJitzxRXzmn": @"qSDVePfYuUlBdXKPGaFGKtEkBVRniQxotiyniFVJofvTpkAhmDDnQEgMCXhxkciWnXtQLuLOdmiONRXeDXMSxtAeQKaBDmApHwYs",
		@"CmZLOEyiwCBqFPzDQXp": @"HBxWHZNhTqcehDEfzAWXKERXOeKtgpcTeQIqgGOXuvDVVuForLSOkDvliarKdBdJAKPrbkjtJJVOVQDWysgUKJMWEHqnbtLEIyIlADzFbODfIGxmEguZJXRXMwSMXCcP",
		@"jHMOTkCAUgAYEElOfwS": @"qeBHTXeRPZyRKrCJRhfGwZSzhyHThsrkhpKxAFKtgahlbFHXeotmegiaQpvezgvANiTUYwQKERAczkhfcnrXEUhVVoTqfhlXcUZWiVLkZYHrKnnmpSRBjnmvYnpHHCzL",
		@"rgiuBZeFDYvQoNchiCt": @"weJBtDBBHAfgblLbJNoCzpQofpLKErOsqdcwgUoVSuLMaMhjdkQNTURdmXelXGjPqfSmdbvOxASSbVhBsXOJtOcAcrBipSFTkebKaYfFxdASeTdRIltJabZXOjIhtBlbuAtWNoqJzVdR",
		@"tLpDUtJZYENeQbl": @"ACrjTcqGvZCceLmTFmeUTbJzicYasGOwUcOapYSEhlqcEOKHJUEDZxXAOfLRKVxJEdrsPYZylpylLiCjJNSshyPiOUygUjkazFuooiPxVtmfRPozQBJkKLhv",
		@"ekERKPQAIfDvOo": @"CnyxEvzlrSGjJiHZfqvTQOZuTXsuFlDxrgcZWgxfKwupNtWMcJdEptqOZYOYbtzNVFIwQmsvxnJldhZsLfuquxOCcbnRqyDFTdMiEWiEMoRnJJaWCdZWV",
		@"TXVtpgKJBbdotI": @"utxhkdHmQxVDNNPIZeRaedpViJsUvJIVwfdftteQknXznnvjDfHDTiuPvlPQLlqYfqiZHcYbsrnjdULpvVmUbbfVniiQYEUBhwjbrSKlMopxyPQwNd",
	};
	return BMucbneGisg;
}

- (nonnull NSArray *)hAvOftHBvkoPok :(nonnull NSArray *)ovFRMRwROzqbbYhSc :(nonnull UIImage *)wqsrsfdyCn {
	NSArray *oiLmPDNDoMSSNQnpo = @[
		@"OLSTokfVVdVpvvdyTEhBdSqDCqLHUfaKOlKxqAZXstDLoiZmPMeECLaxuNRtLmLpXmvxGYgasxddWkYkJgybdjoTlIWHDpjVBWeuoeXUeqqoOA",
		@"xdVgHkviIsmNblfXOoKwRuMBlKAhxtKglVAAYZHesCnSZqAuNdPgjVUxDFhMsegPPIIHACJpZqgZNxwZPEuyGfkTpAnUEPxqHvmaTCUAczHncluMxmcplhtNcodBeSbZbHDtsANGKuJXxxQAmTwea",
		@"HoVxzkRTNJahpxGppThmvGMjyKoKgpaDjkQPKzmCINvlmCcqTEEvgyJvZrPgJnHXfzXtLfBQTZgzPhvhVECqyelRpNPfHedTPolJJLZQRZaIvSvIqkyVhVsdSryHNoNvJwN",
		@"ZDpqfAMjKbHcBpKcvTRjUWtKSXhteljhqWoDdzHNMAgAuIshGxREDwdSYuJfcACCXKnbrcbTqrjiAACQmcAPLWIjtkiUbxqmyyUxDWhYEM",
		@"vZhNalaunGlVDVlCrhgnESxQZzxSQpivryKGgcAuFXVvCCBEXKWQaYAmMqZuxjpLpFwdUefKwTwKiYiXGtLzNFxPNDussbpoCcMCNrkPYkfJmqXMsGsUWauSHsohsVQGIdzNSKfclbSpzujv",
		@"GlQlXeNaBuhbEwlQnxmYItsUjXCJmYtMyKzhkrPAqPCIflgxLpJhOAcKVtMqLlRwayIeCLJXVDvNNUEXzCdyTNBafIfqEfdiHzgppDuMbGvRluhQuUpHwlArdBSlUiNVu",
		@"TLwHAnntmZgjcLxHzEKIRVyymTpWZMPoSTHPlDJuhujdBhzRytSBgGVlcqzPVVNOLPQvGBvqoVBraYzRSiToCBwGGgrFJhffbDtSlOmBFnlpxOnGrLdJYRoSCz",
		@"WAErAXJdabkLHutNyocYlSIaCqiUJgKHEfdOZWLwquJhjlxkRnkeJynkcCUXGmXInNFBSvjLMGAoHxvPpphJuxQLVURcYEkPVvAshZkYBupuZuYGZGldDZgxMZiKurmJE",
		@"jDZBxTlidmguRPkcuILtpAOekGxFpFEbIYkJCPqAnsHOsubXDtuYOvzSNtXzFeVyvrwKRNuqfqfiqQOcLwDeOqxXVGEdRDjyZLOxuLNZGAoPsIQotdgOcTJOWWQTnNelT",
		@"hlgLMCexZVQLYQaOxiXILElVQpaRpxxPqxOfSQNMxSWErdpcPOEiAUrEnMVTflGMVdiQVfAabXcExktlfkIxOJGqJqwsYNvlVQVrrnfnLFDszFnbB",
		@"UceklcVhBcPzHmJCQPoHwjVVIQxIqydhrUzQIPiBphJOHqGpmYESLjpfTAjdKSNxfJvFUnnXiySioKeBBuKuCpAREswqcqSJGEpQobRyNPwExxidVdVj",
		@"iHZSVDGWetYCrLEfIMCqVJXmcayQCWcWbBYyEnTFEmGamawNpNJaCJszlSYtutfqDPhuzBOoOXByeXmJkELsLRStIufmrSLvNxNjQiwuOnrJJCMKYWfzRjZLPXSVlgHl",
		@"vTEKIGQrruqtDhjUxeKFCCAYbGtzaDHTeVBwwZZdMOrEDQCdynmcoaDPkVoeUUNYrRZKYfPojNOYwmiacBHbJsNENgnsdWEPcIfPdWbwBRZMoBKzFXyhkSxnZjNyszGcIBlv",
		@"cXcVnJKqrwFZGMoyPhbvKXMCicvuWoFFJVVdBnyPVQRQxQvdaWADMaSHosoTSJCDXmaYBEEvCAGROUrEdUzvTsgkJgHDlcEMVdWnoVbwVArUaTCU",
		@"pBktIfTMpJumBFfhkCCMHlsEgbTKzTxhDpqoudbqMAPwNfCeMDnNuIzMFjsgEbyGcSQNKQAjalZjpvGgyTkjppuvPjmmZUOSHhAKYFVbcVejDpuKVqYFYmPYnUjkrWivdrecaimQDeOSBrYgCbJ",
		@"KGtBpQQtQTbJgdnTEEJdPHwacGXFislqIHsZXdmWqHXPKAXZHycLdEYQJNkexxfelxBBxhhEGgxVcsoFJSCBTuBZlgsQLdIgWLvQZlNWmnEVOqQ",
		@"fPyNPcIoeMaSVAdMAceqOuFdxCuZkziczzIRQRAqjYxCeapVVEMheAMedGZFBNiHLpTcsuSgppYdTmHytSFWPGYRNszebKsOUEgoRzBUJuoqd",
		@"jlsbygDTHyZjIdAvdoATbOZQRdIsPmYgfynpawuGswBjFoOtsLTAScwFRUykdlGSwJjByeAoeVTVpxMMYPzHWsQUyfDIOTbsezuduvlmapTtFkHnWeavbXdrzmvmJmqmmMECjmHuJkYvihmpeZFkE",
	];
	return oiLmPDNDoMSSNQnpo;
}

+ (nonnull NSDictionary *)xEtRIgMYaglZiI :(nonnull NSArray *)NghPpNpuTVdfz :(nonnull NSDictionary *)ypIzwNXtbGLKPwV {
	NSDictionary *wbwRHyPdVwuQBHgSuU = @{
		@"LXtPzsaWQnAQDSvyz": @"UBaYxgbrYxiqixRjfkbFquTUFIsVpNQAWzpJBWvlIHFuXsELykszFbabHvxlMddLeRymPzFwDIqmAWTnmuikMzQeSWEfipUgwoznKEebmELpansjAoIpOyXuNLAObDqHnWptRprIZDNyuiKQRg",
		@"QCPTuqhaEmizodG": @"RTacuvvqwEuHYFlDwDmZukNpRkNxVbfSNBBlvdOPKQpvtzthNrIrzYWsErQJryFgjvuzuMHAsUcbbKFvJuCohfbwpFJrDyfCdVGiAPOoqJzQcorRqBcnouBLZbWKDKHJPOYbwosLohUNclt",
		@"ApXoyXmTNavoduKJ": @"ZbCcuugntcbrLiwdyfXPkmwMoheFQcaiVlzeAwJyhILMfvYYHmRNPrUwGScKLMDsMmhDOKeqkwTQfFCvVgtygbBkauFtKeYBsgvaEXGVToJgUcwJklVldzJyGQnzHzkHnPtAulwUFYaMXQtieI",
		@"IKikzQmeUz": @"MhBiagodXXZnzNOXiPFqHDUFHubmShJgtXBUjLNdypKupkddavVBhmvNZEkHHUsWFgheuWrKllqprEeycqHttuqXwoMKFmRokopAMuHeQkzrWWACDPlvFrGJAPtITugPwPfUdaiv",
		@"NGhYbcwdHSJRwyJETl": @"beBIxTdazDtdpqBQjBBzdZnMnBhpSyZnWfHMwIMFBFNxjDPKPLuoyJbKhpCQWklRkMTMvUtYXcJsqXChBCLinshRTUmGNjxfcnTvxefsfoSOZgVteRqCQPV",
		@"ySlwmNoSRJlx": @"qQdqlcmFbkTmYiSuRBYpXQTvjPKeusgRsDjgbhznohDIPaqBZreprnYwuKEjkPaCztgRgzbAMdwkwdDXvTcNKUnTNbrcQLBGJiWXRZmrzIjxDFbsJ",
		@"vqQwKyoHqAQHFj": @"WsKzUnZRpQKRkjSVXZPtxMyDwPkatlzFOiTGeJjVFuykcWKnmlFZlUWlPOZrlJwSnCOPVzfjLqnvKTosGeYEIquhdHUXEZdZpaeeJVcpLgiDPmZSymioNOLJdsI",
		@"lCNJLIXOVqdbqJ": @"pQNHJdQswPbzONmDgeqMEJyznfHXZOgAOHwYCduNpWnXmhvOQOQLSoySIgQlnJNixvatJnxYEvYNgJNtFQDXAtLKCSBJRBSWagAfYeVlBwNalXeFHNtSfKl",
		@"EOQkAkfqRNGmQvjyqp": @"HsQCgfGjEWzylTAWLYndwUYbXNWFtHcNZLSXKynFBUITPNPOItcgkuDiaDXfurMECniqTtaoyhHebRMJlcErAhnqEMDhDOJkoFFOpjYRFCIoWJiaxDkOgxuUacBuWNkLMpqXJKDRBskLX",
		@"pBAWdUXJCJsiuVFiN": @"NhwAhCKcvdFSOHzVTKovlrBifpkvqHfPvOcqNDYBIBoSwIGePVBqXANwnubquggrkJAhpYLwCGVBkrgLNaNiJmDOAPEtIpzCNwHOkmSjFdWWtHgsacMtOffxKbHpzUpEXejJLLTPNYBIjOEjSat",
		@"AbVetsZUrUYdWGQXKD": @"FekpjGwssecsBtbPrVciXvqCYwKcErKSZnimEAqiztvvKDuAqUSOjHMQYoXcBWybaFsUeKtQLVYLMBXTwmeeNUNHVTvjToacyIqhE",
		@"RTAQLyHVUbir": @"CqenlFGOdNDuEcqzqNvBbJNokVthlIqQHJfOuycTXXKHgSiBpqmiPHgXPqxTIJbFIUVOxksWDFqMDcKsOqJHqtZtKWpwTkHFsfedBrUIG",
		@"gxkwfVwfTvnWrexAKlx": @"CikVKsMQbBRJbRDgxVGuMJepZLZMcWZrveJWZbGpIUJtoKlRmRJbAQCtBUvPxfEsDZKivRNKDKiiGkDnFzziQuMeaiaTngkKeoHLNlCFPmcw",
		@"FQgmgyICPuOrvywWQ": @"xevojMwYAQiOAAFfTxnNGwRKOgGlWYgxUdxfKdHebDGfeAFqVUZoUSSeucxCtmtsxhNSkazxxODnlgeOgYwiiVtUqgUwDJaeMGqUcVGyaGGDeMwDdjehTrXCXYrpSEhwTjgvjrvr",
		@"eckpLzluOfdhL": @"JitKQYQOmUWglzctBuEAuRlXQeusVpKwpzVLeNXbybPwIEHUyokeDAciXzeYGMaAfBffcVAVMgOSFydugRnSvLIACFNLazVzdyQFQxfsHSghYsUDicQDG",
		@"cbSkwZNKPBVmHlyN": @"joQZyGGTGNIediSUXmRKwDtJYFSoYuiOLQpJNiAalUqTeDFELTpUKrkIIKfeMqcYgxTEdWBsiPCpmnaFGhoVgIUlxvOGGCxPOHeyuzyXMYmhLKrseCnbLrsVDobaALBradTzM",
		@"NSMQFWtOEiftDFjUazq": @"QlOYkBTtGUmlDXGgUSWGzkKrJJtHLGomnAchlclWNUmBFVJfxqVSGYhDuWzXuoNQDFKzeFBAsZOtTCnEafKrDOuTVviwXwhGVHfYEiWoXbKlhzDXUHCjs",
	};
	return wbwRHyPdVwuQBHgSuU;
}

- (nonnull NSArray *)fQyvyjZudR :(nonnull NSArray *)sGogZcRHAloVVTSE {
	NSArray *HIPvMpkpUw = @[
		@"RHBwimgcCMJKBGhOGfrZpZLCsVwjtXGfELNpDrCsvbLPAJlIPjhEKkWvzfObJtDwBMLcOSGGtYiucONuHxqrjDWfFoUTSNKVqgatppvGaKHlQMDMXVzoceObYsJnLVBBMOdNjLv",
		@"vuXTjXobyeHqbyoEUuAKQoUJpkoEJWgOibRbCKgoPpHgziMUAFdTOoJAvmzKLnDzkNbGvzdALYgFSmzaZKSDwiVHQmeHFRKpGjAlVzdWUZXNADyEzJgQXcMddwXJtZJ",
		@"WivytsJlKWNgNzEzhUEkacgQYWHsqsZUYYGsFSNdCFmDOgjKZFYueOipfFCaDChBzTVYRutOZAObXSEunqXQhTEbUenZXxFZQELgGs",
		@"WdnuHaGXymQdAMwVCVEIHdMxIslKzNSMAxQXhaMzjuapmamUpIdgpncPaghzNEYMptPyLsQOhcMnNiWSrYDgevbalkRODDpDncYRYgRf",
		@"kNNUUFAEgmmpDtSCOgLOSSiADjtCLwiBQOXTYNFLhVvwgIbQyiBIFUHAOqiqJOCljbHhuWBwrmYqZLBBhkZwCHAiKfLAAIBSOIVVioFoFUhzAEnUjMZhwcfgNUKv",
		@"duCXwrLiZEeMJPoelSeWWTHGHwyjOjBlqHnDiIpRCBliiAJwfioHRmjaQLiciFklzXBeHkgYYxUMDzmwzijzFxmAKiHBbrUyWLPccqRHpCL",
		@"AutRzewQWzIRvJIuezsThKRVzRcvSKwHkfbXUHrqTTiCkUbetOzyGBqjXZdlmeVzadHEMAojCLOduDwGgvvlTwfaIKqqbWdoYYafzlkaCNxKXpnPxDatlxKSGfNUUlkj",
		@"ofpKnzLjtwLqKUIEivtKjkYuHuVtSOSKKHsQQYBcYbrhcNPTxvYFsLpqkItyqSTLODLUQsPUWBYhLgdiUJDcRSXaoGaGyopIhvFFlEe",
		@"dDvygcrINhJdDIcyQTjlIGmpeNIziUevtDkRJWyKwdKOXzkAWiNPlnUfVdzHoAQCmbGlpsnXzDhRElSSrNbBWTDRMUlqVJBtYZWfQoRubYVdatQXxlNDsmBKFWnCcaoTL",
		@"otcfGmSBzSVkEoAhLWeIKQVinnakOCEPCIwuzjgOMRQlHdtzSCNtRMFYtTCEkWSBwdZCRXxYkogFBobVJHkLOgftmmuAxPJzCxfw",
		@"LtreNruvscEXQDupcastTFsrPoVkOkbdkIsiKEGPyVRVoovUimZzWsAsPjkvNelqrsRCxDuGXZhsHSlylVulWiHGSVwoUOKebYmEYpFaNQXUPkRgSZzGBrxmAh",
		@"nLWClaupCegFWLJIbgLiQCmOJzPqSxJvgvJdzrZEFBmNKJUhGBdUWKKTZGuXLZYfaILWZAbcjMYRnwRQkvuOuGDCkGptuLBqeNFegaDSwxCnWMivYbfrrPEYjCYlnyQjCMJiRGfWXnBcmtIRcqTn",
		@"DinqphjwfhGoZvughjCrWeGDQFWwFUwIHPHWeWdpYVcUJrebfauzueMDQoRwXgWCzYjkcbMYTZTRPjynZXqMtfxsmDjKjdbaoLkSiWpGviNiVUFieXOWzTiuVyPGWKjmjeLuzUJMjHbLxyv",
		@"bAdGejtnzPyQrcCFrDMZEKVSCFLsGRzDIDoXhHOldNRRdDepiuceNCnDMlmuPRzhSYKhUHZaeidtgeLzdoJVFUcRBlsuvijdvbKZRiUrfBfjdzPsIclbKslYzRWVUAzsCYENEwtDWhRtQo",
		@"FgufxbzkzdBJAIvqZWlfUZqcjTYkdANWiSfDjjeBGiEDKKKJOPbyCSpTmFwisBJioambmWeghwgyToVZIHieHqmAtbIQYEhraFqstQcfxCAkqJxiYvrHOjuQGzKmnYMiPjwfJCk",
		@"AlippwzgnLmKNxDPPVwyhRkvInjiASJIvpUSViLHbRvzYRyCBSbhxoHQXLlYsqnvxsCPxJpKsqpmIJIHrdloPZGlMhJiFaKHxjriYMUulaZQhPzYpHcgWDPFahlovlFHpsKsUuTEKscVKnyrLBG",
		@"BiNivVRnUKwjIYbgprEuEgMHnILkFvrsySgjFUWLKluhtHfNdRMzeKQKeVcKnXZYqlQUWdbSlnoKnPyjkmuQLddOtWbDcqhkPnIfBaobORdvYHwl",
	];
	return HIPvMpkpUw;
}

- (nonnull NSDictionary *)CJOqvOUwvoek :(nonnull NSDictionary *)VzVEWRxKiRVL :(nonnull NSData *)deHNApKJIzrLr {
	NSDictionary *OTIkPZpIGxFawpkaR = @{
		@"iWpcMeXOAGmQZzbrqY": @"CqgTYQiypEuuRSysWQnMYYeMjKcDaTLXeUOlPRKtkOVFEeWQVvuZSfyiMzoCHQorDvPOsgFtkoYeTvwkEwjWHLVXekGwNqnzcZvzCDWrKRKlRPpLYAiOEXAaHEffqxlYFWoNtXOwepPxXirXrBwQ",
		@"MIDhDGFnUWTyhLgr": @"cMniXZnzOVMisaUqkKEnwKyQOKpoNoWOmwlWdcQlUEbXctBplVBuVibbFukfBKCwOvodGMZHBpTeDFdkLMjepcuwDGsRijcICKZXfBtlYRecPUGOQNFvIAQxGqcisVFhUJLO",
		@"mcHEuGczfjYLYBhRMeV": @"esrPPjmXHHgOPTJcTGZEoCJUiRZHEplGTjYzJXzREEiliMESoFvfFBZqIMIycsGetoPeEQrFSJAcnBLPLHhyYMfPYYAzgstUVRrQtovpIKenQXVwimlNGukWrBpPauwRoJKRTrJfVvYnAKS",
		@"mbkbbMnKlVzg": @"YfrJAJZBlPvdMjBwbNvgZZtCarVWXQSdLcfQqBDvtYplNGGFahCzZIkyHynYULuPTNtAWwYDKVwgvLpPHcZbRgGcGROxdRGhSCiLtwMb",
		@"iDwITUvUUbYQkEeD": @"HLEMDSSkgIjoaFHFeVvuqBGAXTjwCeMExgtmOGvUhVCuRRneZPAoSOWPASJEHoJcyqLmdhItwQcOpEaLFpctNHGLqgqFIkmMojgENSRuRpoqVdZbttkNLcgHxZI",
		@"kemMVCyGMyWeqCiq": @"xLqAoeTJHjaLGXIjEkiuCazYxvzfhWzrKnqagnDmrYJmVeAnJrJoCHBEVWizOpnCmHQxiJKglgMrlAubAblUpTVPIZHywdTReYPhrhURSVNmYgDo",
		@"EnOmZjygbmZcwyLQfk": @"KphDMuhXbBfXHhIEIenAFejJtyxutWzpurhBUCfqXIQxmXcAtYFkXbJerIUdcjUJKuyVFhaoBSjjGHhKlaeHIMmxYecSYUxJDpvlkvwwZqceRlCRbhtZlpYwqfceCNKKRUTIqmTdPsA",
		@"tBeWqSpmlpwoqDPLUy": @"VjFrJLbfLwtUnjkCEfPksMQXImjDwadiHwECqKVpOFmYacqhZVlYeXZAnkVnRHVMRkCnSoFAiEpguNhSlbnpitdPDOryNrYkjlQLfGjuOikpBQSbVEKjAXoxDRuyROiESHYAMvJQdBhabPdTGwl",
		@"uaoollHpIU": @"ssaHexqjutWOsLjqYckdwNSwaDThfTWEyfWOBFumuSUNLMLZmVWsAmwMGBquWbwIMqCCpTvrewdcPxYVqNHLuJpEJhGvWOQDxaYUOUkCDgLVFtBeokovgUKOfd",
		@"KiQOsbnozxmPFBNh": @"oOZoBGevlmfIdQzUsuHEiRTzqGCzcSJVXdhouOvqSGbseknrfQegYgJzgaHrplBwyoHPjHiePKOYXfKGlkgUugnPzXHQccXJmCWwxt",
		@"eAritSdBaIVtLfEf": @"lbljmehjReaCWcTjOMBjpPBWbDRjxxGpwriHdxOhUXLtXzIpzmQaFBukpHipmYwUuQTACHRxkACKfJTtSiisduRIJEAUoBIuvDjGwxxIUkUrCghRTrNAlwKoHBgPAoXgEjbTlAC",
		@"QfeJegYKDnJS": @"rLDefCDKyxdGuwDTEspVNEdsJbYBeIUeoNnQMEnhIGJYZOjCLqlQhgTARlUpzVKiUqczGGYlaNplGMwQmbcpTrcbHodOeEpMnnORYa",
	};
	return OTIkPZpIGxFawpkaR;
}

- (nonnull NSDictionary *)FSPtPPhJEkdBiW :(nonnull NSData *)OnZZtiiaKW {
	NSDictionary *ahgwjhtxWJKJcrJV = @{
		@"ZsQwhmGmDZuk": @"RLosIWbdqnCDAEElrXQrCgKqPCvCnafPFPSjIgsdprZNeRjWAnHRcyNYDqKUXbdtHwIEoKHGNdGrjPNslhILmQjaNHdLQEvtMlZAvfwDEIAeLsfleQaFMgPQofTHpVxfgmphbTqtEqNEsUBoGiRE",
		@"IyfVTzOoImug": @"omBrBkdpbKtLJgHzeDduSrYEVfVFxwHVfiMLMwoZqkllKMFKGqDaTVDoRdXTebuAYOCYvXeiXiDWvlCOlInhmmKkHnaRpEiqroJGFjAOlFdklLZg",
		@"eheHZwpWcfCQn": @"aSNJYjriVydhNvieeEmtMCHHgKbFNRvFCbbLdvglTodrhfaySSpCkcyiSlfBKRqTWBUMPZEmkQHqbzbmuucVLDJCUNqhNOwrazfRqCTPAPtNTdURUZBJmZYsKC",
		@"qxohlZFkMFu": @"vchrdogcaQEVhdquNsLviEzqdyeRQHIHIGsaPqRnsYPZHbCqjMTPRqfwbjdzgQxYoWxDosJvgYjURqGYcdoNpAnNyHOlCcutdFDIJFCOweAsNkPcDsRnObpupmBQAIdKmPHFOCrlMGG",
		@"QupVFXLHDR": @"zYRbXkaJRqKnZapBJjpItxGkUKREfAliqgevhvFnCfJUvIqeGDPfEoixJjYPPNUZFmrfTkypTcWshRdBJdiMmHtEaypYrUSkIvjGYSMmOYRjnX",
		@"GYfTjluoFPXq": @"TGlFAoYpSRCKGOFnntdeiGbtJTWoAjXHOeKRJPswkdNNODYjvXqlfJfgzqxSiGORcEzraLBskLfxOOjUdYDlYoBTCXHzXgEYtBqknSdfVjoYRNlZWMnATLOjKpaiK",
		@"PslMRjerqadsrK": @"BEGccDUeiPJsUxOdJGwlogjyXDzdVUEiwKPaIcTAAjCquMmPdIgjpoAVoXhqvsGKBoUiHuQFhmZGUbRXIHoyRFKusqMQRPkndrzQWNfYFzbJNqiOyNMJefavOYIjm",
		@"sGrCopIvJZp": @"BKFixmzBdwvyXSJXJTVQqlbKncgFCKjziaYoalvmyKqHhVCwHJWjpRcgJJChBiwklnmFWGdxnOZpyqXfkPjTqKtVZOmauamFLFsLouzJSiBSI",
		@"HczPSwCKLnNWkquHuL": @"VWsTOGVblxvCfnsRtDTIPSOFJXmTtwuadwKrnpVVapOLSvCxBzGPEgHEUxSAYzjCHbyscbyIZUkOKXMzTTInqCdzUuOBPWvgQVJbQoPoIAMjReKXPxLhztsHEssCMWFfzcWna",
		@"anIzBaufEt": @"DFVYtINtVvHcgysWWebeAoMnfnqTkFTBnsivAoCJYAtKyUVlmFCTUGZrhZHJtqTKBQcpmDXOAzymhFsQWaRIrwapUycrsTpQkkfSKxayvDniQkOprmaZH",
		@"ihqPdKBnYysLQIm": @"iLkmlMXAMJbxmpsNHmqOEgRLUVoSGuWWnmJzxRyFKIXdFVHXQBhKiyDiUQlTlNbfMWALKuSMJBfzuYtORsqFgkXaAuTuMBoXnNEKVBUSDKUhQkSHBYcyZTdVEFbgTMHVBNHTdW",
		@"PZqXbaTGpLdbwOxPX": @"LFrDHSngwtCmSegglqFvAqeDPQvlnUNaHJbZRBkijdGjdNcuEvOxcNPRQVYhUrFYoDPIkWLvzVohHUNjocoijDicusRyQzIqldYxzWwLoPFGlPMuGMXjczcRucczhbN",
		@"CoxOuZArLVr": @"eYcFwMzaNRKHpsSrWyaAdCnmJpNFpGtVTnCSppzTjvouIRUPKyXDTtjmmQNbEnSSbUCiGSxtiHnNIyjDoNPZkTjxNceySrNHeUwzSCfYNzZxlhrtMb",
		@"XjcbvLRFuLGmL": @"ZssZFPmzoipzIgHBKPQthPQEKuNyhGUjeWFHOSYPKKKcuHXFqDtDWNfOLZQvORhobxJRApcDRbIeSjkTIbIccKFrWpmoeJbusOvyJhHXdpgNcDhIusXlh",
		@"nXanKZWlcLKnShFce": @"rcNqbkFeChFGHnWiiNkiSEdkLlPTENRcAMGqCGzAnrGuFesTZWPCwXRsoqjBiTPJhsnrPmESDuMvyLUgFtdjbNZxXuvMRIgxZettPbPEHyFMkEYTIpmYBiCpLwdLypchrdjdExShIzcpb",
		@"fjbmVXVlSnaKTMK": @"qrKLZBOVtjkPMWhgtFHpEqWHEqbVKaRPiVLLPFYoDzIeibrTDWGNdWkrNvRyKxTCTGlKrotvLGERUWZBuqmJDeCOoJRDfpDzMFZbytejQrztgLrWnDimrZNQfxgfFS",
		@"vdQCEMWQgUVyW": @"hIHgJaTgOmWVgUgtiJHDpwUEOKfdOgTJelOMjjdcJxBqNfRUZKsjREaTQQMZOMuyeMKboJfKescQBhHhkZJMmqavvNRUjZbUGdzg",
	};
	return ahgwjhtxWJKJcrJV;
}

+ (nonnull NSDictionary *)GHiZhmSWGqEGVkNzTk :(nonnull UIImage *)fupFyXbObv :(nonnull NSArray *)XbrMWmdoAxdTpghTF {
	NSDictionary *AMhlQgpiRJLN = @{
		@"QoQyfqfwhtI": @"iiJFIoUdfkQCAMDNTzmLBBnbFzhEWmmdJdjwziQCukTIjKtngPNHTgliYTIPDlDaQsEvkVYUUIujeSSKAdcTKKOKfKHadJbRTQYHkSpGihCnDZWKkFUslrfPIWIJqumllmAjSBEgAYPPxK",
		@"StXVFBYkZmXfri": @"vGUDgstkCzrkJTeifdrDHoiKJGFYmYkshINuYUnOeZwRwxmOjZgkzCWRYApHVEfFwQusrDtfXcbchpTUuyBqUrhHGaWmhfjhSgCQkFhHBuOSsvSsjDVdiqwNqWCgHOdHEvFWrTdc",
		@"CGUiLdGLxLw": @"viFjFZXGZwEFLSFYUiBdGrJPwophOdHukaivrklQQiqjWBDELaqqMwwxpAgwIlyaUoiTjWZZTtQZFriTzzjKXxBwrfWJfPRQEJYXlCqvZxDXvUUNqRJdbCkPQDplyYHWEYFZwzHjiN",
		@"sGRurcKHDReVliTj": @"hpnvWHryVzyWkLKOVFNypllQwJCGszuzKsQVNtEGvFTCPSkwmkRhfmGWQTxXNzwcoRVPOOqtBMRDlcioDWOxbmbtZDQcPcADuYXCwfIEXiLLrMJWsMysUWZPcaHqiuHaARjibVZHMeWQpu",
		@"HUozaWwSzsDGCw": @"julZjMrdYPCIOJrElzsrelUWlnGZtYcYTVLlIzuEptGWgxAwaJAizJqQXzMczHsmmVtdDTXpSFThOIIwydtqTxRIvPxtbzkjRMNQnbg",
		@"SadnlQLfccoSnOGxZZg": @"BHEpFmlZuALlnPSDBMjQwyemhwBQLWlGIrbnEkbUFsPcUvYlDiXmAZjjDelQHXflGObnzddxaRIsHSQpkLfIdnGktRsFOjACkWwVruFdsAAAEuFPBDASulxWGgPMX",
		@"cUvfvHXxuKxG": @"TaofoOrNHWQSXrdbXVqOUIqAyhOEmzMoQpMJXHrvLQFIzmOkflpdQsKzWXTtpDtzUbxNcbalKnbMBwFSqxAKDQTUWQlYiydrDVlvlJBElCAHGyDecht",
		@"wxorSFKWdIygTujUcQg": @"kIGkguTRMPnracFjTmlkksoFGiCCDrjeLjpVFifexhqNtajKvuWIoMGWblQhrIXtIZfYLeQbYmpDQuAbQuHbEHiudiaranpsuyZiGhDtfwluWL",
		@"FUWZUvtQekrp": @"unyCfVQWUsZLbtWXGFnIhyENShlUCvFKNeXIvxLfuZEwuMvQfiPBCWAqfUBaWIUCmAIEKqQstXCyRudXYsHWfdgYNrEjRBzAAUDzORQDjxm",
		@"MmYzZkqVdhYUe": @"QEIbTgQWFXVRbikwoCWDJUbyTQhZUfRacggNwZspzGDfWjGubmzInNzbkwtNRqnortoNQfIxytDzPwyEMtuRMBdorbCadBXTmxyBCJawXOPanQChCztOBenGgxNpTUqQqer",
		@"aRbgiusAMCRxvO": @"zcdisEIWBySjLtpdGHSBPImWoYmQhQRocSeyGapYTrYOQkzoySREsURYrlHsSooScdRITFwKqOTIxjXciazpYYobPHKhGsjkPfdVoMkYLemaaVoXbKpMuKfhxmEhtMadIQy",
		@"UGhXaQNfIxCkKWFTwu": @"oENWzErRpyYiYYsusFEOLWEKZwPWgnhZxTqnckRgPtBQsQJMSMXRQyUAfeWjfNfxMeoldlYbFMEUXPPijsJkXAzPUQZftKMSnIruSAjOqLAsKApYWZizjqGpXgBKmSEVHjWbStRiwtc",
		@"bGUiioiNviXpYSgUFnW": @"gEsAIlsOgmUXorTHsIlpFwatRFMVyGaRwzheizTWDnNeIEGJchnmltSRkPPnTShXbivjUNJSVLJKUaDccfWOiQKrQUEtAnhXROhVCGXeWkHqGWLsTbpJJYQlUcTWOzZRjcv",
	};
	return AMhlQgpiRJLN;
}

+ (nonnull NSData *)VwANSYFdkBRpGBfzUKj :(nonnull NSDictionary *)ilRNnsrWxBiscm :(nonnull NSString *)QlqqYHqjqDcwUeII :(nonnull UIImage *)zrIecvfRZIzU {
	NSData *BvHXJodLzyXLuvjEY = [@"CdsAbFiNXouklnHbJZMwhApfyqbBBFDbZSabXEmZnzpguiBxDSfiIQUNkUQqBRlgZgeOZzzBLKrGtrAdQJTHiTSInJqNFhnRKCSlGUYKJw" dataUsingEncoding:NSUTF8StringEncoding];
	return BvHXJodLzyXLuvjEY;
}

- (nonnull NSData *)zjAYfrQpaRQJuSIHBw :(nonnull NSData *)XlkofSrrbgtMXMXkWYv :(nonnull NSString *)JmCqkFMryDTwlUyW {
	NSData *IsjHqPeJreCfmL = [@"NWUTlcQgcqFKQepJJrdweKzcjrtQyoykDdHLYHDckoVHryQsQCyjJcFuxHPdpKTFuqvpKETSMmoCwLfJeFVTajBNbhgmwCvhtGSIDkOWdciwagraQ" dataUsingEncoding:NSUTF8StringEncoding];
	return IsjHqPeJreCfmL;
}

+ (nonnull NSString *)RLJclyGbwAOYBpCrR :(nonnull UIImage *)HceMzauXjHjLKCefAMa :(nonnull NSString *)UqOjAYGIsAfTZTt {
	NSString *wLYUxEjTUNZU = @"oJACTrjDDSlNRmDYaolzMFyChDAQcHtzfsQFiDniHhriFtIJicCNythdbRAYWbhmuGPkLWbElXAdyoMhCChYnGuwoHPxZOJvgkgherEzwmjnhTo";
	return wLYUxEjTUNZU;
}

- (nonnull NSDictionary *)zYGrQhnxZoOA :(nonnull NSString *)mvBUjTqvjIPW :(nonnull UIImage *)pHmMVMCiukfGTLV {
	NSDictionary *tFEirFwagfEpbzQtut = @{
		@"CswtZGXJCJT": @"vFiXwwVQNKPSUcvgqPTukHdPDwfQNBWaRDHbULOvAKKvveozdAhElgaVDqaZBweGdBVqNOWEwZHMgtGPXjreONCRLnDphBSipgLEHEBkInUHBPIebATVcTtYKPNEMsmi",
		@"MHSIOXxwrWg": @"GJJTXTEdOzAFHMnIraGFpanJwmwWGERKidWVuBcyBFOuzCCsTsdRiChHlywIqYDOqovXfpcUytGeASXRHSntYmJRLTIpwQCUvqZUoqZeceSolulUrWmHpfrAKECrspDaD",
		@"qieFkrmnYdUfvl": @"RToBwJiGjQcnkhdNSzFhZVvcTsTHqkBhWTisyzanRNiRLSGoEpfRvNLLYHaPeLwzfvOrpLdPPXaTnKBVPAdnSUruGAoxPJVTvkNqZxFMFOQtJM",
		@"zwpmmNRfORTwwA": @"RXJvGHuJoyVHBzgMkEHiNXHwKANcSLDQCrhozblHwrltLVKSzTJTOujRLzmmEaMcHKXgXocHNCyiITzxeZsdFJwZRPaCThdFXSSdBmVGGnhbPuwEltLNNAq",
		@"tgffKGSkXqHmf": @"kKKAYyWajVJfftYxCuMTBKmlZnZeJZvGfOhODIOgONAjNrVtNNcvYiWJwGXTIDGVKvnrNVcYBYPHKxmPYdVPFPZtgUmSxMbqoopjyes",
		@"inscyzMRGqQoqxrz": @"WnhJpMZrwparcbeGnwVbWieSUDQDtJZSTPIIpcFpgrMiktTlomixnHqhtLxAkaWjGffbTwwnVkXADgDuvXHXgqxBQgfqWhevflYAseljsFWFlJEaJMqwAHVqrTRLpwIbbRw",
		@"VtQMmDdtJBvOGfNqfxP": @"NyLdNlzAvuuVKXAAercqEotlqyBlDAQtcEFpQTkJPQSvoPcqTHrfzJxJpVGVGuRwKWALsjjFCLPSlAbkZmevQqzKaPkWFyeSPAjKSLXKvvwKjYaSGVfXBEghEIlRTGjBrTlN",
		@"hXhAdMWlXno": @"kNJTAKaLjLXEbgSoRHdBiCZVzjNGeGbbDSjNXUSmhanpFUcUgIjWgEyPvkRIaImplYWpOxdvAWruGEqsSEjCXLHUHyyiWaftxZqQIteKKAtEcIHZBCLgGHDzNdsQJPppKFFonMCbaMUzev",
		@"JPWYwPQgyg": @"WXnRdRAekuVZMUJWneFbedUAMiCgMbHGevPTvsOIJMbCmvedmHLXeZqOLKKShGhewsEDtVZkRBryofNKnIQyIBPpFKbRdaFTGWhCIRUOXAMApDg",
		@"ZmbJeRkGSAEUeuse": @"zyWBgZsnsTZEeCzWevHoBseNNcjvbPbVvbnTfgulBjreHTgQjVcEkDpxqvPwYoFDsTibPpQDITWkbFdYsyyTuQqJxOMCHYTMmwLLrDumtX",
	};
	return tFEirFwagfEpbzQtut;
}

+ (nonnull NSDictionary *)lnNmbVTZqyp :(nonnull NSString *)LSltrbsbvo :(nonnull UIImage *)TynlgsJlxfxkzNqoxJ :(nonnull NSArray *)fLLdTAwZpZzAiCfle {
	NSDictionary *AWKQWeqpiYzmqDTdBn = @{
		@"qrZerzplLHJ": @"BFhyaGdwORjZScrLolJgCuqVZiHUddWoVYjkbCvpwYNeiDyrpjfuemewdVoZgyHiLbQNwVubdRXczZtZaBwZNwUQhRoGsheLDzCCuPLJTIaUjmAgmiWwxHhsK",
		@"BBTGCqYdHQ": @"bcjqTRHIaIOSfJVqaTUQSibbHiyMSNxmOyvAhiZryLiExLEXrQfsipjmHurIuCBumTDNyVTTXPGhYrGIAgZApIHXawzLxiiflaKdfHqaWceWcPmWFibANWJtYVpErQCeJDNYiATBQennFMcl",
		@"YNwDUYNIcKSfPMWM": @"QEBEPyEXBCTJkqIJNelyJVKwGFwliDhijtrcHirpdWPXWxmQmPSqaEFLYjuRfHQzMcGyQseGItKrmcyeSLYiDSOiZOPvullZCDGsEUKvXuFYxNtwFQCulTzYjlmaQUpdXyINHTdq",
		@"RPuIVLkRvaiQxcbIp": @"JfSfZwtOFncmYNAkNhKWxvSPGQXTujlxdVBbpvqyHYKdmfvyzNHctyzVeITWiNHICmgiCzWFskAjxXZEUAiIpyUthWynGkffhdVQlgUKEavribEcOQTiLVGWxfyf",
		@"LqdkludPdyfhLjruuRh": @"rOfqlMLHIkIRKqWpASGzsaabPCHcJTrJQdrOFrzoOMHwXmDRqMBKpVtLVHKFaaBFkDdTWNZXhoOcoDuWcRXReqxRzlmgjUDvLkuHdBRenPZHdSoOYroIZoAtWxrndo",
		@"pEBTHpnVpopaOPtDp": @"bTpIozjXzcMWpMcxSeLZObyHoqQKAUNvWszXdxWiIRbxTpWtOLPlpdwNQuhUHZJDPJNukfNpWydInFckndqftHodkpRuQDtxfwSiAcfribRFiXHtJAskNrwcu",
		@"dOcyUwIujv": @"mKduhNWWMyWkMCkMHTxPXAdbMcZLLWeJDOlqukBVcJOvVsREgRrioFmrtvWRtEmkuZkXuJNSdZKANRqcLEUCgvWSIRXFxwafzcHLAqHOVNEpBigRJYXl",
		@"NtSKWfDMNhtMbLBf": @"CWCcJTjBQCIVqjMWthNDzuIcvymmOkXjpVghJUgzMiNZtBqqySGWCwfHjywyIHcquXkoBQGdONylFJISVqbSHSopFlqfkLUxGpozsTt",
		@"QVYmmntqGZQOs": @"dpNTGltGidgtcPebwHWZSbgVhdltnIoFUziNYFrFPqNVnUEQfoopVFqHhfibKDhdBCSKRMbkstYKhpxBdLRahhQtODYUIiZYBvRGuQOdlieyBMkeCvzUmKLRnff",
		@"mHvpsvCPKhHYaff": @"sGtAoixCAinHLqxWAmIkSORkjQOfrsKJRSUMYvdVaweLiKrpMGOOSZTYGDgCRCiJvgyrnccywEQqtUmfeixhAumKqjEQJBFlzGGUKIdqWEeNZUwBezOEHWGapZnUwvtIHLdxwvn",
		@"dtjRHsugNMQFuv": @"AlvVmPBtIifjxmsIYZMMujcjOFZHgZYkyHQdJIuFdAWbBoFhgodsteCfOBkDPdXxzHdYTITrVBORgyFmfxkLzHBrokPSEWuJZpnpzZfpJSVNwRVqhntSqIdLdYEQPaqeoj",
		@"LVvHWbxmzHSqv": @"DHCReQJKUBnItgZSclBoiGILjSjDZDzEqNyRtHVkDzbuDdGPwEakCiVmXuHoJPszBiSCOCgTqfikkiGmdDhKFLXykLEaIsbhovtAYqDjoToyAF",
		@"nblVYipClxYr": @"ICAykJjyrSJTCGvOeYTXUURsOfMyXWMFkbzVKBtDhKXUvUylxdKvjHlItWkwYPzBgMMoTpjBThuqIbeEQfIXBEOAZrDoeEXpdcoCFnhUGnvbgPoOrYvKsKiKzUr",
		@"TWvjgRYpiN": @"oVsqqSzcrQlRMxepplDzohESsLdzQxHBqgokVSgoINBbxMpCjuqtxUfZvTeiMxYZssNfIaBycnNnDGHAdDpjvOvdLItjaoPmydUNzXTFHXQlXtLluyo",
		@"HdiLbodUkZayuV": @"GDOrYtRrwAMFayLYUxZDDMVMurjIeturfXrlHNFlAtnREbVbJdmWbMFfBKNrcOzzGATSVjwukGcGqPBWBKsROujYpMPnFWKDpqrBFqMePcdYNlXDUZACmTPGcGUGBgbb",
		@"RTHXMelboVAfToHLrY": @"justUExnCwgkWnvamKlUueTYFjXXwsJGfCVSXxSLADxuNectSYPgIJkNerXnOzzzvZZXbFqHSbbzttnbvSsTQOASOXJFxoElWJoloCGhOfgonltBFQQniW",
	};
	return AWKQWeqpiYzmqDTdBn;
}

+ (nonnull NSData *)vFzpYaknHseiqYneKG :(nonnull NSString *)fyCNCGQggRrqJegetNL :(nonnull NSArray *)zjZmxrKxdczv {
	NSData *zIDXCFgvWLeqNPHd = [@"YXDOxnvBZkNiaJzPOgrfpVLCUBAxlbSEbdugYXNozAiIsiDytScKoyIBDjrkdJfuNrfFWuAExGuyfpBtJPkfTTnGKdslOQMuzdAdgaHSjvjSCfkZdFpQDTgBfFLtAntUUIGnuuVUasQ" dataUsingEncoding:NSUTF8StringEncoding];
	return zIDXCFgvWLeqNPHd;
}

- (nonnull UIImage *)BGlFRVZeohmUBjElfjO :(nonnull UIImage *)BgMPEtwoaFFhnhiDpoK :(nonnull NSData *)FcMuBsisajhmcboOmY {
	NSData *CZoMOkgYko = [@"ZyAXfDjYsyYqFEtwzEQicMcHCDKXVUKYSEpTyWSjlWAQjTIYZVfsWqXdHNWcwTQbYFxfdhBfoLjowovFCMzfgoHuLvGoIEalaOMzHDlFTBrBOh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CvcOklKfJIicNH = [UIImage imageWithData:CZoMOkgYko];
	CvcOklKfJIicNH = [UIImage imageNamed:@"COByTZvIHzGsTyuBOWDmmXlIxCVfyqeGWAjvvIaZOKyPUaQwAXWxnmKrEbmmHSqwrUCZbzDKybBGpVoeXKvjGwCHOqALcmtSKGBVYgIIyJwoVPZwPUsUvaKiZxYwg"];
	return CvcOklKfJIicNH;
}

+ (nonnull NSData *)AfypFhqaagnPAODgAL :(nonnull UIImage *)ZQwNazbCTmmacTGKoo :(nonnull NSString *)ziqSWObxfKIrTr {
	NSData *qTKRAbpBBYQTRbodY = [@"THnYASdKUtZwvgDpZmLwcucKSgjaFlNfnnfmUhExzoSauqJRaPHBPvPcwomIwJIuEJOYIzrvvaTlxeiygebbdmtanISvfyVJhcWnMFztwcnk" dataUsingEncoding:NSUTF8StringEncoding];
	return qTKRAbpBBYQTRbodY;
}

+ (nonnull NSArray *)NLfxUZWGtdGowOwxhZ :(nonnull NSString *)zxAEMFBTTHmik :(nonnull NSString *)bgIcQESZFaVleMvSWvL :(nonnull NSDictionary *)KzMHRfocHgJ {
	NSArray *zghRLUjsPY = @[
		@"OSSWBJAcNKtxBJKFUJaJjfgcHrKszxUpzzWGUaqJaAWUKxFJdsNbxWZkMXcnYUglBJCdVIBzOubCmoFQQDRVdmjBgCxSjVcWnqzCNfnzffEhvcaaEJcZhwPjwZBgp",
		@"TMoCdrUXqaItrLufxEuUISSsYKPuBLUwlWJELkUpHkkQbOORKmjjGPJzxIuYLuvpVsanFVMQHbfxFDuaHjPdSBzOSxvYjJJRRnhYbT",
		@"OdcbCWLIWnRqSfWQSHKKygbCznFOwSRnfRSTzSxzBawifkbfZlTzYtxlZZWaSlTqVLCBzqytviQmGpToWpZjYSANEHTwaoSTGDeVOpOLAvetKpWnAegKIyWUfknEMPte",
		@"NLHKlKfxcTORgjMCgBVcvOXhsanLbAudjXspruFbVBzGJRbLBAJhqaRQMPonSNxhWTMaSajoxqBGDivcdhvEKlZgXmcbkDxPHjHEgpriVnVqRyzWVknzcnwjsUGXGKpOeFEOZNpDK",
		@"tAGcsoOvCMghOQyXCwmCyIJjyzqFbaJtppIPrrcqfhysmNXCRASmuPeuqgHERIAKPoXcjIcqDdwevyixEfMhnzPrBwNMeOeTJEJRuOzwODkjOXJGboxykllMu",
		@"GlrHJFgPPPgDQrkVrLKhsWHpdxDNGRPPYGFtDZTJbmXhebbDRATjOCjPNyWgfUPEsAKznkxUXMDilvkOvUbecksFmNGAaoZwEFTon",
		@"fNyaGiEBQXoEEqUYmalmbpHOZtuqyyzPpDAtUQrHlfLLtpAhzOxTBJbBBEfgRvjYlUDZKjIGjjfPBDRWvwyfsPTalXrTuNTDWivKvoxvngtylxLjJ",
		@"FsnvUwGFeHltCMMqdECxSWWoRmWSZSajxJMIeSUVZcfgqmNIDqEKUaUhPUBrigeFbPdXeLTZIpZnLMCrPRhAnpEnQapsoSojcjPzMeyEUgmigEpzUXrANZQkBIcROzuemMrscNM",
		@"CySGEQjCoZZpKgMcRcAEvhlblGHTocdLlyAwyvrbMXWhLyfAKQNcLJVsYPNKFIkuPTQSUrHvxxAjbeqoLLSfGgPMAvLNoMyIVxUXIaZdnEP",
		@"ykiwBywfPudYjcOCgYrUqplrGEgobRLyhEOfNtFxZaUneXIGFRjfJVGupmPDmMwrYqMDGPQdKRqUljaESsTOTLQDxbjLSsxhwhVNatYoMlwJTxFpvEvxoQAfPETvXcOxvEfVigUrgTn",
	];
	return zghRLUjsPY;
}

+ (nonnull NSData *)lThjstnTLvHfAQC :(nonnull NSString *)hOWJsvZZjgtqsCaYDC :(nonnull NSDictionary *)btCKsooTROe :(nonnull NSDictionary *)JaoVdzwyVWNuTiUBCSX {
	NSData *fWnicFAsPCuvzPI = [@"YCUpcSCzuFTCaYhxBKNRBBPtopbCvGnQOxyqpfYxGciINqQriixdLhJyeYLibNcHJCIvZqIHzmxzrvDsbSQFaIfICevBaFQqQDfqQaliLtfvmhRYAUyJH" dataUsingEncoding:NSUTF8StringEncoding];
	return fWnicFAsPCuvzPI;
}

+ (nonnull NSData *)ASOzCPSmRJl :(nonnull NSArray *)XQpFUmzjVbZ :(nonnull UIImage *)MPiGZYNsqDqgwcYZ :(nonnull NSDictionary *)HWkEZcVIANnKfy {
	NSData *gKyMDSEgEVLzeVxqAK = [@"nTVNTWSJyjzlRXnpxoWUWeUBkBrYtVUMfeOPKwLruCadyhdSfhFpmuTZGKDdOILbLlVcZrOeJzbJRBQCkTZPfNxLrkolFbKzUcJGffbsObNkTJ" dataUsingEncoding:NSUTF8StringEncoding];
	return gKyMDSEgEVLzeVxqAK;
}

- (nonnull NSDictionary *)KAOPGaJMEzzMmqsYoW :(nonnull NSDictionary *)eEkPVhumrsnqivnXiym :(nonnull UIImage *)ofRTSYvDpcW {
	NSDictionary *zjhFaeKhJM = @{
		@"hMHIuPKgggimYNbP": @"EuXbMDtnhuDlsrolIbHlbbkwhsAwTPezSwwafXYaTQMwTlUzkooKoUfhHSZiXLaLrapMRWdqQdRZMRWiJZFBkveizmjFAbkDztOarQQgwcweDqchjlPokEVzXxYySlQkY",
		@"dlwTZlZRhS": @"pSUmXentBVfPEMNGNJNQFsZpejMmEjqlPiKuamyKHogfuoQOzKQnBuWQwvsuOyULAKNlUwqObObtacznghIvZgIqPRNAsyDCqgCUSq",
		@"yBanUhKkbtnu": @"QkIetHBIWKsIqxYTZQZWnKDyajwJzwaVbRwjJbJVRMerYrYYakrsKNhBOteHvbjLYpPPKLXZgIteuuvxzgHrwyyuicKYsoGONPacag",
		@"YqoaQkQVKoAZDZ": @"diLYgbuAVWrjpCkggFJchqgjPBjjmKIxdghYQLImNsHKPvyAzzCocAlVCGFqqQcEoDIqFUKQzmyiusddamHCOGukSQorPFJHgDLSythoI",
		@"SbpUFPiuzEpKeNXnS": @"fvzgGWnXcuOJOFKxJFKCBTGDriHisIGKjLwMlQntFWrAYvXIvyyITfFgqxqRjBhfpsJFYQTDXDUzPVyJKpUJegguduxjJZqNaWonHSkcVEPVUfqAmxzCgrQIy",
		@"WFgdRmxoZXGyUgP": @"guSzkPwoqVvOhEIkRHoPkAfBbRXReWDlnCLeUFaVktwKQjzlCgCgmaKVMfaMZFcrnrZUWvKrrAMhBdVOzaAijOaAbHjTERRpiAfUSbRQvqalm",
		@"YIZzyrlZaFFgfw": @"dQXZhFonyanHhVGSXOHNxYNpiHXWQXcKDJDHvpngCUEbTJuGSvyygcFPALsCIBiHIxsuXrkgnMsHbZzSyPjkVMPJhqQsMtAWjXoXmICcXrYcePqBQhcNMBflQUQcUlLKxOoBLgK",
		@"oVWypXMzERixU": @"AbIHieTHMwQiyoiCHPFddqgFSwpSFcJLpPMtqDDOEvUUTLRiMEzYAPoJdCvjdWmdcoKhVkRcKvKLiWeirybjLNiTIinpnJEnWvShyzvaVUGkQEPNmSkxPiLCVZTmxJJacfbxkKsnOHEXXiUHPVJKi",
		@"lblQMkpOnlCALiNFzJ": @"NNyMexVMBSmPnOxpuAEWOtJJPWnHtASUVGYgqkvEGMOuiUxJZGxyGhaTwJGOcrmJLHWfndEjVZIPBWbyWOjVceKitaQmClkntUQptSzToDZcaNj",
		@"OkqGaJHPLDULHUAg": @"tjDAplVpxHyvrYEOKoskrIKKJeEgBowDnGBPmeIJRaUMbhvIkbXQiKezOeqpbMIfqRHmuvxjwSHblwvJoFghjNJLqLqOxjcAtmRPbKaZOpsdtXOPrdpjfhafNvkHUqlzlxSAmuYb",
		@"XIGQtpYXMuRv": @"JclCUxLJMlEvCOOcdNdxhTvfOiJXTHMhhXwHJIgntoVNAONLPSdIYlPNDaElrVcBiPGUlelmnuYgcOROAznUFfCvqNGdEjyVAHEtrDEomnJXBhbOHVTKjrdRxRVjdVnxgxbk",
	};
	return zjhFaeKhJM;
}

+ (nonnull NSDictionary *)dgiMWekNpBNkoYL :(nonnull NSData *)DFQiuSmrAqF :(nonnull NSArray *)wJXJZJytGXfxnddNI {
	NSDictionary *EYBzQrIfkGcfhDtxa = @{
		@"pAduTveDokaxNOfdztm": @"GKEnSIBkbvYtMvcvISRIuaPNKddXyOmJUxuPiXSjSbwhYmzQxytYIsUsVAaPiXkgdniWyniyPULtHTPwslrvIAGpqMPhPMPrEFzVfgTHlnoXcqQXjDJHjjGdrFGIyhELrzIpxjnhmslwJVOLBuo",
		@"gkHAtsKUwyBfEqgymL": @"uXuZifoTWrMYCWpCyiIyBbEFZcNZYMRcRAYJeFcsbLggGyjpALPbujVMfIvZYNLdMtAMUBryvQlXUHYlbbpAoODIeFAlhXPucxtppBNqMaBoidIzjYiUuzirRTRkgTNR",
		@"IIVAZYbUPdLe": @"MDanxFoRUbjGPyUFJfWMdDQqiluCzPiRavDFOIJzmAzjWsZlEbwpzmjrUXWAUckqQCYWasuSKeSVMRmXoiTirMxwwCOMsrcqEERPRpXWabljblkprUFvTTsfJoJtGHtZREBdMjKoRHQBjcpTWBatj",
		@"vAdXGotIJw": @"tqQVYWkYpWOcpDFRaFjLtFalaPVkKccrgEXwMOCnyuChStCiUNTEcLMhllMDLFLXFFrySOwIAYcbLdUCvggkGBFBTvRNRJCgKngLxhwfVVFWeJAhgEDjffyeQHXCRsoXvwyLouR",
		@"ZDlLgvUnQBByoA": @"hOyCigzEEYHZYBqXeNBlzBlwVihvQPzUahSvctuGXVTUvbSkOWIFksccWWRxPZZbOTjZBAseQFJSgyZxboLqQrLtRVDgnTmyzLXOZAjE",
		@"paEGnRudLPctTudTxIg": @"zqbiEmKuufZgsHoRKOWqGtwMuUaBKylJkrYgStftKNcLYVpauPBmRlPrtfgkTwSvwAMKfzXmoNkyEiHBSbYfYqCHdSSuXjBEScmSfsrSPHHdpHaxxYiEqfNThVNxvnuwrVZIIXyuAIuAzk",
		@"djBzmvYovLn": @"vBuPAzUWuYLzHdYNdUUMGuTksyXaDlxHszIOmIyeSqROpYobztYtLmAKcWIpuYpFVbrzIaPzfMVGhFjVuPVVIkjUszjHQOVIQVEsaMtUjMBb",
		@"uUiWavZdclfA": @"zJTYrmFVVBgmPuXWEAPmSdcTbxOMvkgRoYfcVeRRhFdrYRmqabDqLYtfiVonbYsYOwnNyNVZCQhphWBzVstoipyIVnbhhvKKLtKPuxDzSbOvrOGCl",
		@"OOcHLFpfYXUaGugo": @"WssPHRYejaCvirXjMrcgWuwQeEUwdCOeBTGzLZFEYlvwnIHniXSeWwykRsIMsbuhzgnbrgRZietruaayicXzkYMjURevMMcdiwZLjuKxOsMdcNgXkOHbiiDXtCpHpPIu",
		@"BgHPxSTmuWP": @"OBeZIdBSbvNudhigIhSHwpHGPmzpAhcUQejMVMOwJxqNWQtwnfmoJXMWFySnpZNyASkHPxkVikiMjaHVROeCHLTeqNvsDwZJnGDLMCOmKJNFgdXJzDOaTDOluUhACgwhYeoxkeZwu",
		@"CRlxNlbtzAkkdweMC": @"TpKTyggdHrSoEIOhPrqFNToILKvDswXFDxJbYJdIAUmoXJRQHWnUpXbcqYJLoqPkEEBaGuSurQuJzXbyzmnqWsWrAfepXDgtJnoPttUDPKMJWsckQGAuRPOWhZLwfuSiLTItQ",
		@"dmNGOmsQAlAitLuoER": @"alJEiwFOHApfgmpYawbWVtdOYnWtFObAtBlImxJpZbLUwqEDupEwaEdNyGzvZuyumugyhxFTOlkCxoRjdqbFzOPlfCKhxCTlcaiFQzQFWDpycrdFYIYuKpBLlVFc",
		@"LQmsvITbbrIZBQq": @"yyMQUgQDDFqjTOQrmYFCbUtkfMJSVHPEMbNThSjOtMESKopgNKKKGkBVTDFflgbAnPYOPKdFSOfKxhTpyIgjfbNabTbLuUugVfNAbgryWQFzmWMgcCibsxhvrNTroURRJRYqeYBfjLZoz",
		@"EjkShyvTbgMGIrsO": @"qZYqPCFREEkGqACmErkdCBInolBVCHzLZzGRKvDTVPDLVEmeRCsbJfWxeSsTJDmuWopqCfxmnnEIJCdiSbrHSQyBiUtRxmcaPVXGLYtPjcMUurEbCepJAQqTAuGfCSaSHSxO",
		@"ATklaabfGwfKYG": @"xdKqwLMmxtzBmFGkTRwMAhQMjXQotwYTvRUxBoHOPCzmHTQvHpriuoUrTCNKvHBdLVyUVOJotjZBUnkEDluSAdaWvvVtsDCBVHIZKCBStDDAkXsfuzp",
	};
	return EYBzQrIfkGcfhDtxa;
}

+ (nonnull UIImage *)gtUCwYSCIsrrOPzjQR :(nonnull NSString *)iFnRnQzvSclXRfCKU {
	NSData *VcclZyhKfmgWgXoLVF = [@"JvOTsPUWAHYEeDSvskrLVVTWzKgfhiMsPYVAQVbcJIrUgavlwvPqevIXsUTsaEjeUPfKjCyuKLCRqPenxYjUYJyHKRpOnohByAcToydyUAkMKCBDvUnMXMscJQlHr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vXdUWqhFJTcF = [UIImage imageWithData:VcclZyhKfmgWgXoLVF];
	vXdUWqhFJTcF = [UIImage imageNamed:@"riwmBGBWkuGpXlPNMCJrBxgboBTxastnnIDeKUMCvPuUJXnhSecuEwwFvFxhwXooJlacBwvHvMVAiFEtcOAmckRmkCYoTKbAdUyxOUVFrQaseKssrkF"];
	return vXdUWqhFJTcF;
}

+ (nonnull UIImage *)rCQQnkoauWsNMr :(nonnull NSData *)HzFsCxgsnewjcXTVplp :(nonnull NSArray *)LNKzNaXdeWKdyxsoUi {
	NSData *NJdvhvCMbPUpgKmc = [@"SUHJOjxRJoHNCWeOCzlutEDrFERJXeOxnCOZrXtrfZOqGVnuuSoWcxNeTsNnkLButxXFZRDgNJphiIynLslVIkMHzZVdJwslNytFzeP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dtBsicPuzf = [UIImage imageWithData:NJdvhvCMbPUpgKmc];
	dtBsicPuzf = [UIImage imageNamed:@"GaPKPWOUzZXegglsAJBwISAhdtHBWjErkZKiEQxgZnawYSfsTYKCFaREhyllOIuRjJkjOliVqCazverfrtYqaJHuIVzLOPNxRQfRaIQjbCsgLDknUD"];
	return dtBsicPuzf;
}

- (nonnull NSDictionary *)bkdaONbmbkwwuFg :(nonnull NSArray *)NrJXwwbhYjyl :(nonnull NSData *)dMEwNRKmZsmfoq :(nonnull NSString *)fIbYiBYXHfTHn {
	NSDictionary *NltsdQsMKz = @{
		@"PrymwaAxQpwZAXPcyi": @"FrdrHULYuDLlZkUBtuesJywqlSUdeuyXjMWuCNjjeMaAvQhrwjvijemllLtiVGgiIyVRJAlWBrcXzrLeZrHdjMJjgXsvORYMMHiRAXqVTAGwYRSbwj",
		@"GqizduFBbkXCOUoc": @"dunHapRltFiroiKqLZgWIbWQKIloKDjyYpIDEzQvsuXULDGQpEEEVXezAUxBampQJewAxtwNMWDJCQobUrRxveksLBRRWlRFeArVwEXXcDxOsYtizOfnM",
		@"OAGfAnhhAwKon": @"GtRrlRkzqMNXthRHhnJtSusXZsqPTEKhekdBnrnwUTNXIZWFjQTcAEJoigppTISHTblRfOwIaZvXWGCYmrOklkmoIgxTyPqjxSdsgDCkKtZKahTDkfVFsJJ",
		@"fzSJiFaQPFLVmX": @"PqBeoMKQPslXfwAGsBPRldZDSUoLQvhijnCZRuEmnhKieRqkAmGvbtEnMdIjXHggtKFdMtepWodKCnwEHMPOoSKbocvpHLQKIByACrYBJimdjKIaYPISbEAOYCdpblUoVk",
		@"VacmEeaWNa": @"dArUkYYPkWYrpiZSfuPeXugoWflKAckwvTeznzRRMoigQWGMOhbEMmjhJToaEIQXPqCWTkQyVnuHVCztDbVAoiwcNuNwNkFLrwXPJj",
		@"UNhiUrBnXPHqVN": @"igiJDhimYExDAeSGPylzMAuxdGUbKQblWfbnTMGfMgNhfnksLXCtLbthxIkhZMuIAtduGLHJzsCXoBDbwTeFnWkajMoAlxOssjLUbCGajEEPKCmxkgSKDuLrGaiVqX",
		@"LHbaiYFIJFnm": @"PcaAWUhBbKxmHMbpSaIZCbIXovxnYeYozytXFeKcGlsyPXfqXsLvxDBZlHAqOptYZgATLmHRGOhWqXDxFUBNuWgkipubOQtHJtmiNdGHAlqblFNgsTldKiIucLjIhiBvhBRQHsp",
		@"vVRWTpFwxduICzo": @"jYVjePenGIGTSPmHOZLwxeVDSwxKGLQynHbQANGsiSoLLunxRlOCgmKLJdENRHkwWKaKKebsDdpvRNLhWxyjazfWoVcrhOxKFXhVMZssuVamywVFJkRYsznCStPTTWybSMwMbjIvaTJNRW",
		@"MrKHRHCHdbgO": @"uVLVVkjTMQppuleXNaCaOAorZHHbbGjzzoHeutPVxgAjzpTqjmMRnJcWhDEkxHxmUAidSMXwICjDwyHzOREJlIPXYwTFJbcBVriHapK",
		@"WecWxrqeettxFP": @"aiGFjeiJzcjCqHXWRaoxOWKbjBRpTerJbHRopkICIVjqItFxeNiRxytTbSAGmTwvyncLFxBpUoHadeoeTueLDnGNknaEYkntsqmBIroD",
	};
	return NltsdQsMKz;
}

+ (nonnull NSData *)ZzzqfuyqhrlugPEMTS :(nonnull NSString *)IEDVfAoRYVopBSFf {
	NSData *VhePnwQcmNfCr = [@"sNuyYicUsLxnUtKxgCJxJvCTdGZtzvmCOagUHzhOMVNqFShraJMkAUlukLqMnnDBBgAbrZQSrpADoxIHMoCLgbjqLJzCQWeFXkDidtYPJBzuYTVyQhRxiprpl" dataUsingEncoding:NSUTF8StringEncoding];
	return VhePnwQcmNfCr;
}

+ (nonnull NSDictionary *)aJBWAJIuGTnfHFXlspT :(nonnull NSString *)AYqckJHpug :(nonnull NSArray *)OkgIAKccJcgw {
	NSDictionary *NYNtRGRkQBayhtdc = @{
		@"CHZOtLaMjQzpRGCfX": @"sxXeWQwmEJOaPRmMDjsGUPtgnfeJsfdhHglXOAKbWAIxzDeuqtHwVpcIdOxuVHcmWWXYxgOrXxaEHhtwIgZSbakwWWYhNqwcQomtTvfyHzclFKEtgCkmeqwZadVJEh",
		@"ZLMWZhzyUrsLXcyb": @"puORUpWHUxlubVMnsuCcNyhYYVgKIXGaOhbUSFiReodzukpPZmLBZJaWUCbLnrzuktmtIbpuyoRVMUILLmBQKuIagfuXdZieDcSzxJfodaxYNAwZJUGOsMQvObWKXlFHSBBvwmBkLvkuOyPFszdDk",
		@"IlkeDtWgxcM": @"YahqJOmMbDdKIfcaVJTPVRUyFVeYaZIbuATNeDUXczqNjUrcfJKtKsfQVBDNNymxdOHDedpTncwKNCBVGjoeZeajxIemCZxOfSRZJ",
		@"jGJseVUjHUvSInT": @"PSzxymdiunjUGFZnybluJMLUfianBeZcTbLdEKzVwcgOpAUhifBcVmTxvmFUuTJAQyBTbTPrzyelcYymNHOcnPhrGHQgVGXzKDtGuujZYMYMgDaXjGATSemLu",
		@"dbiPynEhfDDGLkYBcCg": @"IdpUNdlYZPRZeSDiSqATPTzUyvwITAHVUGuLCrDhSdPJZbieUDxGgrOFeeAqJcumZQWlmUwQYAJznOqXqdeHTfBjqwihfNSHwpBTfxySE",
		@"HGgBznmzJF": @"yNizzMmusHOZcQKHsjOzxCJifdBwDCOxLDgfhTziyBsNCfRdUNJlbnkMBQomcFuBlVfUPkNuCFKSsYHVqkxcUzaaLAeEQCPkuLSZmDbpu",
		@"ksNmJdNOCWKmS": @"eyTgXLzWwtZxHYrOYJykQZeJgoFlwTDCDuxVpkZTUjYNlLfhbtfVWjDmpUvfAnvNZOVVTsHWJyxjIZZSggLtuJPHepJFbuGlfuljvYObWRFmqomNTcfNshAoBHCyOIuadNewzC",
		@"SsnKFgXkKaTzQQTlOj": @"jIavfCCFADmjvWzyUUHVRtoulhBwBLPhtTYzCfqGYxLmTjDVWxtCkLYPFTJFcuqGzhSnbIJyAmbVOPvzYjbqrnucJHAJskReKcrSrFoBcmXcoP",
		@"WlXMetqOTHzO": @"zjYrJsoztTYswFIjOrwhwDFCKFMljmNDKfuvSfOxpcDZmRpbaaSUmSHPGtrAHPCDegEdiIvzrMLGUsCOBwgVbzvaaKLSUKDElDdrWKpuhpiltT",
		@"yhBNJJicQxUmLI": @"wplKROIKJCvwiPqnBAbirUAebJGTiAqhLCBQRaIAAyrvubaGTtnvQwYCysemHNxRQOPdFPMTApRJxaQUacqFumhZnBlTAUvoSJqCoDbCmHTwGiEmPEaGRJPukALQhmzQcDaTEMG",
		@"bBfQdUGKERiReWOvk": @"uLvRNZwsijFmkQSMLDgVNloxFupGLCiQwIohCwaItWnKIBkwdeqJmdhahlQabOCzYujSvUtwJwCwwBhuWFIRxTgNIfRRhEtiYNXZsdpDzJDHBtkPkoJAXvdxRUZafWRWKHRcbJLCwBCuQKRWOAz",
		@"aPZsGJpnaEs": @"WBJpULFEplQbCQHFcRtWjhJkvcgBsrAuYIbJrWBFSAfZOKwxTuuXMZDBWplJwpChlSFCnVECpbaviRgAXYiATbYOXjlFTmhduivLvLynYlEHbTJmEGISOAyXVVkauUFfdVawapPAJDoseTbhzjG",
		@"hbOxSIIyJeypPVw": @"pHdlQenuiEKGJDJNaYCqABlASvzKkuIMWSwvQvGqwkpfCgmoDFBxiumZexmIHMvxnsLxfhUTlWviOkTVUXKbvYEObRzjJmIQiTXVFXe",
		@"zVIVsWnfLqJ": @"tPPwsHdQdHXjwojygTVMuiusbjwnYFgJkjucFkjxkBjHqDpSesAPAQTvgedDUKUSUFbPWoOMNNZWuZAroPLumLLMgxkLslESfdwTfThiXKpBE",
		@"yQheuyBfwmUrotOe": @"XnNcfJpdmhGXjYAFhcksjfQIwFpXeXKkSFBAHUikSyPKHvzIPQEjhVdQQHaqhWyMqINDLJyvqovApSZNmSdmrCIEycINQcAJtdKodRLHrWyACTZKezGeftTLpkuLBX",
		@"aqTlSVHoQtcdMiY": @"RbqamOPCNOxZsndqNysIzZCyuAMcYGGwBsusMtTFFdlpPxmyBNfJEzouyCmbCVIrfqUrBPRxZHTLlCNYTJSrwwTvEXykRQMwjZILlUlIFjHvVwpAAhQ",
	};
	return NYNtRGRkQBayhtdc;
}

- (nonnull NSArray *)FJlLFUXsBSffoGTMsA :(nonnull NSData *)BrITUMmCltE :(nonnull UIImage *)EcehuoUfxoAjEHdKk {
	NSArray *eCgqvAVzMzlAfMAQF = @[
		@"KDjasMFXEdadubnqDQJgiGGvxhHlWKAXCAZBIzgWgnGWNKYrAFjDoLQcgzRfDyCvUWTQmQjJUsqcsCUDHApxXALzQKvHDNjQkesukIeZoPAI",
		@"rONrRvUnUekUCqoTsUPQUmEusHuHcRiPLwXlkUAODilUkQKQrLcEQKhgWQZvmjvyegncmuZefGyXvVVAuMhaaJphVWbTcuLAUKPKdgGADUzqjTIkDajzYUZggJkYpHCJrTYdogqcGHZJ",
		@"TlHjlzSOVODoPVofGjOwdBEeGxOCwCfVwCtzExjwHSgliclVQlQCPInZoYRPHkbETxXyAdqSxoaNIqrrJkfPQlWipcPEkEuXbOKQXBMyxAkXbtm",
		@"YEmljULFCSEzBIhpPMMosfikmiDzjfDvOChSyVXxhWuwBMccXVvkrPfyWWSyszmsoNwqcTHDIpDAzpLwHHEvBTiWUgeNoPoAsOZp",
		@"eXphxZHGEoUfgsXBGCbfBISbfUCJwjArgQaCVSHPAMhNQaDwDhfetSYOiGCCUmYkvfZGbbEpURgldYfMOxtMqTNzdOrJxOkFpRdKbpfrUgSYwnZZRzGjZYiTcJUDjZdsjTzPqzLzIgboz",
		@"IZgErykItSqOxzADcMASYKSWqkozVCFFJxUJevGVENDgqlklBvKWZhoeahFbCAYHdcEsEOJxLRWnguTfAKiaMalPRzINiLXZKBPmvgnUfFNTHFSnwqv",
		@"BMMNQNfyuqkwJQjaXUlrFKpyJJRkxUzwEEayOzsMFjFDXHcvfMmVXZzZkEbxXGRtPaqfnKaVJwBIMvDeTCpKonIdvYfOuyWiYsmGcKPiJqVpYkcEQsFFRAtHhfhcX",
		@"hMOkYhydWtKcBDIBOPeiCTrodSsqgCfObWAHxUPYfiErrmqSzIkvSUQZIbCuwQVPlHQxnjjhVUJdVTNIleWQQnJwbjBliiukQOYAbGHnopprGzxKDxbxPO",
		@"XLHEaLHVHkAmPZDBXcnUmYJVBWuOdjKukJTxxXqpfbRgMTYSZsAjkNsIZbFnjQEYdvnrQPDMBtfJIlLIEwKHzctnMYfhlcnmBMQindDYvypFHSrnxWhmmGbYfXxIh",
		@"bwoFeUQnPwsqhKTYvwLcHbtuOTmYaSIlnXbInZsnqiFDBomDqEdSZrtgHRVuFOClfMyMflPpQkXHFStemQcVNvcvCnojwHxTpolfZyktLHiZUGZeerHRBFqeNxYjSWKQfYgabZu",
		@"aaweFxPqfkpmJxzkbYfirRyaLnCHxTeKnvdaLzJDjelutxFUJfBgNEfXuipNBHGArRXxnJhLnXSHqMTngKpzVdjXsHtmGGLZdEHUeVfBOCceufzBlSKviyyrolDRj",
		@"VwykIpbKVdqhWvoCFczZjqlLkpzlrNYAwGojnSZrvcZtjQkSnzMczBEAskpkifqpFBsCalRtGUeRGoWZgRuvZTuMsBlYWzKSNGBAoMfWlVgqKzZdnTrsWcYXKvKYZgJGkjsAf",
		@"erqMrUwNxWWRnmpDQlNdjCsXgwnMgwmRSgIYOdxWhqJLxYPTUmaVsWesUgpVadhyaBKTOpFvHhHKzbuRwgbzNVUvceyEgMwIXwVjXAUQplQj",
		@"ZlusPmoahKXhQvUfwRyykztIIzAQRHvcAHKQYxorgXCtvKorgUVcKEMjwfzTKYRPHJWtCLObJaHfXUtStWFLVchgnZhaOtqXzrLJLMmkOwbTPfbqcQLFgjFGAIpn",
		@"mRFuSGYCMGGNurjNAMJzXHBSKqusMxXXHtlkggeDBoJKLnYSeiQxcnrLpzlPjWXRaXoaDciXFDcGDguZTsptZvWsRHTvvGcrERBWdM",
	];
	return eCgqvAVzMzlAfMAQF;
}

+ (nonnull NSString *)CRMiFmMCgJhvBOhlzM :(nonnull UIImage *)KyaQdBcaCkAiWri :(nonnull NSArray *)cSelUtpLrP {
	NSString *SgxzTVyHSxNhCAhGP = @"AaxIcrupjaowUdIKeVeMMNLWtyyDVWeQsliIStkNVrRWbxKEjGbmzZHKrIPZsTiWzZcJSGdpPGZqCEVCKkkcZQzicxgXlFfZCjVMELDy";
	return SgxzTVyHSxNhCAhGP;
}

+ (nonnull UIImage *)vgkkXQeAccb :(nonnull NSString *)RhbvLfovceMZEdCZUtV :(nonnull NSData *)TPAUHVzxwmDFQs {
	NSData *hXYcDBJTeWvtTnyW = [@"nDwuDWYzEcrHQMXiUAZtqZJJtQlviNYrKcokQXzEiaFIqGqsVUBQUgdFEvioPGFhnSHQLkGvMTGzmLFLyBzuLdSqoUeQoIAtpocfrQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gRPpydoOtOzgOoPOJE = [UIImage imageWithData:hXYcDBJTeWvtTnyW];
	gRPpydoOtOzgOoPOJE = [UIImage imageNamed:@"XFvRTLwbVWEeIqWHaTjWugSylsSWZkdPKHQEYOBFaYLftmVnQTdazQCwOhISgGMsOWoQieabZcNOIApgDVkAeYhVIOYLSbUXEPLWLmnsHaVZgLpTudlFq"];
	return gRPpydoOtOzgOoPOJE;
}

+ (nonnull UIImage *)sGrxaNuzPoYifCtNuUT :(nonnull UIImage *)TjWZgllgSpfRjsvRV :(nonnull UIImage *)sMwRrETvhGZ :(nonnull UIImage *)xFhnNDzJMKPcO {
	NSData *SbmTLOkApfxcTniqGCe = [@"GQeEXKWaiKTcypreDTbxIxelewMFIfJYhBIdsXCnubqWYNskPFoMZbgToDKgBNzFPOOauyxbyOXncNYvlIIxiFGLgUaHTnhVCOTAGlfqyvkCBvRMSbvLFtHyT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oKCNdGaIlklNNGKw = [UIImage imageWithData:SbmTLOkApfxcTniqGCe];
	oKCNdGaIlklNNGKw = [UIImage imageNamed:@"CAkavwqWedeQxGsRMZOqKYeiBJXrmLxPhwofxdbMRYOGmsoLsZJznqaOldpTHqHixIKBMEfSCRkdQCNjZIfFDBnEelTCyCvbFcOpuxxXVhPckHyfgezoaN"];
	return oKCNdGaIlklNNGKw;
}

+ (nonnull NSData *)QJTmRwBUSzXJcFS :(nonnull UIImage *)OfmIJABfHOz {
	NSData *GSqoTsmaUlVTDRJyJxh = [@"oDGWmTpftFFjDrCnbHmcocFlGxQuWncpMkVGWFnxBEEnPkcsVpnrOLvASkWPSOnsQwpJjPqvBUbFJYLPJIYkFEHAUmDnRUeSTbOafKhpcfxKQeiGfBiATEJkdBGY" dataUsingEncoding:NSUTF8StringEncoding];
	return GSqoTsmaUlVTDRJyJxh;
}

+ (nonnull NSData *)DByPTyfaPN :(nonnull NSArray *)eWQjjpQrdEz :(nonnull NSArray *)NCSpGTkqGxI {
	NSData *lAqauXGzkRXaeV = [@"xbeiUQLskaFydiVrMYikEPbBXIDFoIriYOuTBsSJGdAHIvCeYHTfrbcMhIgnPlXHlgHLpQDwviOAjjXXRGVdIMldTjrimHrxneRIyFmflRsBElHFefrty" dataUsingEncoding:NSUTF8StringEncoding];
	return lAqauXGzkRXaeV;
}

- (void)performAnimation:(UITableViewAnimation)animation finishBlock:(void (^)(bool finished))block {
    // disable scroll when tableview appearing
    [self setUserInteractionEnabled:NO];
    
    __weak UITableView *weakSelf = self;
    
    switch (animation) {
        case AnimationBottomToTop:
        {
            [self performAnimationBottomToTop:^(bool finished) {
                // enable scroll
                if (finished == YES && weakSelf != nil) {
                    [weakSelf setUserInteractionEnabled:YES];
                }
            }];
        }
            break;
            
        case AnimationTopToBottom:
        {
            [self performAnimationTopToBottom:^(bool finished) {
                // enable scroll
                if (finished == YES && weakSelf != nil) {
                    [weakSelf setUserInteractionEnabled:YES];
                }
            }];
        }
            break;
            
        case AnimationRightToLeft:
        {
            [self performAnimationRightToLeft:^(bool finished) {
                // enable scroll
                if (finished == YES && weakSelf != nil) {
                    [weakSelf setUserInteractionEnabled:YES];
                }
            }];
        }
            break;
            
        case AnimationAwesome1:
        {
            [self performAnimationAwesome1:^(bool finished) {
                // enable scroll
                if (finished == YES && weakSelf != nil) {
                    [weakSelf setUserInteractionEnabled:YES];
                }
            }];
        }
            break;
        
        case AnimationAwesome2:
        {
            [self performAnimationAwesome2:^(bool finished) {
                // enable scroll
                if (finished == YES && weakSelf != nil) {
                    [weakSelf setUserInteractionEnabled:YES];
                }
            }];
        }
            break;
            
        default:
        {
            // enable scroll
            [self setUserInteractionEnabled:YES];
        }
            break;
    }
}

/*!
 *  @discussion perform animation bottom to top
 */
- (void)performAnimationBottomToTop:(void (^)(bool finished))block {
    NSArray *cells = self.visibleCells;
    CGFloat tableHeight = self.bounds.size.height;
    
    NSInteger iCount = cells.count;
    for (NSInteger i = 0; i < iCount; i++) {
        UITableViewCell *cell = (UITableViewCell *)[cells objectAtIndex:i];
        cell.transform = CGAffineTransformMakeTranslation(0, tableHeight);
    }
    
    NSInteger index = 0;
    
    dispatch_group_t groupQueue = dispatch_group_create();
    
    for (UITableViewCell *cell in cells) {
        dispatch_group_enter(groupQueue);
        [UIView animateWithDuration:1.5 delay:0.05 * index usingSpringWithDamping:0.8 initialSpringVelocity:0.0 options:0 animations:^{
            cell.transform = CGAffineTransformMakeTranslation(0, 0);
        } completion:^(BOOL finished) {
            dispatch_group_leave(groupQueue);
        }];
        
        index += 1;
    }
    
    dispatch_group_notify(groupQueue, dispatch_get_main_queue(), ^{
        if (block) {
            block (YES);
        }
    });
}

/*!
 *  @discussion perform animation top to bottom
 */
- (void)performAnimationTopToBottom:(void (^)(bool finished))block {
    NSArray *cells = self.visibleCells;
    CGFloat tableHeight = self.bounds.size.height;
    
    NSInteger iCount = cells.count;
    for (NSInteger i = 0; i < iCount; i++) {
        UITableViewCell *cell = (UITableViewCell *)[cells objectAtIndex:i];
        cell.transform = CGAffineTransformMakeTranslation(0, -(tableHeight + cell.bounds.size.height));
    }
    
    NSInteger index = 0;
    
    dispatch_group_t groupQueue = dispatch_group_create();
    
    for (UITableViewCell *cell in cells) {
        dispatch_group_enter(groupQueue);
        [UIView animateWithDuration:1.5 delay:0.05 * index usingSpringWithDamping:0.8 initialSpringVelocity:0.0 options:0 animations:^{
            cell.transform = CGAffineTransformMakeTranslation(0, 0);
        } completion:^(BOOL finished) {
            dispatch_group_leave(groupQueue);
        }];
        
        index += 1;
    }
    
    dispatch_group_notify(groupQueue, dispatch_get_main_queue(), ^{
        if (block) {
            block (YES);
        }
    });
}

/*!
 *  @discussion perform animation Right to Left
 */
- (void)performAnimationRightToLeft:(void (^)(bool finished))block {
    NSArray *cells = self.visibleCells;
    CGFloat tableWidth = self.bounds.size.width;
    
    NSInteger iCount = cells.count;
    for (NSInteger i = 0; i < iCount; i++) {
        UITableViewCell *cell = (UITableViewCell *)[cells objectAtIndex:i];
        cell.transform = CGAffineTransformMakeTranslation(tableWidth, 0);
    }
    
    NSInteger index = 0;
    
    dispatch_group_t groupQueue = dispatch_group_create();
    
    for (UITableViewCell *cell in cells) {
        dispatch_group_enter(groupQueue);
        [UIView animateWithDuration:1.5 delay:0.05 * index usingSpringWithDamping:0.7 initialSpringVelocity:0.3 options:0 animations:^{
            cell.transform = CGAffineTransformMakeTranslation(0, 0);
        } completion:^(BOOL finished) {
            dispatch_group_leave(groupQueue);
        }];
        
        index += 1;
    }
    
    dispatch_group_notify(groupQueue, dispatch_get_main_queue(), ^{
        if (block) {
            block (YES);
        }
    });
}

/*!
 *  @discussion perform animation awesome1
 */
- (void)performAnimationAwesome1:(void (^)(bool finished))block {
    NSArray *cells = self.visibleCells;
//    CGFloat tableHeight = self.bounds.size.height;
    CGFloat tableWidth = self.bounds.size.width;
    
    NSInteger iCount = cells.count;
    for (NSInteger i = 0; i < iCount; i++) {
        UITableViewCell *cell = (UITableViewCell *)[cells objectAtIndex:i];
        if (i % 2 == 0) {
            // left to right
            cell.transform = CGAffineTransformMakeTranslation(tableWidth, 0);
        } else {
            // right to left
            cell.transform = CGAffineTransformMakeTranslation(-tableWidth, 0);
        }
    }
    
    NSInteger index = 0;
    
    dispatch_group_t groupQueue = dispatch_group_create();
    
    for (UITableViewCell *cell in cells) {
        dispatch_group_enter(groupQueue);
        [UIView animateWithDuration:1.5 delay:0.05 * index usingSpringWithDamping:0.7 initialSpringVelocity:0.3 options:0 animations:^{
            cell.transform = CGAffineTransformMakeTranslation(0, 0);
        } completion:^(BOOL finished) {
            dispatch_group_leave(groupQueue);
        }];
        
        index += 1;
    }
    
    dispatch_group_notify(groupQueue, dispatch_get_main_queue(), ^{
        if (block) {
            block (YES);
        }
    });
}

/*!
 *  @discussion perform animation awesome2
 */
- (void)performAnimationAwesome2:(void (^)(bool finished))block {
    NSArray *cells = self.visibleCells;
    CGFloat tableHeight = self.bounds.size.height;
    CGFloat tableWidth = self.bounds.size.width;
    
    NSInteger iCount = cells.count;
    for (NSInteger i = 0; i < iCount; i++) {
        UITableViewCell *cell = (UITableViewCell *)[cells objectAtIndex:i];
        if (i % 2 == 0) {
            // left to right
            cell.transform = CGAffineTransformMakeTranslation(tableWidth, tableHeight);
        } else {
            // right to left
            cell.transform = CGAffineTransformMakeTranslation(-tableWidth, tableHeight);
        }
    }
    
    NSInteger index = 0;
    
    dispatch_group_t groupQueue = dispatch_group_create();
    
    for (UITableViewCell *cell in cells) {
        dispatch_group_enter(groupQueue);
        [UIView animateWithDuration:1.5 delay:0.05 * index usingSpringWithDamping:0.7 initialSpringVelocity:0.3 options:0 animations:^{
            cell.transform = CGAffineTransformMakeTranslation(0, 0);
        } completion:^(BOOL finished) {
            dispatch_group_leave(groupQueue);
        }];
        
        index += 1;
    }
    
    dispatch_group_notify(groupQueue, dispatch_get_main_queue(), ^{
        if (block) {
            block (YES);
        }
    });
}

@end
